### ISSUE TITLE
fatal error trying to update own password from Users & Roles section .

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#10065]
**Describe the bug**
Regression introduced with the merge of pkp/pkp-lib#9566 which throws fatal error when trying on update own passowrd from the `Users & Roles` section .

**To Reproduce**
1. Login in and visit the section `Users & Roles` under the `Settings` section
2. From the `Users` list , click on `Edit User` of the user as who current user is logged in
3. In the edit form, update password.
4. Save and see that edit form does not close itself and the spinner the going on. 

**What application are you using?**
 OJS, OMP or OPS version main(upcoming 3.5)

**Additional information**
Full error trace as following 
```
[15-Jun-2024 20:37:39 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: The given password does not match the current password. in /Users/abir/Sites/code/ojs-main/lib/pkp/classes/core/PKPSessionGuard.php:279
Stack trace:
#0 /Users/abir/Sites/code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(670): PKP\core\PKPSessionGuard->rehashUserPassword('123456', 'password')
#1 /Users/abir/Sites/code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(340): Illuminate\Auth\SessionGuard->logoutOtherDevices('123456')
#2 /Users/abir/Sites/code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Illuminate\Auth\AuthManager->__call('logoutOtherDevi...', Array)
#3 /Users/abir/Sites/code/ojs-main/lib/pkp/controllers/grid/settings/user/form/UserDetailsForm.php(353): Illuminate\Support\Facades\Facade::__callStatic('logoutOtherDevi...', Array)
#4 /Users/abir/Sites/code/ojs-main/lib/pkp/controllers/grid/settings/user/UserGridHandler.php(401): PKP\controllers\grid\settings\user\form\UserDetailsForm->execute()
#5 [internal function]: PKP\controllers\grid\settings\user\UserGridHandler->updateUser(Array, Object(APP\core\Request))
#6 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/core/PKPRouter.php(346): call_user_func(Array, Array, Object(APP\core\Request))
#7 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/core/PKPComponentRouter.php(293): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#8 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/core/Dispatcher.php(171): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#9 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/core/PKPApplication.php(379): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#10 /Users/abir/Sites/code/ojs-main/index.php(21): PKP\core\PKPApplication->execute()
#11 /Users/abir/.composer/vendor/laravel/valet/server.php(235): require('/Users/abir/Sit...')
#12 {main}
  thrown in /Users/abir/Sites/code/ojs-main/lib/pkp/classes/core/PKPSessionGuard.php on line 279
```

**PRs**
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/10066
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4320 [TEST ONLY]

[pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp-lib](https://github.com/pkp/pkp-lib) [rehash issue]
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4327 [TEST ONLY]

**Comment by touhidurabir** [comment]
fixed by https://github.com/pkp/pkp-lib/pull/10066 .
