### ISSUE TITLE
Publications stats crashing with Filters selected

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#10098]
**Describe the bug**
Publications stats crashing with Filters selected 

Affects both 3.4 and main branch.

**To Reproduce**
1. Go to Statistics -> Articles 
2. Add Filters -> For example 'Articles' from sections
3. See error in network communication - getting 500 response from `publications?sectionIds%5B%5D=1&count=30&offset=0&dateStart=2024-05-19&dateEnd=2024-06-18&orderBy=total&orderDirection=DESC&_=1718804532792`

Stack trace:
```
[Wed Jun 19 15:44:19 2024] Slim Application Error:
Type: Illuminate\Database\QueryException
Code: 42702
Message: SQLSTATE[42702]: Ambiguous column: 7 ERROR:  column reference &quot;submission_id&quot; is ambiguous
LINE 1: ...in ($4, $5) and &quot;date&quot; between $6 and $7 group by &quot;submissio...
                                                             ^ (SQL: select count(*) as aggregate from (select &quot;metrics_submission&quot;.&quot;submission_id&quot; from &quot;metrics_submission&quot; inner join (select distinct &quot;p&quot;.&quot;submission_id&quot; from &quot;publications&quot; as &quot;p&quot; where &quot;p&quot;.&quot;status&quot; = 3 and &quot;p&quot;.&quot;section_id&quot; in (1)) as &quot;ss&quot; on &quot;metrics_submission&quot;.&quot;submission_id&quot; = &quot;ss&quot;.&quot;submission_id&quot; where &quot;context_id&quot; in (1) and &quot;assoc_type&quot; in (1048585, 515) and &quot;date&quot; between 2024-05-19 and 2024-06-18 group by &quot;submission_id&quot;) as &quot;aggregate_table&quot;)
File: /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php
Line: 760
Trace: #0 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#1 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2705): Illuminate\Database\Connection->select('select count(*)...', Array, true)
#3 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2694): Illuminate\Database\Query\Builder->runSelect()
#4 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3230): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2693): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#6 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2836): Illuminate\Database\Query\Builder->get()
#7 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2803): Illuminate\Database\Query\Builder->runPaginationCountQuery(Array)
#8 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/classes/services/PKPStatsPublicationService.php(90): Illuminate\Database\Query\Builder->getCountForPagination()
#9 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/api/v1/stats/publications/PKPStatsPublicationHandler.php(225): PKP\services\PKPStatsPublicationService->getCount(Array)
#10 [internal function]: PKP\API\v1\stats\publications\PKPStatsPublicationHandler->getMany(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Array)
#11 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(PKP\core\APIResponse), Array)
#12 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(PKP\core\APIResponse), Array)
#13 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#14 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#15 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#16 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/classes/security/authorization/internal/ApiAuthorizationMiddleware.php(90): Slim\App->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#17 [internal function]: PKP\security\authorization\internal\ApiAuthorizationMiddleware->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Slim\App))
#18 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(PKP\security\authorization\internal\ApiAuthorizationMiddleware), Array)
#19 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Slim\App))
#20 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Slim\App))
#21 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/classes/security/authorization/internal/ApiCsrfMiddleware.php(56): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#22 [internal function]: PKP\security\authorization\internal\ApiCsrfMiddleware->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#23 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(PKP\security\authorization\internal\ApiCsrfMiddleware), Array)
#24 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#25 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#26 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/classes/security/authorization/internal/ApiTokenDecodingMiddleware.php(140): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#27 [internal function]: PKP\security\authorization\internal\ApiTokenDecodingMiddleware->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#28 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(PKP\security\authorization\internal\ApiTokenDecodingMiddleware), Array)
#29 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#30 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#31 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/classes/handler/APIHandler.php(83): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#32 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#33 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#34 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#35 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#36 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/classes/handler/APIHandler.php(100): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#37 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#38 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#39 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#40 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#41 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/classes/handler/APIHandler.php(105): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#42 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#43 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#44 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#45 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#46 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#47 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#48 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/classes/handler/APIHandler.php(98): Slim\App->process(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#49 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#50 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#51 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#52 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#53 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/classes/handler/APIHandler.php(105): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#54 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#55 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#56 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#57 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#58 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#59 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#60 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/lib/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#61 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/classes/core/APIRouter.php(110): Slim\App->run()
#62 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\APIRouter->route(Object(APP\core\Request))
#63 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/lib/pkp/classes/core/PKPApplication.php(388): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#64 /Users/jarda/git/pkp/pkp-3_4_0/ojs-3_4_0/index.php(21): PKP\core\PKPApplication->execute()
#65 {main}
```

**What application are you using?**
 OJS, OMP or OPS version 3.4 and main

**Additional information**

<img width="1675" alt="Screenshot 2024-06-19 at 15 44 29" src="https://github.com/pkp/pkp-lib/assets/1590681/128f6f1a-711e-46e9-be79-5d003a9c6724">

**Comment by taslangraham** [comment]
I investigated this issue but was unable to reproduce it. I plan to revisit it later.

For reference, here is additional information provided by Jarda:

Imported a fresh dataset from the dataset repository.
Attempted filtering and encountered the issue.
Database: PostgreSQL

**Comment by taslangraham** [comment]
Hi @bozana,

Yes, I can create the PR. I just wasn't sure about testing it because I couldn't reproduce the issue locally.

**Comment by jardakotesovec** [comment]
@taslangraham Not even with postgresql?

**Comment by taslangraham** [comment]
@bozana 
PRs with the suggested fix:
* `stable-3_4_0`: https://github.com/pkp/pkp-lib/pull/10141
* `main`: https://github.com/pkp/pkp-lib/pull/10142

**Comment by taslangraham** [comment]
> @taslangraham Not even with postgresql?
I didn't get around to doing an installation with postgres as yet

**Comment by bozana** [comment]
All fine @taslangraham. Thanks a lot!
It would be good to always provide the submodule updates for all 3 applications (OJS, OMP and OPS) at least for the stable branches -- then the tests can be run and the users working with git can immediately have the right references to the submodules. I have merge these changes now, because I have a few pending PRs that will update the submodule...
