### ISSUE TITLE
Fatal error when removing a journal

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#10101]
**Describe the bug**
The error was simulated on the `main` branch, but it probably also exists on `stable-3_4_0`.

```php
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`ojs35`.`review_assignments`, CONSTRAINT `review_assignments_submission_id_foreign` FOREIGN KEY (`submission_id`) REFERENCES `submissions` (`submission_id`)) in lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php:605
Stack trace:
#0 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(605): PDOStatement->execute()
#1 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(809): Illuminate\Database\Connection->Illuminate\Database\{closure}('DELETE FROM jou...', Array)
#2 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(776): Illuminate\Database\Connection->runQueryCallback('DELETE FROM jou...', Array, Object(Closure))
#3 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(593): Illuminate\Database\Connection->run('DELETE FROM jou...', Array, Object(Closure))
#4 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(469): Illuminate\Database\Connection->affectingStatement('DELETE FROM jou...', Array)
#5 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Illuminate\Database\DatabaseManager->__call('affectingStatem...', Array)
#6 lib/pkp/classes/db/DAO.php(174): Illuminate\Support\Facades\Facade::__callStatic('affectingStatem...', Array)
#7 lib/pkp/classes/db/SchemaDAO.php(213): PKP\db\DAO->update('DELETE FROM jou...', Array)
#8 lib/pkp/classes/db/SchemaDAO.php(203): PKP\db\SchemaDAO->deleteById(1)
#9 lib/pkp/classes/services/PKPContextService.php(664): PKP\db\SchemaDAO->deleteObject(Object(APP\journal\Journal))
#10 lib/pkp/controllers/grid/admin/context/ContextGridHandler.php(289): PKP\services\PKPContextService->delete(Object(APP\journal\Journal))
#11 [internal function]: PKP\controllers\grid\admin\context\ContextGridHandler->deleteContext(Array, Object(APP\core\Request))
#12 lib/pkp/classes/core/PKPRouter.php(328): call_user_func(Array, Array, Object(APP\core\Request))
#13 lib/pkp/classes/core/PKPComponentRouter.php(273): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#14 lib/pkp/classes/core/Dispatcher.php(161): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#15 lib/pkp/classes/core/PKPApplication.php(379): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#16 index.php(21): PKP\core\PKPApplication->execute()
#17 {main}
```

**To Reproduce**
1. Load a dataset from the datasets repository
2. Attempt to delete the publicknowledge journal

**What application are you using?**
OJS /main

**Comment by Hafsa-Naeem** [comment]
Ready for review @asmecher
### PRs
**OJS_main:**  [pkp/pkp-lib#10101 Fix fatal error when removing a journal due to foreign key constraint #10120](https://github.com/pkp/pkp-lib/pull/10120)

**OJS_3_4_0:** [pkp/pkp-lib#10101 Fix fatal error when removing a journal due to foreign key constraint #10121](https://github.com/pkp/pkp-lib/pull/10121)

**Comment by asmecher** [comment]
Thanks, @Hafsa-Naeem, that looks good! I've added some comments to each branch PR.

**Comment by Hafsa-Naeem** [comment]
@asmecher I've updated PRs and they're ready for another review.
**OJS_main:** [PR#10120](https://github.com/pkp/pkp-lib/pull/10120)
**OJS_3_4_0:** [PR#10121](https://github.com/pkp/pkp-lib/pull/10121)

**Comment by asmecher** [comment]
Thanks, @Hafsa-Naeem! I've merged `stable-3_4_0` and left [a comment](https://github.com/pkp/pkp-lib/pull/10120/files#r1655712041) on `main`.

**Comment by Hafsa-Naeem** [comment]
@asmecher I've added a [comment](https://github.com/pkp/pkp-lib/pull/10120#discussion_r1657550918) on the PR about the `deleteById` method. Could you please share your thoughts on the next step?

**Comment by asmecher** [comment]
@Hafsa-Naeem Responded!

**Comment by Hafsa-Naeem** [comment]
Thank you @asmecher I've updated the [PR#10120](https://github.com/pkp/pkp-lib/pull/10120) and it's ready for review.

**Comment by asmecher** [comment]
All merged; closing. Thanks, @Hafsa-Naeem!
