### ISSUE TITLE
OJS 3.4.0.5 on postgres fatal error in query regarding tombstones

### ISSUE THREAD

**Issue by bdcaf** [pkp/pkp-lib#10155]
**Describe the bug**
I keep getting get errors in my log. I suppose this is related with viewing the article statistics, but the pages appear to render reasonably.
```
[03-Jul-2024 02:51:51 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[22008]: Datetime field overflow: 7 ERROR:  date/time field value out of range: "1678665600"
HINT:  Perhaps you need a different "datestyle" setting. in /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:419
```
(full log at end)

**What application are you using?**
 OJS 3.4.0.5 with postgres database

**Additional information**
Full log:

```
[03-Jul-2024 02:51:51 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[22008]: Datetime field overflow: 7 ERROR:  date/time field value out of range: "1678665600"
HINT:  Perhaps you need a different "datestyle" setting. in /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:419
Stack trace:
#0 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(419): PDOStatement->execute()
#1 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback()
#3 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\Database\Connection->run()
#4 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2705): Illuminate\Database\Connection->select()
#5 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2694): Illuminate\Database\Query\Builder->runSelect()
#6 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3230): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2693): Illuminate\Database\Query\Builder->onceWithColumns()
#8 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3157): Illuminate\Database\Query\Builder->get()
#9 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3085): Illuminate\Database\Query\Builder->aggregate()
#10 /var/www/html/lib/pkp/classes/oai/PKPOAIDAO.php(148): Illuminate\Database\Query\Builder->count()
#11 /var/www/html/classes/oai/ojs/JournalOAI.php(195): PKP\oai\PKPOAIDAO->getRecords()
#12 /var/www/html/lib/pkp/classes/oai/OAI.php(542): APP\oai\ojs\JournalOAI->records()
#13 /var/www/html/lib/pkp/classes/oai/OAI.php(95): PKP\oai\OAI->ListRecords()
#14 /var/www/html/pages/oai/OAIHandler.php(47): PKP\oai\OAI->execute()
#15 [internal function]: APP\pages\oai\OAIHandler->index()
#16 /var/www/html/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()
#17 /var/www/html/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#18 /var/www/html/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter->route()
#19 /var/www/html/lib/pkp/classes/core/PKPApplication.php(388): PKP\core\Dispatcher->dispatch()
#20 /var/www/html/index.php(21): PKP\core\PKPApplication->execute()
#21 {main}
Next Illuminate\Database\QueryException: SQLSTATE[22008]: Datetime field overflow: 7 ERROR:  date/time field value out of range: "1678665600"
HINT:  Perhaps you need a different "datestyle" setting. (SQL: select count(*) as aggregate from ((select GREATEST(a.last_modified, i.last_modified, p.last_modified) AS last_modified, "a"."submission_id" as "submission_id", "i"."issue_id", NULL AS tombstone_id, NULL AS set_spec, NULL AS oai_identifier, "j"."journal_id" as "journal_id", "s"."section_id" as "section_id" from "submissions" as "a" inner join "publications" as "p" on "a"."current_publication_id" = "p"."publication_id" inner join "publication_settings" as "psissue" on "psissue"."publication_id" = "p"."publication_id" and "psissue"."setting_name" = 'issueId' and "psissue"."locale" = '' inner join "issues" as "i" on CAST(i.issue_id AS CHAR(20)) = "psissue"."setting_value" inner join "sections" as "s" on "s"."section_id" = "p"."section_id" inner join "journals" as "j" on "j"."journal_id" = "a"."context_id" where "i"."published" = 1 and "j"."enabled" = 1 and "a"."status" = 3 and
 "j"."journal_id" = 1 and GREATEST(a.last_modified, i.last_modified, p.last_modified)::date >= 2023-03-13 and GREATEST(a.last_modified, i.last_modified, p.last_modified)::date <= 2023-03-31) union (select "dot"."date_deleted" as "last_modified", "dot"."data_object_id" as "submission_id", NULL AS issue_id, "dot"."tombstone_id", "dot"."set_spec", "dot"."oai_identifier", "tsoj"."assoc_id", NULL AS assoc_id from "data_object_tombstones" as "dot" inner join "data_object_tombstone_oai_set_objects" as "tsoj" on "tsoj"."tombstone_id" = "dot"."tombstone_id" and "tsoj"."assoc_type" = 256 and "tsoj"."assoc_id" = 1 where "dot"."date_deleted" >= 1678665600 and "dot"."date_deleted" <= 1680307199) order by journal_id, submission_id asc) as "temp_table") in /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760
Stack trace:
#0 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback()
#1 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\Database\Connection->run()
#2 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2705): Illuminate\Database\Connection->select()
#3 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2694): Illuminate\Database\Query\Builder->runSelect()
#4 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3230): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2693): Illuminate\Database\Query\Builder->onceWithColumns()
#6 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3157): Illuminate\Database\Query\Builder->get()
#7 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3085): Illuminate\Database\Query\Builder->aggregate()
#8 /var/www/html/lib/pkp/classes/oai/PKPOAIDAO.php(148): Illuminate\Database\Query\Builder->count()
#9 /var/www/html/classes/oai/ojs/JournalOAI.php(195): PKP\oai\PKPOAIDAO->getRecords()
#10 /var/www/html/lib/pkp/classes/oai/OAI.php(542): APP\oai\ojs\JournalOAI->records()
#11 /var/www/html/lib/pkp/classes/oai/OAI.php(95): PKP\oai\OAI->ListRecords()
#12 /var/www/html/pages/oai/OAIHandler.php(47): PKP\oai\OAI->execute()
#13 [internal function]: APP\pages\oai\OAIHandler->index()
#14 /var/www/html/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()
#15 /var/www/html/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#16 /var/www/html/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter->route()
#17 /var/www/html/lib/pkp/classes/core/PKPApplication.php(388): PKP\core\Dispatcher->dispatch()
#18 /var/www/html/index.php(21): PKP\core\PKPApplication->execute()
#19 {main}
  thrown in /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 760
```

**Comment by asmecher** [comment]
Hi @bdcaf! You should be able to fix this by applying https://github.com/pkp/ojs/commit/d26cf806de68a453be3749a5c9f93e8055476014. Please confirm if that fixes it for you.

**Comment by bdcaf** [comment]
Thanks. I pulled the recent `stable-3_4_0` and redeployed - so far didn't get any fatal errors in the log. Will keep an eye on it - but looking great so far.

**Comment by asmecher** [comment]
Thanks, @bdcaf! You'll have to use the OAI interface in order to exercise the changed code, if that helps. But I will close this expecting a resolution.
