### ISSUE TITLE
Upgrade fails if there are no files in usageEventLogs

### ISSUE THREAD

**Issue by SydneyUni-Jim** [pkp/pkp-lib#10244]
**Describe the bug**
The preflight check migration fails.

```
PHP Fatal error:  Uncaught ValueError: Path cannot be empty in /var/www/html/lib/pkp/classes/migration/upgrade/v3_4_0/PreflightCheckMigration.php:246
```

**To Reproduce**
1. Start with an OJS 3.3.x instance.
2. Stop the instance.
3. Process all the logs.
4. Start an upgrade to OJS 3.4.

**What application are you using?**
OJS 3.4.0.6

**Additional information**

<details><summary>Logs</summary>
<p>

```
2024-07-24 08:53:41 [migration: APP\migration\upgrade\v3_4_0\PreflightCheckMigration]
2024-07-24 08:53:41 [A pre-flight check failed. The software was successfully upgraded to 3.3.9.9 but could not be upgraded further (to 3.4.0.6). Check and correct the error, then try again.]
PHP Fatal error:  Uncaught ValueError: Path cannot be empty in /var/www/html/lib/pkp/classes/migration/upgrade/v3_4_0/PreflightCheckMigration.php:246
Stack trace:
#0 /var/www/html/lib/pkp/classes/migration/upgrade/v3_4_0/PreflightCheckMigration.php(246): SplFileObject->__construct()
#1 /var/www/html/lib/pkp/classes/migration/upgrade/v3_4_0/PreflightCheckMigration.php(234): PKP\migration\upgrade\v3_4_0\PreflightCheckMigration->checkUsageStatsLogFileUrl()
#2 /var/www/html/lib/pkp/classes/migration/upgrade/v3_4_0/PreflightCheckMigration.php(49): PKP\migration\upgrade\v3_4_0\PreflightCheckMigration->checkUsageStatsLogs()
#3 /var/www/html/classes/migration/upgrade/v3_4_0/PreflightCheckMigration.php(28): PKP\migration\upgrade\v3_4_0\PreflightCheckMigration->up()
#4 /var/www/html/lib/pkp/classes/install/Installer.php(463): APP\migration\upgrade\v3_4_0\PreflightCheckMigration->up()
#5 /var/www/html/lib/pkp/classes/install/Installer.php(294): PKP\install\Installer->executeAction()
#6 /var/www/html/lib/pkp/classes/install/Installer.php(209): PKP\install\Installer->executeInstaller()
#7 /var/www/html/lib/pkp/classes/cliTool/UpgradeTool.php(96): PKP\install\Installer->execute()
#8 /var/www/html/lib/pkp/classes/cliTool/UpgradeTool.php(69): PKP\cliTool\UpgradeTool->upgrade()
#9 /var/www/html/tools/upgrade.php(22): PKP\cliTool\UpgradeTool->execute()
#10 {main}
  thrown in /var/www/html/lib/pkp/classes/migration/upgrade/v3_4_0/PreflightCheckMigration.php on line 246
```

</p>
</details> 

PRs:
stable-3_4_0:
- https://github.com/pkp/pkp-lib/pull/10254
- https://github.com/pkp/ojs/pull/4377 (only submodule update)
- https://github.com/pkp/omp/pull/1655 (only submodule update)
- https://github.com/pkp/ops/pull/736 (only submodule update)

main:
- https://github.com/pkp/pkp-lib/pull/10257

**Comment by SydneyUni-Jim** [comment]
checkUsageStatsLogs calls checkUsageStatsLogFileUrl unconditionally. But checkUsageStatsLogFileUrl is not prepared for $checkUsageStatsLogFileUrl to be `''`.

https://github.com/pkp/pkp-lib/blob/c111708049c9ae8246a22a35aa440b6a35d8c7f9/classes/migration/upgrade/v3_4_0/PreflightCheckMigration.php#L234-L249

**Comment by asmecher** [comment]
@bozana, can you have a look at this one?

**Comment by bozana** [comment]
@jonasraoni, could you please take a look at the PR above?
Thanks a lot!
