### ISSUE TITLE
Fetching template for Participant Notify action crashes PHP backend

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#10288]
**Describe the bug**
On workflow page, when I want to notify participant - it attemps to fetch template after selecting "predefined message to use". But in 3.5 it crashes and does not display the template.

**To Reproduce**
1. Go to Workflow page to any of the existing submission
2. Click on Notify action to any of the participants that are assigned
3. Choose a predefined message to use
4. PHP backend returns 500

```
  thrown in /Users/jarda/git/pkp/pkp-main-2/ojs-main-2/lib/pkp/classes/core/JSONMessage.php on line 45
[Thu Aug  8 12:09:52 2024] [::1]:61795 [500]: POST /index.php/publicknowledge/$$$call$$$/grid/users/stage-participant/stage-participant-grid/fetch-template-body?stageId=5&submissionId=15 - Uncaught TypeError: PKP\core\JSONMessage::__construct(): Argument #2 ($content) must be of type string, array given, called in /Users/jarda/git/pkp/pkp-main-2/ojs-main-2/lib/pkp/controllers/grid/users/stageParticipant/StageParticipantGridHandler.php on line 593 and defined in /Users/jarda/git/pkp/pkp-main-2/ojs-main-2/lib/pkp/classes/core/JSONMessage.php:45
Stack trace:
#0 /Users/jarda/git/pkp/pkp-main-2/ojs-main-2/lib/pkp/controllers/grid/users/stageParticipant/StageParticipantGridHandler.php(593): PKP\core\JSONMessage->__construct(true, Array)
#1 [internal function]: PKP\controllers\grid\users\stageParticipant\StageParticipantGridHandler->fetchTemplateBody(Array, Object(APP\core\Request))
#2 /Users/jarda/git/pkp/pkp-main-2/ojs-main-2/lib/pkp/classes/core/PKPRouter.php(329): call_user_func(Array, Array, Object(APP\core\Request))
#3 /Users/jarda/git/pkp/pkp-main-2/ojs-main-2/lib/pkp/classes/core/PKPComponentRouter.php(265): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#4 /Users/jarda/git/pkp/pkp-main-2/ojs-main-2/lib/pkp/classes/core/Dispatcher.php(158): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#5 /Users/jarda/git/pkp/pkp-main-2/ojs-main-2/lib/pkp/classes/core/PKPApplication.php(386): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#6 /Users/jarda/git/pkp/pkp-main-2/ojs-main-2/index.php(21): PKP\core\PKPApplication->execute()
#7 {main}
  thrown in /Users/jarda/git/pkp/pkp-main-2/ojs-main-2/lib/pkp/classes/core/JSONMessage.php on line 45
```

**What application are you using?**
 OJS, OMP or OPS version 3.5

**Comment by asmecher** [comment]
Fixed, thanks!
