### ISSUE TITLE
[OJS 3.3.0.13] Cannot updated reviewed file, AJAX error

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#10301]
I'm getting the following error when trying to upload a reviewed file:

```
[Mon Aug 12 09:49:21.938752 2024] [php:error] [pid 64133] [client 66.249.66.4:46464] PHP Fatal error:  Uncaught InvalidArgumentException: Passed value cannot be an array in /www/public_html/lib/pkp/lib/vendor/danielstjules/stringy/src/Stringy.php:45
Stack trace:
#0 /www/public_html/lib/pkp/lib/vendor/danielstjules/stringy/src/Stringy.php(73): Stringy\\Stringy->__construct(Array, NULL)
#1 /www/public_html/lib/pkp/classes/core/PKPString.inc.php(160): Stringy\\Stringy::create(Array)
#2 /www/public_html/cache/t_compile/a95e9f20492587d73a4f35fa465ca6ee809b9709^c2055d14f27582f3361894f4184ce1a4c0497385_0.app.frontendpagessearchAuthor.php(58): PKPString::substr(Array, 0, 1)
#3 /www/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_668548700c7477_38247423(Object(Smarty_Internal_Template))
#4 /www/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#5 /www/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#6 /www/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 1)
#7 /www/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, 'a95e9f20492587d...', NULL, 1)
#8 /www/public_html/lib/pkp/classes/template/PKPTemplateManager.inc.php(1187): Smarty_Internal_TemplateBase->display('frontend/pages/...', NULL, 'a95e9f20492587d...', NULL)
#9 /www/public_html/pages/search/SearchHandler.inc.php(297): PKPTemplateManager->display('frontend/pages/...')
#10 /www/public_html/lib/pkp/classes/core/PKPRouter.inc.php(395): SearchHandler->authors(Array, Object(Request))
#11 /www/public_html/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)
#12 /www/public_html/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPPageRouter->route(Object(Request))
#13 /www/public_html/lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher->dispatch(Object(Request))
#14 /www/public_html/index.php(68): PKPApplication->execute()
#15 {main}
  thrown in /www/public_html/lib/pkp/lib/vendor/danielstjules/stringy/src/Stringy.php on line 45

```

Not sure how to further diagnostic this.

**Comment by asmecher** [comment]
@luizbgomide, that error isn't related to any trouble uploading a file in the editorial interface. The error message you quote is related to the author index page, which was removed starting with OJS 3.3.0-15 -- see https://github.com/pkp/pkp-lib/issues/7183 for details. Is there another error message that's more relevant?

**Comment by luizbgomide** [comment]
That is odd. I'm following up on a report from a user, and they described me that with a screenshot of the ajax error, saying they were trying to upload a reviewed file from the author. Looking at the logs at the time informed by them this is the only error that I've found.

I will try to investigate further.

But this error that I got, is there a patch for it anyway?

**Comment by asmecher** [comment]
@luizbgomide, the feature that involves the code in the error report was removed entirely. The PRs to do that are [in the above linked issue](https://github.com/pkp/pkp-lib/issues/7183#issuecomment-1448044764).

If you are able to find out more, feel free to add details -- but meanwhile I'll close this issue.
