### ISSUE TITLE
Cannot upgrade to OJS 3.4.0-7 (from 3.4.0.3) 

### ISSUE THREAD

**Issue by mariuszsienkiewicz** [pkp/pkp-lib#10341]
**Describe the bug**
When I run the upgrade script I get this error:

```log
2024-08-27 11:02:25 [migration: PKP\migration\upgrade\v3_4_0\I10249_FixProfileImageDataLoss]
ERROR: Upgrade failed: DB: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'setting_type' in 'field list' (SQL: update `user_settings` set `setting_value` = {"name":"profileImage-3.png","uploadName":"profileImage-3.png","width":119,"height":150,"dateUploaded":"2024-08-27 10:26:43"}, `setting_type` = object where `user_id` = 3 and `setting_name` = profileImage)
```

**To Reproduce**
1. Install 3.4.0.3
2. Try to upgrade to 3.4.0.7
3. See error

**What application are you using?**
 OJS 3.4.0.3

**Comment by asmecher** [comment]
This was caused by https://github.com/pkp/pkp-lib/issues/9851. @jonasraoni, could you take a look at this? The `user_settings` table should never have had a `setting_type` column within the 3.4.0-x line of releases, I don't think, but the migration appears to reference it.

Meanwhile, @mariuszsienkiewicz, the 3.4.0-x lines are all database-compatible with each other; you can run a 3.4.0-7 codebase with a 3.4.0-3 database without trouble.

**Comment by shantanu198713** [comment]
Same error was generated during upgradetion from OJS-3.4.0-5 to OJS-3.4.0-7.

`````
[08-Sep-2024 10:56:53 Asia/Kolkata] PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'setting_type' in 'field list' in /ojs/ojs3407/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:566
Stack trace:
#0 /ojs/ojs3407/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(566): PDO->prepare()
#1 /ojs/ojs3407/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /ojs/ojs3407/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback()
#3 /ojs/ojs3407/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(577): Illuminate\Database\Connection->run()
#4 /ojs/ojs3407/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(510): Illuminate\Database\Connection->affectingStatement()
#5 /ojs/ojs3407/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3357): Illuminate\Database\Connection->update()
#6 /ojs/ojs3407/lib/pkp/classes/migration/upgrade/v3_4_0/I10249_FixProfileImageDataLoss.php(69): Illuminate\Database\Query\Builder->update()
#7 /ojs/ojs3407/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(141): PKP\migration\upgrade\v3_4_0\I10249_FixProfileImageDataLoss->PKP\migration\upgrade\v3_4_0\{closure}()
#8 /ojs/ojs3407/lib/pkp/classes/migration/upgrade/v3_4_0/I10249_FixProfileImageDataLoss.php(72): Illuminate\Database\Query\Builder->chunkById()
#9 /ojs/ojs3407/lib/pkp/classes/install/Installer.php(463): PKP\migration\upgrade\v3_4_0\I10249_FixProfileImageDataLoss->up()
#10 /ojs/ojs3407/lib/pkp/classes/install/Installer.php(294): PKP\install\Installer->executeAction()
#11 /ojs/ojs3407/lib/pkp/classes/install/Installer.php(209): PKP\install\Installer->executeInstaller()
#12 /ojs/ojs3407/lib/pkp/classes/install/form/UpgradeForm.php(49): PKP\install\Installer->execute()
#13 /ojs/ojs3407/lib/pkp/pages/install/InstallHandler.php(148): PKP\install\form\UpgradeForm->execute()
#14 [internal function]: PKP\pages\install\InstallHandler->installUpgrade()
#15 /ojs/ojs3407/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()
#16 /ojs/ojs3407/lib/pkp/classes/core/PKPPageRouter.php(278): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#17 /ojs/ojs3407/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter->route()
#18 /ojs/ojs3407/lib/pkp/classes/core/PKPApplication.php(395): PKP\core\Dispatcher->dispatch()
#19 /ojs/ojs3407/index.php(21): PKP\core\PKPApplication->execute()
#20 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'setting_type' in 'field list' (SQL: update `user_settings` set `setting_value` = {"name":"profileImage-409.jpg","uploadName":"profileImage-409.jpg","width":749,"height":1024,"dateUploaded":"2021-11-02 11:55:09"}, `setting_type` = object where `user_id` = 409 and `setting_name` = profileImage) in /ojs/ojs3407/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760
Stack trace:
#0 /ojs/ojs3407/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback()
#1 /ojs/ojs3407/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(577): Illuminate\Database\Connection->run()
#2 /ojs/ojs3407/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(510): Illuminate\Database\Connection->affectingStatement()
#3 /ojs/ojs3407/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3357): Illuminate\Database\Connection->update()
#4 /ojs/ojs3407/lib/pkp/classes/migration/upgrade/v3_4_0/I10249_FixProfileImageDataLoss.php(69): Illuminate\Database\Query\Builder->update()
#5 /ojs/ojs3407/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(141): PKP\migration\upgrade\v3_4_0\I10249_FixProfileImageDataLoss->PKP\migration\upgrade\v3_4_0\{closure}()
#6 /ojs/ojs3407/lib/pkp/classes/migration/upgrade/v3_4_0/I10249_FixProfileImageDataLoss.php(72): Illuminate\Database\Query\Builder->chunkById()
#7 /ojs/ojs3407/lib/pkp/classes/install/Installer.php(463): PKP\migration\upgrade\v3_4_0\I10249_FixProfileImageDataLoss->up()
#8 /ojs/ojs3407/lib/pkp/classes/install/Installer.php(294): PKP\install\Installer->executeAction()
#9 /ojs/ojs3407/lib/pkp/classes/install/Installer.php(209): PKP\install\Installer->executeInstaller()
#10 /ojs/ojs3407/lib/pkp/classes/install/form/UpgradeForm.php(49): PKP\install\Installer->execute()
#11 /ojs/ojs3407/lib/pkp/pages/install/InstallHandler.php(148): PKP\install\form\UpgradeForm->execute()
#12 [internal function]: PKP\pages\install\InstallHandler->installUpgrade()
#13 /ojs/ojs3407/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()
#14 /ojs/ojs3407/lib/pkp/classes/core/PKPPageRouter.php(278): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#15 /ojs/ojs3407/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter->route()
#16 /ojs/ojs3407/lib/pkp/classes/core/PKPApplication.php(395): PKP\core\Dispatcher->dispatch()
#17 /ojs/ojs3407/index.php(21): PKP\core\PKPApplication->execute()
#18 {main}
`````

**Comment by asmecher** [comment]
Removed `setting_value` from update.
