### ISSUE TITLE
Date input parameters in article search must be checked for validity  

### ISSUE THREAD

**Issue by mpbraendle** [pkp/pkp-lib#10371]
**Describe the bug**
Non-valid characters in the date parameters of an article search in OJS lead to a white page (HTTP 500 status) and a PHP fatal error.

PHP Fatal error:  Uncaught TypeError: mktime(): Argument #6 ($year) must be of type ?int, string given in /usr/local/hope/www/ojs/lib/pkp/classes/core/PKPRequest.php:698

**To Reproduce**
1. Go to the search page of an OJS installation
2. Choose a date in the Filter section for the Published After or Published Before section carry out the search
3. in the URL in the browser, change a value of the date parameters, e.g. dateFromYear, from an integer to a non-integer value

E.g. https://{baseurl}/search/index?query=&dateFromYear=2021&dateFromMonth=2&dateFromDay=1&dateToYear=&dateToMonth=&dateToDay=&authors=

to 
https://{baseurl}/search/index?query=&dateFromYear=2021xx&dateFromMonth=2&dateFromDay=1&dateToYear=&dateToMonth=&dateToDay=&authors=

and carry the search out eg.

A white page results the PHP Fatal error:  Uncaught TypeError: mktime(): Argument error is produced.

**What application are you using?**
 OJS 3.4.0-5

** Possible solution **
Validate the input parameters and provide an error message on the page

**Additional information**
We observe these errors more than 100 times per week. Whether these are caused by faulty bot URLs or by hacking or other reasons, is unclear.

**Comment by janevsky** [comment]
i'm having the same fatal error on 3.5.0 version of ojs using php 8.2, here is the fatal error:
`[30-May-2026 14:09:49 Europe/Skopje] PHP Fatal error:  Uncaught TypeError: mktime(): Argument #5 ($day) must be of type ?int, string given in PATH/public_html/lib/pkp/classes/core/PKPRequest.php:667
Stack trace:
#0 PATH/public_html/lib/pkp/classes/core/PKPRequest.php(667): mktime()
#1 PATH/public_html/classes/search/ArticleSearch.php(188): PKP\core\PKPRequest->getUserDateVar()
#2 PATH/public_html/pages/search/SearchHandler.php(138): APP\search\ArticleSearch->getSearchFilters()
#3 PATH/public_html/pages/search/SearchHandler.php(50): APP\pages\search\SearchHandler->search()
#4 [internal function]: APP\pages\search\SearchHandler->index()
#5 PATH/public_html/lib/pkp/classes/core/PKPRouter.php(327): call_user_func()
#6 PATH/public_html/lib/pkp/classes/core/PKPPageRouter.php(249): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#7 PATH/public_html/lib/pkp/classes/core/Dispatcher.php(157): PKP\core\PKPPageRouter->route()
#8 PATH/public_html/lib/pkp/classes/core/PKPApplication.php(429): PKP\core\Dispatcher->dispatch()
#9 PATH/public_html/index.php(21): PKP\core\PKPApplication->execute()
#10 {main}
  thrown in PATH/public_html/lib/pkp/classes/core/PKPRequest.php on line 667
[30-May-2026 14:09:52 Europe/Skopje] PHP Fatal error:  Uncaught TypeError: mktime(): Argument #6 ($year) must be of type ?int, string given in PATH/public_html/lib/pkp/classes/core/PKPRequest.php:667
Stack trace:
#0 PATH/public_html/lib/pkp/classes/core/PKPRequest.php(667): mktime()
#1 PATH/public_html/classes/search/ArticleSearch.php(188): PKP\core\PKPRequest->getUserDateVar()
#2 PATH/public_html/pages/search/SearchHandler.php(138): APP\search\ArticleSearch->getSearchFilters()
#3 PATH/public_html/pages/search/SearchHandler.php(50): APP\pages\search\SearchHandler->search()
#4 [internal function]: APP\pages\search\SearchHandler->index()
#5 PATH/public_html/lib/pkp/classes/core/PKPRouter.php(327): call_user_func()
#6 PATH/public_html/lib/pkp/classes/core/PKPPageRouter.php(249): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#7 PATH/public_html/lib/pkp/classes/core/Dispatcher.php(157): PKP\core\PKPPageRouter->route()
#8 PATH/public_html/lib/pkp/classes/core/PKPApplication.php(429): PKP\core\Dispatcher->dispatch()
#9 PATH/public_html/index.php(21): PKP\core\PKPApplication->execute()
#10 {main}
  thrown in PATH/public_html/lib/pkp/classes/core/PKPRequest.php on line 667
[30-May-2026 14:09:53 Europe/Skopje] PHP Fatal error:  Uncaught TypeError: mktime(): Argument #4 ($month) must be of type ?int, string given in PATH/public_html/lib/pkp/classes/core/PKPRequest.php:667
Stack trace:
#0 PATH/public_html/lib/pkp/classes/core/PKPRequest.php(667): mktime()
#1 PATH/public_html/classes/search/ArticleSearch.php(188): PKP\core\PKPRequest->getUserDateVar()
#2 PATH/public_html/pages/search/SearchHandler.php(138): APP\search\ArticleSearch->getSearchFilters()
#3 PATH/public_html/pages/search/SearchHandler.php(50): APP\pages\search\SearchHandler->search()
#4 [internal function]: APP\pages\search\SearchHandler->index()
#5 PATH/public_html/lib/pkp/classes/core/PKPRouter.php(327): call_user_func()
#6 PATH/public_html/lib/pkp/classes/core/PKPPageRouter.php(249): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#7 PATH/public_html/lib/pkp/classes/core/Dispatcher.php(157): PKP\core\PKPPageRouter->route()
#8 PATH/public_html/lib/pkp/classes/core/PKPApplication.php(429): PKP\core\Dispatcher->dispatch()
#9 PATH/public_html/index.php(21): PKP\core\PKPApplication->execute()
#10 {main}
  thrown in PATH/public_html/lib/pkp/classes/core/PKPRequest.php on line 667`

**Comment by janevsky** [comment]
Here is a workaround i made, not sure if its right but i don't have the errors anymore, i want a clear phperror.log to catch some other important errors
https://github.com/janevsky/dateValidatorOJS

**Comment by asmecher** [comment]
@mpbraendle and @janevsky, I fixed this in the `stable-3_5_0` branch for release in OJS/OMP/OPS 3.5.0-5 (LTS) later this month. The fixes in https://github.com/pkp/pkp-lib/commit/9b601a9f384496184188e6bf6c428e64dc57e117 (lib/pkp submodule for OJS, OMP, and OJS) and https://github.com/pkp/ojs/commit/a2836ee0a496ca6009155e67f81eeeb5f4d32f60 (OJS and OPS) will probably apply cleanly to `stable-3_4_0` but I'm not going to port them back further than that.

Evidence:
- Replicated the error with a URL of the form: `http://localhost/git/ojs-main/index.php/publicknowledge/en/search/index?query=&dateFromYear=2026xx&dateFromMonth=&dateFromDay=&dateToYear=2026&dateToMonth=&dateToDay=`
- Applied the changes
- Tested the URL again; no error reported. (Repeated for `stable-3_5_0` and `main`, OJS and OPS. OMP does not have a publication date in the search form.)

**Comment by janevsky** [comment]
Hello @asmecher ,

I did the fix and tried the form you used https://domain/prefix/search?query=&dateFromYear=2026xx&dateFromMonth=&dateFromDay=&dateToYear=2026&dateToMonth=&dateToDay=

Got this in phperror.log
`[03-Jun-2026 10:03:59 Europe/Skopje] PHP Fatal error:  Uncaught TypeError: mktime(): Argument #6 ($year) must be of type ?int, string given in /home/jhrs/domains/jhrs.almamater.si/public_html/pages/search/SearchHandler.php:93
Stack trace:
#0 /home/jhrs/domains/jhrs.almamater.si/public_html/pages/search/SearchHandler.php(93): mktime()
#1 /home/jhrs/domains/jhrs.almamater.si/public_html/pages/search/SearchHandler.php(161): APP\pages\search\SearchHandler->_assignSearchFilters()
#2 /home/jhrs/domains/jhrs.almamater.si/public_html/pages/search/SearchHandler.php(50): APP\pages\search\SearchHandler->search()
#3 [internal function]: APP\pages\search\SearchHandler->index()
#4 /home/jhrs/domains/jhrs.almamater.si/public_html/lib/pkp/classes/core/PKPRouter.php(327): call_user_func()
#5 /home/jhrs/domains/jhrs.almamater.si/public_html/lib/pkp/classes/core/PKPPageRouter.php(249): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#6 /home/jhrs/domains/jhrs.almamater.si/public_html/lib/pkp/classes/core/Dispatcher.php(157): PKP\core\PKPPageRouter->route()
#7 /home/jhrs/domains/jhrs.almamater.si/public_html/lib/pkp/classes/core/PKPApplication.php(429): PKP\core\Dispatcher->dispatch()
#8 /home/jhrs/domains/jhrs.almamater.si/public_html/index.php(21): PKP\core\PKPApplication->execute()
#9 {main}
  thrown in /home/jhrs/domains/jhrs.almamater.si/public_html/pages/search/SearchHandler.php on line 93`

**Comment by asmecher** [comment]
@janevsky, did you apply both patches?

**Comment by janevsky** [comment]
@asmecher yes, but now as i tested it works without any errors, i believe as soon as i changed both files tested the url and the changes did not take effect that fast. Thank you very much.
