### ISSUE TITLE
[OMP] Fatal error when creating a series menu item without content

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#10511]
**Describe the bug**
After creating a series menu item without linking it to any item (see image below), a fatal error happens.

![image](https://github.com/user-attachments/assets/13f7e62a-8e0c-458a-a2c8-adcd6b5b2adb)

```php
PHP Fatal error:  Uncaught TypeError: PKP\section\Repository::get(): Argument #1 ($id) must be of type int, string given, called in classes/services/NavigationMenuService.php on line 157 and defined in lib/pkp/classes/section/Repository.php:58
Stack trace:
#0 classes/services/NavigationMenuService.php(157): PKP\section\Repository->get()
#1 [internal function]: APP\services\NavigationMenuService->getDisplayStatusCallback()
#2 lib/pkp/classes/plugins/Hook.php(139): call_user_func_array()
#3 lib/pkp/classes/plugins/Hook.php(113): PKP\plugins\Hook::run()
#4 lib/pkp/classes/services/PKPNavigationMenuService.php(382): PKP\plugins\Hook::call()
```

The strange thing that needs to be analyzed is that a call to `$navigationMenuItem->getPath()` outputs Laravel code `�*�escapeWhenCastingToString`.

A workaround must be left for bad cases, and the field should be probably turned into required. If the ID is a physical field, it can be setup as not null, but a further script should clear invalid data on the upgrade.

It's also needed to check if the bug applies to OMP 3.3

**To Reproduce**
1. Create a series menu item, like in the sample image
2. Add it to the navigation
3. See the error

**What application are you using?**
OMP 3.4

**Pull requests**
- OMP 3.4: https://github.com/pkp/omp/pull/1763
- OMP main: https://github.com/pkp/omp/pull/1772
- OMP 3.5 (postgres upgrade error fix): https://github.com/pkp/omp/pull/1875
- OMP main (postgres upgrade error fix): https://github.com/pkp/omp/pull/1882

**Comment by YvesLepidus** [comment]
Hi @jonasraoni ! 😃 
I've created a [PR](https://github.com/pkp/omp/pull/1763) to fix the display of series without content when creating a series-type menu item, even when there are series enabled in OMP 3.4.
I think this may also fix this fatal error, given that it is not possible to add a series-type menu item when there are no series registered in OMP.

**Comment by jonasraoni** [comment]
I've checked your PR and it makes sense, I'll update and approve it.

Nevertheless, I'll leave this issue open, it might be possible to create a menu without series yet (e.g. if you create the menu before creating a series) and there's also the people who already have a bad menu on the database.

**Comment by kaitlinnewson** [comment]
@jonasraoni I tested how it works when no series are present, and there is no option to create a series menu if no series exists, so that case already seems to be covered.

**Comment by jonasraoni** [comment]
Great, so there's just one thing to fix, the existing bad records.

**Comment by kaitlinnewson** [comment]
Thanks @YvesLepidus! Your PR is now merged to 3.4, and I can cherry-pick this to main for the 3.5 release and work on the issue with bad records.

**Comment by jonasraoni** [comment]
@kaitlinnewson I was going to handle this one, but as you've self-assigned, please take a look at the `The strange thing that needs to be analyzed is that a call to $navigationMenuItem->getPath() outputs Laravel code �*�escapeWhenCastingToString.`.

Basically, setup a bad menu, then check this line:
https://github.com/pkp/omp/blob/ef4fa4e98015d2af1f7b47dae3dad9e39198e17f/classes/services/NavigationMenuService.php#L156

If you can't reproduce, great 😂

**Comment by kaitlinnewson** [comment]
@jonasraoni I think this is happening when Smarty is trying to convert the Collection objects into strings but failing. With the bad code, this error is logged when creating the bad series menu item:

`[Fri Nov 22 10:26:35 2024] PHP Notice:  html_options: value is an object of class 'Closure' without __toString() method in /Users/kaitlinnewson/Code/omp-3_4_0/lib/pkp/lib/vendor/smarty/smarty/libs/plugins/function.html_options.php on line 184`

...and this is a snippet of what gets rendered in the HTML with the bad code:

```
<label for="seriesSelect">Select Series</label>						
<div>
<select id="relatedSeriesId" name="relatedSeriesId" required="" aria-required="true" aria-invalid="false">
    <option value="�*�escapeWhenCastingToString"></option>
</select>
```

... and as a result of this, `�*�escapeWhenCastingToString` is written to the database as the `path` value in `navigation_menu_items`, so that is what is being returned by `getPath()`.

Is anything needed beyond removing the bad entries?

**Comment by kaitlinnewson** [comment]
I think it's better to remove them, because if they are assigned to a menu they produce a fatal error and blank white screen on the page where the menu is assigned (so they aren't usable at all).

I can test the other scenario you mentioned, and file another issue for that if I find issues with orphaned entries when a series is deleted.

**Comment by asmecher** [comment]
(The `�*�` in `�*�escapeWhenCastingToString` is what you get when PHP serializes a private/protected attribute. [Reference](https://www.phpinternalsbook.com/php5/classes_objects/serialization.html))

**Comment by jonasraoni** [comment]
Just to confirm, I deleted a series and the menu was kept, I guess other "entity links" might have the same issue.

And I think it's worth to fix the origin of the issue (the `TypeError`), which can be done by coercing the `getPath()` calls to an integer where suitable.

**Comment by asmecher** [comment]
@kaitlinnewson and @jonasraoni, this appears to have been merged/fixed in 3.4.0 but not `main`, correct? I'm wrapping up the 3.4.0-8 release and want to make sure I get the release notes accurately.

**Comment by kaitlinnewson** [comment]
@asmecher yes, this is merged for `stable-3_4_0` but in review for `main`.

**Comment by asmecher** [comment]
@jonasraoni and @kaitlinnewson, this causes upgrade [testing to fail in PostgreSQL](https://github.com/pkp/omp/actions/runs/13598152669/job/38019420964):

![Image](https://github.com/user-attachments/assets/ef58c1d8-a7b6-4bc3-ac6e-402e1867ba49)

Could you have a look?

**Comment by asmecher** [comment]
@kaitlinnewson, just checking -- did this one get resolved?

**Comment by kaitlinnewson** [comment]
Hi @asmecher, I've linked the PR above, waiting for review.
