### ISSUE TITLE
Native XML Export/Import is not handling internal review round correctly

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#10606]
**Describe the bug**
While debugging e2e tests - it turned out that export/import test is corrupting data and results in submission which is in internal review (OMP), but without review round created - which is always expected to be there and therefore it crashes at least in one place..

Test is temporarily disabled. Its not easy to pin point if its long standing bug or regression, as this test was disabled for some time - https://github.com/pkp/pkp-lib/issues/10115 .   And the crash is coming from the new code in submission listing.

**To Reproduce**
1. Run MsmithSubmission.cy.js test
2. Re-enable the Import test in NativeXmlImportExportSubmission.cy.js and run it
3. Check the data structure - its missing review round, which is crashing new submission listing

Tested only in 3.5. Once investigated, it might be good to check the older versions if they might be affected by this.

**What application are you using?**
 OJS, OMP or OPS version 3.5 

**Additional information**
Here is crash stack trace when rendering new submission listing. It fails, because it assume that there is always review round for active stage.

```
[Wed Nov 13 15:47:06 2024] 127.0.0.1:44570 [500]: GET /index.php/publicknowledge/api/v1/_submissions?status=1&offset=0&count=30&page=1&perPage=30
[Wed Nov 13 15:47:06 2024] 127.0.0.1:44570 Closing
[Wed Nov 13 15:47:06 2024] 127.0.0.1:44578 Accepted
[Wed Nov 13 15:47:07 2024] Error: Call to a member function getId() on null in /home/runner/omp/classes/submission/maps/Schema.php:183
Stack trace:
#0 /home/runner/omp/lib/pkp/classes/submission/maps/Schema.php(654): APP\submission\maps\Schema->getAvailableEditorialDecisions()
#1 /home/runner/omp/lib/pkp/classes/submission/maps/Schema.php(393): PKP\submission\maps\Schema->getPropertyStages()
#2 /home/runner/omp/classes/submission/maps/Schema.php(65): PKP\submission\maps\Schema->mapByProperties()
#3 /home/runner/omp/lib/pkp/classes/submission/maps/Schema.php(250): APP\submission\maps\Schema->mapByProperties()
#4 /home/runner/omp/lib/pkp/classes/submission/maps/Schema.php(285): PKP\submission\maps\Schema->mapToSubmissionsList()
#5 /home/runner/omp/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Collections/LazyCollection.php(779): PKP\submission\maps\Schema->PKP\submission\maps\{closure}()
#6 /home/runner/omp/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Collections/LazyCollection.php(1707): Illuminate\Support\LazyCollection->Illuminate\Support\{closure}()
#7 [internal function]: Illuminate\Support\LazyCollection->Illuminate\Support\{closure}()
#8 /home/runner/omp/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Collections/LazyCollection.php(106): iterator_to_array()
#9 /home/runner/omp/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(964): Illuminate\Support\LazyCollection->all()
#10 [internal function]: Illuminate\Support\LazyCollection->jsonSerialize()

```

PRs:
- https://github.com/pkp/pkp-lib/pull/10697

**Comment by jardakotesovec** [comment]
Temporarly disabled 2 doi tests, as these were impacted by disabling import/export in pkp-lib.

**Comment by withanage** [comment]
We wlll exend the review rounds in the exports and import them

**Comment by bozana** [comment]
Hi @withanage, @asmecher, @jardakotesovec,

We do not export review rounds, and back then Dimitris also excluded the files that are connected to objects that are not exported (e.g. review files, review attachments, review revisions) because they were making problems, s. https://github.com/pkp/pkp-lib/issues/8137.
Thus, our export XML never contains any information about reviews/review rounds. When such a submission is imported and when we then go to the review stage of such a submission it only displays "The review process has not yet been initiated." without a possibility to do anything (no grids, no buttons, nothing).
The current main branch behaves the same if the submission is not in the review stage.
If the submission is in the review stage however, we expect a review round to exist and thus error occurs.
To solve this I see these possibilities:
1. When a submission in a review stage is imported, create a review round. The problem here is that we would create a review round as there were no reviews/actions done before, which might not be true -- the exported submission could eventually have the reviewers and everything almost finished, it could have several review rounds, etc. -- this just would not be exported. However I believe this is the quickest and at this moment best possible fix.
2. Do not import the submissions in review at all. If someone really needs to export and import immediately, this would make less sense than the first solution.
3. Depending on our future plans i.e. how we would like to deal with review exports, we could consider implementing review round exports now -- that means to expect it to be there in the import XML. I/we would need to investigate what all information we could then consider for export (e.g. what review round statuses, files, etc). This solution, however, does not necessarily exclude #1 -- we can consider #1 however, in case there is no review round data in the import XML file and the submission is in the review stage.
This solution can be done in parallel and maybe not necessarily for 3.5. But maybe to first discuss if this is the way we would like to go in general with our export/import tool (@asmecher)?

So I suppose we can proceed with #1 for 3.5 (@withanage).

Submissions in other stages might have reviews finished but no review rounds. @jardakotesovec, do you maybe see other problems with this (when a review round does not exist and submission is in another (not review) stage) and the new code? -- This can be the case from earlier and when the submissions are imported using native import/export.

Thanks!

**Comment by asmecher** [comment]
Thanks, @bozana -- I would agree with no. 1 as the best approach for now. I don't expect we're going to extend the XML import/export toolset to support much more -- it's more sustainable to expand the JSON API and build future tools to interact with that as a means of batch import/export.

**Comment by withanage** [comment]
Hi @bozana  and @asmecher ,

Thanks for the inputs. I have updated the PR with @bozana s suggestion (1).

**Comment by bozana** [comment]
Hi @withanage, would you add the OJS, OMP and OPS PRs (with native importexport tests commented out again)? When the tests pass, we can merge...

**Comment by withanage** [comment]
@bozana  I merged the changes to OMP and OJS. OPS main branch seems to be broken. Therefore did not merge yet.
- 
- https://github.com/pkp/ojs/pull/4622/checks
-  https://github.com/pkp/omp/pull/1816/checks
-

**Comment by asmecher** [comment]
@withanage, could you rebase and see if the OPS main is working now? This would be good to wrap up for RC1.

**Comment by withanage** [comment]
Hi @asmecher 

sorry, forgot to close the issue and the functionality is working in the ops https://github.com/withanage/ops/actions/runs/13540692875/job/37840877445#step:3:2324


it was integrated in the Vitaliys summodule update https://github.com/pkp/ops/pull/858/files#diff-c19afe164738139d345a940eb083ada822cb4e7e34a6d11bbdf91e1dcd84265f

We can close this issue.

**Comment by asmecher** [comment]
Closing, thanks!
