### ISSUE TITLE
Saving empty references throws an error

### ISSUE THREAD

**Issue by GaziYucel** [pkp/pkp-lib#10629]
**Describe the bug**
If the References are emptied and saved, an error is shown. Saving a second time does not show the error anymore. The change is however saved to the database. 

**To Reproduce**
1. Activate metadata References: Settings > Workflow > Submission > Metadata > References
2. Go to Submissions and open any submission
3. Open References tab: Publication > References
4. Add any text in the textbox
5. Save
6. Empty the references textbox
7. Save => error: the empty references are saved to the database (citations, publication_settings table rows are deleted)
8. Save again, no more error

**What application are you using?**
 OJS version 3.4.0-5, 3.4.0.7

**Additional information**
The error message shown, is thrown here: https://github.com/pkp/pkp-lib/blob/a1caad182db02667ecebe229fb888c8d23423743/classes/filter/Filter.php#L444

This is the error logged in apache2
```
[php:notice] [pid 19534] [client 127.0.0.1:40484]
Slim Application Error:\nType: Exception\nMessage: Filter (Split a reference list into separate citations) supports input string - NULL given\nFile: /var/www/html/ojs340-7/lib/pkp/classes/filter/Filter.php\nLine: 484\nTrace: #0 /var/www/html/ojs340-7/lib/pkp/classes/citation/CitationDAO.php(98): PKP\\filter\\Filter->execute()\n#1 /var/www/html/ojs340-7/lib/pkp/classes/publication/DAO.php(527): PKP\\citation\\CitationDAO->importCitations()\n#2 /var/www/html/ojs340-7/lib/pkp/classes/publication/DAO.php(245): PKP\\publication\\DAO->saveCitations()\n#3 /var/www/html/ojs340-7/lib/pkp/classes/publication/Repository.php(394): PKP\\publication\\DAO->update()\n#4 /var/www/html/ojs340-7/lib/pkp/api/v1/submissions/PKPSubmissionHandler.php(1123): PKP\\publication\\Repository->edit()\n#5 [internal function]: PKP\\API\\v1\\submissions\\PKPSubmissionHandler->editPublication()\n#6 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()\n#7 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(281): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()\n#8 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\Route->__invoke()\n#9 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(268): Slim\\Route->callMiddlewareStack()\n#10 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/App.php(503): Slim\\Route->run()\n#11 /var/www/html/ojs340-7/lib/pkp/classes/security/authorization/internal/ApiAuthorizationMiddleware.php(90): Slim\\App->__invoke()\n#12 [internal function]: PKP\\security\\authorization\\internal\\ApiAuthorizationMiddleware->__invoke()\n#13 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()\n#14 [internal function]: Slim\\DeferredCallable->__invoke()\n#15 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()\n#16 /var/www/html/ojs340-7/lib/pkp/classes/security/authorization/internal/ApiCsrfMiddleware.php(56): Slim\\App->Slim\\{closure}()\n#17 [internal function]: PKP\\security\\authorization\\internal\\ApiCsrfMiddleware->__invoke()\n#18 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()\n#19 [internal function]: Slim\\DeferredCallable->__invoke()\n#20 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()\n#21 /var/www/html/ojs340-7/lib/pkp/classes/security/authorization/internal/ApiTokenDecodingMiddleware.php(140): Slim\\App->Slim\\{closure}()\n#22 [internal function]: PKP\\security\\authorization\\internal\\ApiTokenDecodingMiddleware->__invoke()\n#23 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()\n#24 [internal function]: Slim\\DeferredCallable->__invoke()\n#25 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()\n#26 /var/www/html/ojs340-7/lib/pkp/classes/handler/APIHandler.php(83): Slim\\App->Slim\\{closure}()\n#27 [internal function]: PKP\\handler\\APIHandler->PKP\\handler\\{closure}()\n#28 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()\n#29 [internal function]: Slim\\DeferredCallable->__invoke()\n#30 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()\n#31 /var/www/html/ojs340-7/lib/pkp/classes/handler/APIHandler.php(100): Slim\\App->Slim\\{closure}()\n#32 [internal function]: PKP\\handler\\APIHandler->PKP\\handler\\{closure}()\n#33 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()\n#34 [internal function]: Slim\\DeferredCallable->__invoke()\n#35 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()\n#36 /var/www/html/ojs340-7/lib/pkp/classes/handler/APIHandler.php(105): Slim\\App->Slim\\{closure}()\n#37 [internal function]: PKP\\handler\\APIHandler->PKP\\handler\\{closure}()\n#38 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()\n#39 [internal function]: Slim\\DeferredCallable->__invoke()\n#40 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()\n#41 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\App->Slim\\{closure}()\n#42 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\\App->callMiddlewareStack()\n#43 /var/www/html/ojs340-7/lib/pkp/classes/handler/APIHandler.php(98): Slim\\App->process()\n#44 [internal function]: PKP\\handler\\APIHandler->PKP\\handler\\{closure}()\n#45 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()\n#46 [internal function]: Slim\\DeferredCallable->__invoke()\n#47 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()\n#48 /var/www/html/ojs340-7/lib/pkp/classes/handler/APIHandler.php(105): Slim\\App->Slim\\{closure}()\n#49 [internal function]: PKP\\handler\\APIHandler->PKP\\handler\\{closure}()\n#50 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()\n#51 [internal function]: Slim\\DeferredCallable->__invoke()\n#52 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()\n#53 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\App->Slim\\{closure}()\n#54 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\\App->callMiddlewareStack()\n#55 /var/www/html/ojs340-7/lib/pkp/lib/vendor/slim/slim/Slim/App.php(297): Slim\\App->process()\n#56 /var/www/html/ojs340-7/lib/pkp/classes/core/APIRouter.php(110): Slim\\App->run()\n#57 /var/www/html/ojs340-7/lib/pkp/classes/core/Dispatcher.php(165): PKP\\core\\APIRouter->route()\n#58 /var/www/html/ojs340-7/lib/pkp/classes/core/PKPApplication.php(395): PKP\\core\\Dispatcher->dispatch()\n#59 /var/www/html/ojs340-7/index.php(21): PKP\\core\\PKPApplication->execute()\n#60 {main}\nView in rendered output by enabling the "displayErrorDetails" setting.
referer: http://localhost/ojs340-7/index.php/publicknowledge/workflow/index/15/5
```

**Comment by bozana** [comment]
This will be addressed here: https://github.com/pkp/pkp-lib/issues/11238
