### ISSUE TITLE
Fatal error when saving theme option at site level

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#10714]
**Describe the bug**
A fatal error is encountered when saving a theme option at the site level.

**To Reproduce**

1. Make sure the site has more than one Hosted Journal.
3. Go to Administration > Site Settings > Appearance > Theme
4. Select Default Theme and save the form.
5. See error

**What application are you using?**
`main` branch (3.5 pre-release)

**Additional information**
Error message:

```
Error: Call to a member function getId() on null in /lib/pkp/classes/plugins/ThemePlugin.php:665
Stack trace:
#0 /lib/pkp/classes/plugins/ThemePlugin.php(660): PKP\plugins\ThemePlugin->saveOption('typography', 'notoSans', NULL)
#1 /lib/pkp/api/v1/site/PKPSiteController.php(225): PKP\plugins\ThemePlugin->saveOption('typography', 'notoSans', NULL)
#2 /lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Routing/CallableDispatcher.php(40): PKP\API\v1\site\PKPSiteController->editTheme(Object(Illuminate\Http\Request), 'index', 'v1')
#3 /lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Routing/Route.php(243): Illuminate\Routing\CallableDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Closure))
#4 /lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Routing/Route.php(214): Illuminate\Routing\Route->runCallable()
#5...
#6...
```

**Comment by NateWr** [comment]
The following PR fixes this issue, but I'm not sure about the side effects. The key code is `ThemePlugin::saveOption()`. In previous versions, it looked like this:

```php
public function saveOption($name, $value, $contextId = null)
{
    // ...
    if (is_null($contextId)) {
        $context = Application::get()->getRequest()->getContext();
        $contextId = $context->getId();
    }
}
```

This worked because site-level theme options passed a `$contextId` of `0`. In 3.5, they now pass `null`, so `$context->getId()` gets called without a context. This PR fixes this by checking if there is a request context. However, there is no way to know if `null` was passed to the function deliberately. In other words, there is no way to save a site-level theme option from a request with a context. 

(This is probably bad practice anyway, though I can imagine some unusual use cases, like letting a journal manager self-select an option that is then compiled into an array of all journals that is saved at the site level.)

PR:
https://github.com/pkp/pkp-lib/pull/10715

Tests:
https://github.com/pkp/ojs/pull/4558

**Comment by asmecher** [comment]
Thanks, @NateWr! I've gone ahead and merged the fix for lack of other opinions. I'll take care of the submodule update separately.
