### ISSUE TITLE
Viewing task level notification related to the PayPal payment leads to fatal error

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#10732]
**Describe the bug**
Fatal error occurs when author tries to view notification for making a PayPal plugin payment.

**To Reproduce**
1. Turn on payments by PayPal plugin
2. Make a new submission
3. Sign in as an editor, move submission to the copyediting stage and approve sending payment in the decision step
4. Log in as an author and click on the new notification 

**What application are you using?**
 OJS main branch

**Additional information**
```
127.0.0.1:49733 [500]: GET /index.php/publicknowledge/$$$call$$$/grid/notifications/task-notifications-grid/fetch-grid - Uncaught Error: Call to undefined method APP\submission\Submission::getLocalizedTitle() in /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/controllers/grid/notifications/NotificationsGridCellProvider.php:126
Stack trace:
#0 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/controllers/grid/notifications/NotificationsGridCellProvider.php(63): PKP\controllers\grid\notifications\NotificationsGridCellProvider->_getTitle(Object(PKP\notification\Notification))
#1 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/controllers/grid/GridCellProvider.php(66): PKP\controllers\grid\notifications\NotificationsGridCellProvider->getCellActions(Object(APP\core\Request), Object(PKP\controllers\grid\GridRow), Object(PKP\controllers\grid\GridColumn))
#2 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/controllers/grid/GridHandler.php(1264): PKP\controllers\grid\GridCellProvider->render(Object(APP\core\Request), Object(PKP\controllers\grid\GridRow), Object(PKP\controllers\grid\GridColumn))
#3 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/controllers/grid/GridHandler.php(1165): PKP\controllers\grid\GridHandler->_renderCellInternally(Object(APP\core\Request), Object(PKP\controllers\grid\GridRow), Object(PKP\controllers\grid\GridColumn))
#4 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/controllers/grid/GridHandler.php(1140): PKP\controllers\grid\GridHandler->renderRowInternally(Object(APP\core\Request), Object(PKP\controllers\grid\GridRow))
#5 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/controllers/grid/GridHandler.php(1190): PKP\controllers\grid\GridHandler->renderRowsInternally(Object(APP\core\Request), Array)
#6 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/controllers/grid/GridHandler.php(1065): PKP\controllers\grid\GridHandler->renderGridBodyPartsInternally(Object(APP\core\Request))
#7 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/controllers/grid/GridHandler.php(737): PKP\controllers\grid\GridHandler->doSpecificFetchGridActions(Array, Object(APP\core\Request), Object(APP\template\TemplateManager))
#8 [internal function]: PKP\controllers\grid\GridHandler->fetchGrid(Array, Object(APP\core\Request))
#9 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPRouter.php(329): call_user_func(Array, Array, Object(APP\core\Request))
#10 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPComponentRouter.php(265): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#11 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/Dispatcher.php(158): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#12 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPApplication.php(395): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#13 /Users/vitalii/Documents/development/ojs-main/ojs/index.php(30): PKP\core\PKPApplication->execute()
#14 {main}
  thrown in /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/controllers/grid/notifications/NotificationsGridCellProvider.php on line 126
```

**Comment by Vitaliy-1** [comment]
PR: https://github.com/pkp/pkp-lib/pull/10733
