### ISSUE TITLE
Unable to load user roles on profile page (undefined method UserGroup::getIdsByUserId)

### ISSUE THREAD

**Issue by kaitlinnewson** [pkp/pkp-lib#10749]
**Describe the bug**
On the user profile page, the roles tab does not currently load due to an undefined method in UserGroup (called in `lib/pkp/classes/user/form/RolesForm.php`).

**To Reproduce**
1. Login as any user
2. Click View Profile in the top right corner
3. Click the Roles tab

**What application are you using?**
 OJS, OMP or OPS version main

**Additional information**

```
[Fri Dec 20 10:54:29 2024] [::1]:61758 [500]: GET /index.php/index/$$$call$$$/tab/user/profile-tab/roles?_=1734706467347 - Uncaught BadMethodCallException: Call to undefined method PKP\userGroup\UserGroup::getIdsByUserId() in /Users/kaitlinnewson/Code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:67
Stack trace:
#0 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\Database\Eloquent\Model::throwBadMethodCallException('getIdsByUserId')
#1 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2367): Illuminate\Database\Eloquent\Model->forwardCallTo(Object(PKP\core\SettingsBuilder), 'getIdsByUserId', Array)
#2 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2379): Illuminate\Database\Eloquent\Model->__call('getIdsByUserId', Array)
#3 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/user/form/RolesForm.php(46): Illuminate\Database\Eloquent\Model::__callStatic('getIdsByUserId', Array)
#4 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/controllers/tab/user/ProfileTabHandler.php(162): PKP\user\form\RolesForm->fetch(Object(APP\core\Request))
#5 [internal function]: PKP\controllers\tab\user\ProfileTabHandler->roles(Array, Object(APP\core\Request))
#6 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/core/PKPRouter.php(329): call_user_func(Array, Array, Object(APP\core\Request))
#7 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/core/PKPComponentRouter.php(265): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#8 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/core/Dispatcher.php(158): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#9 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/core/PKPApplication.php(395): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#10 /Users/kaitlinnewson/Code/ojs-main/index.php(30): PKP\core\PKPApplication->execute()
#11 {main}
  thrown in /Users/kaitlinnewson/Code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php on line 67
```

**Comment by touhidurabir** [comment]
will be fixed by pkp/pkp-lib#10292 . changes are applied at https://github.com/pkp/pkp-lib/pull/10324/files#diff-6ba4523ffcafe662bb4a14b8f334bf49935aca719f0484737399c004c1f91642R46-R50

**Comment by Tribunal33** [comment]
@touhidurabir and @kaitlinnewson any reason this broke?  it was working previously.

**Comment by touhidurabir** [comment]
@Tribunal33 this probably a regression introduced by https://github.com/pkp/pkp-lib/issues/10506

**Comment by touhidurabir** [comment]
Fixed and merged as part of https://github.com/pkp/pkp-lib/issues/10292
