### ISSUE TITLE
EditorialMasthead page not loading with Uncaught TypeError (userGroup)

### ISSUE THREAD

**Issue by kaitlinnewson** [pkp/pkp-lib#10751]
**Describe the bug**
The Editorial Masthead page is not loading due to a fatal error from the userGroup class - "`Uncaught TypeError: PKP\userGroup\Repository::getMastheadUserIdsByRoleIds()`"

**To Reproduce**
1. On a journal home page, open the Editorial Masthead page from the main navigation
2. See error

**Expected Behaviour**
When the editorial masthead link is clicked, it should open the editorial masthead page, which contains information about past editors and peer reviewers.

**What application are you using?**
 OJS, OMP or OPS version main

**Additional information**

```
[Mon Dec 23 13:50:27 2024] [::1]:57777 [500]: GET /index.php/publicknowledge/en/about/editorialMasthead - Uncaught TypeError: PKP\userGroup\Repository::getMastheadUserIdsByRoleIds(): Argument #1 ($mastheadRoles) must be of type array, Illuminate\Database\Eloquent\Collection given, called in /Users/kaitlinnewson/Code/ojs-main/lib/pkp/pages/about/AboutContextHandler.php on line 97 and defined in /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/userGroup/Repository.php:572
Stack trace:
#0 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/pages/about/AboutContextHandler.php(97): PKP\userGroup\Repository->getMastheadUserIdsByRoleIds(Object(Illuminate\Database\Eloquent\Collection), 1)
#1 [internal function]: PKP\pages\about\AboutContextHandler->editorialMasthead(Array, Object(APP\core\Request))
#2 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/core/PKPRouter.php(329): call_user_func(Array, Array, Object(APP\core\Request))
#3 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/core/PKPPageRouter.php(253): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#4 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/core/Dispatcher.php(158): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#5 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/core/PKPApplication.php(395): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#6 /Users/kaitlinnewson/Code/ojs-main/index.php(30): PKP\core\PKPApplication->execute()
#7 {main}
  thrown in /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/userGroup/Repository.php on line 572
```

**PRs**
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/10754
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4571 [TEST ONLY]
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1798 [TEST ONLY]
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/835 [TEST ONLY]

**Comment by Tribunal33** [comment]
@kaitlinnewson What is the expected outcome?

**Comment by touhidurabir** [comment]
@Vitaliy-1 can you please review the PR at https://github.com/pkp/pkp-lib/issues/10751#issue-2756499673 . It seems like a regression introduced by pkp/pkp-lib#10506 .
