### ISSUE TITLE
Spotlight grid causes fatal error

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1961]
When I try to load the Spotlight grid under Catalog > Spotlights in the current OMP `master` branch, I get the following fatal PHP error:

```
[Tue Nov 08 10:58:50.369984 2016] [:error] [pid 10688] [client 192.168.0.8:38572] PHP Fatal error:  Uncaught Error: Cannot pass parameter 2 by reference in /var/www/html/omp/controllers/grid/content/spotlights/SpotlightsGridRow.inc.php:71\nStack trace:\n#0 /var/www/html/omp/lib/pkp/classes/controllers/grid/GridHandler.inc.php(1064): SpotlightsGridRow->initialize(Object(Request))\n#1 /var/www/html/omp/lib/pkp/classes/controllers/grid/GridHandler.inc.php(983): GridHandler->_getInitializedRowInstance(Object(Request), 1, Object(Spotlight))\n#2 /var/www/html/omp/lib/pkp/classes/controllers/grid/GridHandler.inc.php(1029): GridHandler->renderRowsInternally(Object(Request), Array)\n#3 /var/www/html/omp/lib/pkp/classes/controllers/grid/GridHandler.inc.php(923): GridHandler->renderGridBodyPartsInternally(Object(Request))\n#4 /var/www/html/omp/lib/pkp/classes/controllers/grid/GridHandler.inc.php(640): GridHandler->doSpecificFetchGridActions(Array, Object(Request), Object(TemplateManager))\n#5 /var/www/html/omp/lib/pkp/classes/core/PKPRouter.inc.php(372): GridHandler->fetchGrid(Array, Object(Request))\n#6 /var/www/html/omp/lib in /var/www/html/omp/controllers/grid/content/spotlights/SpotlightsGridRow.inc.php on line 71, referer: http://192.168.0.8/omp/index.php/test-press/manageCatalog
```

Maybe a PHP 7 thing?

**Comment by asmecher** [comment]
That was my typo in adding CSRF checking. Fixed, thanks!
