### ISSUE TITLE
Can't add note on submission

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2838]
Recording to investigate later. Logged in as a Journal Manager, I got a fatal error when trying to add a note through the Editorial History modal. Error message:

```
[Thu Oct 05 14:37:14.709820 2017] [:error] [pid 27515] [client 127.0.0.1:44018] PHP Fatal error:  Uncaught Error: Call to undefined method SubmissionInformationCenterHandler::_logEvent() in /var/www/html/ojs/lib/pkp/controllers/informationCenter/SubmissionInformationCenterHandler.inc.php:57
Stack trace:
#0 /var/www/html/ojs/lib/pkp/classes/core/PKPRouter.inc.php(372): SubmissionInformationCenterHandler->saveNote(Array, Object(Request))
#1 /var/www/html/ojs/lib/pkp/classes/core/PKPComponentRouter.inc.php(256): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array)
#2 /var/www/html/ojs/lib/pkp/classes/core/Dispatcher.inc.php(134): PKPComponentRouter->route(Object(Request))
#3 /var/www/html/ojs/lib/pkp/classes/core/PKPApplication.inc.php(242): Dispatcher->dispatch(Object(Request))
#4 /var/www/html/ojs/index.php(68): PKPApplication->execute()
#5 {main}
  thrown in /var/www/html/ojs/lib/pkp/controllers/informationCenter/SubmissionInformationCenterHandler.inc.php on line 57, referer: http://localhost/ojs/index.php/publicknowledge/workflow/index/1/3
```

**Comment by bozana** [comment]
PR:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2854

**Comment by bozana** [comment]
@NateWr, could you take a look at the PR?
