### ISSUE TITLE
Uncaught exception during OJS install

### ISSUE THREAD

**Issue by kaschioudi** [pkp/pkp-lib#2878]
I'm getting the error below when trying to install from a package generated using the build script `tools/buildpkg.sh`

```
[Tue Oct 17 11:05:05 2017] ::1:50928 [500]: /index.php/index/$$$call$$$/page/page/css - Uncaught exception 'Less_Exception_Parser' with message 'File `../../ui-library/src/styles/variables.less` not found. in index.less' in /Users/kaschioudi/pkpenv/ojs-3.1/lib/pkp/lib/vendor/oyejorge/less.php/lib/Less/Parser.php:2606
Stack trace:
#0 /Users/kaschioudi/pkpenv/ojs-3.1/lib/pkp/lib/vendor/oyejorge/less.php/lib/Less/Parser.php(319): Less_Parser->Error('File `../../ui-...')
#1 /Users/kaschioudi/pkpenv/ojs-3.1/lib/pkp/lib/vendor/oyejorge/less.php/lib/Less/Tree/Import.php(269): Less_Parser->parseFile('../../ui-librar...', '../../ui-librar...', true)
#2 /Users/kaschioudi/pkpenv/ojs-3.1/lib/pkp/lib/vendor/oyejorge/less.php/lib/Less/Tree/Import.php(193): Less_Tree_Import->ParseImport('../../ui-librar...', '../../ui-librar...', Object(Less_Environment))
#3 /Users/kaschioudi/pkpenv/ojs-3.1/lib/pkp/lib/vendor/oyejorge/less.php/lib/Less/Tree/Ruleset.php(248): Less_Tree_Import->compile(Object(Less_Environment))
#4 /Users/kaschioudi/pkpenv/ojs-3.1/lib/pkp/lib/vendor/oyejorge/less.php/lib/Less/Tree/Import.php(273) in /Users/kaschioudi/pkpenv/ojs-3.1/lib/pkp/lib/vendor/oyejorge/less.php/lib/Less/Parser.php on line 2606
```

**Comment by kaschioudi** [comment]
as per @NateWr , the problem comes from this line: https://github.com/pkp/ojs/blob/master/tools/buildpkg.sh#L109

It seems that older css code is tied to `ui-library`. So unless we're pre-compiling CSS for the build as well,  we'll need to include `ui-library/src/styles` in the build.

**Comment by NateWr** [comment]
@kaschioudi can you try these PRs?

https://github.com/pkp/pkp-lib/pull/2885
https://github.com/pkp/ojs/pull/1596
https://github.com/pkp/omp/pull/450

**Comment by asmecher** [comment]
Hi all -- sorry to hop onto this so late, my morning was a wreck. It looks like this is under control now?

**Comment by asmecher** [comment]
@NateWr, I believe fixes for this have already been merged -- correct? Can this be closed?

**Comment by NateWr** [comment]
:+1:
