### ISSUE TITLE
Citation style language plugin doesn't work in some locales

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3394]
See [this forum thread](https://forum.pkp.sfu.ca/t/solved-upgrade-ojs-2-4-8-1-3-1-0-1-article-view-blank-page/38424/2). 

The relevant log entries are:
```
PHP Fatal error: Uncaught exception ‘Exception’ with message ‘String could not be parsed as XML’ in /home/politi30/public_html/casopis/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Seboettg/CiteProc/Locale/Locale.php:48
Stack trace:
#0 /home/politi30/public_html/casopis/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Seboettg/CiteProc/Locale/Locale.php(48): SimpleXMLElement->__construct(’’)
#1 /home/politi30/public_html/casopis/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Seboettg/CiteProc/CiteProc.php(200): Seboettg\CiteProc\Locale\Locale->__construct(‘sr-RS@latin’)
#2 /home/politi30/public_html/casopis/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Seboettg/CiteProc/CiteProc.php(160): Seboettg\CiteProc\CiteProc->init(false)
#3 /home/politi30/public_html/casopis/plugins/generic/citationStyleLanguage/CitationStyleLanguagePlugin.inc.php(382): Seboettg\CiteProc\CiteProc->render(Array, ‘bibliography’)
#4 /home/politi in /home/politi30/public_html/casopis/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Seboettg/CiteProc/Locale/Locale.php on line 48
```
It looks like `sr-RS@latin` is getting passed in, and presumably the `@latin` part is causing CiteProc indigestion. OJS locales are mapped to CiteProc locales [in CitationStyleLanguagePlugin.inc.php](https://github.com/pkp/citationStyleLanguage/blob/f60fce8b7d08e470400bfeed07497e579e9dbda5/CitationStyleLanguagePlugin.inc.php#L380).

**Comment by bozana** [comment]
PR: https://github.com/pkp/citationStyleLanguage/pull/29

@NateWr, could you take a look?

**Comment by NateWr** [comment]
:+1: Merge when you'd like!
