### ISSUE TITLE
ERROR upgrade OJS 2.4.6 to 3.1.0-1 

### ISSUE THREAD

**Issue by PascualRico** [pkp/pkp-lib#3504]
Hi
I'm upgrading OJS 2.4.6 to OJS 3.1.0-1 and when I run “php tools/upgrade.php upgrade” always return such error 
```
PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /ojs_v3.1.0_1/classes/install/Upgrade.inc.php:1103
Stack trace:
#0 /ojs_v3.1.0_1/lib/pkp/classes/install/Installer.inc.php(415): Upgrade->convertSupplementaryFiles(Object(Upgrade), Array)
#1 /ojs_v3.1.0_1/lib/pkp/classes/install/Installer.inc.php(265): Installer->executeAction(Array)
#2 /ojs_v3.1.0_1/lib/pkp/classes/install/Installer.inc.php(186): Installer->executeInstaller()
#3 /ojs_v3.1.0_1/lib/pkp/classes/cliTool/UpgradeTool.inc.php(88): Installer->execute()
#4 /ojs_v3.1.0_1/lib/pkp/classes/cliTool/UpgradeTool.inc.php(64): UpgradeTool->upgrade()
#5 /ojs_v3.1.0_1/tools/upgrade.php(34): UpgradeTool->execute()
#6 {main}
  thrown in /ojs_v3.1.0_1/classes/install/Upgrade.inc.php on line 1103
```
My system consists of the following:
- PHP 7.0
- MySQL 5.7.21
- Apache 2.4.18

I don’t know how could i solve that?

**Comment by asmecher** [comment]
@PascualRico, it's likely an OJS 2.x data error; the support forum is a better place to debug these kinds of issues. I'd suggest working through this thread in particular: https://forum.pkp.sfu.ca/t/error-upgrade-2-4-8-2-to-3-1-0/35305
