### ISSUE TITLE
Fatal error related to subscriptions when merging a user

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3657]
When merging a user, I got a Fatal Error that seems related to subscription details:

```
[Tue May 01 15:31:46.285506 2018] [:error] [pid 15251] [client 127.0.0.1:37120] PHP Fatal error:  Uncaught Error: Call to undefined method IndividualSubscriptionDAO::deleteSubscriptionById() in /var/www/html/ojs/classes/subscription/IndividualSubscriptionDAO.inc.php:317
Stack trace:
#0 /var/www/html/ojs/classes/user/UserAction.inc.php(98): IndividualSubscriptionDAO->deleteByUserId(52)
#1 /var/www/html/ojs/lib/pkp/controllers/grid/settings/user/UserGridHandler.inc.php(631): UserAction->mergeUsers(52, 36)
#2 /var/www/html/ojs/lib/pkp/classes/core/PKPRouter.inc.php(372): UserGridHandler->mergeUsers(Array, Object(Request))
#3 /var/www/html/ojs/lib/pkp/classes/core/PKPComponentRouter.inc.php(256): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array)
#4 /var/www/html/ojs/lib/pkp/classes/core/Dispatcher.inc.php(134): PKPComponentRouter->route(Object(Request))
#5 /var/www/html/ojs/lib/pkp/classes/core/PKPApplication.inc.php(248): Dispatcher->dispatch(Object(Request))
#6 /var/www/html/ojs/index.php(68): PKPApplication->execute()
#7 {main}
  thrown in /var/www/html/ojs/classes/subscription/IndividualSubscriptionDAO.inc.php on line 317, referer: http://localhost/ojs/index/admin/settings
```

It didn't happen with every user, so it seems to be related to some specific configuration of subscription data (or lacking data). Maybe you have some idea @asmecher?

**Comment by bozana** [comment]
Ah, I first now see this -- it is solved and merged with this issue https://github.com/pkp/pkp-lib/issues/3664. Thus closing...
