### ISSUE TITLE
[OJS] White screen after upgrade from ojs-2.4.6 to ojs-3.1.2.1 

### ISSUE THREAD

**Issue by eprempeh** [pkp/pkp-lib#4839]
Hello,
I successfully I upgraded our version of OJS from **2.4.6** to **3.1.2.1** using the **CLI**. 
![success_meesage](https://user-images.githubusercontent.com/8848736/59964059-14e09a00-94eb-11e9-8ad8-cc76141e8dd3.PNG)

Now, we are stacked at a white screen when we visit the journal [here](https://myjournal.afrijcmr.org/)

**PHP error log**
`[22-Jun-2019 06:53:10 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; ADODB_Cache_File has a deprecated constructor in /home/.../public_html/subdomains/myjournal/lib/pkp/lib/adodb/adodb.inc.php on line 263
[22-Jun-2019 06:53:10 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; ADOConnection has a deprecated constructor in /home/.../public_html/subdomains/myjournal/lib/pkp/lib/adodb/adodb.inc.php on line 359
[22-Jun-2019 06:53:10 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; ADORecordSet has a deprecated constructor in /home/.../public_html/subdomains/myjournal/lib/pkp/lib/adodb/adodb.inc.php on line 2921
[22-Jun-2019 06:53:10 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; ADORecordSet_array has a deprecated constructor in /home/.../public_html/subdomains/myjournal/lib/pkp/lib/adodb/adodb.inc.php on line 3939
[22-Jun-2019 06:53:10 UTC] PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/.../public_html/subdomains/myjournal/lib/pkp/classes/session/SessionManager.inc.php on line 35
[22-Jun-2019 06:53:10 UTC] PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/.../public_html/subdomains/myjournal/lib/pkp/classes/session/SessionManager.inc.php on line 36
[22-Jun-2019 06:53:10 UTC] PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/.../public_html/subdomains/myjournal/lib/pkp/classes/session/SessionManager.inc.php on line 37
[22-Jun-2019 06:53:10 UTC] PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/.../public_html/subdomains/myjournal/lib/pkp/classes/session/SessionManager.inc.php on line 38
[22-Jun-2019 06:53:10 UTC] PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/.../public_html/subdomains/myjournal/lib/pkp/classes/session/SessionManager.inc.php on line 39
[22-Jun-2019 06:53:10 UTC] PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/.../public_html/subdomains/myjournal/lib/pkp/classes/session/SessionManager.inc.php on line 40
[22-Jun-2019 06:53:10 UTC] PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/.../public_html/subdomains/myjournal/lib/pkp/classes/session/SessionManager.inc.php on line 41
[22-Jun-2019 06:53:10 UTC] PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/.../public_html/subdomains/myjournal/lib/pkp/classes/session/SessionManager.inc.php on line 42
[22-Jun-2019 06:53:10 UTC] PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/.../public_html/subdomains/myjournal/lib/pkp/classes/session/SessionManager.inc.php on line 43
[22-Jun-2019 06:53:10 UTC] PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/.../public_html/subdomains/myjournal/lib/pkp/classes/session/SessionManager.inc.php on line 45
[22-Jun-2019 06:53:10 UTC] PHP Warning:  session_set_save_handler(): Cannot change save handler when headers already sent in /home/.../public_html/subdomains/myjournal/lib/pkp/classes/session/SessionManager.inc.php on line 53
[22-Jun-2019 06:53:10 UTC] PHP Warning:  session_start(): Cannot start session when headers already sent in /home/.../public_html/subdomains/myjournal/lib/pkp/classes/session/SessionManager.inc.php on line 58
[22-Jun-2019 06:53:10 UTC] PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls in /home/.../public_html/subdomains/myjournal/lib/pkp/lib/adodb/adodb.inc.php on line 1003
[22-Jun-2019 06:53:10 UTC] PHP Warning:  Declaration of CustomBlockPlugin::getBlockContext() should be compatible with BlockPlugin::getBlockContext($contextId = NULL) in /home/.../public_html/subdomains/myjournal/plugins/generic/customBlockManager/CustomBlockPlugin.inc.php on line 134
[22-Jun-2019 06:53:10 UTC] PHP Warning:  Declaration of RegistrationHandler::validate($request) should be compatible with PKPHandler::validate($requiredContexts = NULL, $request = NULL) in /home/.../public_html/subdomains/myjournal/lib/pkp/pages/user/RegistrationHandler.inc.php on line 19
[22-Jun-2019 06:53:10 UTC] PHP Warning:  Declaration of RegistrationForm::validate() should be compatible with Form::validate($callHooks = true) in /home/.../public_html/subdomains/myjournal/lib/pkp/classes/user/form/RegistrationForm.inc.php on line 21
[22-Jun-2019 06:53:10 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/.../public_html/subdomains/myjournal/lib/pkp/lib/adodb/adodb.inc.php:263) in /home/.../public_html/subdomains/myjournal/lib/pkp/classes/template/PKPTemplateManager.inc.php on line 836
[22-Jun-2019 06:53:10 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/.../public_html/subdomains/myjournal/lib/pkp/lib/adodb/adodb.inc.php:263) in /home/.../public_html/subdomains/myjournal/lib/pkp/classes/template/PKPTemplateManager.inc.php on line 837
[22-Jun-2019 06:53:10 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mb_split() in /home/.../public_html/subdomains/myjournal/lib/pkp/lib/vendor/smarty/smarty/libs/plugins/shared.mb_str_replace.php:47
Stack trace:
#0 /home/.../public_html/subdomains/myjournal/lib/pkp/lib/vendor/smarty/smarty/libs/plugins/modifier.replace.php(34): smarty_mb_str_replace('_', '-', 'en_US')
#1 /home/.../public_html/subdomains/myjournal/cache/t_compile/ecc55761ebbb35f58f8f534694562dbd01538725^10ae5578a0959129b8d4ceeb9f99c1bb2a9cbd65_0.app.frontendcomponentsheader..php(33): smarty_modifier_replace('en_US', '_', '-')
#2 /home/.../public_html/subdomains/myjournal/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5d0dce67c89f11_35196413(Object(Smarty_Internal_Template))
#3 /home/.../public_html/subdomains/myjournal/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_ in /home/.../public_html/subdomains/myjournal/lib/pkp/lib/vendor/smarty/smarty/libs/plugins/shared.mb_str_replace.php on line 47
`
We are running on PHP 7.2.

Also here on the [Forum](https://forum.pkp.sfu.ca/t/white-screen-after-upgrade-from-ojs-2-4-6-to-ojs-3-1-2-1/54248):

**Comment by asmecher** [comment]
Hi @eprempeh -- I've responded to your post on the forum. That's the best way to get support of this kind; I'll close this issue.

**Comment by eprempeh** [comment]
Hi @asmecher -- I switched from PHP 7.2 to 7.0 and now it's working. I'll install missing the `mbstring` extension anyway. Thanks.
