### ISSUE TITLE
Email templates API returning server error

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5220]
The email templates list panel doesn't load because of a `500` server error. It appears to be a DB issue with the mechanism for getting the total count. The exception that's thrown:

```
Previous error:
Type: InvalidArgumentException
Message: Database hosts array is empty.
File: /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/illuminate/database/Connectors/ConnectionFactory.php
Line: 203
Trace: #0 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/illuminate/database/Connectors/ConnectionFactory.php(178): Illuminate\Database\Connectors\ConnectionFactory->parseHosts(Array)
#1 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#2 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/illuminate/database/Connection.php(919): call_user_func(Object(Closure))
#3 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/illuminate/database/Connection.php(944): Illuminate\Database\Connection->getPdo()
#4 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/illuminate/database/Connection.php(399): Illuminate\Database\Connection->getReadPdo()
#5 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/illuminate/database/Connection.php(325): Illuminate\Database\Connection->getPdoForSelect(true)
#6 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/illuminate/database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('select count(*)...', Array)
#7 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#8 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/illuminate/database/Connection.php(333): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#9 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/illuminate/database/Query/Builder.php(2130): Illuminate\Database\Connection->select('select count(*)...', Array, true)
#10 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/illuminate/database/Query/Builder.php(2118): Illuminate\Database\Query\Builder->runSelect()
#11 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/illuminate/database/Query/Builder.php(2604): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#12 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/illuminate/database/Query/Builder.php(2119): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#13 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/illuminate/database/Query/Builder.php(2531): Illuminate\Database\Query\Builder->get(Array)
#14 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/illuminate/database/Query/Builder.php(2459): Illuminate\Database\Query\Builder->aggregate('count', Array)
#15 /home/nate/Projects/pkp/ojs/lib/pkp/classes/services/queryBuilders/PKPEmailTemplateQueryBuilder.inc.php(188): Illuminate\Database\Query\Builder->count()
#16 /home/nate/Projects/pkp/ojs/lib/pkp/classes/services/PKPEmailTemplateService.inc.php(99): PKP\Services\QueryBuilders\PKPEmailTemplateQueryBuilder->getCount()
#17 /home/nate/Projects/pkp/ojs/lib/pkp/api/v1/emailTemplates/PKPEmailTemplateHandler.inc.php(156): PKP\Services\PKPEmailTemplateService->getMax(Array)
```

**Comment by asmecher** [comment]
Is it possible that something happened to your `host` setting in `config.inc.php`? It seems to work fine for me, and the error message you quote seems to be caused by an empty database server hostname in the Laravel toolset.
