### ISSUE TITLE
Resolve "Uncaught TypeError" problems due to inaccurate function definitions

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5421]
See https://forum.pkp.sfu.ca/t/error-after-update-from-3-1-2-to-3-2-1-4/58184 for details.

This causes error messages like this:
```
PHP Fatal error:  Uncaught TypeError: Return value of PKP\Services\QueryBuilders\BaseQueryBuilder::bootstrap() must be an instance of PKP\Services\QueryBuilders\void, none returned in /var/www/html/ojs3/lib/pkp/classes/services/queryBuilders/BaseQueryBuilder.inc.php:65\nStack trace:\n#0 /var/www/html/ojs3/lib/pkp/classes/services/queryBuilders/BaseQueryBuilder.inc.php(30): PKP\Services\QueryBuilders\BaseQueryBuilder->bootstrap()\n#1 /var/www/html/ojs3/lib/pkp/classes/services/queryBuilders/PKPSubmissionListQueryBuilder.inc.php(96): PKP\Services\QueryBuilders\BaseQueryBuilder->__construct()\n#2 /var/www/html/ojs3/classes/services/SubmissionService.inc.php(86): PKP\Services\QueryBuilders\PKPSubmissionListQueryBuilder->__construct('29')\n#3 /var/www/html/ojs3/lib/pkp/classes/services/PKPSubmissionService.inc.php(116): OJS\Services\SubmissionService->getSubmissionListQueryBuilder('29')\n#4 /var/www/html/ojs3/lib/pkp/classes/services/PKPSubmissionService.inc.php(58): PKP\Services\PKPS in /var/www/html/ojs3/lib/pkp/classes/services/queryBuilders/BaseQueryBuilder.inc.php on line 65, referer: https://xxx.com/management/settings/access
```

**Comment by asmecher** [comment]
This affects PHP 7.0; PHP 7.1 and newer support `: void` return types in function definitions and without an explicit `return` in the function: https://wiki.php.net/rfc/void_return_type

The above patches correct the issue for OJS 3.1.2-x. Note that OJS 3.1.2 *does not explicitly support* PHP 7.0, so really a PHP upgrade is the best solution.
