### ISSUE TITLE
OJS3.x compatibility with Mysql and PHP 7+

### ISSUE THREAD

**Issue by bastoune** [pkp/pkp-lib#5425]
I based my installation versions based on this link informations :
https://pkp.sfu.ca/ojs/ojs_download/

**Describe the bug**
I get a fatal error issue when the install process try to connect to a mysql DB.
```
 Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /home/XXXX/lib/pkp/lib/adodb/drivers/adodb-mysql.inc.php:456 Stack trace: #0 /home/XXXX/lib/pkp/lib/adodb/adodb.inc.php(558): ADODB_mysql->_connect('XXXX-001.pr...', 'XXXX...', 'XXXX', 'XXXX...') #1 /home/XXXX/lib/pkp/classes/db/DBConnection.inc.php(162): ADOConnection->Connect('XXXX-001.pr...', 'XXXX...', 'XXXX', 'XXXX...', false) #2 /home/XXXX/lib/pkp/classes/db/DBConnection.inc.php(137): DBConnection->connect() #3 /home/XXXX/lib/pkp/classes/db/DBConnection.inc.php(124): DBConnection->initConn() #4 /home/XXXX/lib/pkp/classes/db/DBConnection.inc.php(56): DBConnection->initCustomDBConnection('mysql', 'XXXX-001.pr...', 'XXXX...', 'sAD4y5Hg9', 'XXXX...', false, 'utf8') #5 /home/XXXX in /home/XXXX/lib/pkp/lib/adodb/drivers/adodb-mysql.inc.php on line 456
```

**To Reproduce**
1. Php 7.3, Mysql 5.7 
2. Fullfill the install form 
3. Get lots of deprecated errors and the FATAL above

**What application are you using?**
 OJS 3.1.2-4

**Comment by asmecher** [comment]
@bastoune, see e.g.: https://forum.pkp.sfu.ca/t/uncaught-error-call-to-undefined-function-mysql-connect/34344
