### ISSUE TITLE
[OJS]

### ISSUE THREAD

**Issue by Beibut** [pkp/pkp-lib#5528]
You also need to enable the OpenJournalSystem service (sj.astanait.edu.kz/journal) to access the host. Click on the "Install OpenJournalSystem" button and see the "HTTP ERROR 500" link. All parameters (name BD, users) are usually good, there is a problem with connection to BD or may not work. Try to change the BD installation in config.inc.php, without the result. Pomogite can solve the problem.
OJS Version 3.1.2.4

**Comment by asmecher** [comment]
@Beibut, please check your PHP error log for details.

**Comment by Beibut** [comment]
2020-02-19 19:45:58	Error	85.159.27.200	500	POST /journal/index.php/index/install/install HTTP/1.0	http://sj.astanait.edu.kz/journal/index.php/index/install/install	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36	169	Доступ к Apache

2020-02-19 19:50:08	Warning	85.159.27.200		mod_fcgid: stderr: PHP Warning: Declaration of InstallForm::execute() should be compatible with Form::execute(...$functionArgs) in /var/www/vhosts/edu.kz/sj.astanait.edu.kz/journal/lib/pkp/classes/install/form/InstallForm.inc.php on line 20, referer: http://sj.astanait.edu.kz/journal/index.php/index/install/install				Ошибки Apache
2020-02-19 19:50:08	Warning	85.159.27.200		mod_fcgid: stderr: PHP Warning: Declaration of UpgradeForm::execute() should be compatible with Form::execute(...$functionArgs) in /var/www/vhosts/edu.kz/sj.astanait.edu.kz/journal/lib/pkp/classes/install/form/UpgradeForm.inc.php on line 0, referer: http://sj.astanait.edu.kz/journal/index.php/index/install/install				Ошибки Apache
2020-02-19 19:50:08	Warning	85.159.27.200		mod_fcgid: stderr: PHP Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /var/www/vhosts/edu.kz/sj.astanait.edu.kz/journal/lib/pkp/lib/adodb/drivers/adodb-mysql.inc.php:456, referer: http://sj.astanait.edu.kz/journal/index.php/index/install/install				Ошибки Apache
2020-02-19 19:50:08	Warning	85.159.27.200		mod_fcgid: stderr: Stack trace:, referer: http://sj.astanait.edu.kz/journal/index.php/index/install/install				Ошибки Apache
2020-02-19 19:50:08	Warning	85.159.27.200		mod_fcgid: stderr: #0 /var/www/vhosts/edu.kz/sj.astanait.edu.kz/journal/lib/pkp/lib/adodb/adodb.inc.php(558): ADODB_mysql->_connect('srv-pleskdb47.p...', 'edukz_ojs', 'SjGulnur2020', 'edukz124_ojs'), referer: http://sj.astanait.edu.kz/journal/index.php/index/install/install				Ошибки Apache
2020-02-19 19:50:08	Warning	85.159.27.200		mod_fcgid: stderr: #1 /var/www/vhosts/edu.kz/sj.astanait.edu.kz/journal/lib/pkp/classes/db/DBConnection.inc.php(162): ADOConnection->Connect('srv-pleskdb47.p...', 'edukz_ojs', 'SjGulnur2020', 'edukz124_ojs', false), referer: http://sj.astanait.edu.kz/journal/index.php/index/install/install				Ошибки Apache
2020-02-19 19:50:08	Warning	85.159.27.200		mod_fcgid: stderr: #2 /var/www/vhosts/edu.kz/sj.astanait.edu.kz/journal/lib/pkp/classes/db/DBConnection.inc.php(137): DBConnection->connect(), referer: http://sj.astanait.edu.kz/journal/index.php/index/install/install				Ошибки Apache
2020-02-19 19:50:08	Warning	85.159.27.200		mod_fcgid: stderr: #3 /var/www/vhosts/edu.kz/sj.astanait.edu.kz/journal/lib/pkp/classes/db/DBConnection.inc.php(124): DBConnection->initConn(), referer: http://sj.astanait.edu.kz/journal/index.php/index/install/install				Ошибки Apache
2020-02-19 19:50:08	Warning	85.159.27.200		mod_fcgid: stderr: #4 /var/www/vhosts/edu.kz/sj.astanait.edu.kz/journal/lib/pkp/classes/db/DBConnection.inc.php(56): DBConnection->initCustomDBConnection('mysql', 'srv-pleskdb47.p...', 'edukz_ojs', 'SjGulnur2020', 'edukz124_ojs', false, 'utf8'), referer: http://sj.astanait.edu.kz/journal/index.php/index/install/install				Ошибки Apache
2020-02-19 19:50:08	Warning	85.159.27.200		mod_fcgid: stderr: in /var/www/vhosts/edu.kz/sj.astanait.edu.kz/journal/lib/pkp/lib/adodb/drivers/adodb-mysql.inc.php on line 456, referer: http://sj.astanait.edu.kz/journal/index.php/index/install/install				Ошибки Apache

**Comment by asmecher** [comment]
This is the relevant message:
```
PHP Fatal error: Uncaught Error: Call to undefined function mysql_connect()
```
Search our support forum for that message and you'll find a solution.

Beware that you've posted your database credentials above; please change them as soon as possible.
