### ISSUE TITLE
Article report plugin references missing function

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5621]
See https://forum.pkp.sfu.ca/t/error-articlereport-plugin/59143/2 for details:
> PHP Fatal error: Uncaught Error: Call to undefined method AuthorDAO::getFetchParameters() in ./plugins/reports/articles/ArticleReportDAO.inc.php:34
Stack trace:
> #0 ./plugins/reports/articles/ArticleReportPlugin.inc.php(67): ArticleReportDAO->getArticleReport()
> #1 ./lib/pkp/pages/management/PKPToolsHandler.inc.php(155): ArticleReportPlugin->display()
> #2 ./lib/pkp/pages/management/PKPToolsHandler.inc.php(58): PKPToolsHandler->report()
> #3 ./lib/pkp/classes/core/PKPRouter.inc.php(391): PKPToolsHandler->tools()
> #4 ./lib/pkp/classes/core/PKPPageRouter.inc.php(231): PKPRouter->_authorizeInitializeAndCallRequest()
> #5 ./lib/pkp/classes/core/Dispatcher.inc.php(143): PKPPageRouter->route()
> #6 ./lib/pkp/classes/core/PKPApplication.inc.php(278): Dispatcher->dispatch()
> #7 in ./plugins/reports/articles/ArticleReportDAO.inc.php on line 34

**Comment by asmecher** [comment]
PR: https://github.com/pkp/ojs/pull/2681

This report could still use some conceptual cleanup -- it sure does generate a lot of columns -- but I've rewritten it to its former state. @NateWr, could you give it a quick look?

**Comment by asmecher** [comment]
Thanks, @NateWr!
