### ISSUE TITLE
Resolve OJS 2.x to 3.2 upgrade issues

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5634]
From https://forum.pkp.sfu.ca/t/uploading-ojs-2-4-x-to-ojs-3-2-error/59223:

```
[code: Installer Installer::convertSupplementaryFiles]
error: <h1>Unknown locale component </h1>ojs2: Unknown locale component
```
This appears to be happening because the `locale` column in the `submissions` table is no longer available (the 2.x to 3.x upgrade moves it to `publications`).

Also:
```
PHP Fatal error:  Uncaught Error: Call to undefined method ArticleGalley::setSubmissionId() in /home/asmecher/git/ojs/classes/install/Upgrade.inc.php:1418
```
...which is caused by the move to associating galleys with publications rather than submissions; however, at this stage in the upgrade process the association is still with submissions.

**Comment by asmecher** [comment]
Patches:
- https://github.com/pkp/ojs/commit/4a8f83680e942d0f8c3a929a0cf99d3e769d17a9 (apply in OJS installation directory)
- https://github.com/pkp/pkp-lib/commit/338488f8429c28a9d12a48d76dcf16a27dc2b560 (apply in `lib/pkp` subdirectory)

**Comment by asmecher** [comment]
Hoping for further confirmation that the data looks OK post-upgrade!

**Comment by NateWr** [comment]
This is causing a fatal error for me in the current `master` branch: https://github.com/pkp/pkp-lib/commit/338488f8429c28a9d12a48d76dcf16a27dc2b560

```
[18-Mar-2020 09:49:46 Europe/London] ojs2: DB Error: Unknown column 's.locale' in 'field list' Query: SELECT DISTINCT
				sf.file_id AS submission_file_id, sf.revision AS submission_revision,
				af.file_id AS artwork_file_id, af.revision AS artwork_revision,
				suf.file_id AS supplementary_file_id, suf.revision AS supplementary_revision,
				COALESCE(p.locale, s.locale) AS submission_locale,
				sf.*, af.*, suf.*
			FROM	submission_files sf
				LEFT JOIN submission_artwork_files af ON sf.file_id = af.file_id AND sf.revision = af.revision
				LEFT JOIN submission_supplementary_files suf ON sf.file_id = suf.file_id AND sf.revision = suf.revision
				LEFT JOIN submissions as s ON s.submission_id = sf.submission_id
				LEFT JOIN publications p ON s.current_publication_id = p.publication_id LEFT JOIN submission_files sf2 ON sf.file_id = sf2.file_id AND sf.revision < sf2.revision
				WHERE sf2.revision IS NULL AND  sf.file_id = ? ORDER BY sf.submission_id ASC, sf.file_stage ASC, sf.file_id ASC, sf.revision DESC
```

Stack trace for the db error:

```
[18-Mar-2020 09:50:32 Europe/London] PHP Fatal error:  Uncaught Exception in /home/nate/Projects/pkp/ojs/lib/pkp/classes/db/DAO.inc.php:703
Stack trace:
#0 /home/nate/Projects/pkp/ojs/lib/pkp/classes/db/DAO.inc.php(103): DAO->handleError(Object(ADODB_mysqli), 'SELECT DISTINCT...')
#1 /home/nate/Projects/pkp/ojs/lib/pkp/classes/submission/SubmissionFileDAO.inc.php(921): DAO->retrieve('SELECT DISTINCT...', Array)
#2 /home/nate/Projects/pkp/ojs/lib/pkp/classes/submission/SubmissionFileDAO.inc.php(165): SubmissionFileDAO->_getInternally(NULL, NULL, 147, NULL, NULL, NULL, NULL, NULL, NULL, true, NULL, NULL)
#3 /home/nate/Projects/pkp/ojs/classes/article/ArticleGalley.inc.php(107): SubmissionFileDAO->getLatestRevision(147)
#4 /home/nate/Projects/pkp/ojs/cache/t_compile/00a0a0910209607cb33eb0fe6474f30ed7399ed7^7cf1cd52b8ba8108de77f197078de34b733dd394_0.app.frontendobjectsarticlesum.php(100): ArticleGalley->getFile()
#5 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5e71eee8124026_29737486(Obje in /home/nate/Projects/pkp/ojs/lib/pkp/classes/db/DAO.inc.php on line 703
```

Is there an upgrade script that needs to be run?

**Comment by asmecher** [comment]
Is it possible that your database was generated/upgraded before pkp/ojs@fe4e111c8133fc9817d4509f42c50f48389eefa3 was merged?

**Comment by NateWr** [comment]
Ah yes, almost certainly. So as long as that was in before 3.2 then this should be fine.
