### ISSUE TITLE
Upgrade fails from OJS 2.x with remote galleys

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5688]
From https://forum.pkp.sfu.ca/t/issue-updating-2-4-8-1-to-3-2-x/59527:
> PHP Fatal error: Uncaught Error: Call to undefined method ArticleGalley::setSubmissionId() in /repository/ojs/ojs-3.2.0-1/classes/install/Upgrade.inc.php:1077
> Stack trace:
> #0 /repository/ojs/ojs-3.2.0-1/lib/pkp/classes/install/Installer.inc.php(417): Upgrade->convertSupplementaryFiles(Object(Upgrade), Array)
> #1 /repository/ojs/ojs-3.2.0-1/lib/pkp/classes/install/Installer.inc.php(263): Installer->executeAction(Array)
> #2 /repository/ojs/ojs-3.2.0-1/lib/pkp/classes/install/Installer.inc.php(186): Installer->executeInstaller()
> #3 /repository/ojs/ojs-3.2.0-1/lib/pkp/classes/cliTool/UpgradeTool.inc.php(88): Installer->execute()
> #4 /repository/ojs/ojs-3.2.0-1/lib/pkp/classes/cliTool/UpgradeTool.inc.php(64): UpgradeTool->upgrade()
> #5 /repository/ojs/ojs-3.2.0-1/tools/upgrade.php(22): UpgradeTool->execute()
> #6 {main}
thrown in /repository/ojs/ojs-3.2.0-1/classes/install/Upgrade.inc.php on line 1077

**Comment by asmecher** [comment]
PR:
- https://github.com/pkp/ojs/pull/2700
(OMP and OPS not affected)

**Comment by asmecher** [comment]
Merged the PR to solve the Fatal Error. The thread contains an additional query that may prove useful depending on the 2.x database: https://forum.pkp.sfu.ca/t/issue-updating-2-4-8-1-to-3-2-x/59527/6
