### ISSUE TITLE
Fatal error when generating custom report

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5769]
**Describe the bug**
When using the custom report generator (Tools > Reports > Custom Report Generator) I get the following error:

```
[21-Apr-2020 16:38:58 Europe/London] PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in /home/nate/Projects/pkp/ojs/classes/statistics/MetricsDAO.inc.php:34
Stack trace:
#0 /home/nate/Projects/pkp/ojs/plugins/generic/usageStats/PKPUsageStatsReportPlugin.inc.php(84): MetricsDAO->getMetrics('ojs::counter', Array, Object(stdClass), Array, NULL)
#1 /home/nate/Projects/pkp/ojs/plugins/generic/usageStats/OJSUsageStatsReportPlugin.inc.php(32): PKPUsageStatsReportPlugin->getMetrics('ojs::counter', Array, Object(stdClass), Array, NULL)
#2 /home/nate/Projects/pkp/ojs/lib/pkp/pages/management/PKPToolsHandler.inc.php(219): OJSUsageStatsReportPlugin->getMetrics('ojs::counter', Array, Object(stdClass), Array)
#3 /home/nate/Projects/pkp/ojs/lib/pkp/pages/management/PKPToolsHandler.inc.php(68): PKPToolsHandler->generateReport(Array, Object(Request))
#4 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/PKPRouter.inc.php(391): PKPToolsHandler->tools(Array, Object(Request))
#5 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/PKPPageRouter.inc.php(246):  in /home/nate/Projects/pkp/ojs/classes/statistics/MetricsDAO.inc.php on line 34
```

**What application are you using?**
OJS 3.2

**Comment by asmecher** [comment]
Is this an installation from git, or from `.tar.gz`?

**Comment by NateWr** [comment]
git.

**Comment by asmecher** [comment]
Is it possible you've got an old version of the usage stats plugin?

**Comment by NateWr** [comment]
The array-to-object problem with PHP and json_encode strikes again! See https://github.com/pkp/pkp-lib/pull/5799/files.

PR:
https://github.com/pkp/pkp-lib/pull/5799/files

Tests:
https://github.com/pkp/ojs/pull/2727

**Comment by NateWr** [comment]
Merged to `master` and `stable-3_2_0`.
