### ISSUE TITLE
Enter Metadata it can't be saved and continued (OJS 3.2.0.3)

### ISSUE THREAD

**Issue by tjmarpaung** [pkp/pkp-lib#5839]
Hi. I have a problem after I upgraded my OJS 3.1 to 3.2.03.
When people want to submit an article at step 3. Enter Metadata it can't be saved and continued. It always stuck loading.  Nevertheless, the actual data entered in the form are saved. But can't go to step 4. Confirmation until finished submission. No errors in PHP logs. I used PHP 7.2. And I was read https://github.com/pkp/pkp-lib/issues/4072 but it's still not working. Thank you

![WhatsApp Image 2020-05-08 at 01 18 01](https://user-images.githubusercontent.com/64982204/81330598-7fca9d80-90ca-11ea-9095-15a015dc7200.jpeg)

![WhatsApp Image 2020-05-08 at 01 18 01 (1)](https://user-images.githubusercontent.com/64982204/81330452-4abe4b00-90ca-11ea-8ec5-0868d1e8dc53.jpeg)

**Comment by asmecher** [comment]
This appears to be https://github.com/marcj/jquery-selectBox/issues/180 (or similar); could you try the following:
- Edit `js/pkp.min.js`; search for `andSelf` and change it to `addBack` (similar to [this change](https://github.com/marcj/jquery-selectBox/pull/188/files))
- Make the same change to `lib/pkp/js/lib/jquery/plugins/jquery.selectBox.min.js`
- Reload the page and see if the same error message appears.

**Comment by tjmarpaung** [comment]
> This appears to be [marcj/jquery-selectBox#180](https://github.com/marcj/jquery-selectBox/issues/180) (or similar); could you try the following:
> 
> * Edit `js/pkp.min.js`; search for `andSelf` and change it to `addBack` (similar to [this change](https://github.com/marcj/jquery-selectBox/pull/188/files))
> * Make the same change to `lib/pkp/js/lib/jquery/plugins/jquery.selectBox.min.js`
> * Reload the page and see if the same error message appears.

It still error..
But with different message error... 

![Untitled](https://user-images.githubusercontent.com/64982204/81364720-94ca1f80-9110-11ea-8007-d0ae68873cd4.png)

**Comment by asmecher** [comment]
That's a 500 error; there will be a log entry on the server side that accompanies this.

**Comment by tjmarpaung** [comment]
So what should I do sir?

**Comment by asmecher** [comment]
@tjmarpaung Check your web server's error logs for details.

**Comment by tjmarpaung** [comment]
> @tjmarpaung Check your web server's error logs for details.
This is sir... 

![new](https://user-images.githubusercontent.com/64982204/81412468-18fec000-916e-11ea-86b3-555e1f5d443c.png)

**Comment by asmecher** [comment]
There's nothing relevant there; try to find something with a datestamp that matches the time you saw a 500 error in the browser.

**Comment by tjmarpaung** [comment]
> try to find something with a datestamp that matches the time you saw a 500 error in the browser.

Just it sir... 
Error in datestamp that matches the time I saw is the same...
And sometimes I submit another article again when step 3 I get a new error...
![new2](https://user-images.githubusercontent.com/64982204/81416140-83662f00-9173-11ea-8302-e1a3607611d6.png)

**Comment by asmecher** [comment]
This message...
![image](https://user-images.githubusercontent.com/200411/81417996-deab0980-9100-11ea-8a38-74aace4151a4.png)
...says that the server reported an error, but doesn't include that error. Somewhere in your server's logs, with a datestamp indicating the same time as you saw this message, there will be more details.

**Comment by tjmarpaung** [comment]
> This message...
> ![image](https://user-images.githubusercontent.com/200411/81417996-deab0980-9100-11ea-8a38-74aace4151a4.png)
> ...says that the server reported an error, but doesn't include that error. Somewhere in your server's logs, with a datestamp indicating the same time as you saw this message, there will be more details.

Hi sir, I get some message errir from error log

Stack trace:
#0 /home/indf6616/public_html/bulletin/lib/pkp/classes/plugins/HookRegistry.inc.php(107): OpenAIREPlugin->metadataExecute('submissionsubmi...', Array)
#1 /home/indf6616/public_html/bulletin/lib/pkp/classes/form/Form.inc.php(314): HookRegistry::call('submissionsubmi...', Array)
#2 /home/indf6616/public_html/bulletin/lib/pkp/classes/submission/form/PKPSubmissionSubmitStep3Form.inc.php(143): Form->execute()
#3 /home/indf6616/public_html/bulletin/lib/pkp/pages/submission/PKPSubmissionHandler.inc.php(171): PKPSubmissionSubmitStep3Form->execute()
#4 /home/indf6616/public_html/bulletin/lib/pkp/classes/core/PKPRouter.inc.php(391): PKPSubmissionHandler->saveStep(Array, Object(Request))
#5 /home/indf6616/public_html/bulletin/lib/pkp/classes/core/PKPPageRouter.inc.php(231): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)
#6 in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREPlugin.inc.php on line 125
[08-May-2020 13:26:46 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:27:07 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:27:08 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:40:56 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:51:44 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:56:34 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:59:57 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 14:15:05 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 14:22:30 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 14:24:29 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 14:29:38 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 14:46:06 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 15:11:42 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19

**Comment by tjmarpaung** [comment]
Stack trace:
#0 /home/indf6616/public_html/bulletin/lib/pkp/classes/plugins/HookRegistry.inc.php(107): OpenAIREPlugin->metadataExecute('submissionsubmi...', Array)
#1 /home/indf6616/public_html/bulletin/lib/pkp/classes/form/Form.inc.php(314): HookRegistry::call('submissionsubmi...', Array)
#2 /home/indf6616/public_html/bulletin/lib/pkp/classes/submission/form/PKPSubmissionSubmitStep3Form.inc.php(143): Form->execute()
#3 /home/indf6616/public_html/bulletin/lib/pkp/pages/submission/PKPSubmissionHandler.inc.php(171): PKPSubmissionSubmitStep3Form->execute()
#4 /home/indf6616/public_html/bulletin/lib/pkp/classes/core/PKPRouter.inc.php(391): PKPSubmissionHandler->saveStep(Array, Object(Request))
#5 /home/indf6616/public_html/bulletin/lib/pkp/classes/core/PKPPageRouter.inc.php(231): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)
#6 in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREPlugin.inc.php on line 125
[08-May-2020 08:53:11 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 08:53:16 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 08:58:10 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 09:10:19 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 09:33:19 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 09:34:18 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 09:39:36 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 09:42:05 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 10:54:13 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 10:55:38 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 10:55:48 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 10:55:48 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 11:10:26 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 11:10:27 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 11:10:38 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 11:10:42 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 11:15:57 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 11:32:40 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 11:32:41 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 11:38:32 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 12:22:28 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:13:24 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:13:25 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:13:53 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:14:16 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:14:54 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:14:54 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:14:54 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:14:54 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:14:55 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:14:56 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:10 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:11 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:13 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:13 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:14 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:14 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:15 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:28 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:29 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:29 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:29 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:32 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:32 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:32 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:33 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:33 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:33 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:34 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:34 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:15:35 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:17:29 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:17:50 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:25:58 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:26:01 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:26:03 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:26:03 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:26:03 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:26:04 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:26:04 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:26:04 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:26:09 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:26:10 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:26:10 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:26:10 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:26:11 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:26:32 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 19
[08-May-2020 13:26:33 UTC] PHP Fatal error:  Uncaught Error: Call to a member function setData() on null in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREPlugin.inc.php:125

**Comment by asmecher** [comment]
@tjmarpaung, that's closer -- what do you see in the log immediately above the `Stack trace:` line?

**Comment by tjmarpaung** [comment]
> lugin.inc.php:125

This is the log above stack trace sir...

**Comment by tjmarpaung** [comment]
[08-May-2020 08:36:53 UTC] PHP Fatal error:  Uncaught Error: Call to a member function setData() on null in /home/indf6616/public_html/bulletin/plugins/generic/openAIRE/OpenAIREPlugin.inc.php:125

**Comment by asmecher** [comment]
@tjmarpaung, it looks like you are using an old version of the OpenAIRE plugin that is not compatible with your release of OJS. Make sure your plugins are up to date.

**Comment by tjmarpaung** [comment]
> @tjmarpaung, it looks like you are using an old version of the OpenAIRE plugin that is not compatible with your release of OJS. Make sure your plugins are up to date.

Thank you very much sir... I can continue my work... 
But when I write abstract with long paragraph it was error message

An unexpected error occurred. You may have been logged out. Please reload the page and try again.

I was logged out but it still happened..

**Comment by tjmarpaung** [comment]
Failed to load resource: the server responded with a status of 403 ()

**Comment by asmecher** [comment]
@tjmarpaung, that's not related to this posting, and I suspect it's not a bug in the software; I'd suggest searching for that message on our support forum, https://forum.pkp.sfu.ca, and if you can't find a solution there, post a new topic (also on the forum).

**Comment by Obidjonabdulloyev** [comment]
I have this problem too. In step 3. Enter Metadata it can't be saved and continued. It is always stuck loading.

**Comment by Obidjonabdulloyev** [comment]
Please help me, anybody.

**Comment by asmecher** [comment]
@Obidjonabdulloyev, this is an older closed issue; the best place to get help is the PKP support forum (https://forum.pkp.sfu.ca). Be sure to include your OJS version and anything that appears in your PHP error log.
