### ISSUE TITLE
Potential issue

### ISSUE THREAD

**Issue by Kolesar** [pkp/pkp-lib#5942]
`$latestPublication` can be null and ` $latestPublication->getId()` will thrown error.

Atm, I have no idea for improving this code except to kindly ask you to run PHPStan on the whole project.

https://github.com/pkp/pkp-lib/blob/e9cc77c9f15b0fc6e13962a7dd9997571bdc28dd/pages/workflow/PKPWorkflowHandler.inc.php#L199

**Comment by asmecher** [comment]
@Kolesar, it's technically possible for `$latestPublication` to be null (if the database includes a `submissions` entry without any corresponding entries in `publications`) but in practice it should always be set. Do you have a practical case where `$latestPublication` is null?

**Comment by Kolesar** [comment]
Hi @asmecher,

Thanks for the quick reply. Actually yes. When I try to open directly URL, for example:  index.php/journal/workflow/index/102/3

Because my Subscription page is blank on the latest version. Actually I tried to upgrade from the 3.2.2.4 and now almost nothing works :/

In the log files, I can see an error for the place that I mention, when try directly to visit this link.

**Comment by asmecher** [comment]
@Kolesar, what version did you try to upgrade to? Did the upgrade succeed? (I've closed https://github.com/pkp/pkp-lib/issues/5941, since I suspect the cause is the same.)

**Comment by Kolesar** [comment]
As I mention. I tried to upgrade from the 3.2.2.4 and look like upgrade works (have some problems with database, but finally works).

**Comment by asmecher** [comment]
(Also cross-posted [here](https://forum.pkp.sfu.ca/t/error-call-to-a-member-function-getdata-on-null-after-trying-to-import/59833/8))

@Kolesar, what do you get for the SQL query:
```
SELECT * FROM versions WHERE product='ojs2' AND current=1;
```

**Comment by asmecher** [comment]
Also, I see that you tried to upgrade from version 3.1.2-4, but what version did you try to upgrade to?

**Comment by Kolesar** [comment]
To latest one, of course

**Comment by asmecher** [comment]
@Kolesar, that would be OJS 3.2.0-3 then? (Please confirm -- it's also helpful to have this specifically for someone who comes across this issue later.)

Did you try the SQL query above?

**Comment by Kolesar** [comment]
```
-
  major: 3
  minor: 2
  revision: 0
  build: 3
  date_installed: "2020-05-29 01:36:22"
  current: 1
  product_type: "core"
  product: "ojs2"
  product_class_name: ""
  lazy_load: 0
  sitewide: 1
...
```

**Comment by asmecher** [comment]
@Kolesar, OK, that confirms 3.2.0-3, and that the upgrade process thinks it finished successfully.

Can you describe the database problems you had? In particular, did you have to work around anything related to `dbscripts/xml/upgrade/3.2.0_versioning.xml`?

**Comment by NateWr** [comment]
Closing due to inactivity but feel free to reopen if there's more info to debug.

**Comment by elenacn** [comment]
Hello, I have OJS 3.2.1.2 
`
-
  major: 3
  minor: 2
  revision: 1
  build: 2
  date_installed: "2020-12-04 16:17:23"
  current: 1
  product_type: "core"
  product: "ojs2"
  product_class_name: ""
  lazy_load: 0
  sitewide: 1
...
`
and the error message is

PHP Fatal error:  Uncaught Error: Call to a member function getData() on null in /lib/pkp/classes/task/ReviewReminder.inc.php:156\nStack trace:\
n#0 /lib/pkp/classes/scheduledTask/ScheduledTask.inc.php(146): ReviewReminder->executeActions()\
n#1 /lib/pkp/plugins/generic/acron/PKPAcronPlugin.inc.php(257): ScheduledTask->execute()\
n#2 [internal function]: PKPAcronPlugin->shutdownFunction()\
n#3 {main}\n  thrown in /lib/pkp/classes/task/ReviewReminder.inc.php on line 156

**Comment by asmecher** [comment]
@elenacn, could you post your question on https://forum.pkp.sfu.ca? That's the best place to get help.
