### ISSUE TITLE
Fatal error viewing HTML publication format in OMP

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5977]
When viewing an HTML-based document in the OMP front end, there is a fatal error:
```
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getLabel() on null in .../cache/t_compile/a2504c4f1162896529674ca58097c7db61591d77^5e12bd6afba2be6e28a1977370389d15cb558c87_0.plugins-plugins-generic-htmlMonographFile-generic-htmlMonographFile.display.tpl.php:79\nStack trace:\n#0 .../lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5edfd50f9101a5_78824943(Object(Smarty_Internal_Template))\n#1 .../lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))\n#2 .../lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))\n#3 .../lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Templat...', referer: http://.../index.php/publicknowledge/catalog/book/14
```
This appears to be caused by this change: https://github.com/pkp/omp/commit/0e66b99d9501680553da1643e137a7d79f6b6707

I'd recommend checking the PDF view as well for a similar problem.

**Comment by NateWr** [comment]
> That's your MIME type detection stuff in PHP

What causes this issue and how can I resolve it? Is it because I'm uploading a `.html` file that doesn't have a doctype declaration at the top?

**Comment by asmecher** [comment]
The underlying toolset smells strongly of UNIX. See the manpage for [`file`](https://linux.die.net/man/1/file):
> The magic tests are used to check for files with data in particular fixed formats. The canonical example of this is a binary executable (compiled program) a.out file, whose format is defined in #include <a.out.h>
> and possibly #include <exec.h>
> in the standard include directory. These files have a 'magic number' stored in a particular place near the beginning of the file that tells the UNIX operating system that the file is a binary executable, and which of several types thereof. The concept of a 'magic' has been applied by extension to data files. Any file with some invariant identifier at a small fixed offset into the file can usually be described in this way. The information identifying these files is read from the compiled magic file /usr/share/misc/magic.mgc, or the files in the directory /usr/share/misc/magic if the compiled file does not exist. In addition, if $HOME/.magic.mgc or $HOME/.magic exists, it will be used in preference to the system magic files. If /etc/magic exists, it will be used together with other magic files.
>
>If a file does not match any of the entries in the magic file, it is examined to see if it seems to be a text file. ASCII, ISO-8859-x, non-ISO 8-bit extended-ASCII character sets (such as those used on Macintosh and IBM PC systems), UTF-8-encoded Unicode, UTF-16-encoded Unicode, and EBCDIC character sets can be distinguished by the different ranges and sequences of bytes that constitute printable text in each set. If a file passes any of these tests, its character set is reported. ASCII, ISO-8859-x, UTF-8, and extended-ASCII files are identified as 'text' because they will be mostly readable on nearly any terminal; UTF-16 and EBCDIC are only 'character data' because, while they contain text, it is text that will require translation before it can be read. In addition, file will attempt to determine other characteristics of text-type files. If the lines of a file are terminated by CR, CRLF, or NEL, instead of the Unix-standard LF, this will be reported. Files that contain embedded escape sequences or overstriking will also be identified.
>
>Once file has determined the character set used in a text-type file, it will attempt to determine in what language the file is written. The language tests look for particular strings (cf. #include <names.h>
) that can appear anywhere in the first few blocks of a file. For example, the keyword .br indicates that the file is most likely a troff(1) input file, just as the keyword struct indicates a C program. These tests are less reliable than the previous two groups, so they are performed last. The language test routines also test for some miscellany (such as tar(1) archives).
>
>Any file that cannot be identified as having been written in any of the character sets listed above is simply said to be 'data'.

So the UNIXy solution would be to adjust the `/usr/share/misc/magic` file or introduce a `$HOME/.magic` one (I'm not sure the PHP toolset specifically looks for this, or shares the same magic file path as the OS) but in practice that's too much for users to do and doesn't work well with HTML files overall. So we introduced a few [work-arounds for common misdetections of trustworthy formats based on file extension](https://github.com/pkp/pkp-lib/blob/656fb2a8899f96d8189654ce2b5ea96ad2f3d9bc/classes/core/PKPString.inc.php#L350..L363), but it seems like yours doesn't fall into that set. Are you also seeing `application/octet-stream`, @NateWr?
