### ISSUE TITLE
[OJS] Upgrading from 2.4 to 3.2: Uncaught Error: Call to a member function getId()

### ISSUE THREAD

**Issue by Azm9oth** [pkp/pkp-lib#6016]
Hello everyone,

I am upgrading from OJS 2.4 to the latest version OJS 3.2.0-3.
When I click on upgrade, it works (upgrading icon circulates) for about one minute, then I get a blank page with the 500 error.

Checking the error logs, I have these warnings/errors:

[18-Jun-2020 06:33:07 UTC] WARNING: Unable to find a match for “146-392-1-RV.docx” in “/home/journal1/private/files/journals/1//articles/146/”. Skipping this file.
[18-Jun-2020 06:33:07 UTC] WARNING: Unable to find a match for “154-460-1-RV.docx” in “/home/journal1/private/files/journals/1//articles/154/”. Skipping this file.
[18-Jun-2020 06:33:07 UTC] WARNING: Unable to find a match for “222-594-1-RV.pdf” in “/home/journal1/private/files/journals/1//articles/222/”. Skipping this file.
[18-Jun-2020 06:33:07 UTC] WARNING: Unable to find a match for “232-635-1-RV.docx” in “/home/journal1/private/files/journals/1//articles/232/”. Skipping this file.
…
//Many other warnings like these
…
[18-Jun-2020 06:33:32 UTC] WARNING: Unable to find a match for “306-823-1-SM.pdf” in “/home/journal1/private/files/journals/1//articles/306/”. Skipping this file.
[18-Jun-2020 06:33:32 UTC] WARNING: Unable to find a match for “306-826-1-SP.pdf” in “/home/journal1/private/files/journals/1//articles/306/”. Skipping this file.

[18-Jun-2020 06:33:32 UTC] PHP Fatal error: Uncaught Error: Call to a member function getId() on null in /home/journal1/public_html/classes/install/Upgrade.inc.php:1053
Stack trace:
#0 /home/journal1/public_html/lib/pkp/classes/install/Installer.inc.php(417): Upgrade->convertSupplementaryFiles(Object(Upgrade), Array)
#1 /home/journal1/public_html/lib/pkp/classes/install/Installer.inc.php(263): Installer->executeAction(Array)
#2 /home/journal1/public_html/lib/pkp/classes/install/Installer.inc.php(186): Installer->executeInstaller()
#3 /home/journal1/public_html/lib/pkp/classes/install/form/UpgradeForm.inc.php(42): Installer->execute()
#4 /home/journal1/public_html/lib/pkp/pages/install/InstallHandler.inc.php(106): UpgradeForm->execute()
#5 /home/journal1/public_html/lib/pkp/classes/core/PKPRouter.inc.php(391): InstallHandler->installUpgrade(Array, Object(Request))
#6 /home/journal1/public_html/lib/pkp/classes/core/PKPPageRouter.inc.php(231): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)
#7 /home/journal1/public_html in /home/journal1/public_html/classes/install/Upgrade.inc.php on line 1053

Please help, we have a new issue of this journal coming soon, I need to have it up and running as soon as possible.

Thanks in advance

@asmecher 
@bozana

**Comment by asmecher** [comment]
@Azm9oth, your forum post is a better place to work on this -- closing in favour of https://forum.pkp.sfu.ca/t/upgrading-from-ojs-2-4-to-3-2-uncaught-error-call-to-a-member-function-getid/61246.
