### ISSUE TITLE
During upgrade to 3.3 email templates' stage_id is populated before being created

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6284]
Upgrades of OMP/OPS/OJS from versions below 3.2.1 to the 3.3 (current master branch) throw a fatal error:
```
[code: Installer Installer::migrateStaticPagesToNavigationMenuItems]
[data: dbscripts/xml/upgrade/3.2.1_update.xml]
[code: Installer Installer::installEmailTemplate]
PHP Fatal error:  Uncaught Exception: DB Error: Unknown column 'stage_id' in 'field list' Query: INSERT INTO email_templates_default
                                (email_key, can_disable, can_edit, from_role_id, to_role_id, stage_id)
                                VALUES
                                ('ANNOUNCEMENT', 0, 1, 16, 1048576, null) in /home/doc/OJS/development/omp/lib/pkp/classes/db/DAO.inc.php:709
Stack trace:
#0 /home/doc/OJS/development/omp/lib/pkp/classes/db/DAO.inc.php(231): DAO->handleError()
#1 /home/doc/OJS/development/omp/lib/pkp/classes/mail/EmailTemplateDAO.inc.php(215): DAO->update()
#2 /home/doc/OJS/development/omp/lib/pkp/classes/install/Installer.inc.php(651): EmailTemplateDAO->installEmailTemplates()
#3 /home/doc/OJS/development/omp/lib/pkp/classes/install/Installer.inc.php(445): Installer->installEmailTemplate()
#4 /home/doc/OJS/development/omp/lib/pkp/classes/install/Installer.inc.php(265): Installer->executeAction()
#5 /home/doc/OJS/development/omp/lib/pkp/classes/install/Installer.inc.php(188): Installer->executeInstaller()
#6 /home/doc/OJS/development/omp/lib/pkp/classes/cl in /home/doc/OJS/development/omp/lib/pkp/classes/db/DAO.inc.php on line 709
``` 
This happens because email templates are being installed before the new upgrade scripts creates a new column `stage_id`: https://github.com/pkp/pkp-lib/blob/be20999f5ebee89d970ef42f6092a56b4f275d14/classes/migration/upgrade/PKPv3_3_0UpgradeMigration.inc.php#L49-L54

Possible solutions:
- Run `Installer::installEmailTemplate` after`PKPv3_3_0UpgradeMigration.inc.php` script execution
-  Create `stage_id` column before email templates are installed if it doesn't exists

**Comment by asmecher** [comment]
@Vitaliy-1, can you include the complete output of the upgrade process? I would think the column should get added during the sync of the `lib/pkp/xml/schema/common.xml` descriptor (specified in `dbscripts/xml/upgrade.xml`)...

**Comment by Vitaliy-1** [comment]
Complete output:
```
[pre-install]
[load: upgrade.xml]
[version: 3.3.0.0]
[code: Installer Installer::checkPhpVersion]
[code: Installer Installer::installDefaultNavigationMenus]
WARNING: The NavigationMenu (ContextId: 2, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
WARNING: The NavigationMenu (ContextId: 2, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
WARNING: The NavigationMenu (ContextId: 1, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
WARNING: The NavigationMenu (ContextId: 1, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
WARNING: The NavigationMenu (ContextId: 0, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
[code: Installer Installer::migrateStaticPagesToNavigationMenuItems]
[data: dbscripts/xml/upgrade/3.2.1_update.xml]
[code: Installer Installer::installEmailTemplate]
PHP Fatal error:  Uncaught Exception: DB Error: Unknown column 'stage_id' in 'field list' Query: INSERT INTO email_templates_default
                                (email_key, can_disable, can_edit, from_role_id, to_role_id, stage_id)
                                VALUES
                                ('ANNOUNCEMENT', 0, 1, 16, 1048576, null) in /home/doc/OJS/development/ojs/lib/pkp/classes/db/DAO.inc.php:709
Stack trace:
#0 /home/doc/OJS/development/ojs/lib/pkp/classes/db/DAO.inc.php(231): DAO->handleError()
#1 /home/doc/OJS/development/ojs/lib/pkp/classes/mail/EmailTemplateDAO.inc.php(215): DAO->update()
#2 /home/doc/OJS/development/ojs/lib/pkp/classes/install/Installer.inc.php(648): EmailTemplateDAO->installEmailTemplates()
#3 /home/doc/OJS/development/ojs/lib/pkp/classes/install/Installer.inc.php(445): Installer->installEmailTemplate()
#4 /home/doc/OJS/development/ojs/lib/pkp/classes/install/Installer.inc.php(265): Installer->executeAction()
#5 /home/doc/OJS/development/ojs/lib/pkp/classes/install/Installer.inc.php(188): Installer->executeInstaller()
#6 /home/doc/OJS/development/ojs/lib/pkp/classes/cl in /home/doc/OJS/development/ojs/lib/pkp/classes/db/DAO.inc.php on line 709
```

**Comment by Vitaliy-1** [comment]
If I understand this right:
```
<upgrade minversion="3.0.0.0" maxversion="3.1.9.9">
		<!-- Old schema syncs: These are deprecated! -->
		<schema file="lib/pkp/xml/schema/common.xml" />
                ...
```
this won't run for upgrades starting from 3.2, thus all upgrades from 3.2.0.* are affected (after `3.2.0.9` installEmailTemplate isn't triggered)

**Comment by asmecher** [comment]
You've got it, @Vitaliy-1, that's exactly the issue. OK, I'm happy with your previous suggestion, to add the column conditionally -- but I'd suggest using the Laravel schema tools instead of coding a manual `ALTER TABLE` statement.

**Comment by Vitaliy-1** [comment]
PR to pkp-lib: https://github.com/pkp/pkp-lib/pull/6311
Tests (OJS master): https://github.com/pkp/ojs/pull/2893

**Comment by asmecher** [comment]
(Discussion on the above PR here: https://github.com/pkp/pkp-lib/pull/6311#issuecomment-721801207)
