### ISSUE TITLE
Author can not access review stage

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6393]
**Describe the bug**
When the author tries to access the review stage the tab does not load and there is a fatal error encountered due to the ADODB rewrite.

**To Reproduce**
1. Move a submission through the review stage into the production stage.
2. Login as the author and go to the author view of the submission workflow.
3. Click the Review tab.

**What application are you using?**
3.3

**Additional information**
The fatal error encountered:
```
[30-Nov-2020 16:08:11 Europe/London] PHP Fatal error:  Uncaught Exception: DAOResultFactory instances do not support wasEmpty (DAO ReviewRoundDAO)! in /home/nate/Projects/pkp/ojs/lib/pkp/classes/db/DAOResultFactory.inc.php:154
Stack trace:
#0 /home/nate/Projects/pkp/ojs/cache/t_compile/6c7db842c08bb461b5d14249b41b977da4a54919^fc32d36e7a4ad3303ec79e51951776442360a0aa_0.app.controllerstabauthorDashb.php(25): DAOResultFactory->wasEmpty()
#1 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5fc518ebaa4819_44737393(Object(Smarty_Internal_Template))
#2 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#3 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#4 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/smarty/smarty/libs in /home/nate/Projects/pkp/ojs/lib/pkp/classes/db/DAOResultFactory.inc.php on line 154
```

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/6394

Tests:
https://github.com/pkp/ojs/pull/2926
https://github.com/pkp/omp/pull/888

**Comment by NateWr** [comment]
Merged.
