### ISSUE TITLE
cannot create an issue galley

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#6405]
**Describe the bug**
When I click on the Save button in the Issue Galley form I get the following PHP error message:
`PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'seq' cannot be null in /../ojs-master/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115\n ...
`
I t seems that the required seq column is nowhere set when the issue galley is created.

**To Reproduce**
1. Go to a Back Issue
2. Click on Edit
3. Go to Issue Galleys tab
4. Click on Create Issue Galley
5. Upload a file and fill out the form
6. Click on Save button
7. Nothing happens, s. php error log file

**What application are you using?**
 OJS version 3.3 github master branch

**Additional information**
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'seq' cannot be null in /.../ojs-master/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115\nStack trace:\n#0 /.../ojs-master/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(115): PDOStatement->execute()\n#1 /.../ojs-master/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(489): Doctrine\\DBAL\\Driver\\PDOStatement->execute()\n#2 /.../ojs-master/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()\n#3 /.../ojs-master/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\\Database\\Connection->runQueryCallback()\n#4 /.../ojs-master/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(496): Illuminate\\Database\\Connection->run()\n#5 /home/b in /.../ojs-master/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671, referer: http://ojs-master.bb/index.php/journal1/manageIssues

PHP Fatal error:  Uncaught Error: Call to a member function getConnection() on null in /.../ojs-master/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php:74\nStack trace:\n#0 /.../ojs-master/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php(200): Illuminate\\Database\\Capsule\\Manager::connection()\n#1 /.../ojs-master/lib/pkp/classes/db/DAO.inc.php(65): Illuminate\\Database\\Capsule\\Manager::__callStatic()\n#2 /.../ojs-master/lib/pkp/classes/context/ContextDAO.inc.php(63): DAO->retrieve()\n#3 /.../ojs-master/lib/pkp/classes/core/PKPRouter.inc.php(252): ContextDAO->getByPath()\n#4 /.../ojs-master/lib/pkp/classes/core/PKPRequest.inc.php(760): PKPRouter->getContext()\n#5 /.../ojs-master/classes/core/Request.inc.php(64): PKPRequest->_delegateToRouter()\n#6 /.../ojs-master/lib/pkp/classes/template/PKPTemplateManager.inc.php(117): Request->getContext()\n#7 /.../ojs-master/classes/ in /.../ojs-master/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php on line 74, referer: http://ojs-master.bb/index.php/journal1/manageIssues


```

**Comment by asmecher** [comment]
Fixed, thanks!
