### ISSUE TITLE
Fatal error while trying to access Journal Settings - Categories tab

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6407]
**Describe the bug**
If at least one category exists, trying to access the categories tab in the journal settings causes a fatal error. If there are no categories, a fatal error appears after creating one:
```
PHP Fatal error:  Uncaught Exception: DAOResultFactory instances cannot be counted unless supplied in constructor (DAO CategoryDAO)! in /home/doc/OJS/development/ojs/lib/pkp/classes/db/DAOResultFactory.inc.php:101
Stack trace:
#0 /home/doc/OJS/development/ojs/lib/pkp/controllers/grid/settings/category/CategoryGridCategoryRow.inc.php(41): DAOResultFactory->getCount()
#1 /home/doc/OJS/development/ojs/lib/pkp/classes/controllers/grid/CategoryGridHandler.inc.php(428): CategoryGridCategoryRow->initialize()
#2 /home/doc/OJS/development/ojs/lib/pkp/classes/controllers/grid/CategoryGridHandler.inc.php(450): CategoryGridHandler->_getInitializedCategoryRowInstance()
#3 /home/doc/OJS/development/ojs/lib/pkp/classes/controllers/grid/CategoryGridHandler.inc.php(276): CategoryGridHandler->_renderCategoriesInternally()
#4 /home/doc/OJS/development/ojs/lib/pkp/classes/controllers/grid/GridHandler.inc.php(643): CategoryGridHandler->doSpecificFetchGridActions()
#5 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPRouter.inc.php(391): GridHa in /home/doc/OJS/development/ojs/lib/pkp/classes/db/DAOResultFactory.inc.php on line 101
```

**To Reproduce**
1. Go to Dashboard -> Journal Settings -> Categories tab
2. See neverending spinner if at least 1 category exists

**What application are you using?**
 OJS 3.3

**Additional information**
See screenshot
![categories](https://user-images.githubusercontent.com/20665587/100903388-838e9900-34ce-11eb-9399-474519878ee1.png)

**Comment by Vitaliy-1** [comment]
Sorry, already resolved: https://github.com/pkp/pkp-lib/issues/6399
