### ISSUE TITLE
Can not change journal's primary language

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6451]
**Describe the bug**
When trying to change the journal's primary language, the setting does not update. The error logs show a fatal error.

**To Reproduce**
1. Go to Settings > Website > Setup > Languages.
2. Change the primary language
3. See error

**What application are you using?**
3.3 RC

**Additional information**
The error log:
```
[07-Dec-2020 13:52:01 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined method Application::getContextSettingsDAO() in /home/nate/Projects/pkp/ojs/lib/pkp/classes/context/Context.inc.php:424
Stack trace:
#0 /home/nate/Projects/pkp/ojs/lib/pkp/controllers/grid/languages/LanguageGridHandler.inc.php(146): Context->updateSetting('supportedSubmis...', Array)
#1 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/PKPRouter.inc.php(391): LanguageGridHandler->setContextPrimaryLocale(Array, Object(Request))
#2 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array)
#3 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/Dispatcher.inc.php(143): PKPComponentRouter->route(Object(Request))
#4 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/PKPApplication.inc.php(353): Dispatcher->dispatch(Object(Request))
#5 /home/nate/Projects/pkp/ojs/index.php(68): PKPApplication->execute()
#6 {main}
  thrown in /home/nate/Projects/pkp/ojs/lib/pkp/classes/context/Context.inc.php on line 424
```

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/6454

Tests:
https://github.com/pkp/ojs/pull/2946
