### ISSUE TITLE
Can't install plugins from plugin gallery

### ISSUE THREAD

**Issue by jmvezic** [pkp/pkp-lib#6487]
**Describe the bug**
Upon clicking "OK" after "Install", nothing happens. error.log file prints out:

```
[Wed Dec 16 14:26:00.141933 2020] [php7:notice] [pid 1016] [client IPADDRESS:63583] PHP Notice:  Undefined variable: body in /var/www/html/journal1/lib/pkp/controllers/grid/plugins/PluginGalleryGridHandler.inc.php on line 262, referer: http://IPADDRESS/journal1/index.php/demo/management/settings/website

[Wed Dec 16 14:26:00.142149 2020] [php7:error] [pid 1016] [client IPADDRESS:63583] PHP Fatal error:  Uncaught Error: Call to a member function getContents() on null in /var/www/html/journal1/lib/pkp/controllers/grid/plugins/PluginGalleryGridHandler.inc.php:262\nStack trace:\n#0 /var/www/html/journal1/lib/pkp/classes/core/PKPRouter.inc.php(391): PluginGalleryGridHandler->installPlugin(Array, Object(Request))\n#1 /var/www/html/journal1/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array)\n#2 /var/www/html/journal1/lib/pkp/classes/core/Dispatcher.inc.php(143): PKPComponentRouter->route(Object(Request))\n#3 /var/www/html/journal1/lib/pkp/classes/core/PKPApplication.inc.php(353): Dispatcher->dispatch(Object(Request))\n#4 /var/www/html/journal1/index.php(68): PKPApplication->execute()\n#5 {main}\n  thrown in /var/www/html/journal1/lib/pkp/controllers/grid/plugins/PluginGalleryGridHandler.inc.php on line 262, referer: http://IPADDRESS/journal1/index.php/demo/management/settings/website
```

**To Reproduce**
1. Go to Website, Plugins, Plugin Gallery, any plugin
2. Install
3. Ok

**What application are you using?**
 OJS 3.3.0.1. (latest master)

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.

**Comment by asmecher** [comment]
Thanks, @jmvezic! This issue can be resolved by applying https://github.com/pkp/pkp-lib/commit/9414c3a865a04d6a801749e3ed8f4d22767c393b in the `lib/pkp` submodule/subdirectory.
