### ISSUE TITLE
Can't load Metadata tab of Publication Format [OMP]

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6496]
**Describe the bug**
The metadata tab of a publication format does not load due to a fatal error.

```
[17-Dec-2020 13:22:44 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined method SubmissionFile::getFileSize() in /home/nate/Projects/pkp/omp/classes/publicationFormat/PublicationFormat.inc.php:266
Stack trace:
#0 /home/nate/Projects/pkp/omp/controllers/grid/catalogEntry/form/PublicationFormatMetadataForm.inc.php(153): PublicationFormat->getCalculatedFileSize()
#1 /home/nate/Projects/pkp/omp/controllers/grid/catalogEntry/PublicationFormatGridHandler.inc.php(585): PublicationFormatMetadataForm->initData()
#2 /home/nate/Projects/pkp/omp/lib/pkp/classes/core/PKPRouter.inc.php(391): PublicationFormatGridHandler->editFormatMetadata(Array, Object(Request))
#3 /home/nate/Projects/pkp/omp/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array)
#4 /home/nate/Projects/pkp/omp/lib/pkp/classes/core/Dispatcher.inc.php(143): PKPComponentRouter->route(Object(Request))
#5 /home/nate/Projects/pkp/omp/lib/pkp/classes/core/PKPApplication.inc.php(353): Dispatcher->dispatch(Object(Request))
#6 / in /home/nate/Projects/pkp/omp/classes/publicationFormat/PublicationFormat.inc.php on line 266
```

**To Reproduce**
1. Go to a submission's workflow and click Publication > Publication Formats.
2. Add a Publication Format.
3. Expand the options for that format and click Edit.
4. Try to load Metadata tab.

**What application are you using?**
OMP 3.3 RC2

**Comment by asmecher** [comment]
I think this was already fixed by https://github.com/pkp/omp/commit/dbe9cc2d899f59d2de86f8509f163844401db9b0 -- is that commit included in your test install?

**Comment by NateWr** [comment]
Correct. I can't reproduce this in latest master.
