### ISSUE TITLE
User subscriptions page is inaccessible

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6509]
**Describe the bug**
Trying to visit user subscriptions page throws a fatal error:
```
127.0.0.1:42356 [500]: GET /index.php/publicknowledge/user/subscriptions - Uncaught Error: Call to undefined method Generator::Close() in /home/doc/OJS/development/ojs/classes/subscription/SubscriptionTypeDAO.inc.php:313
Stack trace:
#0 /home/doc/OJS/development/ojs/pages/user/UserHandler.inc.php(35): SubscriptionTypeDAO->subscriptionTypesExistByInstitutional()
#1 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPRouter.inc.php(391): UserHandler->subscriptions()
#2 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest()
#3 /home/doc/OJS/development/ojs/lib/pkp/classes/core/Dispatcher.inc.php(143): PKPPageRouter->route()
#4 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPApplication.inc.php(353): Dispatcher->dispatch()
#5 /home/doc/OJS/development/ojs/index.php(68): PKPApplication->execute()
#6 {main}
  thrown in /home/doc/OJS/development/ojs/classes/subscription/SubscriptionTypeDAO.inc.php on line 313
```

**To Reproduce**
1. Activate subscriptions: Distribution -> Acess -> The journal will require subscriptions to access some or all of its contents.
2. Visit the journal's user subscriptions page `...user/subscriptions`
3. See the error

**What application are you using?**
 OJS, current master branch (3.3)

**Comment by Vitaliy-1** [comment]
PR to OJS master: https://github.com/pkp/ojs/pull/2967

**Comment by NateWr** [comment]
Thanks @Vitaliy-1!
