### ISSUE TITLE
Accessing search authors page produces a fatal error

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6556]
**Describe the bug**
Visiting searchAuthors page produces a fatal error:
```
[Fri Jan  8 15:39:00 2021] 127.0.0.1:48808 [500]: GET /index.php/publicknowledge/search/authors - Uncaught Exception: DAOResultFactory instances do not support wasEmpty (DAO AuthorDAO)! in /home/doc/OJS/development/ojs/lib/pkp/classes/db/DAOResultFactory.inc.php:154
Stack trace:
#0 /home/doc/OJS/development/ojs/cache/t_compile/b4bc7db39b8c69690e4088d87370de4259f46a3d^c2055d14f27582f3361894f4184ce1a4c0497385_0.app.frontendpagessearchAuthor.php(98): DAOResultFactory->wasEmpty()
pkp/classic#1 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5ff860740e0c09_87521700()
pkp/classic#2 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
pkp/classic#3 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
pkp/classic#4 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render()
pkp/classic#5  in /home/doc/OJS/development/ojs/lib/pkp/classes/db/DAOResultFactory.inc.php on line 154
```

**Comment by Vitaliy-1** [comment]
What about turning Authors DAOResultFactory into VirtualArrayIterator with something like:
```
import('lib.pkp.classes.core.VirtualArrayIterator');
$authors = VirtualArrayIterator::factory($authorsFactory->toArray(), $rangeInfo);
```
or the latter isn't designed for such cases?

**Comment by asmecher** [comment]
I'd like to get rid of the whole custom set of classes (`ItemIterator`, `ArrayItemIterator`, `VirtualArrayIterator`, then eventually `DAOResultFactory` etc) in favour of the Laravel lazy collection toolset -- so I'd rather avoid introducing a new use case for one of them.

**Comment by asmecher** [comment]
There is a change that themes could make to save a SQL query (https://github.com/pkp/ojs/commit/19c508d569c4175ba1b7a5461be882b7fa483fa2#diff-a70e64d25a6d43598b840748a81c6ac1a1a74827297c7e9994d5fcd371b2c5e3) -- but I've fixed the underlying `wasEmpty` function in this case, so it's strictly optional.
