### ISSUE TITLE
Upgrade from command line fails if installed is set to Off in config

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6587]
**Describe the bug**
Receiving a fatal error when upgrade starts with `installed` set to Off:
```
PHP Fatal error:  Uncaught Error: Call to a member function getConnection() on null in /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php:74
Stack trace:
#0 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php(200): Illuminate\Database\Capsule\Manager::connection()
#1 /home/doc/OJS/development/ojs/lib/pkp/classes/db/DAO.inc.php(65): Illuminate\Database\Capsule\Manager::__callStatic()
#2 /home/doc/OJS/development/ojs/lib/pkp/classes/plugins/PluginSettingsDAO.inc.php(106): DAO->retrieve()
#3 /home/doc/OJS/development/ojs/lib/pkp/classes/plugins/PluginSettingsDAO.inc.php(86): PluginSettingsDAO->getPluginSettings()
#4 /home/doc/OJS/development/ojs/lib/pkp/classes/cache/GenericCache.inc.php(63): PluginSettingsDAO->_cacheMiss()
#5 /home/doc/OJS/development/ojs/lib/pkp/classes/plugins/PluginSettingsDAO.inc.php(57): GenericCache->get()
#6 /home/doc/OJS/development/ojs/lib/pkp/classes/plugins/Plugin.inc.php(463): Plugin in /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php on line 74
```

**To Reproduce**
1. Set `installed` to Off in `config.inc.php`
2. execute `php tools/upgrade.php upgrade` from a terminal 
3. See error

**What application are you using?**
 OJS 3.2.1-2 to OJS 3.3 upgrade (current master branch)

**Additional information**
I have a deja vu feeling that I saw a similar bug report before but cannot find it.

**Comment by asmecher** [comment]
PR: https://github.com/pkp/pkp-lib/pull/6622
Test PR: https://github.com/pkp/ojs/pull/2998
Tests: https://travis-ci.com/github/pkp/ojs/builds/213578221

Could you have a look at the pkp-lib PR, @Vitaliy-1?

**Comment by Vitaliy-1** [comment]
@asmecher, yes, it solves the issue

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1! Merged.
