### ISSUE TITLE
OJS 3.3 - Importing article XML format failing

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#6597]
**Describe the bug**
Importing a XML file of a single submission is not working. Even when this submission is generated from a OJS 3.3 installation. It upload

**To Reproduce**
1. Go to 'Tools > Native XML Plugin > Import (tab) '
2. Click on 'Upload a file' or drag and drop a submission XML format file
3. Click 'Import' button
4. See the error

**What application are you using?**
 OJS version 3.3

**Additional information**

https://user-images.githubusercontent.com/4992902/104611954-ac6c8700-5653-11eb-8706-795e309b5346.mov

**Log error output**

```
[Thu Jan 14 07:23:22.572692 2021] [cgi:error] [pid 1910:tid 47449652115200] [client 99.250.150.155:64876] AH01215: #1 /www/ojs3/testing-3_3/lib/pkp/classes/filter/Filter.inc.php(449): NativeXmlArticleFilter->process(Object(DOMDocument)): /www/ojs3/testing-3_3/index.php, referer: https://localhost/ojs3/testing-3_3/index.php/jfit/management/importexport/plugin/NativeImportExportPlugin
[Thu Jan 14 07:23:22.572817 2021] [cgi:error] [pid 1910:tid 47449652115200] [client 99.250.150.155:64876] AH01215: #2 /www/ojs3/testing-3_3/plugins/importexport/native/NativeImportExportPlugin.inc.php(312): Filter->execute(Object(DOMDocument)): /www/ojs3/testing-3_3/index.php, referer: https://localhost/ojs3/testing-3_3/index.php/jfit/management/importexport/plugin/NativeImportExportPlugin
[Thu Jan 14 07:23:22.573174 2021] [cgi:error] [pid 1910:tid 47449652115200] [client 99.250.150.155:64876] AH01215: #3 /www/ojs3/testing-3_3/plugins/importexport/native/NativeImportExportPlugin.inc.php(147): NativeImportExportPlugin->importSubmissions(Object(DOMDocument), 'native-xml=>art...', Object(NativeImport in /www/ojs3/testing-3_3/classes/search/ArticleSearchIndex.inc.php on line 38: /www/ojs3/testing-3_3/index.php, referer: https://localhost/ojs3/testing-3_3/index.php/jfit/management/importexport/plugin/NativeImportExportPlugin
```

**Comment by asmecher** [comment]
Assigning to you, @defstat!

**Comment by emmauhl** [comment]
I attempted to do an article import to get some dummy data for documentation writing and encountered this problem following the same steps, but contrary to Israel's video, I did get a list of validation errors in the results, which I will paste below just in case it's of use!

`Validation errors:
Element '{http://pkp.sfu.ca}revision': This element is not expected. Expected is one of ( {http://pkp.sfu.ca}creator, {http://pkp.sfu.ca}description, {http://pkp.sfu.ca}name ).
Element '{http://pkp.sfu.ca}revision': This element is not expected. Expected is one of ( {http://pkp.sfu.ca}creator, {http://pkp.sfu.ca}description, {http://pkp.sfu.ca}name ).
Element '{http://pkp.sfu.ca}revision': This element is not expected. Expected is one of ( {http://pkp.sfu.ca}creator, {http://pkp.sfu.ca}description, {http://pkp.sfu.ca}name ).
Element '{http://pkp.sfu.ca}revision': This element is not expected. Expected is one of ( {http://pkp.sfu.ca}creator, {http://pkp.sfu.ca}description, {http://pkp.sfu.ca}name ).
Element '{http://pkp.sfu.ca}submission_file_ref', attribute 'revision': The attribute 'revision' is not allowed.
Element '{http://pkp.sfu.ca}revision': This element is not expected. Expected is one of ( {http://pkp.sfu.ca}creator, {http://pkp.sfu.ca}description, {http://pkp.sfu.ca}name ).
Element '{http://pkp.sfu.ca}revision': This element is not expected. Expected is one of ( {http://pkp.sfu.ca}creator, {http://pkp.sfu.ca}description, {http://pkp.sfu.ca}name ).
Element '{http://pkp.sfu.ca}submission_file_ref', attribute 'revision': The attribute 'revision' is not allowed.
Element '{http://pkp.sfu.ca}revision': This element is not expected. Expected is one of ( {http://pkp.sfu.ca}creator, {http://pkp.sfu.ca}description, {http://pkp.sfu.ca}name ).
Element '{http://pkp.sfu.ca}revision': This element is not expected. Expected is one of ( {http://pkp.sfu.ca}creator, {http://pkp.sfu.ca}description, {http://pkp.sfu.ca}name ).
Element '{http://pkp.sfu.ca}submission_file_ref', attribute 'revision': The attribute 'revision' is not allowed.
Element '{http://pkp.sfu.ca}revision': This element is not expected. Expected is one of ( {http://pkp.sfu.ca}creator, {http://pkp.sfu.ca}description, {http://pkp.sfu.ca}name ).
Element '{http://pkp.sfu.ca}revision': This element is not expected. Expected is one of ( {http://pkp.sfu.ca}creator, {http://pkp.sfu.ca}description, {http://pkp.sfu.ca}name ).
Element '{http://pkp.sfu.ca}submission_file_ref', attribute 'revision': The attribute 'revision' is not allowed.
Element '{http://pkp.sfu.ca}revision': This element is not expected. Expected is one of ( {http://pkp.sfu.ca}creator, {http://pkp.sfu.ca}description, {http://pkp.sfu.ca}name ).
Element '{http://pkp.sfu.ca}revision': This element is not expected. Expected is one of ( {http://pkp.sfu.ca}creator, {http://pkp.sfu.ca}description, {http://pkp.sfu.ca}name ).
Element '{http://pkp.sfu.ca}submission_file_ref', attribute 'revision': The attribute 'revision' is not allowed.
Element '{http://pkp.sfu.ca}revision': This element is not expected. Expected is one of ( {http://pkp.sfu.ca}creator, {http://pkp.sfu.ca}description, {http://pkp.sfu.ca}name ).
Element '{http://pkp.sfu.ca}supplementary_file': This element is not expected. Expected is one of ( {http://pkp.sfu.ca}submission_file, {http://pkp.sfu.ca}pkppublication, {http://pkp.sfu.ca}publication ).`

**Comment by asmecher** [comment]
@emmauhl, what XML file are you uploading?

**Comment by emmauhl** [comment]
@asmecher A random selection of 5 or so articles from a 3.2 test journal - sorry for not clarifying!

**Comment by dmasta88** [comment]
> @asmecher A random selection of 5 or so articles from a 3.2 test journal - sorry for not clarifying!

The same errors. What is changes in XML import?

**Comment by defstat** [comment]
@israelcefrin, thanks for reporting that. By using the data from [pkp/datasets](https://github.com/pkp/datasets) and the `ojs:stable-3.3.0` branch I can't reproduce the issue. If the problem persists, can you provide an import file that is problematic?

**Comment by asmecher** [comment]
Hi all -- in order to reproduce this issue we will need an import XML document that demonstrates the problem on a 3.3.0-10 installation. If you're able to pass this along, please do; I'll close this in the meantime.
