### ISSUE TITLE
OMP 3.3 Deleting submission returns an error and removes all submissions

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#6607]
**Describe the bug**
When removing a submission from the system, a modal error shows up and every submission is removed.

**To Reproduce**
1. Go to a submission page
2. Decline it
3.  Go back to submissions and find the declined ond
4.  Click the blue error to show options
5. Click 'delete''
6. See the error

**What application are you using?**
OMP version 3.3

**Additional information**

![image](https://user-images.githubusercontent.com/4992902/104647694-45b19280-5680-11eb-962c-c3d635e85770.png)

![image](https://user-images.githubusercontent.com/4992902/104647770-5bbf5300-5680-11eb-80ca-4864a2605235.png)

**Log error**

```
[Thu Jan 14 13:27:43.296723 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: Slim Application Error:: /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.296755 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: Type: Error: /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.296794 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: Message: Call to a member function getData() on null: /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.296920 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: File: /var/www/omp3/testing-3_3/lib/pkp/classes/submission/PKPSubmission.inc.php: /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.296930 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: Line: 54: /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.297041 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: Trace: #0 /var/www/omp3/testing-3_3/classes/services/SubmissionService.inc.php(134): PKPSubmission->getBestId(): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.297193 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #1 /var/www/omp3/testing-3_3/lib/pkp/classes/plugins/HookRegistry.inc.php(107): APP\\Services\\SubmissionService->modifyPropertyValues('Submission::get...', Array): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.297335 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #2 /var/www/omp3/testing-3_3/lib/pkp/classes/services/PKPSubmissionService.inc.php(254): HookRegistry::call('Submission::get...', Array): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.297487 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #3 /var/www/omp3/testing-3_3/lib/pkp/classes/services/PKPSubmissionService.inc.php(297): PKP\\Services\\PKPSubmissionService->getProperties(Object(Submission), Array, Array): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.297653 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #4 /var/www/omp3/testing-3_3/lib/pkp/api/v1/_submissions/PKPBackendSubmissionsHandler.inc.php(158): PKP\\Services\\PKPSubmissionService->getBackendListProperties(Object(Submission), Array): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.297735 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #5 [internal function]: PKPBackendSubmissionsHandler->getMany(Object(Slim\\Http\\Request), Object(APIResponse), Array): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.297902 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #6 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\\Http\\Request), Object(APIResponse), Array): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.298682 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #7 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(281): Slim\\Handlers\\Strategies\\RequestResponse->__invoke(Array, Object(Slim\\Http\\Request), Object(APIResponse), Array): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.298849 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #8 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\Route->__invoke(Object(Slim\\Http\\Request), Object(APIResponse)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.299002 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #9 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(268): Slim\\Route->callMiddlewareStack(Object(Slim\\Http\\Request), Object(APIResponse)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.299132 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #10 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/App.php(503): Slim\\Route->run(Object(Slim\\Http\\Request), Object(APIResponse)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.300101 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #11 /var/www/omp3/testing-3_3/lib/pkp/classes/security/authorization/internal/ApiAuthorizationMiddleware.inc.php(77): Slim\\App->__invoke(Object(Slim\\Http\\Request), Object(APIResponse)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.300206 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #12 [internal function]: ApiAuthorizationMiddleware->__invoke(Object(Slim\\Http\\Request), Object(APIResponse), Object(Slim\\App)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.300345 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #13 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(ApiAuthorizationMiddleware), Array): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.300429 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #14 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(APIResponse), Object(Slim\\App)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.300624 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #15 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(APIResponse), Object(Slim\\App)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.300798 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #16 /var/www/omp3/testing-3_3/lib/pkp/classes/security/authorization/internal/ApiCsrfMiddleware.inc.php(46): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(APIResponse)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.300882 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #17 [internal function]: ApiCsrfMiddleware->__invoke(Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.301012 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #18 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(ApiCsrfMiddleware), Array): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.301103 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #19 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.301280 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #20 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.301454 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #21 /var/www/omp3/testing-3_3/lib/pkp/classes/security/authorization/internal/ApiTokenDecodingMiddleware.inc.php(82): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(APIResponse)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.301541 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #22 [internal function]: ApiTokenDecodingMiddleware->__invoke(Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.301679 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #23 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(ApiTokenDecodingMiddleware), Array): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.301780 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #24 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.301950 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #25 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.302097 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #26 /var/www/omp3/testing-3_3/lib/pkp/classes/handler/APIHandler.inc.php(68): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(APIResponse)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.302176 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #27 [internal function]: APIHandler->{closure}(Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.302311 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #28 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.302394 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #29 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.302567 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #30 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.302714 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #31 /var/www/omp3/testing-3_3/lib/pkp/classes/handler/APIHandler.inc.php(127): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(APIResponse)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.302798 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #32 [internal function]: APIHandler->{closure}(Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.302937 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #33 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.303045 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #34 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.303258 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #35 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.303432 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #36 /var/www/omp3/testing-3_3/lib/pkp/classes/handler/APIHandler.inc.php(132): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(APIResponse)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.303521 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #37 [internal function]: APIHandler->{closure}(Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.303645 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #38 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.303728 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #39 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.303907 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #40 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.304072 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #41 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(APIResponse)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.304219 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #42 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\\App->callMiddlewareStack(Object(Slim\\Http\\Request), Object(APIResponse)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.304358 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #43 /var/www/omp3/testing-3_3/lib/pkp/classes/handler/APIHandler.inc.php(124): Slim\\App->process(Object(Slim\\Http\\Request), Object(APIResponse)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.304441 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #44 [internal function]: APIHandler->{closure}(Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.304568 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #45 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.304656 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #46 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.304836 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #47 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.304979 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #48 /var/www/omp3/testing-3_3/lib/pkp/classes/handler/APIHandler.inc.php(132): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(APIResponse)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.305072 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #49 [internal function]: APIHandler->{closure}(Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.305199 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #50 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.305286 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #51 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.305465 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #52 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(APIResponse), Object(Closure)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.305621 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #53 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(APIResponse)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.305764 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #54 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\\App->callMiddlewareStack(Object(Slim\\Http\\Request), Object(APIResponse)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.305897 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #55 /var/www/omp3/testing-3_3/lib/pkp/lib/vendor/slim/slim/Slim/App.php(297): Slim\\App->process(Object(Slim\\Http\\Request), Object(APIResponse)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.306004 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #56 /var/www/omp3/testing-3_3/lib/pkp/classes/core/APIRouter.inc.php(115): Slim\\App->run(): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.306113 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #57 /var/www/omp3/testing-3_3/lib/pkp/classes/core/Dispatcher.inc.php(144): APIRouter->route(Object(Request)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.306239 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #58 /var/www/omp3/testing-3_3/lib/pkp/classes/core/PKPApplication.inc.php(353): Dispatcher->dispatch(Object(Request)): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.306332 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #59 /var/www/omp3/testing-3_3/index.php(64): PKPApplication->execute(): /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.306343 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: #60 {main}: /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.306393 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: View in rendered output by enabling the "displayErrorDetails" setting.: /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions
[Thu Jan 14 13:27:43.306398 2021] [cgi:error] [pid 24786:tid 47284100888320] [client 99.250.150.155:51522] AH01215: : /www/omp3/testing-3_3/index.php, referer: https://localhost/omp3/testing-3_3/index.php/pkptp/submissions

```

**Comment by asmecher** [comment]
Thanks, @israelcefrin -- I wasn't able to replicate this locally. Did the disappearance of all submissions get persisted, i.e. does reloading the archive list cause them to reappear?

**Comment by israelcefrin** [comment]
@asmecher the disappearance  persists even reloading the archive list or any other tab.

**Comment by asmecher** [comment]
Investigating a little -- the submission lists weren't displaying because of a couple of submissions that had invalid `current_publication_id` entries. Perhaps something happened during the deletion of the submission that removed `publication` entries without removing the attached `submission`? Or incomplete data due to import/export testing or similar?

**Comment by asmecher** [comment]
Sounds like some import/export testing was happening -- the delete submission feature works fine for me (and there's some robustness improvement coming separately over there).
