### ISSUE TITLE
[OJS] PHP Warning and fatal error

### ISSUE THREAD

**Issue by cboulanger** [pkp/pkp-lib#6774]
```
PHP Warning:  Declaration of ManageSubmissionFilesForm::execute($stageSubmissionFiles, $fileStage = NULL) should be compatible with Form::execute(...$functionArgs) in /var/www/ojs-3.3.0/lib/pkp/controllers/grid/files/form/ManageSubmissionFilesForm.inc.php on line 19, referer: https://mydomain.com/ojs/index.php/myjournal/workflow/index/14/4
PHP Stack trace:, referer: https://mydomain.com/ojs/index.php/myjournal/workflow/index/14/4
PHP   1. {main}() /var/www/ojs-3.3.0/index.php:0, referer: https://mydomain.com/ojs/index.php/myjournal/workflow/index/14/4
PHP   2. Application->execute() /var/www/ojs-3.3.0/index.php:68, referer: https://mydomain.com/ojs/index.php/myjournal/workflow/index/14/4
PHP   3. Dispatcher->dispatch() /var/www/ojs-3.3.0/lib/pkp/classes/core/PKPApplication.inc.php:364, referer: https://mydomain.com/ojs/index.php/myjournal/workflow/index/14/4
PHP   4. PKPComponentRouter->route() /var/www/ojs-3.3.0/lib/pkp/classes/core/Dispatcher.inc.php:144, referer: https://mydomain.com/ojs/index.php/myjournal/workflow/index/14/4
PHP   5. PKPComponentRouter->_authorizeInitializeAndCallRequest() /var/www/ojs-3.3.0/lib/pkp/classes/core/PKPComponentRouter.inc.php:257, referer: https://mydomain.com/ojs/index.php/myjournal/workflow/index/14/4
PHP   6. CopyeditFilesGridHandler->selectFiles() /var/www/ojs-3.3.0/lib/pkp/classes/core/PKPRouter.inc.php:395, referer: https://mydomain.com/ojs/index.php/myjournal/workflow/index/14/4
PHP   7. import() /var/www/ojs-3.3.0/lib/pkp/controllers/grid/files/copyedit/CopyeditFilesGridHandler.inc.php:79, referer: https://mydomain.com/ojs/index.php/myjournal/workflow/index/14/4
PHP   8. require_once() /var/www/ojs-3.3.0/lib/pkp/includes/functions.inc.php:25, referer: https://mydomain.com/ojs/index.php/myjournal/workflow/index/14/4
PHP   9. import() /var/www/ojs-3.3.0/lib/pkp/controllers/grid/files/copyedit/form/ManageCopyeditFilesForm.inc.php:16, referer: https://mydomain.com/ojs/index.php/myjournal/workflow/index/14/4
PHP  10. require_once() /var/www/ojs-3.3.0/lib/pkp/includes/functions.inc.php:25, referer: https://mydomain.com/ojs/index.php/myjournal/workflow/index/14/4

PHP Fatal error:  Uncaught Error: Call to a member function getAssocId() on null in /var/www/ojs-3.3.0/lib/pkp/controllers/grid/files/SubmissionFilesCategoryGridDataProvider.inc.php:131 Stack trace: 
#0 /var/www/ojs-3.3.0/lib/pkp/classes/controllers/grid/CategoryGridHandler.inc.php(402): SubmissionFilesCategoryGridDataProvider->loadCategoryData(Object(Request), 4, Array)
 #1 /var/www/ojs-3.3.0/lib/pkp/classes/controllers/grid/CategoryGridHandler.inc.php(124): CategoryGridHandler->loadCategoryData(Object(Request), 4, Array) 
#2 /var/www/ojs-3.3.0/lib/pkp/classes/controllers/grid/CategoryGridHandler.inc.php(473): CategoryGridHandler->getGridCategoryDataElements(Object(Request), 4) 
#3 /var/www/ojs-3.3.0/lib/pkp/classes/controllers/grid/CategoryGridHandler.inc.php(453): CategoryGridHandler->_renderCategoryInternally(Object(Request), Object(SelectableSubmissionFileListCategoryGridRow))
 #4 /var/www/ojs-3.3.0/lib/pkp/classes/controllers/grid/CategoryGridHandler.inc.php(276): CategoryGridHandler->_renderCategoriesInternally(Object(Reques in /var/www/ojs-3.3.0/lib/pkp/controllers/grid/files/SubmissionFilesCategoryGridDataProvider.inc.php on line 131, referer: https://mydomain.com/ojs/index.php/myjournal/workflow/index/14/4
```
- OJS 3.3.0.2.
- PHP 7.3.27-1~deb10u1
- 5.5.5-10.3.25-MariaDB-0+deb10u1

**Comment by cboulanger** [comment]
Also, I am having this error, don't know if it is related:
```
PHP Fatal error:  Uncaught Error: Call to a member function getAssocType() on null in /var/www/ojs-3.3.0/lib/pkp/classes/security/authorization/internal/SubmissionFileNotQueryAccessPolicy.inc.php:37
Stack trace:\n#0 /var/www/ojs-3.3.0/lib/pkp/classes/security/authorization/AuthorizationDecisionManager.inc.php(196): SubmissionFileNotQueryAccessPolicy->effect()
#1 /var/www/ojs-3.3.0/lib/pkp/classes/security/authorization/AuthorizationDecisionManager.inc.php(204): AuthorizationDecisionManager->_decidePolicySet(Object(PolicySet), NULL)
#2 /var/www/ojs-3.3.0/lib/pkp/classes/security/authorization/AuthorizationDecisionManager.inc.php(204): AuthorizationDecisionManager->_decidePolicySet(Object(PolicySet), NULL)
#3 /var/www/ojs-3.3.0/lib/pkp/classes/security/authorization/AuthorizationDecisionManager.inc.php(204): AuthorizationDecisionManager->_decidePolicySet(Object(PolicySet), NULL)
#4 /var/www/ojs-3.3.0/lib/pkp/classes/security/authorization/AuthorizationDecisionManager.inc.php(204): AuthorizationDecisionManager->_decidePolicySet(Ob in /var/www/ojs-3.3.0/lib/pkp/classes/security/authorization/internal/SubmissionFileNotQueryAccessPolicy.inc.php on line 37,<snip>
```

**Comment by asmecher** [comment]
@cboulanger, I think this is a data error. Try the following query:
```
SELECT sf.submission_file_id FROM submission_files sf LEFT JOIN notes n ON (sf.assoc_id = n.note_id) WHERE sf.assoc_type = 520 AND n.note_id IS NULL;
```
This will list any `submission_files` entries that refer to entries in the `notes` table that do not exist. If these do not appear to be important, you could remove them. (Please take a complete backup of your database before modifying it directly.)

If you're able to replicate the steps that cause the missing entry, please document them here.

**Comment by cboulanger** [comment]
Thank you very much for responding so quickly.

In fact I get three records. After a backup, I tried to delete them with
```sql
delete from submission_files where submission_file_id in (SELECT sf.submission_file_id FROM submission_files sf LEFT JOIN notes n ON (sf.assoc_id = n.note_id) WHERE sf.assoc_type = 520 AND n.note_id IS NULL);
```

but got this:

```
Fehler in der SQL-Abfrage (1451): Cannot delete or update a parent row: a foreign key constraint fails (`ojs_3_3`.`submission_file_revisions`, CONSTRAINT `submission_file_revisions_submission_file_id_foreign` FOREIGN KEY (`submission_file_id`) REFERENCES `submission_files` (`submission_file_id`)) 
```

What would be the right way of deleting the problematic records?

**Comment by asmecher** [comment]
@cboulanger, this means there are references to those records in the `submission_file_revisions` table that need to be cleared out first. You can do that with...
```
DELETE FROM submission_file_revisions WHERE submission_file_id IN (SELECT sf.submission_file_id FROM submission_files sf LEFT JOIN notes n ON (sf.assoc_id = n.note_id) WHERE sf.assoc_type = 520 AND n.note_id IS NULL);
```
(As always, please take a complete backup before running database queries directly!)

**Comment by cboulanger** [comment]
Thank you very much. This worked! 

Maybe you can add some checks to prevent such inconsistencies in the data?

**Comment by NateWr** [comment]
I'll close this for now but feel free to reopen this Alec if you want to do further work on it.

**Comment by elton557** [comment]
Hi @asmecher , here I face a similar problem, I did the above process, but it had no effect, follow my log, can you help me?

[Fri Sep 17 14:19:35.540154 2021] [php7:notice] [pid 17607] [client Oculto] PHP Notice:  Undefined index: stageId in /var/www/submission_scielo_br/htdocs/lib/pkp/controllers/grid/eventLog/SubmissionEventLogGridHandler.inc.php on line 111, referer: https://oculto/index.php/resr/workflow/index/250494/1
[Fri Sep 17 14:19:36.024663 2021] [php7:error] [pid 17607] [client Oculto PHP Fatal error:  Uncaught Error: Call to undefined method SubmissionFile::getFileId() in /var/www/submission_scielo_br/htdocs/lib/pkp/classes/services/PKPSubmissionFileService.inc.php:774\nStack trace:\n#0 /var/www/submission_scielo_br/htdocs/lib/pkp/controllers/grid/eventLog/EventLogGridRow.inc.php(79): PKP\\Services\\PKPSubmissionFileService->getWorkflowStageId(Object(SubmissionFile))\n#1 /var/www/submission_scielo_br/htdocs/lib/pkp/classes/controllers/grid/GridHandler.inc.php(1066): EventLogGridRow->initialize(Object(Request))\n#2 /var/www/submission_scielo_br/htdocs/lib/pkp/classes/controllers/grid/GridHandler.inc.php(983): GridHandler->_getInitializedRowInstance(Object(Request), 54, Object(SubmissionEventLogEntry))\n#3 /var/www/submission_scielo_br/htdocs/lib/pkp/classes/controllers/grid/GridHandler.inc.php(1031): GridHandler->renderRowsInternally(Object(Request), Array)\n#4 /var/www/submission_scielo_br/htdocs/lib/pkp/classes/controllers/grid/GridHandler.inc.php(921): GridHandler->renderGridBodyPartsInternally(Object(Request))\n in /var/www/submission_scielo_br/htdocs/lib/pkp/classes/services/PKPSubmissionFileService.inc.php on line 774, referer: https://Oculto/index.php/resr/workflow/index/250494/1

**Comment by asmecher** [comment]
@elton557, I think this is the same issue described here:

https://forum.pkp.sfu.ca/t/activity-log-doesnt-load-ojs-3-3-0-6/68319/2

Could you follow-up on Jason's suggestion there?
