### ISSUE TITLE
Fatal error when removing announcement types

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6798]
**Describe the bug**
When removing an announcement type, the request returns 500 and a fatal error appears in the logs. 

Although the error message appears, the deletion seems to happen. The list does not refresh, though.

**To Reproduce**
1. Go to Announcements > Announcement Types.
2. Create an announcement.
3. Delete it.
4. See error in l og

**What application are you using?**
3.3.0-3

**Additional information**
The error log:

```
[25-Feb-2021 15:28:11 Europe/London] PHP Fatal error:  Uncaught Error: Cannot use object of type Generator as array in /home/nate/Projects/pkp/ojs-stable/lib/pkp/classes/controllers/grid/GridHandler.inc.php:818
Stack trace:
#0 /home/nate/Projects/pkp/ojs-stable/lib/pkp/classes/controllers/grid/GridHandler.inc.php(508): GridHandler->getRowDataElement(Object(Request), '2')
#1 /home/nate/Projects/pkp/ojs-stable/lib/pkp/classes/controllers/grid/GridHandler.inc.php(699): GridHandler->getRequestedRow(Object(Request), Array)
#2 /home/nate/Projects/pkp/ojs-stable/lib/pkp/classes/core/PKPRouter.inc.php(395): GridHandler->fetchRow(Array, Object(Request))
#3 /home/nate/Projects/pkp/ojs-stable/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array)
#4 /home/nate/Projects/pkp/ojs-stable/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPComponentRouter->route(Object(Request))
#5 /home/nate/Projects/pkp/ojs-stable/lib/pkp/classes/core/PKPApplication.inc.php(364): Dispatcher->dispatch(Object(Request))
#6 / in /home/nate/Projects/pkp/ojs-stable/lib/pkp/classes/controllers/grid/GridHandler.inc.php on line 818
```

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/6799

Tests:
https://github.com/pkp/ojs/pull/3056

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and cherry-picked to `main`.
