### ISSUE TITLE
Make submission deletion more accepting of missing files

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6860]
When an editor deletes a submission from the archive, if the file is missing from the filesystem, they will get an error in the log:
```
[12-Mar-2021 18:56:23 UTC] Slim Application Error:
Type: League\Flysystem\FileNotFoundException
Message: File not found at path: journals/1/articles/18/submission/18-1-27-1-2-20210204.pdf
File: .../lib/pkp/lib/vendor/league/flysystem/src/Filesystem.php
Line: 389
Trace: #0 .../lib/pkp/lib/vendor/league/flysystem/src/Filesystem.php(235): League\Flysystem\Filesystem->assertPresent()
#1 .../lib/pkp/classes/services/PKPFileService.inc.php(106): League\Flysystem\Filesystem->delete()
#2 .../lib/pkp/classes/services/PKPSubmissionFileService.inc.php(580): PKP\Services\PKPFileService->delete()
#3 .../lib/pkp/classes/submission/PKPSubmissionDAO.inc.php(129): PKP\Services\PKPSubmissionFileService->delete()
#4 .../classes/submission/SubmissionDAO.inc.php(51): PKPSubmissionDAO->deleteById()
#5 .../lib/pkp/classes/submission/PKPSubmissionDAO.inc.php(104): SubmissionDAO->deleteById()
#6 .../lib/pkp/classes/services/PKPSubmissionService.inc.php(783): PKPSubmissionDAO->deleteObject()
#7 .../lib/pkp/api/v1/_submissions/PKPBackendSubmissionsHandler.inc.php(197): PKP\Services\PKPSubmissionService->delete()
#8 [internal function]: PKPBackendSubmissionsHandler->delete()
#9 .../lib/pkp/lib/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()
#10 .../lib/pkp/lib/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke()
```

Because the exception interrupted the deletion, some submission details will remain in the database. This can cause downstream problems when the partial submission is fetched:
```
[12-Mar-2021 19:00:40 UTC] Slim Application Error:
Type: Error
Message: Call to a member function getData() on null
File: .../lib/pkp/classes/submission/PKPSubmission.inc.php
Line: 54
Trace: #0 .../classes/services/SubmissionService.inc.php(167): PKPSubmission->getBestId()
#1 .../lib/pkp/classes/plugins/HookRegistry.inc.php(107): APP\Services\SubmissionService->modifyPropertyValues()
#2 .../lib/pkp/classes/services/PKPSubmissionService.inc.php(254): HookRegistry::call()
#3 .../lib/pkp/classes/services/PKPSubmissionService.inc.php(297): PKP\Services\PKPSubmissionService->getProperties()
```

This may be the cause of problems like...
- https://forum.pkp.sfu.ca/t/fatal-error-when-rebuildsearchindex-php/66231
- https://forum.pkp.sfu.ca/t/an-unexpected-error-occurred-you-may-have-been-logged-out/66356

Make nonexistent files less of a show-stopper. For example, continue without failure if the file did not exist in the first place; log other errors but do not fail to delete the rest of submission contents. (For bonus points, if it's easy to make the cases noted in the forum posts more resilient for users with existing data problems, do so.)

**Comment by asmecher** [comment]
Also fixes a minor problem with the notification update for "needs galleys" introduced here: https://github.com/pkp/pkp-lib/commit/90f40e1e1326c26b28c7472f90132e09c1f698fd#diff-7691560277cad85454de4744b19f7add2e8efb20c2b075ef500af4f1a934d0ccR114
