### ISSUE TITLE
Session destruction (and duplicate) warnings in the PHP error log

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6871]
A user reports session destruction warnings in the PHP log:
```
[20-Feb-2021 14:42:08 America/New_York] PHP Warning:  session_destroy(): Session object destruction failed in /home/seisense/journal.seisense.com/lib/pkp/classes/session/SessionManager.inc.php on line 76
[20-Feb-2021 14:42:09 America/New_York] PHP Warning:  session_destroy(): Session object destruction failed in /home/seisense/journal.seisense.com/lib/pkp/classes/session/SessionManager.inc.php on line 76
[20-Feb-2021 14:42:09 America/New_York] PHP Warning:  session_destroy(): Session object destruction failed in /home/seisense/journal.seisense.com/lib/pkp/classes/session/SessionManager.inc.php on line 76
[20-Feb-2021 14:42:09 America/New_York] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'a26f4cc44a8a2557a28a3a8514688483' for key 'sessions_pkey' in /home/seisense/journal.seisense.com/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115
Stack trace:
#0 /home/seisense/journal.seisense.com/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(115): PDOStatement->execute(NULL)
#1 /home/seisense/journal.seisense.com/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(489): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /home/seisense/journal.seisense.com/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\Database\Connection->Illuminate\Database\{closure}('INSERT INTO ses...', Array)
#3 /home/seisense/journal.seisense.com/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\Database\Connection->runQueryCallback('INSERT INTO ses...', Array, Object(Closure)) in /home/seisense/journal.seisense.com/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671
```

**Comment by asmecher** [comment]
I'm not 100% satisfied that this is resolved:
- I'm not sure how this resolves the session duplication message
- I'm not sure why this is only showing up on one server when the same code is deployed far and wide

However: the session `destroy` function appears to have been written to expect a boolean return from `SessionDAO::deleteObject`, and that function does not state a return value. This appears to be the case since the ADODB removal changes introduced with 3.3.0.

The attached commits (e.g. https://github.com/pkp/pkp-lib/commit/6da5ddd5346f9e562c613ebfa6d0b8c6cf9cf6cf, but both are equivalent) resolve the problem by always returning a `true` response from `destroy` (unless there is an exception or similar).
