### ISSUE TITLE
Fatal error in OMP sitemap handler

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6936]
See https://forum.pkp.sfu.ca/t/activation-of-doi-plugin-results-in-fatal-error-during-sitemap-generation-in-omp-3-3-0-4/66596 for details:
```
[21-Mar-2021 00:49:38 Europe/Istanbul] PHP Fatal error:  Uncaught Error: Call to undefined method SubmissionDAO::getLatestRevisionsByAssocId() in /home/omp/public_html/pages/sitemap/SitemapHandler.inc.php:46
Stack trace:
#0 /home/omp/public_html/lib/pkp/pages/sitemap/PKPSitemapHandler.inc.php(36): SitemapHandler->_createContextSitemap(Object(Request))
#1 /home/omp/public_html/lib/pkp/classes/core/PKPRouter.inc.php(395): PKPSitemapHandler->index(Array, Object(Request))
#2 /home/omp/public_html/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)
#3 /home/omp/public_html/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPPageRouter->route(Object(Request))
#4 /home/omp/public_html/lib/pkp/classes/core/PKPApplication.inc.php(364): Dispatcher->dispatch(Object(Request))
#5 /home/omp/public_html/index.php(64): PKPApplication->execute()
#6 {main}
  thrown in /home/omp/public_html/pages/sitemap/SitemapHandler.inc.php on line 46
```

**Comment by asmecher** [comment]
Users of OJS 3.3.0-0 through 3.3.0-5 can resolve the issue by applying https://github.com/pkp/omp/commit/4988986a67507edb6c4a17128989a236b9042b44.
