### ISSUE TITLE
Class not found errors during upgrade

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6967]
**Describe the bug**
OJS master branch. Upgrade from the previous releases cannot be performed because of class not found errors.
Probably related to: https://github.com/pkp/pkp-lib/issues/6091
First one:
```
PHP Fatal error:  Uncaught Error: Class 'PKP\cliTool\Upgrade' not found in /home/doc/OJS/development/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php:97
Stack trace:
#0 /home/doc/OJS/development/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php(73): PKP\cliTool\UpgradeTool->upgrade()
#1 /home/doc/OJS/development/ojs/tools/upgrade.php(21): PKP\cliTool\UpgradeTool->execute()
#2 {main}
  thrown in /home/doc/OJS/development/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php on line 97
```
Second:
```
PHP Fatal error:  Uncaught Error: Class 'XMLDAO' not found in /home/doc/OJS/development/ojs/lib/pkp/classes/migration/upgrade/PKPv3_3_0UpgradeMigration.inc.php:225
Stack trace:
#0 /home/doc/OJS/development/ojs/lib/pkp/classes/migration/upgrade/PKPv3_3_0UpgradeMigration.inc.php(121): PKPv3_3_0UpgradeMigration->_populateEmailTemplates()
#1 /home/doc/OJS/development/ojs/lib/pkp/classes/install/Installer.inc.php(432): PKPv3_3_0UpgradeMigration->up()
#2 /home/doc/OJS/development/ojs/lib/pkp/classes/install/Installer.inc.php(269): Installer->executeAction()
#3 /home/doc/OJS/development/ojs/lib/pkp/classes/install/Installer.inc.php(184): Installer->executeInstaller()
#4 /home/doc/OJS/development/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php(101): Installer->execute()
#5 /home/doc/OJS/development/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php(74): PKP\cliTool\UpgradeTool->upgrade()
#6 /home/doc/OJS/development/ojs/tools/upgrade.php(21): PKP\cliTool\UpgradeTool->execute()
#7 {main}
  thrown in /home/doc/OJS/development/ojs/lib/pkp/classes/migration/upgrade/PKPv3_3_0UpgradeMigration.inc.php on line 225
```
Third:
```
PHP Fatal error:  Uncaught Error: Class 'PKP\db\PKPXMLParser' not found in /home/doc/OJS/development/ojs/lib/pkp/classes/db/DBDataXMLParser.inc.php:46
Stack trace:
#0 /home/doc/OJS/development/ojs/lib/pkp/classes/install/Installer.inc.php(417): PKP\db\DBDataXMLParser->parseData()
#1 /home/doc/OJS/development/ojs/lib/pkp/classes/install/Installer.inc.php(269): Installer->executeAction()
#2 /home/doc/OJS/development/ojs/lib/pkp/classes/install/Installer.inc.php(184): Installer->executeInstaller()
#3 /home/doc/OJS/development/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php(101): Installer->execute()
#4 /home/doc/OJS/development/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php(74): PKP\cliTool\UpgradeTool->upgrade()
#5 /home/doc/OJS/development/ojs/tools/upgrade.php(21): PKP\cliTool\UpgradeTool->execute()
#6 {main}
  thrown in /home/doc/OJS/development/ojs/lib/pkp/classes/db/DBDataXMLParser.inc.php on line 46

```

**What application are you using?**
 OJS master branch

**Additional information**
Looks like just a namespacing issue, nothing more.

**Comment by Vitaliy-1** [comment]
PR pkp-lib: https://github.com/pkp/pkp-lib/pull/6968
@asmecher, can you take a look?

**Comment by asmecher** [comment]
Merged, thanks, @Vitaliy-1 -- there will likely be more of these.
