### ISSUE TITLE
[OJS]

### ISSUE THREAD

**Issue by mstf0ta-app** [pkp/pkp-lib#7043]
Hello ,

i have a problem while install OJS 3.3.0.6

i test mysql and mysqli and got same error
the error is while installing i got error 500 
some tables created but the install is crushed 
mysql server is  MariaDB 10.3.29-MariaDB
in error log i got this 

10-May-2021 08:18:41 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'body, description)
						VALUES
						('NOTIFICATION', 'ar_IQ', 'إشعار ...' at line 2 in /home/ojstestadmin/public_html/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:78
Stack trace:
#0 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(78): PDO->prepare('INSERT INTO ema...', Array)
#1 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(485): Doctrine\DBAL\Driver\PDOConnection->prepare('INSERT INTO ema...')
#2 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\Database\Connection->Illuminate\Database\{closure}('INSERT INTO ema...', Array)
#3 /home/ojstestadmin/public_html/lib/pkp/lib in /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671
[10-May-2021 08:20:59 UTC] SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'announcement_types' already exists (SQL: create table `announcement_types` (`type_id` bigint not null auto_increment primary key, `assoc_type` smallint not null, `assoc_id` bigint not null) default character set utf8 collate 'utf8_general_ci')
[10-May-2021 08:21:25 UTC] SQLSTATE[HY000] [1044] Access denied for user 'ojstestadmin_ojs'@'localhost' to database 'ojstestadmin_ojs_new' (SQL: create table `announcement_types` (`type_id` bigint not null auto_increment primary key, `assoc_type` smallint not null, `assoc_id` bigint not null) default character set utf8 collate 'utf8_general_ci')
[10-May-2021 08:23:50 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'body, description)
						VALUES
						('NOTIFICATION', 'ar_IQ', 'إشعار ...' at line 2 in /home/ojstestadmin/public_html/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:78
Stack trace:
#0 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(78): PDO->prepare('INSERT INTO ema...', Array)
#1 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(485): Doctrine\DBAL\Driver\PDOConnection->prepare('INSERT INTO ema...')
#2 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\Database\Connection->Illuminate\Database\{closure}('INSERT INTO ema...', Array)
#3 /home/ojstestadmin/public_html/lib/pkp/lib in /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671
[10-May-2021 08:30:38 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'body, description)
						VALUES
						('NOTIFICATION', 'ar_IQ', 'إشعار ...' at line 2 in /home/ojstestadmin/public_html/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:78
Stack trace:
#0 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(78): PDO->prepare('INSERT INTO ema...', Array)
#1 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(485): Doctrine\DBAL\Driver\PDOConnection->prepare('INSERT INTO ema...')
#2 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\Database\Connection->Illuminate\Database\{closure}('INSERT INTO ema...', Array)
#3 /home/ojstestadmin/public_html/lib/pkp/lib in /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671
[10-May-2021 08:32:05 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'body, description)
						VALUES
						('NOTIFICATION', 'ar_IQ', 'إشعار ...' at line 2 in /home/ojstestadmin/public_html/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:78
Stack trace:
#0 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(78): PDO->prepare('INSERT INTO ema...', Array)
#1 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(485): Doctrine\DBAL\Driver\PDOConnection->prepare('INSERT INTO ema...')
#2 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\Database\Connection->Illuminate\Database\{closure}('INSERT INTO ema...', Array)
#3 /home/ojstestadmin/public_html/lib/pkp/lib in /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671
[10-May-2021 08:33:07 UTC] SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'announcement_types' already exists (SQL: create table `announcement_types` (`type_id` bigint not null auto_increment primary key, `assoc_type` smallint not null, `assoc_id` bigint not null) default character set utf8 collate 'utf8_general_ci')
[10-May-2021 08:33:46 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'body, description)
						VALUES
						('NOTIFICATION', 'en_US', 'New notifica...' at line 2 in /home/ojstestadmin/public_html/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:78
Stack trace:
#0 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(78): PDO->prepare('INSERT INTO ema...', Array)
#1 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(485): Doctrine\DBAL\Driver\PDOConnection->prepare('INSERT INTO ema...')
#2 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\Database\Connection->Illuminate\Database\{closure}('INSERT INTO ema...', Array)
#3 /home/ojstestadmin/public_html/lib/pkp/li in /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671
[10-May-2021 08:40:40 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'body, description)
						VALUES
						('NOTIFICATION', 'en_US', 'New notifica...' at line 2 in /home/ojstestadmin/public_html/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:78
Stack trace:
#0 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(78): PDO->prepare('INSERT INTO ema...', Array)
#1 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(485): Doctrine\DBAL\Driver\PDOConnection->prepare('INSERT INTO ema...')
#2 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\Database\Connection->Illuminate\Database\{closure}('INSERT INTO ema...', Array)
#3 /home/ojstestadmin/public_html/lib/pkp/li in /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671
[10-May-2021 08:42:38 UTC] SQLSTATE[HY000] [1044] Access denied for user 'ojstestadmin_ojs'@'localhost' to database 'ojs2' (SQL: create table `announcement_types` (`type_id` bigint not null auto_increment primary key, `assoc_type` smallint not null, `assoc_id` bigint not null) default character set utf8 collate 'utf8_general_ci')
[10-May-2021 08:42:55 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'body, description)
						VALUES
						('NOTIFICATION', 'en_US', 'New notifica...' at line 2 in /home/ojstestadmin/public_html/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:78
Stack trace:
#0 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(78): PDO->prepare('INSERT INTO ema...', Array)
#1 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(485): Doctrine\DBAL\Driver\PDOConnection->prepare('INSERT INTO ema...')
#2 /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\Database\Connection->Illuminate\Database\{closure}('INSERT INTO ema...', Array)
#3 /home/ojstestadmin/public_html/lib/pkp/li in /home/ojstestadmin/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671

**Comment by asmecher** [comment]
@mstf0ta-app, could you post on our support forum at https://forum.pkp.sfu.ca? That's the best place to get help.
