### ISSUE TITLE
ReviewFormElement::getMultipleResponsesElementTypes() cannot be called statically

### ISSUE THREAD

**Issue by TheMechanicalButterfly** [pkp/pkp-lib#7076]
OJS version: Stable 3.3.1
PKP-LIB version: Stable 3.3.1
PHP version: 8.0.0

When trying to add a new review field via the dashboard, the frontend sends a request to `https://{baseUrl}/{context}/$$$call$$$/grid/settings/review-forms/review-form-elements-grid/create-review-form-element?reviewFormId=1&_=1621676390447`

This triggers the following PHP error:

```
Fatal error: Uncaught Error: Non-static method ReviewFormElement::getMultipleResponsesElementTypes() cannot be called statically in {installation root}\lib\pkp\controllers\grid\settings\reviewForms\form\ReviewFormElementForm.inc.php:65 
Stack trace: 
#0 {installation root}\lib\pkp\controllers\grid\settings\reviewForms\ReviewFormElementsGridHandler.inc.php(185): ReviewFormElementForm->fetch(Object(Request)) 
#1 {installation root}\lib\pkp\classes\core\PKPRouter.inc.php(395): ReviewFormElementsGridHandler->createReviewFormElement(Array, Object(Request)) 
#2 {installation root}\lib\pkp\classes\core\PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array) 
#3 {installation root}\lib\pkp\classes\core\Dispatcher.inc.php(144): PKPComponentRouter->route(Object(Request)) 
#4 {installation root}\lib\pkp\classes\core\PKPApplication.inc.php(362): Dispatcher->dispatch(Object(Request)) 
#5 {installation root}\ojs-zfpp\index.php(68): PKPApplication->execute() 
#6 {main} thrown in {installation root}\lib\pkp\controllers\grid\settings\reviewForms\form\ReviewFormElementForm.inc.php on line 65
```

New review fields cannot be added.

**Comment by NateWr** [comment]
@asmecher this looked like a straightforward fix but I'm not too familiar with the review form stuff. Any concerns here?

PR:
https://github.com/pkp/pkp-lib/pull/7079

Tests:
https://github.com/pkp/ojs/pull/3136

**Comment by asmecher** [comment]
This has my blessing, thanks: https://github.com/pkp/pkp-lib/pull/7079#issuecomment-848314133
