### ISSUE TITLE
Convert the UserService to the new Repository/DAO/Map pattern

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7127]
The `user` entity needs to be converted to use the new pattern for DAOs, Maps and Repositories introduced in #5328. This requires the following:

- [ ] Convert the DAO to extend `EntityDAO` and use type hints.
- [ ] Convert the `PKPUserService` to a repository .
- [ ] Adapt the schema for add/edit operations and add methods to add/edit/delete users to the DAO/Repository.
- [ ] Convert `PKPUserService::getProperties()` to a Map that extends `PKP\core\maps\SchemaMap`. 
- [ ] Add any necessary methods to `PKPUserService` so that direct access to the DAO is not required.
- [ ] Refactor existing uses of `DAORegistry::getDAO('UserDAO')` to use the repository instead.

**Comment by asmecher** [comment]
Thanks for organizing this, @NateWr!

**Comment by asmecher** [comment]
Needs fixing/confirmation:

If I don't specify the `type` in `lib/pkp/schemas/user.json` for `LocaleObject` fields, I get the following warning and error:
```
[25-Jun-2021 22:12:50 UTC] PHP Notice:  Undefined property: stdClass::$type in /home/asmecher/git/ojs/lib/pkp/classes/core/EntityDAO.inc.php on line 127
[25-Jun-2021 22:12:50 UTC] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to PKP\core\EntityDAO::convertFromDB() must be of the type string, null given, called in /home/asmecher/git/ojs/lib/pkp/classes/core/EntityDAO.inc.php on line 127 and defined in /home/asmecher/git/ojs/lib/pkp/classes/core/EntityDAO.inc.php:310
Stack trace:
#0 /home/asmecher/git/ojs/lib/pkp/classes/core/EntityDAO.inc.php(127): PKP\core\EntityDAO->convertFromDB()
#1 /home/asmecher/git/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(202): PKP\core\EntityDAO->PKP\core\{closure}()
#2 /home/asmecher/git/ojs/lib/pkp/classes/core/EntityDAO.inc.php(132): Illuminate\Support\Collection->each()
#3 /home/asmecher/git/ojs/lib/pkp/classes/core/EntityDAO.inc.php(95): PKP\core\EntityDAO->fromRow()
#4 /home/asmecher/git/ojs/lib/pkp/classes/user/DAO.inc.php(93): PKP\core\EntityDAO->get()
#5 /home/asmecher/git/ojs/lib/pkp/classes/user/DAO.inc.php(115): PKP\user\DAO->get()
#6 /home/asmecher/git/ojs/lib/pkp/classes/user/Repository.inc.php(52): PKP\user\DAO->getByUsername()
#7 /home/asmecher/git/ojs/lib/pkp/classes/security/Validation.inc.php(42): PKP\user\Repository->getByUsername()
#8 /home/asmecher/git/ojs/lib/pkp/pages/login/LoginHandler.inc.php(132): PKP\security\Validation::login()
#9 [internal function]: LoginHandler->signIn()
#10 /home/asmecher/git/ojs/lib/pkp/classes/core/PKPRouter.inc.php(465): call_user_func()
#11 /home/asmecher/git/ojs/lib/pkp/classes/core/PKPPageRouter.inc.php(295): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#12 /home/asmecher/git/ojs/lib/pkp/classes/core/Dispatcher.inc.php(166): PKP\core\PKPPageRouter->route()
#13 /home/asmecher/git/ojs/lib/pkp/classes/core/PKPApplication.inc.php(338): PKP\core\Dispatcher->dispatch()
#14 /home/asmecher/git/ojs/index.php(68): PKP\core\PKPApplication->execute()
#15 {main}
  thrown in /home/asmecher/git/ojs/lib/pkp/classes/core/EntityDAO.inc.php on line 310
```
1. Should I be declaring types for these fields in the schema alongside `LocaleObject`, or is something missing in e.g. `EntityDAO`?
2. If I am to be declaring types, should it be the atomic type of the localized content -- e.g. a string for a submission title?

**Comment by NateWr** [comment]
Yeah, so this is a little bit confusing because a few of the existing schemas have so far only been used for documentation purposes (API docs) instead of as a schema. The `$ref` should never be used in a schema:

```
"$ref": "#/definitions/LocaleObject"
```

That's only used to build the REST API docs. When converting an entity over to use the `EntityDAO`, that should be removed and the property should be defined like this:

```
"biography": {
  "type": "string",
  "multilingual": true
}
```

I think a missing `type` declaration in the schema should be a fatal error. The fatal error thrown by the type hint on `convertFromDB` does the trick here. I'm on the fence about whether we should check this earlier and throw a validation exception. How expensive would it be to check each schema as it's loaded by the system?

**Comment by asmecher** [comment]
I don't mind if the error message isn't 100% helpful in a case like this, as long as googling it up will get us to this documentation. Since it's something only the dev team is likely to be encountering. Thanks for the hints!

**Comment by asmecher** [comment]
@NateWr, could you give a first look at the two draft PRs?
- https://github.com/pkp/pkp-lib/pull/7170
- https://github.com/pkp/ojs/pull/3164
- 
The stuff I'm least confident about is the entity JSON.

**Comment by asmecher** [comment]
Thanks, @NateWr, I've worked through your comments and either fixed or commented. The review really helped to fit some of the last puzzle pieces in place for the intentions of the refactor -- it's looking really good and I'm excited to start rolling out some of the implications elsewhere in the system, e.g. around API and testing. Please let me know how the changes (and comments) look and the next step for me after that will be porting the changes to OMP and OPS.

**Comment by asmecher** [comment]
(@NateWr, I've adapted the PRs to OMP and OPS -- very minimal changes, but anyway. PRs listed at the head of this issue.)

**Comment by bozana** [comment]
@asmecher, the UserDAO->getFetchColumns and ->getFetchJoins are removed from SQL in InstitutionalSubscriptionDAO (maybe also somewhere else) but the function SubscriptionDAO::_generateSearchSQL does need them (e.g. when one is searching the subscriptions by user given or family name)

**Comment by asmecher** [comment]
Thanks, @bozana, I've filed that here: https://github.com/pkp/pkp-lib/issues/7332
