### ISSUE TITLE
Fatal error when trying to create a new instance of CitationListTokenizerFilter

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7145]
**Describe the bug**
Creating a new instance of the class throws a fatal error as tested within the JATS Parser Plugin:
```
[Mon Jun 21 14:12:51 2021] Slim Application Error:
Type: Error
Message: Class 'Filter' not found
File: /home/doc/OJS/development/ojs/lib/pkp/classes/citation/CitationListTokenizerFilter.inc.php
Line: 22
Trace: #0 /home/doc/OJS/development/ojs/lib/pkp/includes/functions.inc.php(390): require_once()
#1 /home/doc/OJS/development/ojs/lib/pkp/includes/bootstrap.inc.php(42): customAutoload()
#2 [internal function]: {closure}()
#3 /home/doc/OJS/development/ojs/plugins/generic/jatsParser/JatsParserPlugin.inc.php(590): spl_autoload_call()
#4 /home/doc/OJS/development/ojs/plugins/generic/jatsParser/JatsParserPlugin.inc.php(487): JatsParserPlugin->_setReferences()
#5 [internal function]: JatsParserPlugin->createPdfGalley()
#6 /home/doc/OJS/development/ojs/lib/pkp/classes/plugins/HookRegistry.inc.php(122): call_user_func()
#7 /home/doc/OJS/development/ojs/lib/pkp/classes/publication/Repository.inc.php(385): PKP\plugins\HookRegistry::call()
#8 /home/doc/OJS/development/ojs/lib/pkp/api/v1/submissions/PKPSubmissionHandler.inc.php(761): PKP\publication\Repository->edit()
#9 [internal function]: PKPSubmissionHandler->editPublication()
#10 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()
#11 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke()
#13 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack()
#14 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/App.php(503): Slim\Route->run()
#15 /home/doc/OJS/development/ojs/lib/pkp/classes/security/authorization/internal/ApiAuthorizationMiddleware.inc.php(90): Slim\App->__invoke()
#16 [internal function]: PKP\security\authorization\internal\ApiAuthorizationMiddleware->__invoke()
#17 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#18 [internal function]: Slim\DeferredCallable->__invoke()
#19 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#20 /home/doc/OJS/development/ojs/lib/pkp/classes/security/authorization/internal/ApiCsrfMiddleware.inc.php(54): Slim\App->Slim\{closure}()
#21 [internal function]: PKP\security\authorization\internal\ApiCsrfMiddleware->__invoke()
#22 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#23 [internal function]: Slim\DeferredCallable->__invoke()
#24 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#25 /home/doc/OJS/development/ojs/lib/pkp/classes/security/authorization/internal/ApiTokenDecodingMiddleware.inc.php(131): Slim\App->Slim\{closure}()
#26 [internal function]: PKP\security\authorization\internal\ApiTokenDecodingMiddleware->__invoke()
#27 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#28 [internal function]: Slim\DeferredCallable->__invoke()
#29 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#30 /home/doc/OJS/development/ojs/lib/pkp/classes/handler/APIHandler.inc.php(80): Slim\App->Slim\{closure}()
#31 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
#32 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#33 [internal function]: Slim\DeferredCallable->__invoke()
#34 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#35 /home/doc/OJS/development/ojs/lib/pkp/classes/handler/APIHandler.inc.php(139): Slim\App->Slim\{closure}()
#36 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
#37 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#38 [internal function]: Slim\DeferredCallable->__invoke()
#39 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#40 /home/doc/OJS/development/ojs/lib/pkp/classes/handler/APIHandler.inc.php(144): Slim\App->Slim\{closure}()
#41 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
#42 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#43 [internal function]: Slim\DeferredCallable->__invoke()
#44 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#45 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}()
#46 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack()
#47 /home/doc/OJS/development/ojs/lib/pkp/classes/handler/APIHandler.inc.php(136): Slim\App->process()
#48 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
#49 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#50 [internal function]: Slim\DeferredCallable->__invoke()
#51 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#52 /home/doc/OJS/development/ojs/lib/pkp/classes/handler/APIHandler.inc.php(144): Slim\App->Slim\{closure}()
#53 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
#54 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#55 [internal function]: Slim\DeferredCallable->__invoke()
#56 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#57 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}()
#58 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack()
#59 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/slim/slim/Slim/App.php(297): Slim\App->process()
#60 /home/doc/OJS/development/ojs/lib/pkp/classes/core/APIRouter.inc.php(129): Slim\App->run()
#61 /home/doc/OJS/development/ojs/lib/pkp/classes/core/Dispatcher.inc.php(166): PKP\core\APIRouter->route()
#62 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPApplication.inc.php(338): PKP\core\Dispatcher->dispatch()
#63 /home/doc/OJS/development/ojs/index.php(68): PKP\core\PKPApplication->execute()
#64 {main}
View in rendered output by enabling the "displayErrorDetails" setting.

```

**To Reproduce**
Create a new instance of the class, e.g.:
```
$citationTokenizer = new \PKP\citation\CitationListTokenizerFilter()
```

**What application are you using?**
current OJS master branch

**Additional information**
Trailing backslash from the declaration of the extended class should be removed as alias is already created: https://github.com/pkp/pkp-lib/blob/6f578997a99666f3d4a27cf4d51b36fe3e476c98/classes/citation/CitationListTokenizerFilter.inc.php#L22

**Comment by asmecher** [comment]
Fixed, @Vitaliy-1!
