### ISSUE TITLE
Fatal error is thrown when Unassign Reviewer

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7147]
**Describe the bug**
Pressing Unassign Reviewer button triggers a fatal error:
```
PHP Fatal error:  Uncaught Error: Class 'PKP\controllers\grid\users\reviewer\UnassignReviewerForm' not found in /home/doc/OJS/development/ojs/lib/pkp/classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.inc.php:491
Stack trace:
#0 [internal function]: PKP\controllers\grid\users\reviewer\PKPReviewerGridHandler->unassignReviewer()
#1 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPRouter.inc.php(465): call_user_func()
#2 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPComponentRouter.inc.php(280): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#3 /home/doc/OJS/development/ojs/lib/pkp/classes/core/Dispatcher.inc.php(166): PKP\core\PKPComponentRouter->route()
#4 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPApplication.inc.php(338): PKP\core\Dispatcher->dispatch()
#5 /home/doc/OJS/development/ojs/index.php(68): PKP\core\PKPApplication->execute()
#6 {main}
  thrown in /home/doc/OJS/development/ojs/lib/pkp/classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.inc.php on line 491
```

**To Reproduce**
1. Submit an article
2. Pass it to the review stage
3. Assign reviewer
4. Press Unassign Reviewer button and see error

**What application are you using?**
 OJS master branch

**Additional information**
https://github.com/pkp/pkp-lib/blob/6f578997a99666f3d4a27cf4d51b36fe3e476c98/classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.inc.php#L491 should be imported using a fully qualified class name

**Edit**
Noticed 2 errors here actually. The second one:
```
PHP Fatal error:  Uncaught Error: Call to undefined method APP\submission\DAO::updateObject() in /home/doc/OJS/development/ojs/lib/pkp/controllers/grid/users/reviewer/form/UnassignReviewerForm.inc.php:82
Stack trace:
#0 /home/doc/OJS/development/ojs/lib/pkp/classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.inc.php(567): UnassignReviewerForm->execute()
#1 [internal function]: PKP\controllers\grid\users\reviewer\PKPReviewerGridHandler->updateUnassignReviewer()
#2 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPRouter.inc.php(465): call_user_func()
#3 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPComponentRouter.inc.php(280): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#4 /home/doc/OJS/development/ojs/lib/pkp/classes/core/Dispatcher.inc.php(166): PKP\core\PKPComponentRouter->route()
#5 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPApplication.inc.php(338): PKP\core\Dispatcher->dispatch()
#6 /home/doc/OJS/development/ojs/index.php(68): PKP\core\PKPApplication->execute()
#7 {main}
  t in /home/doc/OJS/development/ojs/lib/pkp/controllers/grid/users/reviewer/form/UnassignReviewerForm.inc.php on line 82
```
Occurs because a method name hasn't been renamed according to recent changes: https://github.com/pkp/pkp-lib/blob/6f578997a99666f3d4a27cf4d51b36fe3e476c98/controllers/grid/users/reviewer/form/UnassignReviewerForm.inc.php#L82 (should be `update`)

**Comment by asmecher** [comment]
Both fixed -- thanks for the thorough descriptions!
