### ISSUE TITLE
Fatal error on adding a discussion on a review stage

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7196]
**Describe the bug**
Trying to initiate a discussion while submission is on a review stage leads to a fatal error:
```
PHP Fatal error:  Uncaught Error: Call to undefined method APP\submission\Repository::getReviewAssignments() in /home/doc/ojs/development/ojs/lib/pkp/controllers/grid/queries/form/QueryForm.inc.php:282
Stack trace:
#0 /home/doc/ojs/development/ojs/lib/pkp/controllers/grid/queries/QueriesGridHandler.inc.php(354): QueryForm->fetch()
#1 [internal function]: QueriesGridHandler->addQuery()
#2 /home/doc/ojs/development/ojs/lib/pkp/classes/core/PKPRouter.inc.php(465): call_user_func()
#3 /home/doc/ojs/development/ojs/lib/pkp/classes/core/PKPComponentRouter.inc.php(280): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#4 /home/doc/ojs/development/ojs/lib/pkp/classes/core/Dispatcher.inc.php(166): PKP\core\PKPComponentRouter->route()
#5 /home/doc/ojs/development/ojs/lib/pkp/classes/core/PKPApplication.inc.php(338): PKP\core\Dispatcher->dispatch()
#6 /home/doc/ojs/development/ojs/index.php(68): PKP\core\PKPApplication->execute()
#7 {main}
  thrown in /home/doc/ojs/development/ojs/lib/pkp/controllers/grid/queries/form/QueryForm.inc.php on line 282
```
**To Reproduce**
1. Make a submission and pass it to the review stage
2. Click on `add discussion` button near `Review Discussions`
3. See error

**What application are you using?**
 OJS current main branch

**Additional information**
![add_discussion](https://user-images.githubusercontent.com/20665587/126521416-cbbefebb-c870-4aef-9c93-ba80be850541.png)

**Comment by NateWr** [comment]
Could not reproduce this in `main`. It looks like `APP\submission\Repository::getReviewAssignments()` was removed and the code that gets review assignments in `QueryForm` has been rewritten.
