### ISSUE TITLE
Author's internal review stage broken in OMP

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7230]
**Describe the bug**
The internal review stage of the author dashboard causes a fatal error in OMP. The error is:

```
PHP Fatal error:  Uncaught Error: Call to a member function wasEmpty() on array in /home/nate/Projects/pkp/omp-stable/cache/t_compile/0bb3515e2e771a0ed49e171fc2359401740fd982^6e70e9e6e8ba68121fb27f2a18e3f289e496e986_0.app.controllerstabauthorDashb.php:25
Stack trace:
#0 /home/nate/Projects/pkp/omp-stable/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_611a2d4789f9f9_63069645(Object(Smarty_Internal_Template))
#1 /home/nate/Projects/pkp/omp-stable/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#2 /home/nate/Projects/pkp/omp-stable/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#3 /home/nate/Projects/pkp/omp-stable/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 0)
#4 /home/nat in /home/nate/Projects/pkp/omp-stable/cache/t_compile/0bb3515e2e771a0ed49e171fc2359401740fd982^6e70e9e6e8ba68121fb27f2a18e3f289e496e986_0.app.controllerstabauthorDashb.php on line 25
```

**To Reproduce**
1. Create submission and move to internal review stage.
2. Login as the author and view the submission's internal review stage
4. See error in the log.

**What application are you using?**
OMP 3.3.0-7

**Additional information**
See the [original forum report](https://forum.pkp.sfu.ca/t/omp-3-3-0-4-and-3-3-0-7-authors-see-an-empty-internal-review-tab/69166/4).

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/omp/pull/998

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and cherry-picked to `stable-3_3_1` and `main`.
