### ISSUE TITLE
Can't open activity log and upload files in copyediting section for some submissions

### ISSUE THREAD

**Issue by NikitaPO** [pkp/pkp-lib#7306]
This problem occurs with only one submission, with other all normal.

When I click "Activity log", I see this:

![image](https://user-images.githubusercontent.com/31895695/133929027-d321adc0-b84c-4079-8ea7-b611e3aa663e.png)

```bash
[Sun Sep 19 16:09:09.059512 2021] [fcgid:warn] [pid 32217] [client 95.55.41.14:53382] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to a member function getAssocId() on null in /var/www/freejazz123/data/www/iik-journal.ru/lib/pkp/classes/services/PKPSubmissionFileService.inc.php:774, referer: https://iik-journal.ru/index.php/main/workflow/index/85/4
[Sun Sep 19 16:09:09.059520 2021] [fcgid:warn] [pid 32217] [client 95.55.41.14:53382] mod_fcgid: stderr: Stack trace:, referer: https://iik-journal.ru/index.php/main/workflow/index/85/4
[Sun Sep 19 16:09:09.059527 2021] [fcgid:warn] [pid 32217] [client 95.55.41.14:53382] mod_fcgid: stderr: #0 /var/www/freejazz123/data/www/iik-journal.ru/lib/pkp/controllers/grid/eventLog/EventLogGridRow.inc.php(79): PKP\\Services\\PKPSubmissionFileService->getWorkflowStageId(Object(SubmissionFile)), referer: https://iik-journal.ru/index.php/main/workflow/index/85/4
[Sun Sep 19 16:09:09.059534 2021] [fcgid:warn] [pid 32217] [client 95.55.41.14:53382] mod_fcgid: stderr: #1 /var/www/freejazz123/data/www/iik-journal.ru/lib/pkp/classes/controllers/grid/GridHandler.inc.php(1066): EventLogGridRow->initialize(Object(Request)), referer: https://iik-journal.ru/index.php/main/workflow/index/85/4
[Sun Sep 19 16:09:09.059541 2021] [fcgid:warn] [pid 32217] [client 95.55.41.14:53382] mod_fcgid: stderr: #2 /var/www/freejazz123/data/www/iik-journal.ru/lib/pkp/classes/controllers/grid/GridHandler.inc.php(983): GridHandler->_getInitializedRowInstance(Object(Request), 30, Object(SubmissionEventLogEntry)), referer: https://iik-journal.ru/index.php/main/workflow/index/85/4
[Sun Sep 19 16:09:09.059548 2021] [fcgid:warn] [pid 32217] [client 95.55.41.14:53382] mod_fcgid: stderr: #3 /var/www/freejazz123/data/www/iik-journal.ru/lib/pkp/classes/controllers/grid/GridHandler.inc.php(1031): GridHandler->renderRowsInternally(Object(Request), Array), referer: https://iik-journal.ru/index.php/main/workflow/index/85/4
[Sun Sep 19 16:09:09.059555 2021] [fcgid:warn] [pid 32217] [client 95.55.41.14:53382] mod_fcgid: stderr: #4 /var/www/freejazz123/data/www/iik-journal.ru/lib/pkp/classes/controllers/grid/GridHandler.inc.php(921): GridHandler->rende in /var/www/freejazz123/data/www/iik-journal.ru/lib/pkp/classes/services/PKPSubmissionFileService.inc.php on line 774, referer: https://iik-journal.ru/index.php/main/workflow/index/85/4
```

When I click "Upload/Select files" in Draft files:

![image](https://user-images.githubusercontent.com/31895695/133929086-79798f03-49f9-4211-891c-baf25c59fc9f.png)

```bash
[Sun Sep 19 16:22:34.433331 2021] [fcgid:warn] [pid 1843] [client 95.55.41.14:44006] mod_fcgid: stderr: PHP Warning:  Declaration of ManageFinalDraftFilesForm::execute($stageSubmissionFiles, $fileStage = NULL) should be compatible with ManageSubmissionFilesForm::execute($stageSubmissionFiles = NULL, $fileStage = NULL, ...$functionArgs) in /var/www/freejazz123/data/www/iik-journal.ru/lib/pkp/controllers/grid/files/final/form/ManageFinalDraftFilesForm.inc.php on line 18, referer: https://iik-journal.ru/index.php/main/workflow/index/85/4
[Sun Sep 19 16:22:34.565478 2021] [fcgid:warn] [pid 32297] [client 95.55.41.14:44012] mod_fcgid: stderr: PHP Warning:  assert(): assert($note &amp;&amp; $note-&gt;getAssocType() == ASSOC_TYPE_QUERY) failed in /var/www/freejazz123/data/www/iik-journal.ru/lib/pkp/controllers/grid/files/SubmissionFilesCategoryGridDataProvider.inc.php on line 129, referer: https://iik-journal.ru/index.php/main/workflow/index/85/4
[Sun Sep 19 16:22:34.565536 2021] [fcgid:warn] [pid 32297] [client 95.55.41.14:44012] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to a member function getAssocId() on null in /var/www/freejazz123/data/www/iik-journal.ru/lib/pkp/controllers/grid/files/SubmissionFilesCategoryGridDataProvider.inc.php:131, referer: https://iik-journal.ru/index.php/main/workflow/index/85/4
[Sun Sep 19 16:22:34.565544 2021] [fcgid:warn] [pid 32297] [client 95.55.41.14:44012] mod_fcgid: stderr: Stack trace:, referer: https://iik-journal.ru/index.php/main/workflow/index/85/4
[Sun Sep 19 16:22:34.565551 2021] [fcgid:warn] [pid 32297] [client 95.55.41.14:44012] mod_fcgid: stderr: #0 /var/www/freejazz123/data/www/iik-journal.ru/lib/pkp/classes/controllers/grid/CategoryGridHandler.inc.php(402): SubmissionFilesCategoryGridDataProvider->loadCategoryData(Object(Request), 4, Array), referer: https://iik-journal.ru/index.php/main/workflow/index/85/4
[Sun Sep 19 16:22:34.565558 2021] [fcgid:warn] [pid 32297] [client 95.55.41.14:44012] mod_fcgid: stderr: #1 /var/www/freejazz123/data/www/iik-journal.ru/lib/pkp/classes/controllers/grid/CategoryGridHandler.inc.php(124): CategoryGridHandler->loadCategoryData(Object(Request), 4, Array), referer: https://iik-journal.ru/index.php/main/workflow/index/85/4
[Sun Sep 19 16:22:34.565565 2021] [fcgid:warn] [pid 32297] [client 95.55.41.14:44012] mod_fcgid: stderr: #2 /var/www/freejazz123/data/www/iik-journal.ru/lib/pkp/classes/controllers/grid/CategoryGridHandler.inc.php(473): CategoryGridHandler->getGridCategoryDataElements(Object(Request), 4), referer: https://iik-journal.ru/index.php/main/workflow/index/85/4
[Sun Sep 19 16:22:34.565580 2021] [fcgid:warn] [pid 32297] [client 95.55.41.14:44012] mod_fcgid: stderr: #3 /var/www/freejazz123/data/www/iik-journal.ru/lib/pkp/classes/controllers/grid/CategoryGridHandler.inc.php(453): CategoryGridHandler->_renderCategoryInternally(Object(Request), Object(SelectableSubmissionFileListCategoryGridRow)), referer: https://iik-journal.ru/index.php/main/workflow/index/85/4
[Sun Sep 19 16:22:34.565588 2021] [fcgid:warn] [pid 32297] [client 95.55.41.14:44012] mod_fcgid: stderr: #4 /var/www/freejazz1 in /var/www/freejazz123/data/www/iik-journal.ru/lib/pkp/controllers/grid/files/SubmissionFilesCategoryGridDataProvider.inc.php on line 131, referer: https://iik-journal.ru/index.php/main/workflow/index/85/4
```

 OJS, version 3.3.0.6

**Comment by NikitaPO** [comment]
It helps https://github.com/pkp/pkp-lib/issues/6774#issuecomment-782351864
I didn't find it before, thanks)
