### ISSUE TITLE
Fatal error when trying to access context settings

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7411]
**Describe the bug**
A fatal error is thrown when accessing journal settings in the current main branch:
```
PHP Fatal error:  Uncaught Error: Call to undefined method PKP\db\DAOResultFactory::first() in /home/doc/OJS/development/ojs/lib/pkp/pages/management/ManagementHandler.inc.php:144
Stack trace:
#0 /home/doc/OJS/development/ojs/lib/pkp/pages/management/ManagementHandler.inc.php(74): ManagementHandler->context()
#1 [internal function]: ManagementHandler->settings()
#2 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPRouter.inc.php(465): call_user_func()
#3 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPPageRouter.inc.php(295): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#4 /home/doc/OJS/development/ojs/lib/pkp/classes/core/Dispatcher.inc.php(166): PKP\core\PKPPageRouter->route()
#5 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPApplication.inc.php(339): PKP\core\Dispatcher->dispatch()
#6 /home/doc/OJS/development/ojs/index.php(68): PKP\core\PKPApplication->execute()
#7 {main}
  thrown in /home/doc/OJS/development/ojs/lib/pkp/pages/management/ManagementHandler.inc.php on line 144
```

**To Reproduce**
1. Log in and enter the dashboard
2. Click on the Journal settings
3. See error

**What application are you using?**
 OJS main branch

**Additional information**
Looks like related to the recent user refactoring. Also, there is a typo with a variable name `$siteAdmin` in the same method where error occurs: https://github.com/pkp/pkp-lib/blob/f8a8231b2064fa72afccd9fb0aa88ac8178e17aa/pages/management/ManagementHandler.inc.php#L149

**Comment by Vitaliy-1** [comment]
Yes, I've experimented with upgrades recently.

**Comment by Vitaliy-1** [comment]
It's good sometimes to have a non-standard configuration for testing :) But sorry that haven't mentioned this info in the topic.
