### ISSUE TITLE
Can not create publication format with ISBN in OMP

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7440]
**Describe the bug**
When trying to create a publication format with an ISBN, a fatal error occurs.

```
PHP Fatal error:  Uncaught Error: Class 'APP\publicationFormat\DataObject' not found in /home/nate/Projects/pkp/omp/classes/publicationFormat/IdentificationCode.inc.php:22
Stack trace:
#0 /home/nate/Projects/pkp/omp/lib/pkp/includes/functions.inc.php(390): require_once()
#1 /home/nate/Projects/pkp/omp/lib/pkp/includes/bootstrap.inc.php(47): customAutoload('/home/nate/Proj...', 'APP\\', 'publicationForm...')
#2 [internal function]: {closure}('APP\\publication...')
#3 /home/nate/Projects/pkp/omp/classes/publicationFormat/IdentificationCodeDAO.inc.php(79): spl_autoload_call('APP\\publication...')
#4 /home/nate/Projects/pkp/omp/controllers/grid/catalogEntry/form/PublicationFormatForm.inc.php(249): APP\publicationFormat\IdentificationCodeDAO->newDataObject()
#5 /home/nate/Projects/pkp/omp/controllers/grid/catalogEntry/PublicationFormatGridHandler.inc.php(331): PublicationFormatForm->execute()
#6 [internal function]: PublicationFormatGridHandler->updateFormat(Array, Object(APP\core\Request))
#7 /home/nate/Projects/pkp/omp/lib/pkp/cl in /home/nate/Projects/pkp/omp/classes/publicationFormat/IdentificationCode.inc.php on line 22
```

**To Reproduce**
1. Go to a submission's workflow
2. Go to Publication > Publication Formats
3. Click Add Publication Format
4. Enter an ISBN (copy the example ISBN next to the form field).
5. Try to save Publication Format.

**What application are you using?**
OMP 3.4 pre-release (`main` branch)

**Additional information**
When this bug is fixed, at least one test should create a publication format with an ISBN.

**Comment by ajnyga** [comment]
I can not see this error.

I tried both a) adding a whole new format with an ISBN and b) adding a new format, saving and then by editing adding an ISBN. It was probably fixed with https://github.com/pkp/omp/pull/1012

I will add the test you asked in any case and we can close this after that.

**Comment by ajnyga** [comment]
OMP: https://github.com/pkp/omp/pull/1039

**Comment by asmecher** [comment]
Sorry to jump in but since I'm working with namespace stuff... @NateWr, I suspect your checkout didn't include https://github.com/pkp/omp/commit/b2b0be87b435d82661ab4bac31a05c78dbb68757#diff-611f9577405a43a4455199dc5cb60dfe5419b6a6f745809d6de70793d94410e2R19, which should resolve the message you encountered. @ajnyga, I've merged the test -- thanks!
