### ISSUE TITLE
Can't use apiToken when logged in as another user

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7539]
**Describe the bug**
When an admin or journal manager uses the "login as" feature to login as another user, the `apiToken` is ignored in requests to the API. The admin is always set to the current user, even when using an API token for another user.

This is _not_ a security issue, because nothing is ever exposed to the user with fewer permissions. But it may eventually cause hard-to-find bugs with tools that use the API through an API Key.

**To Reproduce**
1. Login as an admin.
2. Go to Settings > Users and login as an author (ccorino)
3. Go to Edit Profile > API Key
4. Create an API Key for the author (ccorino)
5. Use the author's API Key to make a GET request to `/api/v1/submissions?apiToken=<authorApiKey>`.
4. See that the response returns submissions that the author doesn't have access to. If you inspect `$request->getUser()`, you will see that the admin is the user.

Note: this only works when sending the API request from the same browser where you are logged in as, because the cookies override the API key.

**What application are you using?**
3.3.0

**Additional information**
@asmecher I suspect this is happening because the login as feature is setting the request user before the API Key has a chance to intervene here:

https://github.com/pkp/pkp-lib/blob/46d1226de2556bab9741d59e8a5e2caed3bf17b0/classes/core/PKPRequest.inc.php#L601-L614

If an API token is found, decoded, and matches a user, should the registry user be reset here?

```php
$user =& Registry::get('user', true, null);

$router = $this->getRouter();
if (!is_null($handler = $router->getHandler()) && !is_null($token = $handler->getApiToken())) {
    if ($user->getData('apiKey') !== $token) {
        $userDao = DAORegistry::getDAO('UserDAO'); /* @var $userDao UserDAO */
        $apiUser = $userDao->getBySetting('apiKey', $token);
        if (!is_null($apiUser) || $apiUser->getData('apiKeyEnabled')) {
            Registry::set('user', $apiUser);
        }
    }
    return $user;
}
```

**Comment by asmecher** [comment]
To be sure I'm following, are you proposing that the user's session be ignored totally when an API key is provided, regardless of whether they're logged in or not, including with the "Log In As" feature? If so, great; that would avoid entanglements between the features, which might get tricky.

**Comment by NateWr** [comment]
Yes. I think an API key should override a user's session. :+1:

**Comment by NateWr** [comment]
This appears to have been fixed in https://github.com/pkp/pkp-lib/commit/7bb51ec656afcd67519795bac37418e243c76bc8. The code now checks the API key before the session:

https://github.com/pkp/pkp-lib/blob/7ad8b84d2fa4f80c8cdf528c48cf3dcb28bde057/classes/core/PKPRequest.inc.php#L596-L610

**Comment by NateWr** [comment]
I was going to backport this to 3.3, but now I have some questions. The new code (which is very readable, thanks @jonasraoni!), makes one change I'm not sure about. If a user is fetched from the `Registry`, it doesn't go on to check the API token or session. It returns early with that user.

So I guess the question is: where is the user set in the `Registry`? Is there some risk of the API token or session being ignored here? And if this method finds a user by API token or session, should it be setting the user in the `Registry`?

**Comment by asmecher** [comment]
The user is set in the registry in `PKPRequest::getUser`. It's a `Registry::get` call, but returns a reference, so the variable can be set lower in the function if it was null.

https://github.com/pkp/pkp-lib/blob/39fc4faa83b01b2d8f1b8feb108b28a0f7ab38f6/classes/core/PKPRequest.inc.php#L517

**Comment by NateWr** [comment]
This isn't working when applied to 3.3, and I suspect it's not working in the `main` branch either. The problem is that `Request::getUser()` is being called before the router has identified and loaded the handler. As such, this line is returning false and the API token check is being skipped:

```
if (($handler = $this->getRouter()->getHandler()) 
```

The following is a stack trace that shows it is a generic plugin (usage stats) that is calling `Request::getUser()` before the handler is set:

```
PHP Fatal error:  Uncaught Exception in lib/pkp/classes/core/PKPRequest.inc.php:523
Stack trace:
#0 lib/pkp/classes/template/PKPTemplateManager.inc.php(326): PKPRequest->getUser()
#1 classes/template/TemplateManager.inc.php(28): PKPTemplateManager->initialize(Object(Request))
#2 lib/pkp/classes/template/PKPTemplateManager.inc.php(1247): TemplateManager->initialize(Object(Request))
#3 lib/pkp/classes/plugins/Plugin.inc.php(359): PKPTemplateManager::getManager()
#4 lib/pkp/classes/plugins/Plugin.inc.php(115): Plugin->_registerTemplateResource()
#5 lib/pkp/classes/plugins/LazyLoadPlugin.inc.php(28): Plugin->register('generic', 'plugins/generic...', NULL)
#6 plugins/generic/usageStats/UsageStatsPlugin.inc.php(112): LazyLoadPlugin->register('generic', 'plugins/generic...', NULL)
#7 lib/pkp/classes/plugins/PluginRegistry.inc.php(69): UsageStatsPlugin->register('generic', 'plugins/generic...', NULL)
#8 lib/pkp/classes/plugins/PluginRegistry.inc.php(142): PluginRegistry::register('generic', Object(UsageStatsPlugin), 'plugins/generic...', NULL)
#9 lib/pkp/classes/core/Dispatcher.inc.php(133): PluginRegistry::loadCategory('generic', true)
#10 lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher->dispatch(Object(Request))
#11 index.php(68): PKPApplication->execute()
#12 {main}
  thrown in lib/pkp/classes/core/PKPRequest.inc.php on line 523
```

I'm not sure what the best approach is here.
