### ISSUE TITLE
Typo in deprecated ArticleHandler::downloadSuppFile()

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7552]
**Describe the bug**
Call to the deprecated method in ArticleHandler leads to a fatal error:
```
PHP Fatal error: Uncaught Error: Call to a member function getId() on string in /web/htdocs/revistas/respyn/pages/article/ArticleHandler.inc.php:378\nStack trace:\n#0 /web/htdocs/revistas/respyn/lib/pkp/classes/core/PKPRouter.inc.php(395): ArticleHandler->downloadSuppFile(Array, Object(Request))\n#1 /web/htdocs/revistas/respyn/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)\n#2 /web/htdocs/revistas/respyn/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPPageRouter->route(Object(Request))\n#3 /web/htdocs/revistas/respyn/lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher->dispatch(Object(Request))\n#4 /web/htdocs/revistas/respyn/index.php(68): PKPApplication->execute()\n#5 {main}\n thrown in /web/htdocs/revistas/respyn/pages/article/ArticleHandler.inc.php on line 378
```

**To Reproduce**
Reported on the forum: https://forum.pkp.sfu.ca/t/persisten-error-in-ojs3-3-0-8-in-articlehandler-inc-php/70971

**What application are you using?**
 OJS 3.3.0-8

**Additional information**
Caused by a typo here: https://github.com/pkp/ojs/blob/2dcaac64d15c637e9113c146856d3371234c7506/pages/article/ArticleHandler.inc.php#L378

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1!
