### ISSUE TITLE
Gossip User property is defined as multilingual but is not 

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7567]
**Describe the bug**
Receiving fatal error on testing OJS instance when trying to assign a reviewer, after pressing `add reviewer` button:
```
PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /home/doc/OJS/development/ojs/lib/pkp/classes/services/PKPSchemaService.inc.php:621
Stack trace:
#0 /home/doc/OJS/development/ojs/lib/pkp/classes/user/maps/Schema.inc.php(182): PKP\services\PKPSchemaService->addMissingMultilingualValues()
#1 /home/doc/OJS/development/ojs/lib/pkp/classes/user/maps/Schema.inc.php(63): PKP\user\maps\Schema->mapByProperties()
#2 /home/doc/OJS/development/ojs/lib/pkp/classes/components/listPanels/PKPSelectReviewerListPanel.inc.php(155): PKP\user\maps\Schema->summarizeReviewer()
#3 /home/doc/OJS/development/ojs/lib/pkp/controllers/grid/users/reviewer/form/AdvancedSearchReviewerForm.inc.php(127): PKP\components\listPanels\PKPSelectReviewerListPanel->getItems()
#4 /home/doc/OJS/development/ojs/lib/pkp/classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.inc.php(1029): AdvancedSearchReviewerForm->fetch()
#5 /home/doc/OJS/development/ojs/lib/pkp/classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.inc.php(347): PKP\controllers\grid\users\reviewer\PKPReviewerGridHandler->_fetchReviewerForm()
#6 [internal function]: PKP\controllers\grid\users\reviewer\PKPReviewerGridHandler->showReviewerForm()
#7 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPRouter.inc.php(465): call_user_func()
#8 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPComponentRouter.inc.php(282): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#9 /home/doc/OJS/development/ojs/lib/pkp/classes/core/Dispatcher.inc.php(166): PKP\core\PKPComponentRouter->route()
#10 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPApplication.inc.php(336): PKP\core\Dispatcher->dispatch()
#11 /home/doc/OJS/development/ojs/index.php(68): PKP\core\PKPApplication->execute()
#12 {main}
  thrown in /home/doc/OJS/development/ojs/lib/pkp/classes/services/PKPSchemaService.inc.php on line 621
``` 

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a reviewer to OJS instance and populate `Editorial Notes` field for this user in user settings
1. Submit an article and move it to the review stage 
2. Click on 'add reviewer` button
3. See error

**What application are you using?**
 OJS main branch

**Additional information**
The cause is that `gossip` property is defined as multilingual in the schema: https://github.com/pkp/pkp-lib/blob/38b0064f8f8164dff06ef085cadeeb25936c4d64/schemas/user.json#L130, but it's not localized in the database. Possible solution - move it to the settings table

**Comment by asmecher** [comment]
My mistake in flagging that setting as `multilingual` in the JSON; I've removed that line.
