### ISSUE TITLE
Fatal error when trying to delete section

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7664]
**Describe the bug**
Error message:
```
PHP Fatal error:  Uncaught Exception: Submissions can not be retrieved without a context id. Pass the CONTEXT_ID_ALL wildcard to get submissions from any context. in /home/doc/OJS/development/ojs/lib/pkp/classes/submission/Collector.inc.php:208
Stack trace:
#0 /home/doc/OJS/development/ojs/classes/submission/Collector.inc.php(54): PKP\submission\Collector->getQueryBuilder()
#1 /home/doc/OJS/development/ojs/lib/pkp/classes/submission/DAO.inc.php(90): APP\submission\Collector->getQueryBuilder()
#2 /home/doc/OJS/development/ojs/lib/pkp/classes/submission/Repository.inc.php(81): PKP\submission\DAO->getCount()
#3 /home/doc/OJS/development/ojs/classes/journal/SectionDAO.inc.php(330): PKP\submission\Repository->getCount()
#4 /home/doc/OJS/development/ojs/lib/pkp/classes/context/PKPSectionDAO.inc.php(74): APP\journal\SectionDAO->deleteById()
#5 /home/doc/OJS/development/ojs/controllers/grid/settings/sections/SectionGridHandler.inc.php(293): PKP\context\PKPSectionDAO->deleteObject()
#6 [internal function]: SectionGridHandler->deleteSec in /home/doc/OJS/development/ojs/lib/pkp/classes/submission/Collector.inc.php on line 208
```
***Edit*** 
There is a similar problem but with stable OPS and another error message initially reported on the forum: https://forum.pkp.sfu.ca/t/fatal-error-when-trying-to-delete-a-created-section/71690:
```
PHP Fatal error:  Uncaught Error: Call to undefined method Generator::numRows() in /home/doc/OJS/development/versions/ops-3.3.0-8/ops/controllers/grid/settings/sections/SectionGridHandler.inc.php:248
Stack trace:
#0 /home/doc/OJS/development/versions/ops-3.3.0-8/ops/lib/pkp/classes/core/PKPRouter.inc.php(395): SectionGridHandler->deleteSection()
#1 /home/doc/OJS/development/versions/ops-3.3.0-8/ops/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest()
#2 /home/doc/OJS/development/versions/ops-3.3.0-8/ops/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPComponentRouter->route()
#3 /home/doc/OJS/development/versions/ops-3.3.0-8/ops/lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher->dispatch()
#4 /home/doc/OJS/development/versions/ops-3.3.0-8/ops/index.php(68): PKPApplication->execute()
#5 {main}
  thrown in /home/doc/OJS/development/versions/ops-3.3.0-8/ops/controllers/grid/settings/sections/SectionGridHandler.inc.php on line 248
```
**To Reproduce**
1. Go to Journal Settings -> Sections
2. Click on create a new section, fill the data and save the form
3. Click on delete

**What application are you using?**
 OJS main branch, OPS 3.3.0-8

**Comment by tanabem** [comment]
@Vitaliy-1 @asmecher 
Thanks a lot! 
I confirmed it with OPS 3.3.0.7 and 3.3.0.8.

**Comment by asmecher** [comment]
Thanks for confirming, @tanabem!
