### ISSUE TITLE
Job test fails with PHP8.1

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#7704]
Running `php lib/pkp/tools/jobs.php test` with PHP8.1 generates an exception:
```
Fatal error: Uncaught Exception: Serialization of 'Illuminate\Contracts\Queue\ShouldQueue@anonymous' is not allowed in /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:147
Stack trace:
#0 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(147): serialize(Object(Illuminate\Contracts\Queue\ShouldQueue@anonymous))
#1 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(116): Illuminate\Queue\Queue->createObjectPayload(Object(Illuminate\Contracts\Queue\ShouldQueue@anonymous), 'queuedTestJob')
#2 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(94): Illuminate\Queue\Queue->createPayloadArray(Object(Illuminate\Contracts\Queue\ShouldQueue@anonymous), 'queuedTestJob', '')
#3 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(83): Illuminate\Queue\Queue->createPayload(Object(Illuminate\Contracts\Queue\ShouldQueue@anonymous), 'queuedTestJob', '')
#4 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(46): Illuminate\Queue\DatabaseQueue->push(Object(Illuminate\Contracts\Queue\ShouldQueue@anonymous), '', 'queuedTestJob')
#5 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(175): Illuminate\Queue\Queue->pushOn('queuedTestJob', Object(Illuminate\Contracts\Queue\ShouldQueue@anonymous))
#6 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(158): Illuminate\Bus\Dispatcher->pushCommandToQueue(Object(Illuminate\Queue\DatabaseQueue), Object(Illuminate\Contracts\Queue\ShouldQueue@anonymous))
#7 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(73): Illuminate\Bus\Dispatcher->dispatchToQueue(Object(Illuminate\Contracts\Queue\ShouldQueue@anonymous))
#8 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(134): Illuminate\Bus\Dispatcher->dispatch(Object(Illuminate\Contracts\Queue\ShouldQueue@anonymous))
#9 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(391): Illuminate\Foundation\Bus\PendingDispatch->__destruct()
#10 /home/asmecher/git/ojs-main/lib/pkp/tools/jobs.php(387): dispatch(Object(Illuminate\Contracts\Queue\ShouldQueue@anonymous))
#11 /home/asmecher/git/ojs-main/lib/pkp/tools/jobs.php(417): PKP\tools\commandJobs->test()
#12 /home/asmecher/git/ojs-main/lib/pkp/tools/jobs.php(423): PKP\tools\commandJobs->execute()
#13 {main}
  thrown in /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Queue/Queue.php on line 147
```

(Travis example: https://app.travis-ci.com/github/pkp/ojs/jobs/559871247)

**Comment by asmecher** [comment]
@henriqueramos, could you take a look at this one?
