### ISSUE TITLE
Stage participants API request fails

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8055]
**Describe the bug**
A 500 error is returned when trying to access the API endpoint to get stage participants.

**To Reproduce**
1. Make a `GET` request to `/api/v1/submissions/{submissionId}/participants/{stageId}`
4. See error in the error logs

**What application are you using?**
3.3.0-8

**Additional information**
Error:
```
[30-Jun-2022 10:22:09 Europe/London] Slim Application Error:
Type: Exception
Message: DAOResultFactory instances cannot be counted unless supplied in constructor (DAO UserDAO)!
File: lib/pkp/classes/db/DAOResultFactory.inc.php
Line: 101
Trace: #0 lib/pkp/classes/db/DAOResultIterator.inc.php(83): DAOResultFactory->getCount()
#1 lib/pkp/api/v1/submissions/PKPSubmissionHandler.inc.php(473): DAOResultIterator->count()
#2 [internal function]: PKPSubmissionHandler->getParticipants(Object(Slim\Http\Request), Object(APIResponse), Array)
#3 lib/pkp/lib/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(APIResponse), Array)
#4 lib/pkp/lib/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(APIResponse), Array)
#5 lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(APIResponse))
#6 lib/pkp/lib/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(APIResponse))
#7 lib/pkp/lib/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(APIResponse))
#8 lib/pkp/classes/security/authorization/internal/ApiAuthorizationMiddleware.inc.php(77): Slim\App->__invoke(Object(Slim\Http\Request), Object(APIResponse))
#9 [internal function]: ApiAuthorizationMiddleware->__invoke(Object(Slim\Http\Request), Object(APIResponse), Object(Slim\App))
#10 lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(ApiAuthorizationMiddleware), Array)
#11 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(APIResponse), Object(Slim\App))
#12 lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(APIResponse), Object(Slim\App))
#13 lib/pkp/classes/security/authorization/internal/ApiCsrfMiddleware.inc.php(46): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(APIResponse))
#14 [internal function]: ApiCsrfMiddleware->__invoke(Object(Slim\Http\Request), Object(APIResponse), Object(Closure))
#15 lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(ApiCsrfMiddleware), Array)
#16 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(APIResponse), Object(Closure))
#17 lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(APIResponse), Object(Closure))
#18 lib/pkp/classes/security/authorization/internal/ApiTokenDecodingMiddleware.inc.php(131): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(APIResponse))
#19 [internal function]: ApiTokenDecodingMiddleware->__invoke(Object(Slim\Http\Request), Object(APIResponse), Object(Closure))
#20 lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(ApiTokenDecodingMiddleware), Array)
#21 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(APIResponse), Object(Closure))
#22 lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(APIResponse), Object(Closure))
#23 lib/pkp/classes/handler/APIHandler.inc.php(68): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(APIResponse))
#24 [internal function]: APIHandler->{closure}(Object(Slim\Http\Request), Object(APIResponse), Object(Closure))
#25 lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#26 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(APIResponse), Object(Closure))
#27 lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(APIResponse), Object(Closure))
#28 lib/pkp/classes/handler/APIHandler.inc.php(127): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(APIResponse))
#29 [internal function]: APIHandler->{closure}(Object(Slim\Http\Request), Object(APIResponse), Object(Closure))
#30 lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#31 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(APIResponse), Object(Closure))
#32 lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(APIResponse), Object(Closure))
#33 lib/pkp/classes/handler/APIHandler.inc.php(132): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(APIResponse))
#34 [internal function]: APIHandler->{closure}(Object(Slim\Http\Request), Object(APIResponse), Object(Closure))
#35 lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#36 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(APIResponse), Object(Closure))
#37 lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(APIResponse), Object(Closure))
#38 lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(APIResponse))
#39 lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(APIResponse))
#40 lib/pkp/lib/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(APIResponse))
#41 lib/pkp/classes/core/APIRouter.inc.php(115): Slim\App->run()
#42 lib/pkp/classes/core/Dispatcher.inc.php(144): APIRouter->route(Object(Request))
#43 lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher->dispatch(Object(Request))
#44 index.php(68): PKPApplication->execute()
#45 {main}
```

Originally [reported](https://forum.pkp.sfu.ca/t/participants-api-endpoint-not-working-in-3-3/73698/3) in the forum.

**Comment by touhidurabir** [comment]
@NateWr PRs are done . please review 

[pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#8055 Update the initialization of DAOResultFactory with sql and bindings params](https://github.com/pkp/pkp-lib/pull/8078)
[omp](https://github.com/pkp/omp) --> [Submodule Update ##touhidurabir/i8055_stable_3_3_0_fix##](https://github.com/pkp/omp/pull/1151)
[ops](https://github.com/pkp/ops) --> [Submodule Update ##touhidurabir/i8055_stable_3_3_0_fix##](https://github.com/pkp/ops/pull/305)
[ojs](https://github.com/pkp/ojs) --> [Submodule Update ##touhidurabir/i8055_stable_3_3_0_fix##](https://github.com/pkp/ojs/pull/3454)

Target branch is `stable-3_3_0` as this bug does not exists in the `main` branch as I have tested .

**Comment by NateWr** [comment]
Thanks @touhidurabir. It looks ok to me. @asmecher can you do a sanity check on this? Will [this change](https://github.com/pkp/pkp-lib/pull/8078/files) effect performance much? I know it's probably called a lot.

**Comment by asmecher** [comment]
> Will [this change](https://github.com/pkp/pkp-lib/pull/8078/files) effect performance much? I know it's probably called a lot.

No, this won't make performance worse. It makes visible an inefficiency that ADODB used to hide -- getting a set of results and also counting that set of results caused two separate queries. `DAOResultFactory` is deprecated and this bit of cruft will go away with it.
