### ISSUE TITLE
PHP Fatal Error in OMP classes/observers/events/Usage.php

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#8123]
**Describe the bug**
During the data build scripts, I see this recurring error message in the log:
```
PHP Fatal error:  Uncaught Error: Typed property APP\observers\events\Usage::$request must not be accessed before initialization in /home/asmecher/git/omp-main/classes/observers/events/Usage.php:81
Stack trace:
#0 /home/asmecher/git/omp-main/lib/pkp/classes/observers/traits/UsageEvent.php(70): APP\observers\events\Usage->getCanonicalUrl()
#1 /home/asmecher/git/omp-main/classes/observers/events/Usage.php(39): APP\observers\events\Usage->traitConstruct()
#2 /home/asmecher/git/omp-main/pages/index/IndexHandler.inc.php(144): APP\observers\events\Usage->__construct()
#3 /home/asmecher/git/omp-main/pages/index/IndexHandler.inc.php(57): IndexHandler->_displayPressIndexPage()
#4 [internal function]: IndexHandler->index()
#5 /home/asmecher/git/omp-main/lib/pkp/classes/core/PKPRouter.php(465): call_user_func()
#6 /home/asmecher/git/omp-main/lib/pkp/classes/core/PKPPageRouter.php(307): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#7 /home/asmecher/git/omp-main/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPPageRouter->route()
#8 /home/asmecher/git/omp-main/lib/pkp/classes/core/PKPApplication.php(379): PKP\core\Dispatcher->dispatch()
#9 /home/asmecher/git/omp-main/index.php(65): PKP\core\PKPApplication->execute()
#10 {main}
  thrown in /home/asmecher/git/omp-main/classes/observers/events/Usage.php on line 81
```

It doesn't appear to break the builds, but does likely mean that stats aren't being recorded for some events.

**To Reproduce**
With a current OMP `main` checkout, run the data build scripts.

**Comment by bozana** [comment]
PRs:
pkp-lib: https://github.com/pkp/pkp-lib/pull/8149
omp: https://github.com/pkp/omp/pull/1169
