### ISSUE TITLE
PHP fatal error in OPS APP\observers\events\Usage

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#8125]
**Describe the bug**
When building the test dataset with OPS `main`, I see the following error:
```
PHP Fatal error:  Uncaught Error: Call to undefined method APP\observers\events\Usage::getCanonicalUrl() in /home/asmecher/git/ops-main/lib/pkp/classes/observers/traits/UsageEvent.php:70
Stack trace:
#0 /home/asmecher/git/ops-main/classes/observers/events/Usage.php(31): APP\observers\events\Usage->traitConstruct()
#1 /home/asmecher/git/ops-main/pages/index/IndexHandler.php(99): APP\observers\events\Usage->__construct()
#2 [internal function]: APP\pages\index\IndexHandler->index()
#3 /home/asmecher/git/ops-main/lib/pkp/classes/core/PKPRouter.php(465): call_user_func()
#4 /home/asmecher/git/ops-main/lib/pkp/classes/core/PKPPageRouter.php(307): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#5 /home/asmecher/git/ops-main/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPPageRouter->route()
#6 /home/asmecher/git/ops-main/lib/pkp/classes/core/PKPApplication.php(379): PKP\core\Dispatcher->dispatch()
#7 /home/asmecher/git/ops-main/index.php(70): PKP\core\PKPApplication->execute()
#8 {main}
  thrown in /home/asmecher/git/ops-main/lib/pkp/classes/observers/traits/UsageEvent.php on line 70
```
This doesn't appear to break the test builds, but does suggest that events are not getting recorded.

**To Reproduce**
Build the test dataset on OMP main.

**Comment by Vitaliy-1** [comment]
I see the same error in OJS too

**Comment by bozana** [comment]
PR: https://github.com/pkp/ops/pull/324
