### ISSUE TITLE
Integrity constraint violation when removing a context

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8129]
**Describe the bug**
Unable to remove the journal due to fatal error:
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`cypress-master`.`genres`, CONSTRAINT `genres_context_id_foreign` FOREIGN KEY (`context_id`) REFERENCES `journals` (`journal_id`)) in /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
Stack trace:
#0 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute()
#1 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(526): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(709): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(676): Illuminate\Database\Connection->runQueryCallback()
#4 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(533): Illuminate\Database\Connection->run()
#5 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(453): Illuminate\Database\Connection->affectingStatement()
#6 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Illuminate\Database\DatabaseManager->__call()
#7 /home/doc/OJS/development/ojs/lib/pkp/classes/db/DAO.inc.php(169): Illuminate\Support\Facades\Facade::__callStatic()
#8 /home/doc/OJS/development/ojs/lib/pkp/classes/db/SchemaDAO.inc.php(214): PKP\db\DAO->update()
#9 /home/doc/OJS/development/ojs/lib/pkp/classes/db/SchemaDAO.inc.php(202): PKP\db\SchemaDAO->deleteById()
#10 /home/doc/OJS/development/ojs/lib/pkp/classes/services/PKPContextService.inc.php(615): PKP\db\SchemaDAO->deleteObject()
#11 /home/doc/OJS/development/ojs/lib/pkp/controllers/grid/admin/context/ContextGridHandler.inc.php(288): PKP\services\PKPContextService->delete()
#12 [internal function]: ContextGridHandler->deleteContext()
#13 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPRouter.inc.php(465): call_user_func()
#14 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPComponentRouter.inc.php(288): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#15 /home/doc/OJS/development/ojs/lib/pkp/classes/core/Dispatcher.inc.php(163): PKP\core\PKPComponentRouter->route()
#16 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPApplication.inc.php(379): PKP\core\Dispatcher->dispatch()
#17 /home/doc/OJS/development/ojs/index.php(70): PKP\core\PKPApplication->execute()
#18 {main}

Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`cypress-master`.`genres`, CONSTRAINT `genres_context_id_foreign` FOREIGN KEY (`context_id`) REFERENCES `journals` (`journal_id`)) in /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
Stack trace:
#0 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(119): Doctrine\DBAL\Driver\PDO\Exception::new()
#1 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(526): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(709): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(676): Illuminate\Database\Connection->runQueryCallback()
#4 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(533): Illuminate\Database\Connection->run()
#5 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(453): Illuminate\Database\Connection->affectingStatement()
#6 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Illuminate\Database\DatabaseManager->__call()
#7 /home/doc/OJS/development/ojs/lib/pkp/classes/db/DAO.inc.php(169): Illuminate\Support\Facades\Facade::__callStatic()
#8 /home/doc/OJS/development/ojs/lib/pkp/classes/db/SchemaDAO.inc.php(214): PKP\db\DAO->update()
#9 /home/doc/OJS/development/ojs/lib/pkp/classes/db/SchemaDAO.inc.php(202): PKP\db\SchemaDAO->deleteById()
#10 /home/doc/OJS/development/ojs/lib/pkp/classes/services/PKPContextService.inc.php(615): PKP\db\SchemaDAO->deleteObject()
#11 /home/doc/OJS/development/ojs/lib/pkp/controllers/grid/admin/context/ContextGridHandler.inc.php(288): PKP\services\PKPContextService->delete()
#12 [internal function]: ContextGridHandler->deleteContext()
#13 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPRouter.inc.php(465): call_user_func()
#14 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPComponentRouter.inc.php(288): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#15 /home/doc/OJS/development/ojs/lib/pkp/classes/core/Dispatcher.inc.php(163): PKP\core\PKPComponentRouter->route()
#16 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPApplication.inc.php(379): PKP\core\Dispatcher->dispatch()
#17 /home/doc/OJS/development/ojs/index.php(70): PKP\core\PKPApplication->execute()
#18 {main}

Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`cypress-master`.`genres`, CONSTRAINT `genres_context_id_foreign` FOREIGN KEY (`context_id`) REFERENCES `journals` (`journal_id`)) (SQL: DELETE FROM journals WHERE journal_id = 2) in /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:716
Stack trace:
#0 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(676): Illuminate\Database\Connection->runQueryCallback()
#1 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(533): Illuminate\Database\Connection->run()
#2 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(453): Illuminate\Database\Connection->affectingStatement()
#3 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Illuminate\Database\DatabaseManager->__call()
#4 /home/doc/OJS/development/ojs/lib/pkp/classes/db/DAO.inc.php(169): Illuminate\Support\Facades\Facade::__callStatic()
#5 /home/doc/OJS/development/ojs/lib/pkp/classes/db/SchemaDAO.inc.php(214): PKP\db\DAO->update()
#6 /home/doc/OJS/development/ojs/lib/pkp/classes/db/SchemaDAO.inc.php(202): PKP\db\SchemaDAO->deleteById()
#7 /home/doc/OJS/development/ojs/lib/pkp/classes/services/PKPContextService.inc.php(615): PKP\db\SchemaDAO->deleteObject()
#8 /home/doc/OJS/development/ojs/lib/pkp/controllers/grid/admin/context/ContextGridHandler.inc.php(288): PKP\services\PKPContextService->delete()
#9 [internal function]: ContextGridHandler->deleteContext()
#10 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPRouter.inc.php(465): call_user_func()
#11 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPComponentRouter.inc.php(288): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#12 /home/doc/OJS/development/ojs/lib/pkp/classes/core/Dispatcher.inc.php(163): PKP\core\PKPComponentRouter->route()
#13 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPApplication.inc.php(379): PKP\core\Dispatcher->dispatch()
#14 /home/doc/OJS/development/ojs/index.php(70): PKP\core\PKPApplication->execute()
#15 {main}
  thrown in /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 716
```

**To Reproduce**
1. Go to admin dashboard -> hosted journals
2. Create a new journal
3. When created, go back to hosted journals, click `Remove` button in the journal's grid

**What application are you using?**
 OJS main branch

**Comment by asmecher** [comment]
Fixed, thanks! We're going to see more of these as we add foreign constraints -- it's a good thing, because we were previously leaving orphaned rows in cases like this.
