### ISSUE TITLE
Discussions broken in the main branch

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8141]
**Describe the bug**
Discussions can not be created, notes can not be added, and the UI does not updated after save actions are taken.

**To Reproduce**
1. Go to any submission.
2. Click on Add Discussion
3. Open the browser's dev tools and look at the network panel to see XHR requests.
4. Add a discussion subject and message and assign two or more participants, including the current user.
5. Click OK.
6. See in the network panel that the XHR request succeeded with 200 return status.
7. See error: the modal does not disappear.
8. Reload the page.
9. See error: the discussion was not created.
10. Go to any submission with an existing discussion.
11. Click on the discussion subject to open it.
12. Click Add Messaage
13. See in the network panel that the XHR request returned a 500 error.
14. See error: the loading spinner does not go away and no add message UI appears.

**What application are you using?**
`main` branch (3.4 pre-release)

**Additional information**
The following error message appears during step 13, when the XHR request to add a message to a query fails with 500:

```
[09-Aug-2022 11:06:10 UTC] PHP Fatal error:  Uncaught Error: Class "PKP\controllers\grid\queries\form\QueryNoteForm" not found in lib/pkp/controllers/grid/queries/QueryNotesGridHandler.php:181
Stack trace:
#0 [internal function]: PKP\controllers\grid\queries\QueryNotesGridHandler->addNote(Array, Object(APP\core\Request))
#1 lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#2 lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#3 lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#4 lib/pkp/classes/core/PKPApplication.php(379): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#5 index.php(70): PKP\core\PKPApplication->execute()
#6 {main}
  thrown in lib/pkp/controllers/grid/queries/QueryNotesGridHandler.php on line 181
```

**Comment by NateWr** [comment]
I have temporarily skipped the discussions tests until this is fixed. To enable them again, revert https://github.com/pkp/ojs/commit/af7a6a9f8865a7e0acf7e4b65dc2e5b0763e2cc2.

**Comment by NateWr** [comment]
Thanks @defstat. That looks like it fixed it up. I've pulled your commits in and restored the discussion tests. I'll wait and see if the tests are fixed now.

PRs:
https://github.com/pkp/pkp-lib/pull/8152
https://github.com/pkp/ojs/pull/3484

**Comment by NateWr** [comment]
All merged to `main`. Thanks again, @defstat!
