### ISSUE TITLE
Unable to delete submission due to foreign key cascade

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8337]
**Describe the bug**
It's not possible to delete a submission when that submission has at least one review assignment. The error appears to be caused when a publication is deleted and it is the only publication for the submission. The database tries to delete the submission but other related objects have not been removed.

**To Reproduce**
1. Assign a review to a submission.
2. Delete that submission from the API. (It is probably possible to emulate this by declining and then deleting the submission through the UI.)

**What application are you using?**
`main` branch (3.4 pre-release)

**Additional information**
This is happening because of [this line](https://github.com/pkp/ojs/blob/main/classes/migration/install/OJSMigration.php#L217) in the publications table:

```
$table->foreign('submission_id', 'publications_submission_id')->references('submission_id')->on('submissions')->onDelete('cascade');
```

This causes a problem because the publication is deleted before other objects related to the submission:

https://github.com/pkp/pkp-lib/blob/main/classes/submission/DAO.php#L242

It may be possible to fix this by deleting the publications last.

Here is the full error message:

```
Previous error:
Type: PDOException
Code: 23503
Message: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table &quot;submissions&quot; violates foreign key constraint &quot;review_assignments_submission_id_foreign&quot; on table &quot;review_assignments&quot;
DETAIL:  Key (submission_id)=(49) is still referenced from table &quot;review_assignments&quot;.
File: lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php
Line: 117
Trace: #0 lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute(NULL)
#1 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(569): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(752): Illuminate\Database\Connection->Illuminate\Database\{closure}('delete from "pu...', Array)
#3 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(719): Illuminate\Database\Connection->runQueryCallback('delete from "pu...', Array, Object(Closure))
#4 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(576): Illuminate\Database\Connection->run('delete from "pu...', Array, Object(Closure))
#5 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->affectingStatement('delete from "pu...', Array)
#6 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3436): Illuminate\Database\Connection->delete('delete from "pu...', Array)
#7 lib/pkp/classes/core/EntityDAO.php(253): Illuminate\Database\Query\Builder->delete()
#8 lib/pkp/classes/publication/DAO.php(253): PKP\core\EntityDAO->deleteById(49)
#9 lib/pkp/classes/core/EntityDAO.php(238): PKP\publication\DAO->deleteById(49)
#10 lib/pkp/classes/publication/DAO.php(245): PKP\core\EntityDAO->_delete(Object(APP\publication\Publication))
#11 lib/pkp/classes/publication/Repository.php(582): PKP\publication\DAO->delete(Object(APP\publication\Publication))
#12 classes/publication/Repository.php(184): PKP\publication\Repository->delete(Object(APP\publication\Publication))
#13 lib/pkp/classes/submission/DAO.php(245): APP\publication\Repository->delete(Object(APP\publication\Publication))
#14 classes/submission/DAO.php(33): PKP\submission\DAO->deleteById(49)
#15 lib/pkp/classes/core/EntityDAO.php(238): APP\submission\DAO->deleteById(49)
#16 lib/pkp/classes/submission/DAO.php(228): PKP\core\EntityDAO->_delete(Object(APP\submission\Submission))
#17 lib/pkp/classes/submission/Repository.php(522): PKP\submission\DAO->delete(Object(APP\submission\Submission))
#18 lib/pkp/api/v1/submissions/PKPSubmissionHandler.php(723): PKP\submission\Repository->delete(Object(APP\submission\Submission))
#19 [internal function]: PKP\API\v1\submissions\PKPSubmissionHandler->delete(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Array)
#20 lib/pkp/lib/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(PKP\core\APIResponse), Array)
#21 lib/pkp/lib/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(PKP\core\APIResponse), Array)
#22 lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#23 lib/pkp/lib/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#24 lib/pkp/lib/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#25 lib/pkp/classes/security/authorization/internal/ApiAuthorizationMiddleware.php(87): Slim\App->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#26 [internal function]: PKP\security\authorization\internal\ApiAuthorizationMiddleware->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Slim\App))
#27 lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(PKP\security\authorization\internal\ApiAuthorizationMiddleware), Array)
#28 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Slim\App))
#29 lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Slim\App))
#30 lib/pkp/classes/security/authorization/internal/ApiCsrfMiddleware.php(54): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#31 [internal function]: PKP\security\authorization\internal\ApiCsrfMiddleware->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#32 lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(PKP\security\authorization\internal\ApiCsrfMiddleware), Array)
#33 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#34 lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#35 lib/pkp/classes/security/authorization/internal/ApiTokenDecodingMiddleware.php(141): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#36 [internal function]: PKP\security\authorization\internal\ApiTokenDecodingMiddleware->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#37 lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(PKP\security\authorization\internal\ApiTokenDecodingMiddleware), Array)
#38 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#39 lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#40 lib/pkp/classes/handler/APIHandler.php(78): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#41 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#42 lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#43 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#44 lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#45 lib/pkp/classes/handler/APIHandler.php(137): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#46 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#47 lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#48 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#49 lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#50 lib/pkp/classes/handler/APIHandler.php(142): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#51 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#52 lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#53 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#54 lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#55 lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#56 lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#57 lib/pkp/lib/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#58 lib/pkp/classes/core/APIRouter.php(127): Slim\App->run()
#59 lib/pkp/classes/core/Dispatcher.php(163): PKP\core\APIRouter->route(Object(APP\core\Request))
#60 lib/pkp/classes/core/PKPApplication.php(379): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#61 index.php(21): PKP\core\PKPApplication->execute()
#62 {main}
View in rendered output by enabling the "displayErrorDetails" setting.
```

**Comment by touhidurabir** [comment]
@NateWr can you still produce this error when deleting a submission . I have tested with several different combination such as 
1. with active review round . 
2. review round with review assignment added
3. review assignment accepted and confirmed by Editor/JM . 

but could not produce the problem at all . I also made sure that I have those `foreign` constrains properly defined for `submissions`, `publications` and `review_assignments` table .

**Comment by NateWr** [comment]
Thanks for testing, @touhidurabir. I will leave this open and try to reproduce it closer to release. It's possible it only effects postgres or that the database I was using was out of sync or something.

**Comment by asmecher** [comment]
It's possible that I added some `ON DELETE CASCADE` clauses after introducing FKs, and that your database was created between the two, @NateWr. If anyone runs into this kind of problem, feel free to ping me about the twists and turns of https://github.com/pkp/pkp-lib/issues/6093 -- there were many.

**Comment by asmecher** [comment]
This was caused by an errant `ON DELETE CASCADE` on `submissions.current_publication_id` (https://github.com/pkp/ojs/commit/95d08fa51049218557cbbba9ee24709d56a74c40). You'll need a rebuilt database before the fix will take effect.
