### ISSUE TITLE
Resolve static call error message accessing reviewer one-click link

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#8378]
**Describe the bug**
From https://forum.pkp.sfu.ca/t/one-click-link-within-email-generate-php-error-non-static-method-cannot-be-called-statically/75211:

> The direct “one click” link (e.g. of the form: https://dev.ojs.umontreal.ca/index.php/abc/reviewer/submission?submissionId=xx&reviewId=xx&key=xxxxxx) included within the email sent to the reviewer generates an error.
> 
> PHP Log:
> 
> ```
> [27-Oct-2022 13:53:10 UTC] PHP Fatal error:  Uncaught Error: Non-static method AccessKeyManager::generateKeyHash() cannot be called statically in /apps/ojs/dev/ojs-3.3.0-11/pages/reviewer/ReviewerHandler.inc.php:78
> Stack trace:
> #0 /apps/ojs/dev/ojs-3.3.0-11/pages/reviewer/ReviewerHandler.inc.php(38): ReviewerHandler->_validateAccessKey()
> #1 /apps/ojs/dev/ojs-3.3.0-11/lib/pkp/classes/core/PKPRouter.inc.php(387): ReviewerHandler->authorize()
> #2 /apps/ojs/dev/ojs-3.3.0-11/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest()
> #3 /apps/ojs/dev/ojs-3.3.0-11/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPPageRouter->route()
> #4 /apps/ojs/dev/ojs-3.3.0-11/lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher->dispatch()
> #5 /apps/ojs/dev/ojs-3.3.0-11/index.php(67): PKPApplication->execute()
> #6 {main}
>   thrown in /apps/ojs/dev/ojs-3.3.0-11/pages/reviewer/ReviewerHandler.inc.php on line 78
> ```

**What application are you using?**
 OJS, OMP or OPS version 3.3.0-13

**Comment by asmecher** [comment]
If you're encountering this error message in OJS 3.3.0-x, you can fix it by applying [this one-line change](https://github.com/pkp/ojs/commit/9ba97bae5ad6629c6d70ffbf20e19825a4ed9abc) (or upgrading to 3.3.0-14 or newer, once that is released).
