### ISSUE TITLE
Fatal error with Carbon dependency when running PHP 8.2

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8521]
**Describe the bug**
When running PHP 8.2, there is a fatal error in the Carbon dependency used by Laravel. It seems that upgrading our Laravel to ^9.45.x might solve this problem.

https://stackoverflow.com/questions/74749564/laravel-carbon-carbonsetlasterrors

**What application are you using?**
`main` branch (3.4 pre-release)

**Additional information**
Error message:
```
[22-Dec-2022 12:33:05 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mb_regex_encoding() in /ojs/lib/pkp/lib/vendor/smarty/smarty/libs/plugins/shared.mb_str_replace.php:47
Stack trace:
#0 /ojs/lib/pkp/lib/vendor/smarty/smarty/libs/plugins/modifier.replace.php(34): smarty_mb_str_replace('_', '-', 'en_US')
#1 /ojs/cache/t_compile/13376d7934b5f251160733e5e3c8b2ff6a1e1f24^164bd5a4f3891532cf93e9d19911fe9cb3308efd_0.app.layoutsbackend.tpl.php(31): smarty_modifier_replace('en_US', '_', '-')
#2 /ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6395ff6581cca7_95717256(Object(Smarty_Internal_Template))
#3 /ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#4 /ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#5 /ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#6 /ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(115): Smarty_Internal_Template->_subTemplateRender('layouts/backend...', NULL, '13376d7934b5f25...', 0, 3600, Array, 2, false, NULL, NULL)
#7 /ojs/cache/t_compile/13376d7934b5f251160733e5e3c8b2ff6a1e1f24^8e26d4d5b957a6848a96c58ac27d2fddb2c40f9a_0.app.installinstall.tpl.php(34): Smarty_Internal_Runtime_Inheritance->endChild(Object(Smarty_Internal_Template), 'layouts/backend...')
#8 /ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6395ff65806505_86645248(Object(Smarty_Internal_Template))
#9 /ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#10 /ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#11 /ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 1)
#12 /ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, '13376d7934b5f25...', NULL, 1)
#13 /ojs/lib/pkp/classes/template/PKPTemplateManager.php(1306): Smarty_Internal_TemplateBase->display('install/install...', NULL, '13376d7934b5f25...', NULL)
#14 /ojs/lib/pkp/classes/form/Form.php(203): PKP\template\PKPTemplateManager->display('install/install...')
#15 /ojs/lib/pkp/classes/form/Form.php(154): PKP\form\Form->fetch(Object(APP\core\Request), NULL, true)
#16 /ojs/lib/pkp/classes/install/form/MaintenanceForm.php(48): PKP\form\Form->display(Object(APP\core\Request), NULL)
#17 /ojs/lib/pkp/classes/install/form/InstallForm.php(121): PKP\install\form\MaintenanceForm->display(Object(APP\core\Request), NULL)
#18 /ojs/lib/pkp/pages/install/InstallHandler.php(57): PKP\install\form\InstallForm->display(Object(APP\core\Request))
#19 [internal function]: PKP\pages\install\InstallHandler->index(Array, Object(APP\core\Request))
#20 /ojs/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#21 /ojs/lib/pkp/classes/core/PKPPageRouter.php(308): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#22 /ojs/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#23 /ojs/lib/pkp/classes/core/PKPApplication.php(379): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#24 /ojs/index.php(21): PKP\core\PKPApplication->execute()
#25 {main}
  thrown in /ojs/lib/pkp/lib/vendor/smarty/smarty/libs/plugins/shared.mb_str_replace.php on line 47
```

**Comment by asmecher** [comment]
This is caused by a missing `mbstring` extension.
