### ISSUE TITLE
Can't load UI to manage email templates

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8567]
**Describe the bug**
I receive a fatal error when trying to load the UI to manage email templates. This is because #2135 removed the `PasswordReset` mailable, but it is still listed as a mailable in the system.

**To Reproduce**
1. Go to Settings > Workflow > Email > Manage Emails > Add and edit templates.
4. See error in logs

**What application are you using?**
`main` branch (3.4 pre-release)

**Additional information**
@touhidurabir can you pick this one up? Here's the exact error message.

```
[25-Jan-2023 09:44:29 UTC] PHP Fatal error:  Uncaught Error: Class "PKP\mail\mailables\PasswordReset" not found in lib/pkp/classes/mail/Repository.php:85
Stack trace:
#0 lib/pkp/pages/management/ManagementHandler.php(530): PKP\mail\Repository->summarizeMailable('PKP\\mail\\mailab...')
#1 [internal function]: PKP\pages\management\ManagementHandler->PKP\pages\management\{closure}('PKP\\mail\\mailab...', 23)
#2 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(560): array_map(Object(Closure), Array, Array)
#3 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(719): Illuminate\Support\Arr::map(Array, Object(Closure))
#4 lib/pkp/pages/management/ManagementHandler.php(530): Illuminate\Support\Collection->map(Object(Closure))
#5 lib/pkp/pages/management/ManagementHandler.php(99): PKP\pages\management\ManagementHandler->manageEmails(Array, Object(APP\core\Request))
#6 [internal function]: PKP\pages\management\ManagementHandler->settings(Array, Object(APP\core\Request))
#7 lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#8 lib/pkp/classes/core/PKPPageRouter.php(308): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#9 lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#10 lib/pkp/classes/core/PKPApplication.php(379): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#11 index.php(21): PKP\core\PKPApplication->execute()
#12 {main}
  thrown in lib/pkp/classes/mail/Repository.php on line 85
```

**Comment by touhidurabir** [comment]
@NateWr PRs
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8569
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3723 [TEST ONLY]

**Comment by touhidurabir** [comment]
@NateWr updated PRs

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8569
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3723 [TEST ONLY]
[ops](https://github.com/touhidurabir/ops) --> https://github.com/pkp/ops/pull/447

**Comment by NateWr** [comment]
Merged to `main`. Cherry-picked commits for OJS/OPS to bypass merge conflict. I included a submodule update so hopefully I won't break the tests this time. :laughing: 

Thanks @touhidurabir!
