### ISSUE TITLE
DataCite export error with PHP8.1

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#8579]
See https://forum.pkp.sfu.ca/t/dataciteexport-plugin-error-when-using-php-8-1-14/76528:

> We updated php to 8.1.14, using OJS 3.3.0.8.
>  When exporting articles using the DataCiteExport plugin, we get a blank screen and the following error message in the log:
> 
> ```
> PHP Fatal error: Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in /var/www/html/plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php:173\nStack trace:\n#0 /var/www/html/plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php(173): array_merge()\n#1 /var/www/html/lib/pkp/classes/filter/Filter.inc.php(449): DataciteXmlFilter->process()\n#2 /var/www/html/classes/plugins/PubObjectsExportPlugin.inc.php(391): Filter->execute()\n#3 /var/www/html/plugins/importexport/datacite/DataciteExportPlugin.inc.php(110): PubObjectsExportPlugin->exportXML()\n#4 /var/www/html/classes/plugins/PubObjectsExportPlugin.inc.php(171): DataciteExportPlugin->executeExportAction()\n#5 /var/www/html/classes/plugins/DOIPubIdExportPlugin.inc.php(29): PubObjectsExportPlugin->display()\n#6 /var/www/html/lib/pkp/pages/management/PKPToolsHandler.inc.php(94): DOIPubIdExportPlugin->display()\n#7 /var/www/html/lib/pkp/classes/core/PKPRouter.inc.php(395): PKPToolsHandler->importexport()\n#8 /var/www/html/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest()\n#9 /var/www/html/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPPageRouter->route()\n#10 /var/www/html/lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher->dispatch()\n#11 /var/www/html/index.php(67): PKPApplication->execute()\n#12 {main}\n thrown in /var/www/html/plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php on line 173, referer: https://test.com/ojstest/management/importexport/plugin/DataciteExportPlugin
> ```
> 
> Steps I took leading up to the issue
> 
> - Go to ‘Tools’/‘DataCite Export/Registration Plugin’
> - Click on the ‘Articles’ tab
> - Select articles to export
> - Click ‘Export’ button
> - Blank Screen
> 
> What application are you using?
> OJS 3.3.0.8

**Comment by asmecher** [comment]
For OJS 3.3.0-x users before 3.3.0-14, you can apply https://github.com/pkp/ojs/commit/c88345cf30211d0ac3726f988e2f175ef34f43ed to resolve the issue. The fix is included in OJS 3.3.0-14 and newer.
