### ISSUE TITLE
Unable to remove a role in the user profile form

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8603]
**Describe the bug**
![roles](https://user-images.githubusercontent.com/20665587/216370648-9a9bb715-391c-4a31-93bb-8bc3b4618bf9.png)
Fatal error prevents from deselecting a role within the context in the user profile:
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'user_group_id' in where clause is ambiguous in /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:565
Stack trace:
#0 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(565): PDO->prepare('delete `user_us...')
#1 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(752): Illuminate\Database\Connection->Illuminate\Database\{closure}('delete `user_us...', Array)
#2 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(719): Illuminate\Database\Connection->runQueryCallback('delete `user_us...', Array, Object(Closure))
#3 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(576): Illuminate\Database\Connection->run('delete `user_us...', Array, Object(Closure))
#4 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->affectingStatement('delete `user_us...', Array)
#5 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3436): Illuminate\Database\Connection->delete('delete `user_us...', Array)
#6 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1154): Illuminate\Database\Query\Builder->delete()
#7 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/userGroup/Repository.php(270): Illuminate\Database\Eloquent\Builder->delete()
#8 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/user/form/UserFormHelper.php(115): PKP\userGroup\Repository->removeUserFromGroup(1, 17, 1)
#9 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/user/form/RolesForm.php(98): PKP\user\form\UserFormHelper->saveRoleContent(Object(PKP\user\form\RolesForm), Object(PKP\user\User))
#10 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/controllers/tab/user/ProfileTabHandler.php(162): PKP\user\form\RolesForm->execute()
#11 [internal function]: PKP\controllers\tab\user\ProfileTabHandler->saveRoles(Array, Object(APP\core\Request))
#12 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#13 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#14 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#15 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPApplication.php(379): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#16 /Users/vitalii/Documents/development/ojs-main/ojs/index.php(21): PKP\core\PKPApplication->execute()
#17 {main}

Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'user_group_id' in where clause is ambiguous (SQL: delete `user_user_groups` from `user_user_groups` inner join `user_groups` as `ug` on `user_user_groups`.`user_group_id` = `ug`.`user_group_id` where `user_id` = 1 and `user_group_id` = 17 and `ug`.`context_id` = 1) in /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:759
Stack trace:
#0 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(719): Illuminate\Database\Connection->runQueryCallback('delete `user_us...', Array, Object(Closure))
#1 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(576): Illuminate\Database\Connection->run('delete `user_us...', Array, Object(Closure))
#2 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->affectingStatement('delete `user_us...', Array)
#3 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3436): Illuminate\Database\Connection->delete('delete `user_us...', Array)
#4 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1154): Illuminate\Database\Query\Builder->delete()
#5 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/userGroup/Repository.php(270): Illuminate\Database\Eloquent\Builder->delete()
#6 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/user/form/UserFormHelper.php(115): PKP\userGroup\Repository->removeUserFromGroup(1, 17, 1)
#7 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/user/form/RolesForm.php(98): PKP\user\form\UserFormHelper->saveRoleContent(Object(PKP\user\form\RolesForm), Object(PKP\user\User))
#8 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/controllers/tab/user/ProfileTabHandler.php(162): PKP\user\form\RolesForm->execute()
#9 [internal function]: PKP\controllers\tab\user\ProfileTabHandler->saveRoles(Array, Object(APP\core\Request))
#10 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#11 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#12 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#13 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPApplication.php(379): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#14 /Users/vitalii/Documents/development/ojs-main/ojs/index.php(21): PKP\core\PKPApplication->execute()
#15 {main}
  thrown in /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 759
```
**To Reproduce**
1. Go to user profile menu
2. Select a role `reader` and save the form 
3. Deselect a role `reader` as save the form

**What application are you using?**
 OJS main branch

**Comment by asmecher** [comment]
Resolved by https://github.com/pkp/pkp-lib/commit/cc983d1e54f5210f8a95b6c8b4818ef2ab5fd249, thanks!
