### ISSUE TITLE
Error when trying to remove an issue in OJS

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8659]
**Describe the bug**
```php
PHP Fatal error:  Uncaught Error: Call to undefined method Closure::getData() in classes/controllers/grid/issues/IssueGridHandler.php:377
Stack trace:
#0 [internal function]: APP\controllers\grid\issues\IssueGridHandler->deleteIssue(Array, Object(APP\core\Request))
#1 lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#2 lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#3 lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#4 lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#5 C:\work\pkp\ojs\index.php(21): PKP\core\PKPApplication->execute()
#6 {main}
  thrown in classes/controllers/grid/issues/IssueGridHandler.php on line 377
```

**To Reproduce**
1. Create an issue at least one publication
2. Attempt to remove the issue

**What application are you using?**
OJS/main

**PRs**
- https://github.com/pkp/pkp-lib/pull/8660
- https://github.com/pkp/ojs/pull/3782

**Comment by jonasraoni** [comment]
@asmecher Here are the PRs to address this issue:

**PRs**
- https://github.com/pkp/pkp-lib/pull/8660
- https://github.com/pkp/ojs/pull/3782

**Comment by asmecher** [comment]
Merged, thanks!
