### ISSUE TITLE
Fatal error when uploading file to publisher library due to foreign key constraint

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8668]
**Describe the bug**
When I try to upload a file to the publisher library, I get a fatal error due to a foreign key constraint

**To Reproduce**
1. Go to Settings > Workflow > Publisher Library.
2. Click Add a File.
3. Enter a name and upload a file.
4. Click OK
5. See that the saving spinner never stops.
7. See error in server logs.

**What application are you using?**
 `main` branch (3.4 pre-release)

**Additional information**
error:
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  insert or update on table "library_files" violates foreign key constraint "library_files_submission_id_foreign"
DETAIL:  Key (submission_id)=(0) is not present in table "submissions". in /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:569
Stack trace:
#0 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(569): PDOStatement->execute()
#1 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(752): Illuminate\Database\Connection->Illuminate\Database\{closure}('INSERT INTO lib...', Array)
#2 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(719): Illuminate\Database\Connection->runQueryCallback('INSERT INTO lib...', Array, Object(Closure))
#3 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(576): Illuminate\Database\Connection->run('INSERT INTO lib...', Array, Object(Closure))
#4 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(462): Illuminate\Database\Connection->affectingStatement('INSERT INTO lib...', Array)
#5 /home/nate/Projects/pkp/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Illuminate\Database\DatabaseManager->__call('affectingStatem...', Array)
#6 /home/nate/Projects/pkp/ojs/lib/pkp/classes/db/DAO.php(169): Illuminate\Support\Facades\Facade::__callStatic('affectingStatem...', Array)
#7 /home/nate/Projects/pkp/ojs/lib/pkp/classes/context/LibraryFileDAO.php(190): PKP\db\DAO->update('INSERT INTO lib...', Array)
#8 /home/nate/Projects/pkp/ojs/lib/pkp/controllers/grid/settings/library/form/NewLibraryFileForm.php(75): PKP\context\LibraryFileDAO->insertObject(Object(PKP\context\LibraryFile))
#9 /home/nate/Projects/pkp/ojs/lib/pkp/controllers/grid/files/LibraryFileGridHandler.php(221): PKP\controllers\grid\settings\library\form\NewLibraryFileForm->execute()
#10 [internal function]: PKP\controllers\grid\files\LibraryFileGridHandler->saveFile(Array, Object(APP\core\Request))
#11 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#12 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#13 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#14 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#15 /home/nate/Projects/pkp/ojs/index.php(21): PKP\core\PKPApplication->execute()
#16 {main}
```

**Comment by NateWr** [comment]
Reopening this because I am still receiving the error with a database downloaded from the dataset at https://github.com/pkp/datasets/commit/082bff7ed0b0507144e5dafbd51dc8b18c0bfec8. That seems to be after this fix.

I haven't yet reproduced it fresh from `main`.

**Comment by asmecher** [comment]
Whoops! Thanks for catching -- this should be fixed now.
