### ISSUE TITLE
authorUserGroups variable isn't assigned to the catalogCategory template

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8684]
**Describe the bug**
Visiting category page results in a fatal error due to missing variable:
```
[::1]:55961 [500]: GET /index.php/publicknowledge/catalog/category/first-category - Uncaught TypeError: PKP\publication\PKPPublication::getAuthorString(): Argument #1 ($userGroups) must be of type Traversable, null given, called in /Users/vitalii/Documents/development/ojs-main/ojs/cache/t_compile/487b610351ebf9d7c64f1869ee8d77745c23a9cb^7cf1cd52b8ba8108de77f197078de34b733dd394_0.app.frontendobjectsarticlesum.php on line 76 and defined in /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/publication/PKPPublication.php:211
Stack trace:
#0 /Users/vitalii/Documents/development/ojs-main/ojs/cache/t_compile/487b610351ebf9d7c64f1869ee8d77745c23a9cb^7cf1cd52b8ba8108de77f197078de34b733dd394_0.app.frontendobjectsarticlesum.php(76): PKP\publication\PKPPublication->getAuthorString(NULL)
#1 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_63f5e72d5aba26_60894366(Object(Smarty_Internal_Template))
#2 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#3 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#4 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#5 /Users/vitalii/Documents/development/ojs-main/ojs/cache/t_compile/487b610351ebf9d7c64f1869ee8d77745c23a9cb^5d0ca16a7c78afd59d26eb1b852e00f92f50a8d9_0.app.frontendpagescatalogCateg.php(107): Smarty_Internal_Template->_subTemplateRender('app:frontend/ob...', NULL, '487b610351ebf9d...', 0, 3600, Array, 0, true)
#6 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_63f5cff7048148_95768535(Object(Smarty_Internal_Template))
#7 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#8 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#9 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 1)
#10 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, '487b610351ebf9d...', NULL, 1)
#11 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/template/PKPTemplateManager.php(1307): Smarty_Internal_TemplateBase->display('frontend/pages/...', NULL, '487b610351ebf9d...', NULL)
#12 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/pages/catalog/PKPCatalogHandler.php(107): PKP\template\PKPTemplateManager->display('frontend/pages/...')
#13 [internal function]: PKP\pages\catalog\PKPCatalogHandler->category(Array, Object(APP\core\Request))
#14 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#15 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPPageRouter.php(308): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#16 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#17 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#18 /Users/vitalii/Documents/development/ojs-main/ojs/index.php(21): PKP\core\PKPApplication->execute()
#19 {main}
  thrown in /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/publication/PKPPublication.php on line 211
```

**To Reproduce**
1. Create a category wit a path `any-category`
2. Make a submission, assign it to this category and publish it
3. Go to the `...catalog/category/any-category`
4. See the fatal error in the log

**What application are you using?**
 OJS main branch

**Comment by Vitaliy-1** [comment]
Likely was forgotten as part of this PR: https://github.com/pkp/ojs/pull/3732

**Comment by asmecher** [comment]
@Vitaliy-1, you're right, I forgot to add it to his part; the PR looks good, and once tests pass I'm OK for it to be merged :+1:
