### ISSUE TITLE
Submission keywords not truncated to column length during indexing

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#8693]
See https://forum.pkp.sfu.ca/t/problem-reindexing-ojs-3-3-0-13/76274:
> I have a problem trying to reindex (php tools/rebuildSearchIndex.php) in a OJS v. 3.3.0-13 portal, it fails at the second journal with the following error.
>
> PHP Fatal error: Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column ‘keyword_text’ at row 1 in /var/www/sitio33/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115
> Stack trace:
> #0 /var/www/sitio33/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(115): PDOStatement->execute(NULL)
> #1 /var/www/sitio33/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(489): Doctrine\DBAL\Driver\PDOStatement->execute()
> #2 /var/www/sitio33/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\Database\Connection->Illuminate\Database{closure}(‘INSERT INTO sub…’, Array)
> #3 /var/www/sitio33/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\Database\Connection->runQueryCallback(‘INSERT INTO sub…’, Array, Object(Closure))
> #4 /var/www/sitio33/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(496): Illuminate\Database\ in /var/www/sitio33/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671

**Comment by asmecher** [comment]
OJS/OMP/OPS 3.3.0-14 and prior can apply https://github.com/pkp/pkp-lib/commit/1824f2d09e49af9d79a303e492cca53f98bb2496 in lib/pkp to resolve this.
