### ISSUE TITLE
[OMP] Error 500 when assigning a cover image to category

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8730]
**Describe the bug**
When creating or editing a category with a cover image, the request returns a 500 error.
The category is created, but the cover image is missing.

```php
PHP Fatal error:  Uncaught Error: Class "PKP\controllers\grid\settings\category\form\Core" not found in /var/www/html/lib/pkp/controllers/grid/settings/category/form/CategoryForm.php:400
Stack trace:
    #0 /var/www/html/lib/pkp/controllers/grid/settings/category/CategoryCategoryGridHandler.php(256): PKP\controllers\grid\settings\category\form\CategoryForm->execute()
#1 [internal function]: PKP\controllers\grid\settings\category\CategoryCategoryGridHandler->updateCategory(Array, Object(APP\core\Request))
#2 /var/www/html/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#3 /var/www/html/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#4 /var/www/html/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#5 /var/www/html/lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#6 /var/www/html/index.php(21): PKP\core\PKPApplication->execute()
#7 {main}
  thrown in /var/www/html/lib/pkp/controllers/grid/settings/category/form/CategoryForm.php on line 400
```

**To Reproduce**
1. Go to Press > Categories
2. Click on Add Category
3. Fill the required fields, include a cover image

**What application are you using?**
OMP 3.4

**PRs**
- https://github.com/pkp/pkp-lib/pull/8764

**Comment by asmecher** [comment]
(Don't forget to include the error message from the log when hitting something like this!)

**Comment by jonasraoni** [comment]
Merged linked PR.
