### ISSUE TITLE
[OJS] Fatal error at web feed

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8731]
**Describe the bug**
```php
PHP Fatal error:  Uncaught Error: Call to undefined method APP\submission\Submission::getAuthorString() in /var/www/html/cache/t_compile/c63ed8b004d376c12e345d3a7af37a01f0be865e^c5a64687d825cbd410323f081b8e13fb7be00543_0.plugins-1-plugins-generic-webFeed-generic-webFeed.rss2.tpl.php:103
Stack trace:
#0 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_63f37c2b1e09a2_28929187(Object(Smarty_Internal_Template))
#1 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#2 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#3 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 1)
#4 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, 'c63ed8b004d376c...', NULL, 1)
#5 /var/www/html/lib/pkp/classes/template/PKPTemplateManager.php(1307): Smarty_Internal_TemplateBase->display('plugins-1-plugi...', NULL, 'c63ed8b004d376c...', NULL)
#6 /var/www/html/plugins/generic/webFeed/WebFeedGatewayPlugin.php(166): PKP\template\PKPTemplateManager->display('plugins-1-plugi...')
#7 /var/www/html/pages/gateway/GatewayHandler.php(210): APP\plugins\generic\webFeed\WebFeedGatewayPlugin->fetch(Array, Object(APP\core\Request))
#8 [internal function]: APP\pages\gateway\GatewayHandler->plugin(Array, Object(APP\core\Request))
#9 /var/www/html/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#10 /var/www/html/lib/pkp/classes/core/PKPPageRouter.php(308): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#11 /var/www/html/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#12 /var/www/html/lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#13 /var/www/html/index.php(21): PKP\core\PKPApplication->execute()
#14 {main}
  thrown in /var/www/html/cache/t_compile/c63ed8b004d376c12e345d3a7af37a01f0be865e^c5a64687d825cbd410323f081b8e13fb7be00543_0.plugins-1-plugins-generic-webFeed-generic-webFeed.rss2.tpl.php on line 103
```

**To Reproduce**
1. Enable the web feed plugin
2. Access the feed

**What application are you using?**
OJS 3.4

**Comment by jonasraoni** [comment]
I've updated the web feed at OMP and OPS recently, so I'll forward the changes I did.
