### ISSUE TITLE
Fatal error at GenreGridHandler

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8735]
**Describe the bug**
I'm unable to delete an item at the Settings > Workflow > Workflow Settings > Components.

```php
PHP Fatal error:  Uncaught Error: Call to undefined method PKP\submissionFile\Collector::count() in /var/www/html/lib/pkp/controllers/grid/settings/genre/GenreGridHandler.php:253
Stack trace:
#0 [internal function]: PKP\controllers\grid\settings\genre\GenreGridHandler->deleteGenre(Array, Object(APP\core\Request))
#1 /var/www/html/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#2 /var/www/html/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#3 /var/www/html/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#4 /var/www/html/lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#5 /var/www/html/index.php(21): PKP\core\PKPApplication->execute()
#6 {main}
```

**What application are you using?**
OJS 3.4

**PRs**
- https://github.com/pkp/pkp-lib/pull/8754
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3818

**Comment by asmecher** [comment]
@jonasraoni, can you include reproduction steps?

**Comment by jonasraoni** [comment]
@asmecher PRs
- https://github.com/pkp/pkp-lib/pull/8754
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3818

**Comment by asmecher** [comment]
Merged, thanks!
