### ISSUE TITLE
[OJS] Error 500 at section form

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8737]
**Describe the bug**
At the section form, the `Editorial Assignments` displays one checkbox for each role that a given user has.

- After selecting at least two roles for the same user, an error happens, but the section is created.
- If you select only one of the available roles for a user, it works, but when you edit the form, all roles are selected (see image B).

**What application are you using?**
OJS 3.4

**Additional information**
![image](https://user-images.githubusercontent.com/361921/222956699-061d867a-9e8f-4d49-a690-db16486aa634.png)
![image](https://user-images.githubusercontent.com/361921/222957012-4d7c0c6d-4fe3-43ca-8301-cacc30db6664.png)

**Comment by touhidurabir** [comment]
Digging deeper into the cause of this issue, it happens mainly because when a single user assigned to multiple group form `Settings --> Users & Roles` . For example , we have a user named `Test Editor 1` and then assigned that user to following user groups 
1. Journal Editor
2. Section Editor
3. Guest Editor

Now for the target section , open the section edit form and try adding that same user to for more than one Editorial assignment and it will cause internal error such as 

```
[07-Mar-2023 10:10:59 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-10-530-38' for key 'subeditor_submission_group.section_editors_pkey' in /Users/abir/Sites/code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:569
Stack trace:
#0 /Users/abir/Sites/code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(569): PDOStatement->execute()
#1 /Users/abir/Sites/code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(752): Illuminate\Database\Connection->Illuminate\Database\{closure}('INSERT INTO sub...', Array)
#2 /Users/abir/Sites/code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(719): Illuminate\Database\Connection->runQueryCallback('INSERT INTO sub...', Array, Object(Closure))
#3 /Users/abir/Sites/code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(576): Illuminate\Database\Connection->run('INSERT INTO sub...', Array, Object(Closure))
#4 /Users/abir/Sites/code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(462): Illuminate\Database\Connection->affectingStatement('INSERT INTO sub...', Array)
#5 /Users/abir/Sites/code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Illuminate\Database\DatabaseManager->__call('affectingStatem...', Array)
#6 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/db/DAO.php(169): Illuminate\Support\Facades\Facade::__callStatic('affectingStatem...', Array)
#7 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/context/SubEditorsDAO.php(58): PKP\db\DAO->update('INSERT INTO sub...', Array)
#8 /Users/abir/Sites/code/ojs-main/lib/pkp/controllers/grid/settings/sections/form/PKPSectionForm.php(181): PKP\context\SubEditorsDAO->insertEditor(1, '10', '38', 530, 5)
#9 /Users/abir/Sites/code/ojs-main/controllers/grid/settings/sections/form/SectionForm.php(193): PKP\controllers\grid\settings\sections\form\PKPSectionForm->execute()
#10 /Users/abir/Sites/code/ojs-main/controllers/grid/settings/sections/SectionGridHandler.php(231): APP\controllers\grid\settings\sections\form\SectionForm->execute()
#11 [internal function]: APP\controllers\grid\settings\sections\SectionGridHandler->updateSection(Array, Object(APP\core\Request))
#12 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#13 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#14 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#15 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#16 /Users/abir/Sites/code/ojs-main/index.php(21): PKP\core\PKPApplication->execute()
#17 /Users/abir/.composer/vendor/laravel/valet/server.php(235): require('/Users/abir/Sit...')
#18 {main}
```
It's mainly due to we have unique index named `section_editors_pkey` in the table `subeditor_submission_group` combined with `4 columns(context_id, assoc_id, assoc_type, user_id)` for which above `Integrity constraint violation` exception is getting thrown . 

@asmecher @NateWr any suggestion to fix it ? We can add the `user_group_id` column to generate the `section_editors_pkey` unique index which will solve it. Or we can not allow to select one single user for more than one `Editorial Assignment` . But none of these seems like the best way to handle it .

**Comment by NateWr** [comment]
Thanks @touhidurabir. I think adding `user_group_id` to the unique index is correct. An editorial user should be able to be assigned to submissions to a section in multiple user groups.

**Comment by touhidurabir** [comment]
@asmecher PRs to review

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8769
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3824

Once we finalise, this need to be ported to both `OMP` and `OPS` as this problem exists there as I have tested .

**Comment by asmecher** [comment]
Thanks, @touhidurabir, I've reviewed the PRs [here].(https://github.com/pkp/pkp-lib/pull/8769#pullrequestreview-1335236416).

**Comment by touhidurabir** [comment]
@asmecher see all the PRs at https://github.com/pkp/pkp-lib/issues/8737#issue-1610157439

**Comment by asmecher** [comment]
Thanks, @touhidurabir -- the app PRs all look good, I've just added a few more comments to the pkp-lib PR.
