### ISSUE TITLE
Fatal error when deleting journal from OJS 3.4.0

### ISSUE THREAD

**Issue by janiosarmento** [pkp/pkp-lib#8744]
**Describe the bug**
Deleting a journal from the installation results in an internal error 500 due to a fatal PHP error:

```
PHP Fatal error:  Uncaught Error: Call to undefined method APP\\section\\Repository::deleteByContextId() in /var/www/html/classes/services/ContextService.php:165
Stack trace:
#0 [internal function]: APP\\services\\ContextService->afterDeleteContext('Context::delete', Array)
#1 /var/www/html/lib/pkp/classes/plugins/Hook.php(139): call_user_func_array(Array, Array)
#2 /var/www/html/lib/pkp/classes/plugins/Hook.php(112): PKP\\plugins\\Hook::run('Context::delete', Array)\
#3 /var/www/html/lib/pkp/classes/services/PKPContextService.php(634): PKP\\plugins\\Hook::call('Context::delete', Array)
#4 /var/www/html/lib/pkp/controllers/grid/admin/context/ContextGridHandler.php(288): PKP\\services\\PKPContextService->delete(Object(APP\\journal\\Journal))
#5 [internal function]: PKP\\controllers\\grid\\admin\\context\\ContextGridHandler->deleteContext(Array, Object(APP\\core\\Request))
#6 /var/www/html/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\\core\\Request))
#7 /var/www/html/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\\core\\Request), Array)
#8 /var/www/html/lib/pkp/classes/core/Dispatcher.php(163): PKP\\core\\PKPComponentRouter->route(Object(APP\\core\\Request))
#9 /var/www/html/lib/pkp/classes/core/PKPApplication.php(372): PKP\\core\\Dispatcher->dispatch(Object(APP\\core\\Request))
#10 /var/www/html/index.php(21): PKP\\core\\PKPApplication->execute()\n#11 {main}\n  thrown in /var/www/html/classes/services/ContextService.php on line 165, referer: https://ojs.testing.publicknowledgeproject.org/
```

**To Reproduce**

1. Go to `/index.php/index/admin/contexts`
2. Click on the chevron besides the journal you want to delete, to open it's contextual menu
3. Open the browser's development console, go to the Network tab
4. Click on Remove to delete the journal
5. Click OK on the confirmation modal
6. Watch the request on the Developer Tools: it will finish with the HTTP status 500
7. Look at PHP error log

**What application are you using?**
OJS 3.4.0

**Comment by asmecher** [comment]
Looks good, @touhidurabir; does this need porting to OMP/OPS as well?

**Comment by touhidurabir** [comment]
> does this need porting to OMP/OPS as well?

@asmecher not really , it's only the `pkp-lib` submodule update that matters . The changes I did for `OJS` is adding some `@var` doc blocks so we can omit it .

**Comment by asmecher** [comment]
Great, thanks!

**Comment by jonasraoni** [comment]
@asmecher The PRs for this issue were not merged :)
I've merged the one for `pkp-lib`, and closed the one for OJS (the same updates were covered by another PR).

**Comment by asmecher** [comment]
Whoops, thanks for catching that!
