### ISSUE TITLE
[CitationStyleLanguage] Unable to access plugin settings

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8757]
**Describe the bug**
Unable to access the settings of the citation style language plugin

```php
PHP Fatal error:  Uncaught AssertionError: assert(isset($params['id'])) in C:\work\pkp\ojs\lib\pkp\classes\form\FormBuilderVocabulary.php:133
Stack trace:
#0 C:\work\pkp\ojs\lib\pkp\classes\form\FormBuilderVocabulary.php(133): assert(false, 'assert(isset($p...')
#1 C:\work\pkp\ojs\cache\t_compile\d2d7b7a9723f6cd9a3c8858d97582a0ea9072dd0^d3a2d093227a03d8bc90f1a883edfcc42a293798_0.plugins-1-plugins-generic-citationStyleLanguage-generic-citationStyleLanguage.settings.tpl.php(138): PKP\form\FormBuilderVocabulary->smartyFBVFormArea(Array, NULL, Object(Smarty_Internal_Template), true)
#2 C:\work\pkp\ojs\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\smarty_template_resource_base.php(123): content_64073fbdc537c5_30619757(Object(Smarty_Internal_Template))
#3 C:\work\pkp\ojs\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#4 C:\work\pkp\ojs\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#5 C:\work\pkp\ojs\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 0)
#6 C:\work\pkp\ojs\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, 'd2d7b7a9723f6cd...', NULL, 0)
#7 C:\work\pkp\ojs\lib\pkp\classes\template\PKPTemplateManager.php(1173): Smarty_Internal_TemplateBase->fetch('plugins-1-plugi...', NULL, 'd2d7b7a9723f6cd...', NULL)
#8 C:\work\pkp\ojs\lib\pkp\classes\form\Form.php(216): PKP\template\PKPTemplateManager->fetch('plugins-1-plugi...')
#9 C:\work\pkp\ojs\plugins\generic\citationStyleLanguage\CitationStyleLanguageSettingsForm.php(133): PKP\form\Form->fetch(Object(APP\core\Request), NULL, false)
#10 C:\work\pkp\ojs\plugins\generic\citationStyleLanguage\CitationStyleLanguagePlugin.php(708): APP\plugins\generic\citationStyleLanguage\CitationStyleLanguageSettingsForm->fetch(Object(APP\core\Request))
#11 C:\work\pkp\ojs\lib\pkp\classes\controllers\grid\plugins\PluginGridHandler.php(278): APP\plugins\generic\citationStyleLanguage\CitationStyleLanguagePlugin->manage(Array, Object(APP\core\Request))
#12 [internal function]: PKP\controllers\grid\plugins\PluginGridHandler->manage(Array, Object(APP\core\Request))
#13 C:\work\pkp\ojs\lib\pkp\classes\core\PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#14 C:\work\pkp\ojs\lib\pkp\classes\core\PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#15 C:\work\pkp\ojs\lib\pkp\classes\core\Dispatcher.php(163): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#16 C:\work\pkp\ojs\lib\pkp\classes\core\PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#17 C:\work\pkp\ojs\index.php(21): PKP\core\PKPApplication->execute()
#18 {main}
  thrown in C:\work\pkp\ojs\lib\pkp\classes\form\FormBuilderVocabulary.php on line 133
```

**To Reproduce**
1. Enable the plugin
2. Access its settings

**What application are you using?**
OJS 3.4.0rc1

**PRs**
- https://github.com/pkp/citationStyleLanguage/pull/106

**Comment by jonasraoni** [comment]
@asmecher PR
- https://github.com/pkp/citationStyleLanguage/pull/106

**Comment by asmecher** [comment]
Merged, thanks!
