### ISSUE TITLE
Locale issues at the migrations

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8766]
**Describe the bug**
There are a couple of issues at the database migration for OPS/OMP/OJS related to the recent merge of localization files, example below:

```php
InvalidArgumentException: Invalid/unsupported locale "en_US", default locale restored in /home/travis/build/pkp/omp/lib/pkp/classes/i18n/Locale.php:140
Stack trace:
#0 /home/travis/build/pkp/omp/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): PKP\i18n\Locale->setLocale('en_US')
#1 /home/travis/build/pkp/omp/lib/pkp/classes/migration/upgrade/v3_4_0/I7191_SubmissionChecklistMigration.php(68): Illuminate\Support\Facades\Facade::__callStatic('setLocale', Array)
#2 /home/travis/build/pkp/omp/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(264): PKP\migration\upgrade\v3_4_0\I7191_SubmissionChecklistMigration->PKP\migration\upgrade\v3_4_0\{closure}(Object(stdClass), 0)
#3 /home/travis/build/pkp/omp/lib/pkp/classes/migration/upgrade/v3_4_0/I7191_SubmissionChecklistMigration.php(84): Illuminate\Support\Collection->each(Object(Closure))
#4 /home/travis/build/pkp/omp/lib/pkp/classes/install/Installer.php(461): PKP\migration\upgrade\v3_4_0\I7191_SubmissionChecklistMigration->up()
#5 /home/travis/build/pkp/omp/lib/pkp/classes/install/Installer.php(290): PKP\install\Installer->executeAction(Array)
#6 /home/travis/build/pkp/omp/lib/pkp/classes/install/Installer.php(205): PKP\install\Installer->executeInstaller()
#7 /home/travis/build/pkp/omp/lib/pkp/classes/cliTool/UpgradeTool.php(95): PKP\install\Installer->execute()
#8 /home/travis/build/pkp/omp/lib/pkp/classes/cliTool/UpgradeTool.php(68): PKP\cliTool\UpgradeTool->upgrade()
#9 /home/travis/build/pkp/omp/tools/upgrade.php(21): PKP\cliTool\UpgradeTool->execute()
#10 {main}
```

**What application are you using?**
OMP 3.4.0rc1

**Comment by jonasraoni** [comment]
Perhaps moving up the migration which updates/merges the locale keys at the database is enough, I'll check 🤔

**Comment by jonasraoni** [comment]
@asmecher PRs
- https://github.com/pkp/pkp-lib/pull/8767
- https://github.com/pkp/omp/pull/1363
- https://github.com/pkp/ops/pull/490

**Comment by asmecher** [comment]
@defstat, could you review the above PRs?

**Comment by defstat** [comment]
@asmecher @jonasraoni The changes look ok to me.

**Comment by jonasraoni** [comment]
Thanks @defstat, I've merged the linked PRs.
