### ISSUE TITLE
Error 500 while trying to open a book as anonymous on OMP 3.4 RC

### ISSUE THREAD

**Issue by joshnoronha** [pkp/pkp-lib#8773]
**Describe the bug**
Clicking on a book on homepage, as anonymous, leads to 500 error.

**To Reproduce**
1. Click on a book, opens error 500 blank page

**What application are you using?**
 OMP 3.4.0 RC

**Additional information**
Error log:

```
PHP Fatal error:  Uncaught Exception: Unrecognized DAO SeriesDAO! in /var/www/html/lib/pkp/classes/db/DAORegistry.php:77
Stack trace:
#0 /var/www/html/plugins/generic/citationStyleLanguage/CitationStyleLanguagePlugin.php(776): PKP\db\DAORegistry::getDAO('SeriesDAO')
#1 /var/www/html/plugins/generic/citationStyleLanguage/CitationStyleLanguagePlugin.php(459): APP\plugins\generic\citationStyleLanguage\CitationStyleLanguagePlugin->addSeriesInformation(Object(stdClass), Object(APP\publication\Publication))
#2 /var/www/html/plugins/generic/citationStyleLanguage/CitationStyleLanguagePlugin.php(338): APP\plugins\generic\citationStyleLanguage\CitationStyleLanguagePlugin->getCitation(Object(APP\core\Request), Object(APP\submission\Submission), 'apa', NULL, Object(APP\publication\Publication))
#3 [internal function]: APP\plugins\generic\citationStyleLanguage\CitationStyleLanguagePlugin->getTemplateData('CatalogBookHand...', Array)
#4 /var/www/html/lib/pkp/classes/plugins/Hook.php(139): call_user_func_array(Array, Array)
#5 /var/www/html/lib/pkp/classes/plugins/Hook.php(112): PKP\plugins\Hook::run('CatalogBookHand...', Array)
#6 /var/www/html/pages/catalog/CatalogBookHandler.php(291): PKP\plugins\Hook::call('CatalogBookHand...', Array)
#7 [internal function]: APP\pages\catalog\CatalogBookHandler->book(Array, Object(APP\core\Request))
#8 /var/www/html/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#9 /var/www/html/lib/pkp/classes/core/PKPPageRouter.php(308): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#10 /var/www/html/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#11 /var/www/html/lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#12 /var/www/html/index.php(21): PKP\core\PKPApplication->execute()
#13 {main}
  thrown in /var/www/html/lib/pkp/classes/db/DAORegistry.php on line 77
```

**Comment by jonasraoni** [comment]
@asmecher
- https://github.com/pkp/citationStyleLanguage/pull/109

**Comment by asmecher** [comment]
Merged, thanks!
