### ISSUE TITLE
[OJS] Fatal error at the ArticleReportPlugin

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8774]
**Describe the bug**
When generating the article report, it comes out empty, at the error log there's the entry below:

```php
PHP Fatal error:  Uncaught TypeError: PKP\section\Repository::get(): Argument #1 ($id) must be of type int, null given, called in /var/www/html/plugins/reports/articles/ArticleReportPlugin.php on line 151 and defined in /var/www/html/lib/pkp/classes/section/Repository.php:59
Stack trace:
#0 /var/www/html/plugins/reports/articles/ArticleReportPlugin.php(151): PKP\section\Repository->get(NULL)
#1 /var/www/html/lib/pkp/pages/stats/PKPStatsHandler.php(546): APP\plugins\reports\articles\ArticleReportPlugin->display(Array, Object(APP\core\Request))
#2 /var/www/html/lib/pkp/pages/stats/PKPStatsHandler.php(494): PKP\pages\stats\PKPStatsHandler->report(Array, Object(APP\core\Request))
#3 [internal function]: PKP\pages\stats\PKPStatsHandler->reports(Array, Object(APP\core\Request))
#4 /var/www/html/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#5 /var/www/html/lib/pkp/classes/core/PKPPageRouter.php(308): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#6 /var/www/html/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#7 /var/www/html/lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#8 /var/www/html/index.php(21): PKP\core\PKPApplication->execute()
#9 {main}
  thrown in /var/www/html/lib/pkp/classes/section/Repository.php on line 59
```

**To Reproduce**
1. Setup some basic data at the installation
2. Ensure one of the submissions doesn't have a section (still trying to guess how it happened)
3. Access the report

**What application are you using?**
OJS 3.4.0rc1

**Comment by jonasraoni** [comment]
@asmecher This one smells strange, someone found a way to create a submission without a section OR the section was updated along the way and lost...
PR
- https://github.com/pkp/ojs/pull/3826

**Comment by asmecher** [comment]
Merged, thanks!
