### ISSUE TITLE
[OJS] Fatal error at the counter report

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8775]
**Describe the bug**
When attempting to generate the counter report, a fatal error happens.

```php
PHP Fatal error:  Uncaught Error: Class "CounterReportJR1" not found in /var/www/html/plugins/reports/counter/CounterReportPlugin.php:111
Stack trace:
#0 /var/www/html/plugins/reports/counter/CounterReportPlugin.php(159): APP\\plugins\\reports\\counter\\CounterReportPlugin->getReporter('JR1', '4.1')
#1 /var/www/html/lib/pkp/pages/stats/PKPStatsHandler.php(546): APP\\plugins\\reports\\counter\\CounterReportPlugin->display(Array, Object(APP\\core\\Request))
#2 /var/www/html/lib/pkp/pages/stats/PKPStatsHandler.php(494): PKP\\pages\\stats\\PKPStatsHandler->report(Array, Object(APP\\core\\Request))
#3 [internal function]: PKP\\pages\\stats\\PKPStatsHandler->reports(Array, Object(APP\\core\\Request))
#4 /var/www/html/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\\core\\Request))
#5 /var/www/html/lib/pkp/classes/core/PKPPageRouter.php(308): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\\core\\Request), Array, false)
#6 /var/www/html/lib/pkp/classes/core/Dispatcher.php(163): PKP\\core\\PKPPageRouter->route(Object(APP\\core\\Request))
#7 /var/www/html/lib/pkp/classes/core/PKPApplication.php(372): PKP\\core\\Dispatcher->dispatch(Object(APP\\core\\Request))
#8 /var/www/html/index.php(21): PKP\\core\\PKPApplication->execute()
#9 {main}
  thrown in /var/www/html/plugins/reports/counter/CounterReportPlugin.php on line 111
```

**To Reproduce**
1. Go to Reports > COUNTER Reports
2. Select any report

**What application are you using?**
OJS 3.4.0rc1

**PRs**
- https://github.com/pkp/ojs/pull/3827

**Comment by jonasraoni** [comment]
@asmecher PR
- https://github.com/pkp/ojs/pull/3827

**Comment by asmecher** [comment]
@bozana, could you have a look at the PR? I'm not sure what the relationship is between the old COUNTER reports and the new R5 stuff.
