### ISSUE TITLE
Fatal error when inserting a library file

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8784]
**Describe the bug**
```php
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'submission_id' cannot be null in /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:569
Stack trace:
#0 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(569): PDOStatement->execute()
#1 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(752): Illuminate\Database\Connection->Illuminate\Database\{closure}('INSERT INTO lib...', Array)
#2 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(719): Illuminate\Database\Connection->runQueryCallback('INSERT INTO lib...', Array, Object(Closure))
#3 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(576): Illuminate\Database\Connection->run('INSERT INTO lib...', Array, Object(Closure))
#4 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(462): Illuminate\Database\Connection->affectingStatement('INSERT INTO lib...', Array)
#5 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Illuminate\Database\DatabaseManager->__call('affectingStatem...', Array)
#6 /var/www/html/lib/pkp/classes/db/DAO.php(169): Illuminate\Support\Facades\Facade::__callStatic('affectingStatem...', Array)
#7 /var/www/html/lib/pkp/classes/context/LibraryFileDAO.php(189): PKP\db\DAO->update('INSERT INTO lib...', Array)
#8 /var/www/html/lib/pkp/controllers/grid/settings/library/form/NewLibraryFileForm.php(75): PKP\context\LibraryFileDAO->insertObject(Object(PKP\context\LibraryFile))
#9 /var/www/html/lib/pkp/controllers/grid/files/LibraryFileGridHandler.php(221): PKP\controllers\grid\settings\library\form\
ewLibraryFileForm->execute()
#10 [internal function]: PKP\controllers\grid\files\LibraryFileGridHandler->saveFile(Array, Object(APP\core\Request))
#11 /var/www/html/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#12 /var/www/html/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#13 /var/www/html/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#14 /var/www/html/lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#15 /var/www/html/index.php(21): PKP\core\PKPApplication->execute()
#16 {main}
```

**To Reproduce**
1. Go to a submission
2. Access the files library through the `Library` button at the top
3. Insert a file

**What application are you using?**
OJS 3.4.0rc1

**Comment by asmecher** [comment]
@jonasraoni, is this a duplicate of https://github.com/pkp/pkp-lib/issues/8668? If you created your database before it was fixed, recreating the DB should fix it.

**Comment by jonasraoni** [comment]
Closed as duplicate of https://github.com/pkp/pkp-lib/issues/8668.
