### ISSUE TITLE
Fatal error at reset permissions

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8789]
**Describe the bug**
A fatal error happens when trying to reset the permissions.

```php
PHP Fatal error:  Uncaught BadMethodCallException: Method Illuminate\\Support\\LazyCollection::next does not exist. in /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113
Stack trace:
#0 /var/www/html/lib/pkp/classes/submission/Repository.php(669): Illuminate\\Support\\LazyCollection->__call('next', Array)
#1 /var/www/html/lib/pkp/pages/management/PKPToolsHandler.php(142): PKP\\submission\\Repository->resetPermissions(1)
#2 /var/www/html/lib/pkp/pages/management/PKPToolsHandler.php(63): PKP\\pages\\management\\PKPToolsHandler->resetPermissions(Array, Object(APP\\core\\Request))
#3 [internal function]: PKP\\pages\\management\\PKPToolsHandler->tools(Array, Object(APP\\core\\Request))
#4 /var/www/html/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\\core\\Request))
#5 /var/www/html/lib/pkp/classes/core/PKPPageRouter.php(308): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\\core\\Request), Array, false)
#6 /var/www/html/lib/pkp/classes/core/Dispatcher.php(163): PKP\\core\\PKPPageRouter->route(Object(APP\\core\\Request))
#7 /var/www/html/lib/pkp/classes/core/PKPApplication.php(372): PKP\\core\\Dispatcher->dispatch(Object(APP\\core\\Request))
#8 /var/www/html/index.php(21): PKP\\core\\PKPApplication->execute()
#9 {main}
  thrown in /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php on line 113, referer: https://omp.testing.publicknowledgeproject.org/
```

**To Reproduce**
1. Access the Tools > Permissions
2. Attempt to reset the permissions

**What application are you using?**
OMP 3.4.0rc1

**PRs**
- https://github.com/pkp/pkp-lib/pull/8790
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3829

**Comment by jonasraoni** [comment]
@asmecher PRs
- https://github.com/pkp/pkp-lib/pull/8790
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3829

**Comment by asmecher** [comment]
Merged, thanks!
