### ISSUE TITLE
[OJS] PubMed XML Export Plugin is generating invalid output

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8791]
**Describe the bug**
When exporting a submission through the PubMedExportPlugin, there's a warning on the screen saying the DTD validation failed.

```php
Filter output validation failed, expected "dtd", but found "object", referer: https://ojs.testing.publicknowledgeproject.org/

PHP Fatal error:  Uncaught Exception: Could not convert selected objects. in /var/www/html/lib/pkp/classes/plugins/ImportExportPlugin.php:239
Stack trace:
#0 /var/www/html/plugins/importexport/pubmed/PubMedExportPlugin.php(165): PKP\plugins\ImportExportPlugin->displayXMLValidationErrors(Array, '<?xml version="...')
#1 /var/www/html/plugins/importexport/pubmed/PubMedExportPlugin.php(111): APP\plugins\importexport\pubmed\PubMedExportPlugin->exportSubmissions(Array, Object(APP\journal\Journal), Object(PKP\user\User))
#2 /var/www/html/lib/pkp/pages/management/PKPToolsHandler.php(100): APP\plugins\importexport\pubmed\PubMedExportPlugin->display(Array, Object(APP\core\Request))
#3 [internal function]: PKP\pages\management\PKPToolsHandler->importexport(Array, Object(APP\core\Request))
#4 /var/www/html/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#5 /var/www/html/lib/pkp/classes/core/PKPPageRouter.php(308): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#6 /var/www/html/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#7 /var/www/html/lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#8 /var/www/html/index.php(21): PKP\core\PKPApplication->execute()
#9 {main}
  thrown in /var/www/html/lib/pkp/classes/plugins/ImportExportPlugin.php on line 239
```

**To Reproduce**
1. Go to Tools > Import/Export > PubMed XML Export Plugin
2. Try to export a submission

**What application are you using?**
OJS 3.4.0rc1

**Comment by asmecher** [comment]
@ewhanson or @bozana, could you have a look?

**Comment by ewhanson** [comment]
@asmecher, happy to!

**Comment by bozana** [comment]
This happens when one tries to export articles that are not published yet. It seems it is also a problem in the stable release/branch. 

The validation message is:
`Element Journal content does not follow the DTD, expecting (PublisherName , JournalTitle , Issn , Volume? , Issue? , PubDate), got (PublisherName JournalTitle Issn)`

And an example invalid XML:
```
<?xml version="1.0"?>
<!DOCTYPE ArticleSet PUBLIC "-//NLM//DTD PubMed 2.0//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/static/PubMed.dtd">
<ArticleSet>
  <Article>
    <Journal>
      <PublisherName>Public Knowledge Project</PublisherName>
      <JournalTitle>Journal of Public Knowledge</JournalTitle>
      <Issn>0378-5955</Issn>
    </Journal>
    <ArticleTitle>Finocchiaro: Arguments About Arguments</ArticleTitle>
    <Language>eng</Language>
    <AuthorList>
      <Author>
        <FirstName>Zita</FirstName>
        <LastName>Woods</LastName>
        <Affiliation>CUNY. zwoods@mailinator.com</Affiliation>
      </Author>
    </AuthorList>
    <History>
      <PubDate PubStatus="received">
        <Year>2022</Year>
        <Month>02</Month>
        <Day>20</Day>
      </PubDate>
      <PubDate PubStatus="accepted">
        <Year>2023</Year>
        <Month>02</Month>
        <Day>20</Day>
      </PubDate>
    </History>
    <Abstract>None.</Abstract>
  </Article>
</ArticleSet>
```

Shell not published articles be available for export at all?

**Comment by bozana** [comment]
We have just discussed on the dev call that this is OK to be so -- to display the validation error message when user tries to export an unpublished articles, rather then to exclude those articles from the list.
The published articles export works correctly.
Thus, closing...
