### ISSUE TITLE
Error when creating generic notification

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8797]
**Describe the bug**
It's not possible to create a generic notification through the `createTrivialNotification()`, it's using the `\PKP\core\PKPApplication::CONTEXT_ID_NONE` as context, which in the end gets translated to null and fails a NOT NULL field constraint.

```php
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'context_id' cannot be null in lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php:569
Stack trace:
#0 lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(569): PDOStatement->execute()
#1 lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(752): Illuminate\Database\Connection->Illuminate\Database\{closure}('INSERT INTO not...', Array)
#2 lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(719): Illuminate\Database\Connection->runQueryCallback('INSERT INTO not...', Array, Object(Closure))
#3 lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php(576): Illuminate\Database\Connection->run('INSERT INTO not...', Array, Object(Closure))
#4 lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(462): Illuminate\Database\Connection->affectingStatement('INSERT INTO not...', Array)
#5 lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(337): Illuminate\Database\DatabaseManager->__call('affectingStatem...', Array)
#6 lib\pkp\classes\db\DAO.php(169): Illuminate\Support\Facades\Facade::__callStatic('affectingStatem...', Array)
#7 lib\pkp\classes\notification\NotificationDAO.php(148): PKP\db\DAO->update('INSERT INTO not...', Array)
#8 lib\pkp\classes\notification\PKPNotificationOperationManager.php(203): PKP\notification\NotificationDAO->insertObject(Object(APP\notification\Notification))
#9 controllers\grid\settings\series\SeriesGridHandler.php(262): PKP\notification\PKPNotificationOperationManager->createTrivialNotification(1)
#10 [internal function]: APP\controllers\grid\settings\series\SeriesGridHandler->updateSeries(Array, Object(APP\core\Request))
#11 lib\pkp\classes\core\PKPRouter.php(328): call_user_func(Array, Array, Object(APP\core\Request))
#12 lib\pkp\classes\core\PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#13 lib\pkp\classes\core\Dispatcher.php(163): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#14 lib\pkp\classes\core\PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#15 index.php(21): PKP\core\PKPApplication->execute()
#16 {main}
```

**To Reproduce**
1. Run anything that generates a notification (e.g. edit a section)

**What application are you using?**
OMP 3.4.0rc1

**Comment by jonasraoni** [comment]
This has been fixed 2 days ago, closing.
