### ISSUE TITLE
[OPS][returningAuthorScreening] Fatal error when trying to repost a published preprint 

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8810]
**Describe the bug**
@rcgillis flagged this bug while trying to repost a preprint after publishing it.

I found two related entries at the log (which means this plugin probably wasn't updated to work with OPS 3.4):

```php
PHP Fatal error:  Uncaught Pimple\Exception\UnknownIdentifierException: Identifier "submission" is not defined. in /var/www/html/lib/pkp/lib/vendor/pimple/pimple/src/Pimple/Container.php:105
Stack trace:
    #0 /var/www/html/lib/pkp/classes/core/PKPServices.php(82): Pimple\Container->offsetGet('submission')
#1 /var/www/html/lib/pkp/classes/core/PKPServices.php(60): PKP\core\PKPServices->_getFromContainer('submission')
#2 /var/www/html/plugins/generic/returningAuthorScreening/ReturningAuthorScreeningPlugin.inc.php(173): PKP\core\PKPServices::get('submission')
#3 /var/www/html/plugins/generic/returningAuthorScreening/ReturningAuthorScreeningPlugin.inc.php(156): ReturningAuthorScreeningPlugin->_hasPublishedBefore(3, 1)
#4 /var/www/html/plugins/generic/returningAuthorScreening/ReturningAuthorScreeningPlugin.inc.php(142): ReturningAuthorScreeningPlugin->applyRules(3, 1, 3)
#5 [internal function]: ReturningAuthorScreeningPlugin->validateTest('Publication::te...', Array)
#6 /var/www/html/lib/pkp/classes/plugins/Hook.php(139): call_user_func_array(Array, Array)
#7 /var/www/html/lib/pkp/classes/plugins/Hook.php(112): PKP\plugins\Hook::run('Publication::te...', Array)
#8 /var/www/html/controllers/tab/workflow/WorkflowTabHandler.php(45): PKP\plugins\Hook::call('Publication::te...', Array)
#9 [internal function]: APP\controllers\tab\workflow\WorkflowTabHandler->fetchTab(Array, Object(APP\core\Request))
#10 /var/www/html/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#11 /var/www/html/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#12 /var/www/html/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#13 /var/www/html/lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#14 /var/www/html/index.php(21): PKP\core\PKPApplication->execute()
#15 {main}
  thrown in /var/www/html/lib/pkp/lib/vendor/pimple/pimple/src/Pimple/Container.php on line 105
```

```php
PHP Fatal error:  Uncaught Exception: DAOResultFactory instances cannot be counted unless supplied in constructor (DAO PKP\stageAssignment\StageAssignmentDAO)! in /var/www/html/lib/pkp/classes/db/DAOResultFactory.php:133
Stack trace:
#0 /var/www/html/lib/pkp/classes/db/DAOResultFactory.php(212): PKP\db\DAOResultFactory->getCount()
#1 /var/www/html/plugins/generic/returningAuthorScreening/ReturningAuthorScreeningPlugin.inc.php(200): PKP\db\DAOResultFactory->wasEmpty()
#2 /var/www/html/plugins/generic/returningAuthorScreening/ReturningAuthorScreeningPlugin.inc.php(114): ReturningAuthorScreeningPlugin->_isAuthor(1, 3)
#3 [internal function]: ReturningAuthorScreeningPlugin->validate('Publication::va...', Array)
#4 /var/www/html/lib/pkp/classes/plugins/Hook.php(139): call_user_func_array(Array, Array)
#5 /var/www/html/lib/pkp/classes/plugins/Hook.php(112): PKP\plugins\Hook::run('Publication::va...', Array)
#6 /var/www/html/lib/pkp/classes/publication/Repository.php(264): PKP\plugins\Hook::call('Publication::va...', Array)
#7 /var/www/html/classes/publication/Repository.php(128): PKP\publication\Repository->validatePublish(Object(APP\publication\Publication), Object(APP\submission\Submission), Array, 'en')
#8 /var/www/html/lib/pkp/controllers/modals/publish/PublishHandler.php(98): APP\publication\Repository->validatePublish(Object(APP\publication\Publication), Object(APP\submission\Submission), Array, 'en')
#9 [internal function]: PKP\controllers\modals\publish\PublishHandler->publish(Array, Object(APP\core\Request))
#10 /var/www/html/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#11 /var/www/html/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#12 /var/www/html/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#13 /var/www/html/lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#14 /var/www/html/index.php(21): PKP\core\PKPApplication->execute()
#15 {main}
  thrown in /var/www/html/lib/pkp/classes/db/DAOResultFactory.php on line 133
```

**What application are you using?**
OPS 3.4.0rc1

**Comment by asmecher** [comment]
This plugin just needs updating for 3.4.0. I've added it to the list: https://github.com/pkp/pkp-lib/issues/8338

**Comment by ajnyga** [comment]
Fyi I am working on this.
