### ISSUE TITLE
View article page blank

### ISSUE THREAD

**Issue by ramli01** [pkp/pkp-lib#8947]
**Describe the bug**
Blank page when open view article page.

**To Reproduce**
1. Go to 'Issue Page'
2. Click on 'the title of published article'
3. Result 'Blank page'

**What application are you using?**
 OJS RC3 3.4

**Additional information**
Testing OJS RC3. Successfuly installed.
1. Trying quickSubmit plugin for one article to a published issue (success with pdf galley)
2. Trying submission by accepting without review process and assigned into a published issue (success with pdf galley).
3. View the article by going to issue, clicking on the article and resulting blank page.
4. Viewing galley by clicking the Pdf link on Table of content and the pdf is successfully loaded.
5. Error log list a php fatal error related to generic plugin recommendBySimilalrityPlugin (which is enabled)
6. Go to setting->website->plugins and disable the  plugin. Reload the artivle view page and the page is succesfully loaded.

Note. Php version 8.1.18 and. Linux OS

**Comment by jonasraoni** [comment]
Hi @ramli01, could you please include the complete fatal error message?

I think the error will be fixed here https://github.com/pkp/pkp-lib/issues/8710, but I'd like to confirm.

**Comment by ramli01** [comment]
Here is the logged errors:

2023-04-28 12:49:32.019555 [NOTICE] [899877] [T0] [182.1.177.214:35362:HTTP2-59#APVH_ram:443] [STDERR] PHP Fatal error:  Uncaught Error: Class "APP\plugins\generic\recommendBySimilarity\Handler" not found in /home/ram/public_html/ojsrct/plugins/generic/recommendBySimilarity/RecommendBySimilarityPlugin.php:93\nStack trace:\n#0 [internal function]: APP\plugins\generic\recommendBySimilarity\RecommendBySimilarityPlugin->callbackTemplateArticlePageFooter()\n#1 /home/ram/public_html/ojsrct/lib/pkp/classes/plugins/Hook.php(139): call_user_func_array()\n#2 /home/ram/public_html/ojsrct/lib/pkp/classes/plugins/Hook.php(112): PKP\plugins\Hook::run()\n#3 /home/ram/public_html/ojsrct/lib/pkp/classes/template/PKPTemplateManager.php(1735): PKP\plugins\Hook::call()\n#4 /home/ram/public_html/ojsrct/cache/t_compile/42362804174f266c598cdb32c3208fc745b92101^1c372c95cd85572e0fbc9a53d0323a0b229cfc78_0.app.frontendpagesarticle.tpl.php(43): PKP\template\PKPTemplateManager->smartyCallHook()\n#5 /home/ram/public_html/ojsrct/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_644b5e68955c50_88629290()\n#6 /home/ram/public_html/ojsrct/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()\n#7 /home/ram/public_html/ojsrct/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render()\n#8 /home/ram/public_html/ojsrct/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render()\n#9 /home/ram/public_html/ojsrct/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute()\n#10 /home/ram/public_html/ojsrct/lib/pkp/classes/template/PKPTemplateManager.php(1320): Smarty_Internal_TemplateBase->display()\n#11 /home/ram/public_html/ojsrct/pages/article/ArticleHandler.php(357): PKP\template\PKPTemplateManager->display()\n#12 [internal function]: APP\pages\article
2023-04-28 12:49:32.019586 [NOTICE] [899877] [T0] [182.1.177.214:35362:HTTP2-59#APVH_ram:443] [STDERR] \ArticleHandler->view()\n#13 /home/ram/public_html/ojsrct/lib/pkp/classes/core/PKPRouter.php(333): call_user_func()\n#14 /home/ram/public_html/ojsrct/lib/pkp/classes/core/PKPPageRouter.php(278): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()\n#15 /home/ram/public_html/ojsrct/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter->route()\n#16 /home/ram/public_html/ojsrct/lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch()\n#17 /home/ram/public_html/ojsrct/index.php(21): PKP\core\PKPApplication->execute()\n#18 {main}\n  thrown in /home/ram/public_html/ojsrct/plugins/generic/recommendBySimilarity/RecommendBySimilarityPlugin.php on line 93\n
2023-04-28 12:49:34.660014 [NOTICE] [899877] [T0] [182.1.177.214:35362:HTTP2-61#APVH_ram:443] [STDERR] PHP Warning:  Trying to access array offset on value of type null in /home/ram/public_html/ojsrct/plugins/themes/default/DefaultThemePlugin.php on line 187\n
2023-04-28 12:49:36.459741 [NOTICE] [899877] [T0] [182.1.177.214:35362:HTTP2-63#APVH_ram:443] [STDERR] PHP Warning:  Trying to access array offset on value of type null in /home/ram/public_html/ojsrct/plugins/themes/default/DefaultThemePlugin.php on line 187\n
2023-04-28 12:49:38.511182 [NOTICE] [899877] [T0] [182.1.177.214:35362:HTTP2-97#APVH_ram:443] [STDERR] PHP Warning:  Trying to access array offset on value of type null in /home/ram/public_html/ojsrct/plugins/themes/default/DefaultThemePlugin.php on line 187\n
2023-04-28 12:49:45.972778 [NOTICE] [899877] [T0] [182.1.177.214:35362:HTTP2-105#APVH_ram:443] [STDERR] PHP Warning:  Trying to access array offset on value of type null in /home/ram/public_html/ojsrct/plugins/themes/default/DefaultThemePlugin.php on line 187\n

**Comment by jonasraoni** [comment]
Thanks! I'll close this issue in favor of https://github.com/pkp/pkp-lib/issues/8710, which is just waiting for a review.

**Comment by jonasraoni** [comment]
Fixed by https://github.com/pkp/ojs/commit/b9f79d4553a8195e3963f1dd68c460d988b936b9
