### ISSUE TITLE
[OJS 3.4 rc3] When Cancel first review round, get an error 500 in Activity Log

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#8948]
As an editor, I send to review a new submission and, then cancel this first review round review, so submission go back in Submission step. I want to show the Activity Log and then get this Error 500.

```
[Thu Apr 27 10:00:58 2023] 127.0.0.1:33648 [500]: GET /index.php/publicknowledge/$$$call$$$/grid/event-log/submission-event-log-grid/fetch-grid?submissionId=11&=1682582418978 - Uncaught Error: Call to a member function getStageId() on null in /tmp/ojs/lib/pkp/classes/submissionFile/Repository.php:704
Stack trace:
#0 /tmp/ojs/lib/pkp/controllers/grid/eventLog/EventLogGridRow.php(91): PKP\submissionFile\Repository->getWorkflowStageId()
#1 /tmp/ojs/lib/pkp/classes/controllers/grid/GridHandler.php(1220): PKP\controllers\grid\eventLog\EventLogGridRow->initialize()
#2 /tmp/ojs/lib/pkp/classes/controllers/grid/GridHandler.php(1130): PKP\controllers\grid\GridHandler->_getInitializedRowInstance()
#3 /tmp/ojs/lib/pkp/classes/controllers/grid/GridHandler.php(1183): PKP\controllers\grid\GridHandler->renderRowsInternally()
#4 /tmp/ojs/lib/pkp/classes/controllers/grid/GridHandler.php(1058): PKP\controllers\grid\GridHandler->renderGridBodyPartsInternally()
#5 /tmp/ojs/lib/pkp/classes/controllers/grid/GridHandler.php(729): PKP\controllers\grid\GridHandler->doSpecificFetchGridActions()
#6 [internal function]: PKP\controllers\grid\GridHandler->fetchGrid()
#7 /tmp/ojs/lib/pkp/classes/core/PKPRouter.php(333): call_user_func()
#8 /tmp/ojs/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#9 /tmp/ojs/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPComponentRouter->route()
#10 /tmp/ojs/lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch()
#11 /tmp/ojs/index.php(21): PKP\core\PKPApplication->execute()
#12 {main}
thrown in /tmp/ojs/lib/pkp/classes/submissionFile/Repository.php on line 704

``` 
thank you

**Comment by asmecher** [comment]
Merged, thanks!
