### ISSUE TITLE
Fatal error in event log grid when trying to load logged submission file data

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#9067]
**Describe the bug**
Activity log is impossible to load due to a fatal error:
```
PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/log/event/EventLogEntry.php:196
Stack trace:
#0 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/log/event/EventLogEntry.php(196): array_merge(Array, NULL)
#1 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/controllers/grid/eventLog/EventLogGridCellProvider.php(69): PKP\log\event\EventLogEntry->getTranslatedMessage('en', false)
#2 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/controllers/grid/GridCellProvider.php(59): PKP\controllers\grid\eventLog\EventLogGridCellProvider->getTemplateVarsFromRowColumn(Object(PKP\controllers\grid\eventLog\EventLogGridRow), Object(PKP\controllers\grid\GridColumn))
#3 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/controllers/grid/GridHandler.php(1262): PKP\controllers\grid\GridCellProvider->render(Object(APP\core\Request), Object(PKP\controllers\grid\eventLog\EventLogGridRow), Object(PKP\controllers\grid\GridColumn))
#4 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/controllers/grid/GridHandler.php(1163): PKP\controllers\grid\GridHandler->_renderCellInternally(Object(APP\core\Request), Object(PKP\controllers\grid\eventLog\EventLogGridRow), Object(PKP\controllers\grid\GridColumn))
#5 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/controllers/grid/GridHandler.php(1138): PKP\controllers\grid\GridHandler->renderRowInternally(Object(APP\core\Request), Object(PKP\controllers\grid\eventLog\EventLogGridRow))
#6 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/controllers/grid/GridHandler.php(1188): PKP\controllers\grid\GridHandler->renderRowsInternally(Object(APP\core\Request), Array)
#7 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/controllers/grid/GridHandler.php(1063): PKP\controllers\grid\GridHandler->renderGridBodyPartsInternally(Object(APP\core\Request))
#8 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/controllers/grid/GridHandler.php(735): PKP\controllers\grid\GridHandler->doSpecificFetchGridActions(Array, Object(APP\core\Request), Object(APP\template\TemplateManager))
#9 [internal function]: PKP\controllers\grid\GridHandler->fetchGrid(Array, Object(APP\core\Request))
#10 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPRouter.php(334): call_user_func(Array, Array, Object(APP\core\Request))
#11 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#12 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#13 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPApplication.php(373): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#14 /Users/vitalii/Documents/development/ojs-main/ojs/index.php(21): PKP\core\PKPApplication->execute()
#15 {main}
  thrown in /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/log/event/EventLogEntry.php on line 196
```

**To Reproduce**
1. Make a submission, upload a file
2. Click on `Activity Log`
3. See error

**What application are you using?**
 OJS 3.4

**Comment by Vitaliy-1** [comment]
PR pkp-lib: https://github.com/pkp/pkp-lib/pull/9070
tests: https://github.com/pkp/ojs/pull/3943

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1 -- we did get a new translation come in, but I've already adjusted it to incorporate the change required here.
