### ISSUE TITLE
OMP 3.4.0-0 Creating new version from an existing version fails with error

### ISSUE THREAD

**Issue by nils-stefan-weiher** [pkp/pkp-lib#9095]
**Describe the bug**
In the submission workflow on the "Publication" tab, when clicking the "Create new version" button after a while the application shows a popup with an error and cancels. See below for the error log output.

**To Reproduce**
1. Login to a press with an existing and already published publication.
2. Select the submimssions with an already existing and go to the "Publication" tab
3. Click on button 'Create new Version'
4. See the error popup and no new version was created

**What application are you using?**
OMP 3.4.0-0

**Additional information**
PHP error log output:
```
[15-Jun-2023 10:40:29 Europe/Amsterdam] Slim Application Error:
Type: Error
Message: Call to a member function getLocalizedData() on null
File: /web/omp-3-4/lib/pkp/api/v1/submissions/PKPSubmissionHandler.php
Line: 1033
Trace: #0 [internal function]: PKP\API\v1\submissions\PKPSubmissionHandler->versionPublication()
#1 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()
#2 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke()
#3 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke()
#4 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack()
#5 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/App.php(503): Slim\Route->run()
#6 /web/omp-3-4/lib/pkp/classes/security/authorization/internal/ApiAuthorizationMiddleware.php(90): Slim\App->__invoke()
#7 [internal function]: PKP\security\authorization\internal\ApiAuthorizationMiddleware->__invoke()
#8 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#9 [internal function]: Slim\DeferredCallable->__invoke()
#10 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#11 /web/omp-3-4/lib/pkp/classes/security/authorization/internal/ApiCsrfMiddleware.php(56): Slim\App->Slim\{closure}()
#12 [internal function]: PKP\security\authorization\internal\ApiCsrfMiddleware->__invoke()
#13 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#14 [internal function]: Slim\DeferredCallable->__invoke()
#15 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#16 /web/omp-3-4/lib/pkp/classes/security/authorization/internal/ApiTokenDecodingMiddleware.php(140): Slim\App->Slim\{closure}()
#17 [internal function]: PKP\security\authorization\internal\ApiTokenDecodingMiddleware->__invoke()
#18 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#19 [internal function]: Slim\DeferredCallable->__invoke()
#20 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#21 /web/omp-3-4/lib/pkp/classes/handler/APIHandler.php(83): Slim\App->Slim\{closure}()
#22 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
#23 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#24 [internal function]: Slim\DeferredCallable->__invoke()
#25 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#26 /web/omp-3-4/lib/pkp/classes/handler/APIHandler.php(100): Slim\App->Slim\{closure}()
#27 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
#28 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#29 [internal function]: Slim\DeferredCallable->__invoke()
#30 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#31 /web/omp-3-4/lib/pkp/classes/handler/APIHandler.php(105): Slim\App->Slim\{closure}()
#32 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
#33 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#34 [internal function]: Slim\DeferredCallable->__invoke()
#35 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#36 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}()
#37 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack()
#38 /web/omp-3-4/lib/pkp/classes/handler/APIHandler.php(98): Slim\App->process()
#39 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
#40 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#41 [internal function]: Slim\DeferredCallable->__invoke()
#42 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#43 /web/omp-3-4/lib/pkp/classes/handler/APIHandler.php(105): Slim\App->Slim\{closure}()
#44 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
#45 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#46 [internal function]: Slim\DeferredCallable->__invoke()
#47 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#48 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}()
#49 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack()
#50 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/App.php(297): Slim\App->process()
#51 /web/omp-3-4/lib/pkp/classes/core/APIRouter.php(110): Slim\App->run()
#52 /web/omp-3-4/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\APIRouter->route()
#53 /web/omp-3-4/lib/pkp/classes/core/PKPApplication.php(373): PKP\core\Dispatcher->dispatch()
#54 /web/omp-3-4/index.php(21): PKP\core\PKPApplication->execute()
#55 {main}
```

This is the same intallation as reported in the other issue #9094 . If you need more details concerning the database or installation please let me know in the comments.

**Comment by asmecher** [comment]
@nils-stefan-weiher, I think the problem is your upgrade path from 3.4.0rc3 to 3.4.0-0. There were some late database changes and we don't write migrations with the release candidates in mind. Could you re-run the upgrade from 3.3.0-x to 3.4.0-0 without the intermediate release candidate stop-over?

**Comment by nils-stefan-weiher** [comment]
I will try to do this once again, but the issue already came up in the 3.4.0rc3 version of the instance.

**Comment by nils-stefan-weiher** [comment]
So after a clean upgrade, I could not reproduce the error again.
I will close this issue.
