### ISSUE TITLE
[OJS upgrade from 3_3_0_14 to 3_4_0_1] REVIEW_COMPLETE email template seems to be not installed

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#9109]
**Describe the bug**
I upgraded a 3_3_0_14 to 3_4_0_1 OJS, and in the new version, when I complete a review, I get an error 500. 
```PHP Fatal error:  Uncaught Error: Call to a member function getLocalizedData() on null in /home/ojs3401_cml/lib/pkp/classes/submission/reviewer/form/PKPReviewerReviewStep3Form.php:223
Stack trace:
#0 /home/ojs3401_cml/lib/pkp/pages/reviewer/PKPReviewerHandler.php(141): PKP\submission\reviewer\form\PKPReviewerReviewStep3Form->execute()
#1 [internal function]: PKP\pages\reviewer\PKPReviewerHandler->saveStep()
#2 /home/ojs3401_cml/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()
#3 /home/ojs3401_cml/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#4 /home/ojs3401_cml/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter->route()
#5 /home/ojs3401_cml/lib/pkp/classes/core/PKPApplication.php(373): PKP\core\Dispatcher->dispatch()
#6 /home/ojs3401_cml/index.php(21): PKP\core\PKPApplication->execute()
#7 {main}
  thrown in /home/ojs3401_cml/lib/pkp/classes/submission/reviewer/form/PKPReviewerReviewStep3Form.php on line 223
```

**To Reproduce**
new submission, send to review, add a reviewer, login as the reviewer, complete the review and look at error.log

and error 404 when you want to edit the REVIEW_COMPLETE template

**What application are you using?**
 OJS 3 4 0 1
php 8.1 / mysql

Thank you

**Comment by asmecher** [comment]
@forgive38, can you include the line *above* the ones you've quoted? I see the stack trace, but not the actual error message.

**Comment by forgive38** [comment]
@asmecher : I edit the issue with error message

PS: I looked in the DB and email template REVIEW_COMPLETE is not available. I think this only happens during an update.

Thank you

**Comment by asmecher** [comment]
@Vitaliy-1, could you have a look at this?

**Comment by Vitaliy-1** [comment]
`REVIEW_COMPLETE` and `REVIEW_EDIT` are 2 new email templates, which weren't added to the migration script: https://github.com/pkp/ojs/blob/main/classes/migration/upgrade/v3_4_0/InstallEmailTemplates.php#L19. 
Before it was a generic notification email. Without new migration,  as a temporary fix, I can restore this behaviour and the template wouldn't be available for editing.

**Comment by Vitaliy-1** [comment]
PRs:
main
pkp-lib: https://github.com/pkp/pkp-lib/pull/9187
OJS: https://github.com/pkp/ojs/pull/3987

requires porting to 3.4 stable and OMP

It appears that not only `REVIEW_COMPLETE` and `REVIEW_EDIT` weren't added but also `NOTIFICATION` template wasn't removed during migration meaning that I can use latter to fallback the behaviour to 3.3. 

These PRs 1) replace `REVIEW_COMPLETE` and `REVIEW_EDIT` on OJS instances where they not exist with generic `NOTIFICATION` template 2) exclude associated mailables from manage emails form because they can't be configured without the default template

**Comment by Vitaliy-1** [comment]
@asmecher, do you have time to review these PRs?

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1 -- I've left a comment here: https://github.com/pkp/ojs/pull/3987/files#r1277764664

**Comment by Vitaliy-1** [comment]
Migration required for 3.5 described in the separate issue: https://github.com/pkp/pkp-lib/issues/9202
