### ISSUE TITLE
(OMP 3.4.0-1)  Error when changing Cover Image Max Width & Height

### ISSUE THREAD

**Issue by rahmanramsi** [pkp/pkp-lib#9134]
**Describe the bug**
Error when changing Cover Image Max Width & Height
![CleanShot 2023-07-05 at 15 27 41](https://github.com/pkp/pkp-lib/assets/48276043/c7c266fb-d050-40e5-a3cc-6c9d705cdcb2)

**To Reproduce**
1. Go to `Website Settings` -> `Appearance` -> `Advance`. 
2. Change Cover Image Max Width / Height
4. Click 'Save' button
5. See error

**What application are you using?**
OMP version 3.4.0-1

**Additional information**
Here's the error log
```
[05-Jul-2023 15:33:10 Australia/Perth] Slim Application Error:
Type: TypeError
Message: PKP\publication\DAO::update(): Argument #1 ($publication) must be of type APP\publication\Publication, APP\section\Section given, called in /Users/rahmanramsi/Valet/omp3401/classes/services/ContextService.php on line 324
File: /Users/rahmanramsi/Valet/omp3401/lib/pkp/classes/publication/DAO.php
Line: 235
Trace: #0 /Users/rahmanramsi/Valet/omp3401/classes/services/ContextService.php(324): PKP\publication\DAO->update(Object(APP\section\Section))
#1 /Users/rahmanramsi/Valet/omp3401/classes/services/ContextService.php(90): APP\services\ContextService->resizeCoverThumbnails(Object(APP\press\Press), 1051, 100)
#2 [internal function]: APP\services\ContextService->afterEditContext('Context::edit', Array)
#3 /Users/rahmanramsi/Valet/omp3401/lib/pkp/classes/plugins/Hook.php(140): call_user_func_array(Array, Array)
#4 /Users/rahmanramsi/Valet/omp3401/lib/pkp/classes/plugins/Hook.php(113): PKP\plugins\Hook::run('Context::edit', Array)
#5 /Users/rahmanramsi/Valet/omp3401/lib/pkp/classes/services/PKPContextService.php(583): PKP\plugins\Hook::call('Context::edit', Array)
#6 /Users/rahmanramsi/Valet/omp3401/lib/pkp/api/v1/contexts/PKPContextHandler.php(406): PKP\services\PKPContextService->edit(Object(APP\press\Press), Array, Object(APP\core\Request))
#7 [internal function]: PKP\API\v1\contexts\PKPContextHandler->edit(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Array)
#8 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(PKP\core\APIResponse), Array)
#9 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(PKP\core\APIResponse), Array)
#10 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#11 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#12 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#13 /Users/rahmanramsi/Valet/omp3401/lib/pkp/classes/security/authorization/internal/ApiAuthorizationMiddleware.php(90): Slim\App->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#14 [internal function]: PKP\security\authorization\internal\ApiAuthorizationMiddleware->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Slim\App))
#15 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(PKP\security\authorization\internal\ApiAuthorizationMiddleware), Array)
#16 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Slim\App))
#17 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Slim\App))
#18 /Users/rahmanramsi/Valet/omp3401/lib/pkp/classes/security/authorization/internal/ApiCsrfMiddleware.php(56): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#19 [internal function]: PKP\security\authorization\internal\ApiCsrfMiddleware->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#20 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(PKP\security\authorization\internal\ApiCsrfMiddleware), Array)
#21 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#22 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#23 /Users/rahmanramsi/Valet/omp3401/lib/pkp/classes/security/authorization/internal/ApiTokenDecodingMiddleware.php(140): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#24 [internal function]: PKP\security\authorization\internal\ApiTokenDecodingMiddleware->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#25 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(PKP\security\authorization\internal\ApiTokenDecodingMiddleware), Array)
#26 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#27 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#28 /Users/rahmanramsi/Valet/omp3401/lib/pkp/classes/handler/APIHandler.php(83): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#29 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#30 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#31 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#32 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#33 /Users/rahmanramsi/Valet/omp3401/lib/pkp/classes/handler/APIHandler.php(100): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#34 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#35 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#36 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#37 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#38 /Users/rahmanramsi/Valet/omp3401/lib/pkp/classes/handler/APIHandler.php(105): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#39 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#40 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#41 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#42 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#43 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#44 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#45 /Users/rahmanramsi/Valet/omp3401/lib/pkp/classes/handler/APIHandler.php(98): Slim\App->process(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#46 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#47 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#48 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#49 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#50 /Users/rahmanramsi/Valet/omp3401/lib/pkp/classes/handler/APIHandler.php(105): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#51 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#52 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#53 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#54 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(PKP\core\APIResponse), Object(Closure))
#55 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#56 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#57 /Users/rahmanramsi/Valet/omp3401/lib/pkp/lib/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(PKP\core\APIResponse))
#58 /Users/rahmanramsi/Valet/omp3401/lib/pkp/classes/core/APIRouter.php(110): Slim\App->run()
#59 /Users/rahmanramsi/Valet/omp3401/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\APIRouter->route(Object(APP\core\Request))
#60 /Users/rahmanramsi/Valet/omp3401/lib/pkp/classes/core/PKPApplication.php(373): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#61 /Users/rahmanramsi/Valet/omp3401/index.php(21): PKP\core\PKPApplication->execute()
#62 /Users/rahmanramsi/.composer/vendor/laravel/valet/server.php(250): require('/Users/rahmanra...')
#63 {main}
View in rendered output by enabling the "displayErrorDetails" setting.
```

**Comment by asmecher** [comment]
Thanks for reporting, @rahmanramsi! You can fix this by applying: https://github.com/pkp/omp/commit/225f55e47c9bdd1578ebac7d04ed46d5a41396c3
