### ISSUE TITLE
Illuminate\Database\Query\Expression::getValue() method signature change in Laravel 10

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#9137]
**Describe the bug**
`Expression::getValue()` now expects an argument `\Illuminate\Database\Grammar`: https://laravel.com/api/10.x/Illuminate/Contracts/Database/Query/Expression.html#method_getValue

**To Reproduce**
1. Perform an upgrade from a command line: `php tools/upgrade.php upgrade`
2. See error

```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Illuminate\Database\Query\Expression::getValue(), 0 passed in /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/db/DAO.php on line 77 and exactly 1 expected in /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Expression.php:34
Stack trace:
#0 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/db/DAO.php(77): Illuminate\Database\Query\Expression->getValue()
#1 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/plugins/PluginSettingsDAO.php(115): PKP\db\DAO->retrieve('SELECT setting_...', Array)
#2 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/plugins/PluginSettingsDAO.php(93): PKP\plugins\PluginSettingsDAO->getPluginSettings('0', 'googlescholarpl...')
#3 [internal function]: PKP\plugins\PluginSettingsDAO->_cacheMiss(Object(PKP\cache\FileCache), 'enabled')
#4 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/cache/GenericCache.php(69): call_user_func_array(Array, Array)
#5 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/plugins/PluginSettingsDAO.php(60): PKP\cache\GenericCache->get('enabled')
#6 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/plugins/Plugin.php(509): PKP\plugins\PluginSettingsDAO->getSetting(0, 'googlescholarpl...', 'enabled')
#7 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/plugins/LazyLoadPlugin.php(81): PKP\plugins\Plugin->getSetting(0, 'enabled')
#8 /Users/vitalii/Documents/development/ojs-main/ojs/plugins/generic/googleScholar/GoogleScholarPlugin.php(39): PKP\plugins\LazyLoadPlugin->getEnabled(0)
#9 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/plugins/PluginRegistry.php(76): APP\plugins\generic\googleScholar\GoogleScholarPlugin->register('generic', 'plugins/generic...', NULL)
#10 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/plugins/PluginRegistry.php(121): PKP\plugins\PluginRegistry::register('generic', Object(APP\plugins\generic\googleScholar\GoogleScholarPlugin), 'plugins/generic...', NULL)
#11 [internal function]: PKP\plugins\PluginRegistry::PKP\plugins\{closure}(Object(APP\plugins\generic\googleScholar\GoogleScholarPlugin), 'plugins/generic...')
#12 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/plugins/PluginRegistry.php(121): array_walk_recursive(Array, Object(Closure))
#13 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/cliTool/CommandLineTool.php(70): PKP\plugins\PluginRegistry::loadCategory('generic')
#14 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/cliTool/UpgradeTool.php(39): PKP\cliTool\CommandLineTool->__construct(Array)
#15 /Users/vitalii/Documents/development/ojs-main/ojs/tools/upgrade.php(21): PKP\cliTool\UpgradeTool->__construct(Array)
#16 {main}
  thrown in /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Expression.php on line 34
```

**What application are you using?**
 OJS, OMP and OPS main branch

**Comment by Vitaliy-1** [comment]
@touhidurabir, can you take a look at this issue?

**Comment by touhidurabir** [comment]
@Vitaliy-1 , I can see that this has already been applied , check at https://github.com/pkp/pkp-lib/blob/main/classes/db/DAO.php#L77 . This was the part of Laravel 9.x to 10.x upgrade process. Is this happening when upgrading from `3.4.0-x` to `3.5.0` as running `php tools/upgrade.php upgrade` in latest `main` does not cause any issue ?

**Comment by Vitaliy-1** [comment]
Sorry, my bad, forgot to update the branch
