### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function getDisplayName() on null 

### ISSUE THREAD

**Issue by loadbrain** [pkp/pkp-lib#9146]
In OJS 3.4.1, when clicking on "Accept submission" I get a white page, 500 error.

From apache error.log:
` mod_proxy_fcgi.c(887): AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getDisplayName() on null in /var/www/clients/client50/web168/web/ojs3/lib/pkp/classes/decision/steps/Email.php:100\nStack trace:\n#0 /var/www/clients/client50/web168/web/ojs3/lib/pkp/classes/decision/Steps.php(66): PKP\\decision\\steps\\Email->getState()\n#1 /var/www/clients/client50/web168/web/ojs3/lib/pkp/pages/decision/DecisionHandler.php(154): PKP\\decision\\Steps->getState()\n#2 [internal function]: PKP\\pages\\decision\\DecisionHandler->record()\n#3 /var/www/clients/client50/web168/web/ojs3/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()\n#4 /var/www/clients/client50/web168/web/ojs3/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest()\n#5 /var/www/clients/client50/web168/web/ojs3/lib/pkp/classes/core/Dispatcher.php(165): PKP\\core\\PKPPageRouter->route()\n#6 /var/www/clients/client50/web168/web/ojs3/lib/pkp/classes/core/PKPApplication.php(373): PKP\\core\\Dispatcher->dispatch()\n#7 ...'
`

Any ideas?

**Comment by loadbrain** [comment]
Error on server side by hoster
