### ISSUE TITLE
Sending email to a reviewer results in a fatal error

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#9153]
**Describe the bug**
Receiving a fatal error when trying to send email through `Email Reviewer` feature:
```
PHP Fatal error:  Uncaught Exception: APP\mail\variables\SubmissionEmailVariable is unable to generate email variables without providing the context to the Mailable in /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/mail/variables/Variable.php:43
Stack trace:
#0 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/mail/variables/SubmissionEmailVariable.php(74): PKP\mail\variables\Variable->getContext()
#1 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/mail/Mailable.php(234): PKP\mail\variables\SubmissionEmailVariable->values('en')
#2 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/mail/Mailer.php(118): PKP\mail\Mailable->setData()
#3 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(563): PKP\mail\Mailer->send(Object(PKP\mail\Mailable))
#4 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Illuminate\Mail\MailManager->__call('send', Array)
#5 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/controllers/grid/users/reviewer/form/EmailReviewerForm.php(110): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#6 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.php(965): PKP\controllers\grid\users\reviewer\form\EmailReviewerForm->execute()
#7 [internal function]: PKP\controllers\grid\users\reviewer\PKPReviewerGridHandler->sendEmail(Array, Object(APP\core\Request))
#8 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPRouter.php(334): call_user_func(Array, Array, Object(APP\core\Request))
#9 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#10 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#11 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPApplication.php(360): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#12 /Users/vitalii/Documents/development/ojs-main/ojs/index.php(21): PKP\core\PKPApplication->execute()
#13 {main}
  thrown in /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/mail/variables/Variable.php on line 43
```

**To Reproduce**
1. Make a submission
2. Assign reviewers
3. Under the reviewer grid press `Email Reviewer` button
4. Compose email and press `Send Email` button
5. See error

**What application are you using?**
 OJS, OMP main branch and stable 3.4.0

**Additional information**
![email_reviewer](https://github.com/pkp/pkp-lib/assets/20665587/cafabe78-43ba-4722-b91c-e91722cecb29)

**Comment by Vitaliy-1** [comment]
PRs
main: https://github.com/pkp/pkp-lib/pull/9154
stable 3.4.0: https://github.com/pkp/pkp-lib/pull/9155
