### ISSUE TITLE
Acron Plugin doesn't synchronise correctly with other plugins

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#9206]
**Describe the bug**
Able to reproduce on the test instance when trying to enable or disable plugins:
```
PHP Fatal error:  Uncaught Error: Cannot use object of type Closure as array in /Users/vitalii/Documents/development/ojs-main/ojs/plugins/generic/acron/AcronPlugin.php:206
Stack trace:
#0 /Users/vitalii/Documents/development/ojs-main/ojs/plugins/generic/acron/AcronPlugin.php(61): APP\plugins\generic\acron\AcronPlugin->_callbackManage(Object(PKP\observers\events\PluginSettingChanged))
#1 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): APP\plugins\generic\acron\AcronPlugin->APP\plugins\generic\acron\{closure}(Object(PKP\observers\events\PluginSettingChanged))
#2 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('PKP\\observers\\e...', Array)
#3 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(433): Illuminate\Events\Dispatcher->dispatch('PKP\\observers\\e...')
#4 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/plugins/Plugin.php(526): event(Object(PKP\observers\events\PluginSettingChanged))
#5 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/plugins/BlockPlugin.php(45): PKP\plugins\Plugin->updateSetting(1, 'enabled', true, 'bool')
#6 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/controllers/grid/plugins/PluginGridHandler.php(297): PKP\plugins\BlockPlugin->setEnabled(true)
#7 [internal function]: PKP\controllers\grid\plugins\PluginGridHandler->enable(Array, Object(APP\core\Request))
#8 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPRouter.php(334): call_user_func(Array, Array, Object(APP\core\Request))
#9 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#10 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#11 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPApplication.php(360): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#12 /Users/vitalii/Documents/development/ojs-main/ojs/index.php(21): PKP\core\PKPApplication->execute()
#13 {main}
  thrown in /Users/vitalii/Documents/development/ojs-main/ojs/plugins/generic/acron/AcronPlugin.php on line 206
```

The error originates from https://github.com/pkp/acron/blob/main/AcronPlugin.php#L204-L209, which, I think, want work even after fixing a typo when declaring iteration through the hook list. If I caught the idea right, we need to compare the Closure name (it's origin) with the plugin's class name, e.g., something like:
```php
 foreach ($hookPriorityList as $callback) {
  $callbackName = (new \ReflectionFunction($callback))->getClosureScopeClass()->getName();
  if (is_a($event->plugin, $callbackName)) {
    $this->_parseCrontab();
    break 2;
  }
}
```

**To Reproduce**
1. Import test dataset derived from the `main` (A plugin that uses `AcronPlugin::parseCronTab` hook should be enabled, like Crossref Export)
2. Enable or disable any plugin from website settings -> plugins
3. See error

**What application are you using?**
 OJS, OMP and OPS main branch. Likely stable 3.4.0 is affected to as the code is the same, although I haven't tested

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1! I've fixed this by reverting [part](https://github.com/pkp/ojs/commit/3305420e1498f7fb71c5eb0b08cf9db9866aa13c) of [this change](https://github.com/pkp/ojs/commit/7d3a60ed60d8ec2dec1079fc03481d53f9a15680#diff-070d2ec32d1b6036896890ae4002f378260dbbc2b669467bad1892dc1303e28a), which introduces first-class callable syntax for hooks. The acron plugin expects array-based callbacks for its specific case, so I've given it what it wants.
