### ISSUE TITLE
OMP 3.4.0 Missing E-mail Template SUBMISSION_SAVED_FOR_LATER after upgrade from 3.3.0-1

### ISSUE THREAD

**Issue by nils-stefan-weiher** [pkp/pkp-lib#9217]
**Describe the bug**
Hi everyone,

While using the Submission wizard to create a new submission in our OMP 3.4.0-1 instance. The "Save for Later" button is not working.

Details are below.

**To Reproduce**
In an upgraded OMP 3.4.0-1 installtion (not a fresh install)
1. Go to Submissions in any press
2. Click on 'New Submission'
3. Fill in the required fields
4. Click "Begin Submission"
5. Wait for the new view
6. Click "Save for Later"
7. Submission is not saved and a fatal error is logged in the instance.

**What application are you using?**
 OMP 3.4.0 (current `stable-3_4_0` Branch), upgraded from version 3.3.0-7

**Additional information**
The migration from the class that should list the new e-mail template:
https://github.com/pkp/omp/blob/stable-3_4_0/classes/migration/upgrade/v3_4_0/InstallEmailTemplates.php

See the corresponding migration for OJS:
https://github.com/pkp/ojs/blob/stable-3_4_0/classes/migration/upgrade/v3_4_0/InstallEmailTemplates.php

Exception from PHP error log:
```
Slim Application Error:
Type: Error
Message: Call to a member function getLocalizedData() on null
File: /web/omp-3-4/lib/pkp/api/v1/submissions/PKPSubmissionHandler.php
Line: 644
Trace: #0 [internal function]: PKP\API\v1\submissions\PKPSubmissionHandler->saveForLater()
#1 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()
#2 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke()
#3 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke()
#4 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack()
#5 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/App.php(503): Slim\Route->run()
#6 /web/omp-3-4/lib/pkp/classes/security/authorization/internal/ApiAuthorizationMiddleware.php(90): Slim\App->__invoke()
#7 [internal function]: PKP\security\authorization\internal\ApiAuthorizationMiddleware->__invoke()
#8 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#9 [internal function]: Slim\DeferredCallable->__invoke()
#10 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#11 /web/omp-3-4/lib/pkp/classes/security/authorization/internal/ApiCsrfMiddleware.php(56): Slim\App->Slim\{closure}()
#12 [internal function]: PKP\security\authorization\internal\ApiCsrfMiddleware->__invoke()
#13 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#14 [internal function]: Slim\DeferredCallable->__invoke()
#15 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#16 /web/omp-3-4/lib/pkp/classes/security/authorization/internal/ApiTokenDecodingMiddleware.php(140): Slim\App->Slim\{closure}()
#17 [internal function]: PKP\security\authorization\internal\ApiTokenDecodingMiddleware->__invoke()
#18 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#19 [internal function]: Slim\DeferredCallable->__invoke()
#20 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#21 /web/omp-3-4/lib/pkp/classes/handler/APIHandler.php(83): Slim\App->Slim\{closure}()
#22 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
#23 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#24 [internal function]: Slim\DeferredCallable->__invoke()
#25 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#26 /web/omp-3-4/lib/pkp/classes/handler/APIHandler.php(100): Slim\App->Slim\{closure}()
#27 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
#28 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#29 [internal function]: Slim\DeferredCallable->__invoke()
#30 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#31 /web/omp-3-4/lib/pkp/classes/handler/APIHandler.php(105): Slim\App->Slim\{closure}()
#32 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
#33 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#34 [internal function]: Slim\DeferredCallable->__invoke()
#35 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#36 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}()
#37 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack()
#38 /web/omp-3-4/lib/pkp/classes/handler/APIHandler.php(98): Slim\App->process()
#39 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
#40 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#41 [internal function]: Slim\DeferredCallable->__invoke()
#42 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#43 /web/omp-3-4/lib/pkp/classes/handler/APIHandler.php(105): Slim\App->Slim\{closure}()
#44 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
#45 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#46 [internal function]: Slim\DeferredCallable->__invoke()
#47 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#48 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}()
#49 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack()
#50 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/App.php(297): Slim\App->process()
#51 /web/omp-3-4/lib/pkp/classes/core/APIRouter.php(110): Slim\App->run()
#52 /web/omp-3-4/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\APIRouter->route()
#53 /web/omp-3-4/lib/pkp/classes/core/PKPApplication.php(370): PKP\core\Dispatcher->dispatch()
#54 /web/omp-3-4/index.php(21): PKP\core\PKPApplication->execute()
#55 {main}
View in rendered output by enabling the "displayErrorDetails" setting.
```

**Comment by nils-stefan-weiher** [comment]
The issue can be fixed in an already upgraded instance by installing the email template with the CLI tool: `installEmailTemplate.php`

Command:
```
cd $OMP_ROOT
php lib/pkp/tools/installEmailTemplate.php SUBMISSION_SAVED_FOR_LATER
```


I can open a pull request for `stable_3_4_0`

Could someone add this to the migration for the next version?

This issue is related: https://github.com/pkp/pkp-lib/issues/9202

**Comment by asmecher** [comment]
@Vitaliy-1, can you have a look? This is similar to one or two other 3.4.0-2 issues.

**Comment by Vitaliy-1** [comment]
PRs main
pkp-lib: https://github.com/pkp/pkp-lib/pull/9234
OMP: https://github.com/pkp/omp/pull/1444

(PRs for the stable 3.4.0 required)

**Comment by Vitaliy-1** [comment]
This migrates missing templates `SUBMISSION_SAVED_FOR_LATER` and `SUBMISSION_NEEDS_EDITOR`. For affected instances substitutes the latter with the NOTIFICATION template as it was in 3.3 and the former just with localized text. Migration for affected instances for 3.5 will be done as a part of https://github.com/pkp/pkp-lib/issues/9202

**Comment by Vitaliy-1** [comment]
@asmecher, can you take a look at these PRs?

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1, those all look fine; please go ahead.

**Comment by nils-stefan-weiher** [comment]
Dear  @Vitaliy-1 
I get a NULL error in a line introduced with the fixed for this issue.

See error log:

```
[05-Sep-2023 14:36:31 Europe/Amsterdam] Slim Application Error:
Type: Error
Message: Call to a member function getType() on null
File: /web/omp-3-4/lib/pkp/classes/notification/PKPNotificationManager.php
Line: 119
Trace: #0 /web/omp-3-4/lib/pkp/classes/notification/PKPNotificationOperationManager.php(66): PKP\notifica
tion\PKPNotificationManager->getNotificationMessage()
#1 /web/omp-3-4/lib/pkp/classes/notification/PKPNotificationManager.php(214): PKP\notification\PKPNotific
ationOperationManager->getNotificationContents()
#2 /web/omp-3-4/lib/pkp/classes/observers/listeners/AssignEditors.php(107): PKP\notification\PKPNotificat
ionManager->getNotificationContents()
#3 /web/omp-3-4/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(441): PKP\obser
vers\listeners\AssignEditors->handle()
#4 /web/omp-3-4/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#5 /web/omp-3-4/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(451): Illuminate\Events\Dispatcher->dispatch()
#6 /web/omp-3-4/lib/pkp/classes/submission/Repository.php(595): event()
#7 /web/omp-3-4/lib/pkp/api/v1/submissions/PKPSubmissionHandler.php(717): PKP\submission\Repository->submit()
#8 [internal function]: PKP\API\v1\submissions\PKPSubmissionHandler->submit()
#9 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()
#10 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke()
#11 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke()
#12 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack()
#13 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/App.php(503): Slim\Route->run()
#14 /web/omp-3-4/lib/pkp/classes/security/authorization/internal/ApiAuthorizationMiddleware.php(90): Slim\App->__invoke()
#15 [internal function]: PKP\security\authorization\internal\ApiAuthorizationMiddleware->__invoke()
#16 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#17 [internal function]: Slim\DeferredCallable->__invoke()
#18 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#19 /web/omp-3-4/lib/pkp/classes/security/authorization/internal/ApiCsrfMiddleware.php(56): Slim\App->Slim\{closure}()
#20 [internal function]: PKP\security\authorization\internal\ApiCsrfMiddleware->__invoke()
#21 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#22 [internal function]: Slim\DeferredCallable->__invoke()
#23 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#24 /web/omp-3-4/lib/pkp/classes/security/authorization/internal/ApiTokenDecodingMiddleware.php(140): Slim\App->Slim\{closure}()
#25 [internal function]: PKP\security\authorization\internal\ApiTokenDecodingMiddleware->__invoke()
#26 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#27 [internal function]: Slim\DeferredCallable->__invoke()
#28 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#29 /web/omp-3-4/lib/pkp/classes/handler/APIHandler.php(83): Slim\App->Slim\{closure}()
#30 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
#31 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#32 [internal function]: Slim\DeferredCallable->__invoke()
#33 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#34 /web/omp-3-4/lib/pkp/classes/handler/APIHandler.php(100): Slim\App->Slim\{closure}()
#35 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
#36 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#37 [internal function]: Slim\DeferredCallable->__invoke()
#38 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#39 /web/omp-3-4/lib/pkp/classes/handler/APIHandler.php(105): Slim\App->Slim\{closure}()
#40 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
#41 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#42 [internal function]: Slim\DeferredCallable->__invoke()
#43 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#44 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}()
#45 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack()
#46 /web/omp-3-4/lib/pkp/lib/vendor/slim/slim/Slim/App.php(297): Slim\App->process()
#47 /web/omp-3-4/lib/pkp/classes/core/APIRouter.php(110): Slim\App->run()
#48 /web/omp-3-4/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\APIRouter->route()
#49 /web/omp-3-4/lib/pkp/classes/core/PKPApplication.php(387): PKP\core\Dispatcher->dispatch()
#50 /web/omp-3-4/index.php(21): PKP\core\PKPApplication->execute()
#51 {main}
View in rendered output by enabling the "displayErrorDetails" setting.
```

Should I file a separate issue for this?

**Comment by nils-stefan-weiher** [comment]
It seems the `createNotification` method also can return a NULL, it the notification is disabled for the user.
https://github.com/pkp/pkp-lib/blob/stable-3_4_0/classes/notification/PKPNotificationOperationManager.php#L164

**Comment by Vitaliy-1** [comment]
The relevant line is:

> #2 /web/omp-3-4/lib/pkp/classes/observers/listeners/AssignEditors.php(107): PKP\notification\PKPNotificat
ionManager->getNotificationContents()

@nils-stefan-weiher, are the reproduction steps the same?

**Comment by nils-stefan-weiher** [comment]
@Vitaliy-1 Sorry for the confusion.

The error appears after the final step of the submission.
