### ISSUE TITLE
Task list failed to load on context delete. 

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#9228]
**Describe the bug**
After deleting a new context, if that context has any associated tasks, then the task list failed to load. This is happening because at delete of context, the tasks does not get removed also . 

**To Reproduce**
1. Create a new Context (e.g. for OJS a new journal)
2. make sure the newly created context has some unread task associated with . 
3. Delete the context .
4. Try to load the task list and see there is only a spinning loader only and no list . (see image below)

**What application are you using?**
 OJS `main` . Probably also included into `stable-3.4.0` .

**Additional information**
<img width="1783" alt="CleanShot 2023-08-14 at 17 55 00@2x" src="https://github.com/pkp/pkp-lib/assets/2587979/2409c4f8-9b5e-4a53-a3cb-de8639bb7e0f">

The cause of the problem lies at https://github.com/pkp/pkp-lib/blob/main/templates/controllers/grid/tasks/task.tpl#L26 where as the context is removed the `$context` is `NULL` . 

A quick solution can be to include the check of the existence of `$context` also . But the proper solution should be the removal of a task associated with an removed context . 

**Exception Trace**
```php
[14-Aug-2023 11:54:47 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getLocalizedAcronym() on null in /Users/abir/Sites/code/ojs-main/cache/t_compile/7bdb22b1beb9ad34cdbc123fe840c756abbed6db^642608917fb21577c3f7235b556979f3e7c86b25_0.app.controllersgridtaskstask.tpl.php:32
Stack trace:
#0 /Users/abir/Sites/code/ojs-main/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_64da1606bd2ed4_52337059(Object(Smarty_Internal_Template))
#1 /Users/abir/Sites/code/ojs-main/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#2 /Users/abir/Sites/code/ojs-main/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#3 /Users/abir/Sites/code/ojs-main/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 0)
#4 /Users/abir/Sites/code/ojs-main/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, '7bdb22b1beb9ad3...', NULL, 0)
#5 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/template/PKPTemplateManager.php(1195): Smarty_Internal_TemplateBase->fetch('controllers/gri...', NULL, '7bdb22b1beb9ad3...', NULL)
#6 /Users/abir/Sites/code/ojs-main/lib/pkp/controllers/grid/notifications/NotificationsGridCellProvider.php(84): PKP\template\PKPTemplateManager->fetch('controllers/gri...')
#7 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/controllers/grid/GridCellProvider.php(66): PKP\controllers\grid\notifications\NotificationsGridCellProvider->getCellActions(Object(APP\core\Request), Object(PKP\controllers\grid\GridRow), Object(PKP\controllers\grid\GridColumn))
#8 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/controllers/grid/GridHandler.php(1262): PKP\controllers\grid\GridCellProvider->render(Object(APP\core\Request), Object(PKP\controllers\grid\GridRow), Object(PKP\controllers\grid\GridColumn))
#9 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/controllers/grid/GridHandler.php(1163): PKP\controllers\grid\GridHandler->_renderCellInternally(Object(APP\core\Request), Object(PKP\controllers\grid\GridRow), Object(PKP\controllers\grid\GridColumn))
#10 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/controllers/grid/GridHandler.php(1138): PKP\controllers\grid\GridHandler->renderRowInternally(Object(APP\core\Request), Object(PKP\controllers\grid\GridRow))
#11 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/controllers/grid/GridHandler.php(1188): PKP\controllers\grid\GridHandler->renderRowsInternally(Object(APP\core\Request), Array)
#12 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/controllers/grid/GridHandler.php(1063): PKP\controllers\grid\GridHandler->renderGridBodyPartsInternally(Object(APP\core\Request))
#13 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/controllers/grid/GridHandler.php(735): PKP\controllers\grid\GridHandler->doSpecificFetchGridActions(Array, Object(APP\core\Request), Object(APP\template\TemplateManager))
#14 [internal function]: PKP\controllers\grid\GridHandler->fetchGrid(Array, Object(APP\core\Request))
#15 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/core/PKPRouter.php(334): call_user_func(Array, Array, Object(APP\core\Request))
#16 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#17 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#18 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/core/PKPApplication.php(360): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#19 /Users/abir/Sites/code/ojs-main/index.php(21): PKP\core\PKPApplication->execute()
#20 /Users/abir/.composer/vendor/laravel/valet/server.php(235): require('/Users/abir/Sit...')
#21 {main}
  thrown in /Users/abir/Sites/code/ojs-main/cache/t_compile/7bdb22b1beb9ad34cdbc123fe840c756abbed6db^642608917fb21577c3f7235b556979f3e7c86b25_0.app.controllersgridtaskstask.tpl.php on line 32
```

**Comment by taslangraham** [comment]
@touhidurabir I've followed the steps you outlined to reproduce the issue, but I wasn't able to replicate it. After deleting a Context, I can still view the task list, and the unread tasks for the deleted Context are no longer present.

Could you provide any additional details or steps that might help?

**Comment by touhidurabir** [comment]
> the unread tasks for the deleted Context are no longer present

@taslangraham  my guess is that this has been resolved with some other PR or issue if you can not reproduce with latest checkout of the `main` branch as this was definitely happening . can you please double check it in `stable-3.4.0` branch ? if this does not arise there, I believe this has been properly resolved(through some different PR) and the issue can be closed .

**Comment by touhidurabir** [comment]
@taslangraham thanks for checking and confirmation . 

I am closing this issue as it can't be reproduce anymore . we can re-open it later if it resurface again .
