### ISSUE TITLE
[OJS-3.4.0-3] Unable to reassign DOI if accidentally deleted DOI from article. DOI is entered only manually.

### ISSUE THREAD

**Issue by shantanu198713** [pkp/pkp-lib#9273]
OJS-3.4.0-3

If the DOI is removed from an article by mistake, I am unable to reassign the DOI to the article. DOI is entered only manually.

**To Reproduce**
1. Assign a DOI to the article the first time it is assigned as normal.
2. If a DOI is accidentally deleted, there will be an inability to reassign the DOI to the article.
![Screenshot 2023-09-01 162510](https://github.com/pkp/pkp-lib/assets/108086810/21eadab5-58f9-4c71-a5ba-adbb85c4874b)

**Comment by bozana** [comment]
Hi @shantanu198713, can you explain how the DOI was deleted and how do you try to assign a new DOI to the article?

**Comment by shantanu198713** [comment]
Hi @bozana 

In above mentioned image, after reaching the DOI section, I edited the article's DOI and assigned it which got deleted by mistake/self and while trying to reassign a DOI for the same article by selecting the article and assigning the DOI through `Bulk Actions` tab. I am not able to reassign it.

**Comment by shantanu198713** [comment]
Hi @bozana 

I have checked PHP error log only plugin exception is generated no fatal error was reported. I have made a video for example may be help you.

Youtube video [link](https://youtu.be/3zu86UlTYsY

**Comment by shantanu198713** [comment]
Hi @bozana 

Any update?

**Comment by bozana** [comment]
Hi @shantanu198713, strange... I got the exact 3.4.0-3 code and I cannot reproduce it :-(
What  plugin exception do you see in your PHP log?

**Comment by shantanu198713** [comment]
Hi @bozana 

I have tried to reproduce the error while reassigning the DOI to the article. Below is the log just after reassigning the DOI.

`````
 [22-Sep-2023 11:02:35 UTC] Exception: Plugin referral expected to inherit from ReferralPlugin, actual type NULL in ojs34/lib/pkp/classes/plugins/PluginRegistry.php:203
Stack trace:
#0 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(219): PKP\plugins\PluginRegistry::_instantiatePlugin()
#1 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\plugins\PluginRegistry::_loadFromDatabase()
#2 ojs34/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory()
#3 ojs34/lib/pkp/classes/core/PKPApplication.php(387): PKP\core\Dispatcher->dispatch()
#4 ojs34/index.php(21): PKP\core\PKPApplication->execute()
#5 {main}
[22-Sep-2023 11:02:35 UTC] Exception: Plugin coins expected to inherit from CoinsPlugin, actual type NULL in ojs34/lib/pkp/classes/plugins/PluginRegistry.php:203
Stack trace:
#0 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(219): PKP\plugins\PluginRegistry::_instantiatePlugin()
#1 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\plugins\PluginRegistry::_loadFromDatabase()
#2 ojs34/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory()
#3 ojs34/lib/pkp/classes/core/PKPApplication.php(387): PKP\core\Dispatcher->dispatch()
#4 ojs34/index.php(21): PKP\core\PKPApplication->execute()
#5 {main}
[22-Sep-2023 11:02:35 UTC] Exception: Plugin crossrefReferenceLinking expected to inherit from CrossrefReferenceLinkingPlugin, actual type NULL in ojs34/lib/pkp/classes/plugins/PluginRegistry.php:203
Stack trace:
#0 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(219): PKP\plugins\PluginRegistry::_instantiatePlugin()
#1 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\plugins\PluginRegistry::_loadFromDatabase()
#2 ojs34/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory()
#3 ojs34/lib/pkp/classes/core/PKPApplication.php(387): PKP\core\Dispatcher->dispatch()
#4 ojs34/index.php(21): PKP\core\PKPApplication->execute()
#5 {main}
[22-Sep-2023 11:02:35 UTC] Exception: Plugin citations expected to inherit from CitationsPlugin, actual type NULL in ojs34/lib/pkp/classes/plugins/PluginRegistry.php:203
Stack trace:
#0 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(219): PKP\plugins\PluginRegistry::_instantiatePlugin()
#1 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\plugins\PluginRegistry::_loadFromDatabase()
#2 ojs34/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory()
#3 ojs34/lib/pkp/classes/core/PKPApplication.php(387): PKP\core\Dispatcher->dispatch()
#4 ojs34/index.php(21): PKP\core\PKPApplication->execute()
#5 {main}
[22-Sep-2023 11:02:35 UTC] Exception: Plugin defaultManuscript expected to inherit from DefaultManuscriptChildThemePlugin, actual type NULL in ojs34/lib/pkp/classes/plugins/PluginRegistry.php:203
Stack trace:
#0 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(219): PKP\plugins\PluginRegistry::_instantiatePlugin()
#1 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\plugins\PluginRegistry::_loadFromDatabase()
#2 ojs34/lib/pkp/classes/template/PKPTemplateManager.php(1392): PKP\plugins\PluginRegistry::loadCategory()
#3 ojs34/lib/pkp/classes/plugins/Plugin.php(403): PKP\template\PKPTemplateManager::getManager()
#4 ojs34/lib/pkp/classes/plugins/Plugin.php(137): PKP\plugins\Plugin->_registerTemplateResource()
#5 ojs34/lib/pkp/classes/plugins/LazyLoadPlugin.php(34): PKP\plugins\Plugin->register()
#6 ojs34/plugins/generic/recommendBySimilarity/RecommendBySimilarityPlugin.php(39): PKP\plugins\LazyLoadPlugin->register()
#7 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(76): APP\plugins\generic\recommendBySimilarity\RecommendBySimilarityPlugin->register()
#8 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(121): PKP\plugins\PluginRegistry::register()
#9 [internal function]: PKP\plugins\PluginRegistry::PKP\plugins\{closure}()
#10 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(121): array_walk_recursive()
#11 ojs34/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory()
#12 ojs34/lib/pkp/classes/core/PKPApplication.php(387): PKP\core\Dispatcher->dispatch()
#13 ojs34/index.php(21): PKP\core\PKPApplication->execute()
#14 {main}
[22-Sep-2023 11:02:35 UTC] Exception: Plugin referral expected to inherit from ReferralPlugin, actual type NULL in ojs34/lib/pkp/classes/plugins/PluginRegistry.php:203
Stack trace:
#0 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(219): PKP\plugins\PluginRegistry::_instantiatePlugin()
#1 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\plugins\PluginRegistry::_loadFromDatabase()
#2 ojs34/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory()
#3 ojs34/lib/pkp/classes/core/PKPApplication.php(387): PKP\core\Dispatcher->dispatch()
#4 ojs34/index.php(21): PKP\core\PKPApplication->execute()
#5 {main}
[22-Sep-2023 11:02:35 UTC] Exception: Plugin coins expected to inherit from CoinsPlugin, actual type NULL in ojs34/lib/pkp/classes/plugins/PluginRegistry.php:203
Stack trace:
#0 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(219): PKP\plugins\PluginRegistry::_instantiatePlugin()
#1 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\plugins\PluginRegistry::_loadFromDatabase()
#2 ojs34/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory()
#3 ojs34/lib/pkp/classes/core/PKPApplication.php(387): PKP\core\Dispatcher->dispatch()
#4 ojs34/index.php(21): PKP\core\PKPApplication->execute()
#5 {main}
[22-Sep-2023 11:02:35 UTC] Exception: Plugin crossrefReferenceLinking expected to inherit from CrossrefReferenceLinkingPlugin, actual type NULL in ojs34/lib/pkp/classes/plugins/PluginRegistry.php:203
Stack trace:
#0 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(219): PKP\plugins\PluginRegistry::_instantiatePlugin()
#1 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\plugins\PluginRegistry::_loadFromDatabase()
#2 ojs34/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory()
#3 ojs34/lib/pkp/classes/core/PKPApplication.php(387): PKP\core\Dispatcher->dispatch()
#4 ojs34/index.php(21): PKP\core\PKPApplication->execute()
#5 {main}
[22-Sep-2023 11:02:35 UTC] Exception: Plugin citations expected to inherit from CitationsPlugin, actual type NULL in ojs34/lib/pkp/classes/plugins/PluginRegistry.php:203
Stack trace:
#0 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(219): PKP\plugins\PluginRegistry::_instantiatePlugin()
#1 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\plugins\PluginRegistry::_loadFromDatabase()
#2 ojs34/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory()
#3 ojs34/lib/pkp/classes/core/PKPApplication.php(387): PKP\core\Dispatcher->dispatch()
#4 ojs34/index.php(21): PKP\core\PKPApplication->execute()
#5 {main}
[22-Sep-2023 11:02:35 UTC] Exception: Plugin defaultManuscript expected to inherit from DefaultManuscriptChildThemePlugin, actual type NULL in ojs34/lib/pkp/classes/plugins/PluginRegistry.php:203
Stack trace:
#0 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(219): PKP\plugins\PluginRegistry::_instantiatePlugin()
#1 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\plugins\PluginRegistry::_loadFromDatabase()
#2 ojs34/lib/pkp/classes/template/PKPTemplateManager.php(1392): PKP\plugins\PluginRegistry::loadCategory()
#3 ojs34/lib/pkp/classes/plugins/Plugin.php(403): PKP\template\PKPTemplateManager::getManager()
#4 ojs34/lib/pkp/classes/plugins/Plugin.php(137): PKP\plugins\Plugin->_registerTemplateResource()
#5 ojs34/lib/pkp/classes/plugins/LazyLoadPlugin.php(34): PKP\plugins\Plugin->register()
#6 ojs34/plugins/generic/recommendBySimilarity/RecommendBySimilarityPlugin.php(39): PKP\plugins\LazyLoadPlugin->register()
#7 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(76): APP\plugins\generic\recommendBySimilarity\RecommendBySimilarityPlugin->register()
#8 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(121): PKP\plugins\PluginRegistry::register()
#9 [internal function]: PKP\plugins\PluginRegistry::PKP\plugins\{closure}()
#10 ojs34/lib/pkp/classes/plugins/PluginRegistry.php(121): array_walk_recursive()
#11 ojs34/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory()
#12 ojs34/lib/pkp/classes/core/PKPApplication.php(387): PKP\core\Dispatcher->dispatch()
#13 ojs34/index.php(21): PKP\core\PKPApplication->execute()
#14 {main}
`````

**Comment by bozana** [comment]
Hmmm... What is with those plugins, do you have them?
Would it be possible for you to disable the plugins just for a short time, to try to assign DOI then?
Also maybe: when you use `AssignDOIs`, do you see a new DOI inserted in the DB table `dois`?
If you use dev tools in your browser, do you see anything there, e.g. is everything OK under "network"?
Hmmmm... :thinking:

**Comment by shantanu198713** [comment]
Hi @bozana 

I have tested it on the server. below is the snapshot of the `dev tools`.

`````
{
  "error": "api.404.endpointNotFound",
  "errorMessage": "The requested URL was not recognized."
}
`````
![Screenshot 2023-09-26 140819](https://github.com/pkp/pkp-lib/assets/108086810/d41996b2-66e8-4b06-99f5-47046206280e)

**Comment by bozana** [comment]
Hi @shantanu198713, when does this error occur? At the last request listed in your screenshot, with the name "submission?stageIds..."? What do you see there as "Request URL" (under `Headers`)?
Why do you have all requests twice, have you tried two times to assign the DOI?

**Comment by jonasraoni** [comment]
@bozana FYI those are not real exceptions, I mean, they won't interrupt the code execution, see: https://github.com/pkp/pkp-lib/blob/777b10995699b8419a61f62adbceb5cfcba8522d/classes/plugins/PluginRegistry.php#L201-L205

**Comment by bozana** [comment]
Hi @jonasraoni, oh I see :-) So those plugins can be enabled/used.
The error here however seems to be: 
"error": "api.404.endpointNotFound",
"errorMessage": "The requested URL was not recognized."

**Comment by bozana** [comment]
Hi @shantanu198713, any news on this issue?

**Comment by shantanu198713** [comment]
Hi @bozana I tried several times but same problem occurred.

The main thing is that I don't know what to do next.

**Comment by bozana** [comment]
@shantanu198713, when you click on "assignDOIs" in your browser's developer tools "Network" area, can you then investigate what you see under "Headers" (e.g. what do you see as Request URL) and under "Response"? Could you check it for all requests listed there when you try to assign a DOI, also for "submissions?stageIds"?
I am trying to find out where that error message that you wrote occurs and what URL is it:
"error": "api.404.endpointNotFound",
"errorMessage": "The requested URL was not recognized."

**Comment by shantanu198713** [comment]
@bozana I have checked but I don't understand what to do, I am sharing a screenshot and a file with you, please check.

[Link to download file](https://drive.google.com/file/d/1R3-eD8S-cipd_17jWbiqqw9fi07q_6p9/view?usp=share_link).

![Screenshot 2023-10-19 173216](https://github.com/pkp/pkp-lib/assets/108086810/64f01566-49ec-4c2b-a51d-269ab2096aa9)
![Screenshot 2023-10-19 173619](https://github.com/pkp/pkp-lib/assets/108086810/dfe3f4d2-3320-4941-8fe3-65b83c5cbd4e)
![Screenshot 2023-10-19 173152](https://github.com/pkp/pkp-lib/assets/108086810/8081124b-8ffc-4a7b-9863-ee934639bf77)

**Comment by bozana** [comment]
Hmm... @shantanu198713, I do not see any errors there... Hmmmm...
Where did you see this error:
"error": "api.404.endpointNotFound",
"errorMessage": "The requested URL was not recognized."
?

**Comment by bozana** [comment]
@shantanu198713, I will close this issue for now, because we cannot reproduce it and I do not know what error you get... but please feel free to re-open it if you figure out more...
Thanks!
