### ISSUE TITLE
Add support for early and continuous access to version of record (continuous publication)

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9295]
**Describe the bug**

As an Editor, I would like to be able to publish the work of authors as early as possible rather than waiting for a complete issue to be ready for simultaneous publication.

- I may want to schedule an article for an issue, but still have it available in advance of the issue’s formal publication. (I may want to use issue scheduling as organizational method for when I have a lot of articles awaiting posting.)
- I may or may not want to designate an issue at all, for example my journal may organize content through thematic areas (categories) and have no use at all for issues.
- I may decide to publish e.g. quarterly issues based on some of the content that has been posted early; this may mean going through already-posted content and publishing a formal issue based on things that have already been made available online. (For articles, this will mean that previously issueless content will have an issue.)
- I would like major functions e.g. DOIs to function in a predictable way regardless of the mix of the above.

To be determined:
- Implications for integrations – see sprint log (Hanover 2023)
- Upgrade path
- Publication dates may be a problem.

Of interest but out of scope for this issue:
- Open reviews
- Making non-final versions of articles available early
- Reconciling preprint functionality in OJS with OPS

**Comment by radjr2** [comment]
We are interested in this and decided that OJS could support this as long as continuous page numbering was not used. eg page numbers restart at 1 for each issue. That way, we can assign articles to a defined issue with real page numbers and point the active issue to the current calendar issue while the published future issues are still available. What would make this really possible is if the future calendar issues could be hidden in some way or displayed some where else. We like this model as the page numbers are set as soon as they are added to the issue. That all said, a more defined process that allows continuous numbering would be great.

**Comment by pmangahis** [comment]
Flagging this as an issue that would need to be solved - https://github.com/pkp/pkp-lib/issues/8998 in order to support the continuous publication model.

**Comment by asmecher** [comment]
(See also NISO JAV revision for terminology around versions: https://www.niso.org/press-releases/nisos-draft-revision-journal-article-version-jav-recommended-practice-now-open)

**Comment by radjr2** [comment]
Thanks Alec.


What PKP's plans to support multiple revisions and preprints?


Cheers!


Richard A. DeVito, Jr

Publisher

Weston Medical Publishing, LLC

470 Boston Post Road, Suite 301

Weston, MA 02493

www.wmpllc.org<http://www.wmpllc.org> - ***@***.***

781-899-2702 Ext. 107

339-222-4364 Cell


________________________________

**Comment by touhidurabir** [comment]
@asmecher I have addressed the review points and tests are passing now . please take a second look at the PRs at https://github.com/pkp/pkp-lib/issues/9295#issue-1890658760 .

**Comment by radjr2** [comment]
Sorry for the Nubie question.


It is tough to locate and comprehend the design and goal of this 9295. Is there a design spec somewhere that defines how you want the continuous publishing model to work on OJS?  I am happy to help or test but without a design spec, I really have no clue how to help or get involved. Maybe I need a primer course on github too!


Cheers!


Richard A. DeVito, Jr

Publisher

Weston Medical Publishing, LLC

470 Boston Post Road, Suite 301

Weston, MA 02493

www.wmpllc.org<http://www.wmpllc.org> - ***@***.***

781-899-2702 Ext. 107

339-222-4364 Cell


________________________________

**Comment by asmecher** [comment]
Thanks, @touhidurabir!

I think a few additional changes are required:
- Instead of an entry in `publication_settings` called `continuousPublication`, create a new column called `published` in `publications` (similar to the `published` column in `issues` for OJS). This will need a migration for existing content; you can set it the same as the `published` column in `issues` (joining on `publications.issue_id` = `issues.issue_id`). This is just for OJS.
- Change `ArticleHandler.php` to allow access to content with `publications.published = 1`, not just `issues.published = 1`.
- I've added a quick comment on coding conventions [on the OJS PR as well](https://github.com/pkp/ojs/pull/4875#discussion_r2129194119).

**Comment by touhidurabir** [comment]
@asmecher ready for review .

**Comment by asmecher** [comment]
Thanks, @touhidurabir -- I've added some comments to a few of the PRs. Once you've had a chance to work through those and rebase, I suggest we set up a meeting with Devika to look over the design questions.

**Comment by asmecher** [comment]
@touhidurabir, thanks, I've merged all those PRs (or manually updated the submodules in the case of OMP and OPS).

I'll leave this issue open until we can work through the UI parts that need adjustment.

Can you have a look at the QuickSubmit plugin? Its tests are failing, even after the datasets successfully updated.

**Comment by kaitlinnewson** [comment]
Hi @touhidurabir, I know this is still in-progress, but in case you aren't aware of it, the current changes made in `main` for this seem to be breaking the index page when a different theme has been enabled (Immersion in this case), with the following error:

```
[Fri Jul  4 15:22:19 2025] [::1]:52232 [500]: GET /index.php/publicknowledge/en/index - Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, bool given in /Users/kaitlinnewson/Code/ojs-main/pages/index/IndexHandler.php:80
Stack trace:
#0 /Users/kaitlinnewson/Code/ojs-main/pages/index/IndexHandler.php(80): in_array(3, false)
#1 [internal function]: APP\pages\index\IndexHandler->index(Array, Object(APP\core\Request))
#2 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/core/PKPRouter.php(327): call_user_func(Array, Array, Object(APP\core\Request))
#3 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/core/PKPPageRouter.php(249): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#4 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/core/Dispatcher.php(157): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#5 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/core/PKPApplication.php(431): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#6 /Users/kaitlinnewson/Code/ojs-main/index.php(21): PKP\core\PKPApplication->execute()
#7 {main}
  thrown in /Users/kaitlinnewson/Code/ojs-main/pages/index/IndexHandler.php on line 80
```

I assume the themes just need to be updated to reflect this new option, but wanted to note it here in case more is needed (e.g. handling the missing option).

**Comment by touhidurabir** [comment]
@asmecher tests are finally passing, can you please review the PRs at https://github.com/pkp/pkp-lib/issues/9295#issue-1890658760 . Commits need some squashing and will do after the review . 
BTW , QuickSubmit plugin need some update and working on that .

**Comment by asmecher** [comment]
Thanks, @touhidurabir, I've sent in reviews to the PRs at the head comment!

**Comment by asmecher** [comment]
@touhidurabir, I've merged all the PRs, thanks! There are still a few clean-up elements needing addressing in `main`:

- I still see a few unresolved comments from Jarda here: https://github.com/pkp/ui-library/pull/683/files
- The `Issues` sidebar menu item should be moved into `Content`, now that we have that top-level menu
- You had mentioned cleaning out the PHP-side implementation of the issue form.

**Comment by touhidurabir** [comment]
@asmecher @jardakotesovec can you please review the cleanup PRs at https://github.com/pkp/pkp-lib/issues/9295#issue-1890658760 . This is mostly remove the issue selection server side code and fully now use the client side implementation .

**Comment by asmecher** [comment]
@touhidurabir, thanks, I've added my approvals -- but this is mostly for @jardakotesovec to review for the changed approach on the VueJS side.

**Comment by touhidurabir** [comment]
Merged all the `cleanup` PRs for OJS/OMP/OPS main branch , confirming that before merge all tests for all 3 apps in the main branch was passing .

**Comment by touhidurabir** [comment]
@Tribunal33 does it need QA test before closing ?

**Comment by Tribunal33** [comment]
@touhidurabir I would like to echo this comment : https://github.com/pkp/pkp-lib/issues/9295#issuecomment-2935608080

I'm not seeing what to test.  There is no A/C or requirements or design specs to reference.  Maybe this is part of another ticket?

**Comment by asmecher** [comment]
@Tribunal33 Let's talk about testing on this one today -- I think otherwise it's ready to be closed.

**Comment by radjr2** [comment]
How do we get Alec's attention to ask a couple of technical questions please?

Also, where would I find the road map for continuous publishing?

Thanks!

**Comment by asmecher** [comment]
Hi @radjr2 -- just a heads-up that replies to Github notifications are posted [on the public Github issue](https://github.com/pkp/pkp-lib/issues/9295), which might not be what you intend. The best place to get hold of me is probably private message on the [PKP support forum](https://forum.pkp.sfu.ca/).

**Comment by radjr2** [comment]
Thanks. Still looking for the road map that is guiding the development of the continuous publishing updates to OJS.


Don't know remember how to PM you on the forum. Sorry!

**Comment by Tribunal33** [comment]
@asmecher I will try to get this closed today.  I have a plan and will post the test scenarios for this feature for future.

**Comment by Tribunal33** [comment]
This passes QA.  

Here are the test scenarios.
1. Test basic functionality of continuous publication
2. Test Journal Content Organization Setting Include the Current issue's table of contents
3. Test Journal Content Organization Setting Include recent most published articles
4. Test Journal Content Organization Setting Include a listing of Categories
5. Test Journal Content Organization Setting Multiple options 
6. Test Journal that has no issues.  
7. Test Issue Assignment - Don't Assign to an issue
8. Test Issue Assignment - Assign to future issue and schedule only
9. Test Issue Assignment - Assign to future issue and Publish immediately
10. Test Issue Assignment - Assign to Current/Back issues (default)
11. Test Publication Issue Don't Assign to an Issue
12. Test Publication Issue Assign to Future issue and Publish immediately
13. Test Publication Issue Assign to Future issue and Schedule only
14. Test Publication issue Assign to Current/Back issue
15. Test Publication Issue assignement selection is maintained on schedule for publication Issue Assignment
16. Test for OMP ->This should not exist (button to schedule in lower stages or options to display as issueless)
17. Test for OPS -> This should not exist (button to schedule in lower stages or options to display as issueless)
