### ISSUE TITLE
[OJS 3.3.0-15] Generation of PKP Usage Statistics Report fails with 500 HTTP error

### ISSUE THREAD

**Issue by kswro** [pkp/pkp-lib#9316]
**Describe the bug**
I got an HTTP 500 Error message when trying to generate Usage Statistics Report.

**To Reproduce**
1. Login to Admin Area
2. Click "Reports" from Statistics section
3. Click "PKP Usage statistics report"
4. HTTP ERROR 500

**What application are you using?**
 OJS 3.3.0-15

**Additional Information**
PHP 7.4.33

**Log**
```
[22-Sep-2023 16:13:57 Asia/Jakarta] PHP Warning:  array_key_exists() expects parameter 2 to be array, string given in /home/.../public_html/classes/statistics/MetricsDAO.inc.php on line 28
[22-Sep-2023 16:13:57 Asia/Jakarta] PHP Warning:  array_search() expects parameter 2 to be array, string given in /home/.../public_html/classes/statistics/MetricsDAO.inc.php on line 32
[22-Sep-2023 16:13:57 Asia/Jakarta] PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /home/.../public_html/classes/statistics/MetricsDAO.inc.php:34
Stack trace:
#0 /home/.../public_html/plugins/generic/usageStats/PKPUsageStatsReportPlugin.inc.php(84): MetricsDAO->getMetrics()
#1 /home/.../public_html/plugins/generic/usageStats/OJSUsageStatsReportPlugin.inc.php(32): PKPUsageStatsReportPlugin->getMetrics()
#2 /home/.../public_html/lib/pkp/pages/stats/PKPStatsHandler.inc.php(524): OJSUsageStatsReportPlugin->getMetrics()
#3 /home/.../public_html/lib/pkp/pages/stats/PKPStatsHandler.inc.php(403): PKPStatsHandler->generateReport()
#4 /home/.../public_html/lib/pkp/classes/core/PKPRouter.inc.php(397): PKPStatsHandler->reports()
#5 /home/.../public_html/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest()
#6 /home/.../public_html/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPPageRouter->route()
#7 /home/.../public_html/lib/pkp/classes/core/PKPAppl in /home/.../public_html/classes/statistics/MetricsDAO.inc.php on line 34
```

**Comment by kswro** [comment]
Oh, sorry. This appears to be caused by my firewall sanitizing the url query.
