### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array

### ISSUE THREAD

**Issue by janevsky** [pkp/pkp-lib#9450]
**Describe the bug**
Getting a php fatal error on submission step 1 when clicking save and continue without selecting category section. There is no notification "Please select an appropriate journal section for this submission." because the site keeps loading, and it should refresh and show the notification on the right and additional info under section selection. After a manual refresh the notification pops up. I've tested it on my old version 3.3.0-11 and its working as it should.

**To Reproduce**
1. Click on New submission 
2. Check everything in Submission Requirements and Corresponding Contact, leave sections empty.
3. Scroll down to Save and continue (without section selected)
4. Site keeps loading and the error occurs

**What application are you using?**
OJS version 3.3.0-14
PHP version 8.0.26

**Additional information**
PHP error log:
`[23-Oct-2023 00:19:23 Europe/Ljubljana] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /home/xxx/domains/XXXdomainXXX/public_html/cache/t_compile/f3f61f20c8cf263a6a0dca9d99469f9f95568d26^4ef1996850f75e89a53007d1a8243f48d8f4148f_0.app.submissionformcategories..php:24
Stack trace:
#0 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6532454bdff141_16311372()
#1 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#2 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#3 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#4 /home/xxx/domains/XXXdomainXXX/public_html/cache/t_compile/f3f61f20c8cf263a6a0dca9d99469f9f95568d26^c7d6d017cda209d97dfa69aba1e0226666e0255e_0.core.submissionformstep1.tpl.php(66): Smarty_Internal_Template->_subTemplateRender()
#5 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6532454bdd8c58_88114758()
#6 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#7 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#8 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#9 /home/xxx/domains/XXXdomainXXX/public_html/cache/t_compile/f3f61f20c8cf263a6a0dca9d99469f9f95568d26^d4a7db69d40565910b7236a1c96ad325268f4ab6_0.app.submissionformstep1.tpl.php(52): Smarty_Internal_Template->_subTemplateRender()
#10 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6532454bd90c63_02565143()
#11 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#12 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#13 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render()
#14 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute()
#15 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/classes/template/PKPTemplateManager.inc.php(1075): Smarty_Internal_TemplateBase->fetch()
#16 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/classes/form/Form.inc.php(197): PKPTemplateManager->fetch()
#17 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/classes/submission/form/SubmissionSubmitForm.inc.php(69): Form->fetch()
#18 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/classes/submission/form/PKPSubmissionSubmitStep1Form.inc.php(179): SubmissionSubmitForm->fetch()
#19 /home/xxx/domains/XXXdomainXXX/public_html/classes/submission/form/SubmissionSubmitStep1Form.inc.php(63): PKPSubmissionSubmitStep1Form->fetch()
#20 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/pages/submission/PKPSubmissionHandler.inc.php(198): SubmissionSubmitStep1Form->fetch()
#21 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/classes/core/PKPRouter.inc.php(395): PKPSubmissionHandler->saveStep()
#22 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest()
#23 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPPageRouter->route()
#24 /home/xxx/domains/XXXdomainXXX/public_html/lib/pkp/classes/core/PKPApplication.inc.php(363): Dispatcher->dispatch()
#25 /home/xxx/domains/XXXdomainXXX/public_html/index.php(68): PKPApplication->execute()
#26 {main}
  thrown in /home/xxx/domains/XXXdomainXXX/public_html/cache/t_compile/f3f61f20c8cf263a6a0dca9d99469f9f95568d26^4ef1996850f75e89a53007d1a8243f48d8f4148f_0.app.submissionformcategories..php on line 24`

Apache logs:
`[23/Oct/2023:00:19:23 +0200] "POST /xxx/submission/saveStep/1 HTTP/1.1" 500 796 "https://XXXdomainXXX/xxx/submission/wizard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"`

f3f61f20c8cf263a6a0dca9d99469f9f95568d26^4ef1996850f75e89a53007d1a8243f48d8f4148f_0.app.submissionformcategories..php:24 contains:
```
<?php
/* Smarty version 3.1.39, created on 2023-10-20 11:15:55
  from 'app:submissionformcategories.' */

/* @var Smarty_Internal_Template $_smarty_tpl */
if ($_smarty_tpl->_decodeProperties($_smarty_tpl, array (
  'version' => '3.1.39',
  'unifunc' => 'content_6532454bdff141_16311372',
  'has_nocache_code' => false,
  'file_dependency' => 
  array (
    '4ef1996850f75e89a53007d1a8243f48d8f4148f' => 
    array (
      0 => 'app:submissionformcategories.',
      1 => 1660032999,
      2 => 'app',
    ),
  ),
  'includes' => 
  array (
  ),
),false)) {
function content_6532454bdff141_16311372 (Smarty_Internal_Template $_smarty_tpl) {
if (count($_smarty_tpl->tpl_vars['categories']->value)) {?>
	<?php if ($_smarty_tpl->tpl_vars['readOnly']->value) {?>
		<?php $_block_plugin13 = isset($_smarty_tpl->smarty->registered_plugins['block']['fbvFormSection'][0][0]) ? $_smarty_tpl->smarty->registered_plugins['block']['fbvFormSection'][0][0] : null;
if (!is_callable(array($_block_plugin13, 'smartyFBVFormSection'))) {
throw new SmartyException('block tag \'fbvFormSection\' not callable or registered');
}
$_smarty_tpl->smarty->_cache['_tag_stack'][] = array('fbvFormSection', array('title'=>"grid.category.categories",'list'=>true));
$_block_repeat=true;
echo $_block_plugin13->smartyFBVFormSection(array('title'=>"grid.category.categories",'list'=>true), null, $_smarty_tpl, $_block_repeat);
while ($_block_repeat) {
ob_start();?>
			<?php
$_from = $_smarty_tpl->smarty->ext->_foreach->init($_smarty_tpl, $_smarty_tpl->tpl_vars['categories']->value, 'category', false, 'id');
$_smarty_tpl->tpl_vars['category']->do_else = true;
if ($_from !== null) foreach ($_from as $_smarty_tpl->tpl_vars['id']->value => $_smarty_tpl->tpl_vars['category']->value) {
$_smarty_tpl->tpl_vars['category']->do_else = false;
?>
				<?php if (in_array($_smarty_tpl->tpl_vars['id']->value,$_smarty_tpl->tpl_vars['assignedCategories']->value)) {?>
					<li><?php echo call_user_func_array($_smarty_tpl->registered_plugins[ 'modifier' ][ 'escape' ][ 0 ], array( $_smarty_tpl->tpl_vars['category']->value->getLocalizedTitle() ));?>
</li>
				<?php }?>
			<?php
}
$_smarty_tpl->smarty->ext->_foreach->restore($_smarty_tpl, 1);?>
		<?php $_block_repeat=false;
echo $_block_plugin13->smartyFBVFormSection(array('title'=>"grid.category.categories",'list'=>true), ob_get_clean(), $_smarty_tpl, $_block_repeat);
}
array_pop($_smarty_tpl->smarty->_cache['_tag_stack']);?>
	<?php } else { ?>
		<?php $_block_plugin14 = isset($_smarty_tpl->smarty->registered_plugins['block']['fbvFormSection'][0][0]) ? $_smarty_tpl->smarty->registered_plugins['block']['fbvFormSection'][0][0] : null;
if (!is_callable(array($_block_plugin14, 'smartyFBVFormSection'))) {
throw new SmartyException('block tag \'fbvFormSection\' not callable or registered');
}
$_smarty_tpl->smarty->_cache['_tag_stack'][] = array('fbvFormSection', array('list'=>true,'title'=>"grid.category.categories"));
$_block_repeat=true;
echo $_block_plugin14->smartyFBVFormSection(array('list'=>true,'title'=>"grid.category.categories"), null, $_smarty_tpl, $_block_repeat);
while ($_block_repeat) {
ob_start();?>
			<?php
$_from = $_smarty_tpl->smarty->ext->_foreach->init($_smarty_tpl, $_smarty_tpl->tpl_vars['categories']->value, 'category', false, 'id');
$_smarty_tpl->tpl_vars['category']->do_else = true;
if ($_from !== null) foreach ($_from as $_smarty_tpl->tpl_vars['id']->value => $_smarty_tpl->tpl_vars['category']->value) {
$_smarty_tpl->tpl_vars['category']->do_else = false;
?>
				<?php echo call_user_func_array( $_smarty_tpl->smarty->registered_plugins[Smarty::PLUGIN_FUNCTION]['fbvElement'][0], array( array('type'=>"checkbox",'id'=>"categories[]",'value'=>$_smarty_tpl->tpl_vars['id']->value,'checked'=>in_array($_smarty_tpl->tpl_vars['id']->value,$_smarty_tpl->tpl_vars['assignedCategories']->value),'label'=>call_user_func_array($_smarty_tpl->registered_plugins[ 'modifier' ][ 'escape' ][ 0 ], array( $_smarty_tpl->tpl_vars['category']->value )),'translate'=>false),$_smarty_tpl ) );?>

			<?php
}
$_smarty_tpl->smarty->ext->_foreach->restore($_smarty_tpl, 1);?>
		<?php $_block_repeat=false;
echo $_block_plugin14->smartyFBVFormSection(array('list'=>true,'title'=>"grid.category.categories"), ob_get_clean(), $_smarty_tpl, $_block_repeat);
}
array_pop($_smarty_tpl->smarty->_cache['_tag_stack']);?>
	<?php }
}
}
}
```

Networking tab dev tools:
![image](https://github.com/pkp/pkp-lib/assets/63719545/1a38a793-6d8a-436a-87cd-23c5f5a0bf48)

After manual refresh notification pops up:
![image](https://github.com/pkp/pkp-lib/assets/63719545/3c678d55-d386-46bc-9834-46393d391acf)

Don't know if this is related to this fatal error but I got this also:
`[20-Oct-2023 08:39:48 Europe/Ljubljana] PHP Warning:  Undefined array key 1 in /home/XXX/domains/xxxDOMAINxxx/public_html/pages/article/ArticleHandler.inc.php on line 50`

**Comment by touhidurabir** [comment]
@Vitaliy-1 can you check the PRs 

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9460
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4085 [TEST ONLY]

**Comment by janevsky** [comment]
> @Vitaliy-1 can you check the PRs
> 
> [pkp-lib](https://github.com/pkp/pkp-lib) --> #9460 [ojs](https://github.com/pkp/ojs) --> [pkp/ojs#4085](https://github.com/pkp/ojs/pull/4085) [TEST ONLY]

@touhidurabir I can confirm this fixes the problem with the refresh on the form, showing notification on the top right corner and adds message under category selection input as required. This is a 3.3.0-11 updated to 3.3.0-14 version running php 8.

Thank you!

**Comment by asmecher** [comment]
Merged! No cherry-picking forward is required, we think -- but @touhidurabir will double-check.

**Comment by touhidurabir** [comment]
@asmecher @Vitaliy-1 confirmed this issue does not arise for `3.4.0` and `main` .

**Comment by asmecher** [comment]
Thanks, @touhidurabir!
