### ISSUE TITLE
Error updating version 3.0.2.0 to version 3.3.0.15

### ISSUE THREAD

**Issue by tiagosiqueira1** [pkp/pkp-lib#9454]
Hello, I'm trying to update the version of my ojs 3.0.2.0 to version 3.3.0.15 using /tools/upgrade.php however the following error is appearing. 

tiagosiqueira@tunisia:/var/www/html/tools$ sudo php upgrade.php upgrade
2023-10-23 13:48:54 [pre-install]
2023-10-23 13:48:54 [load: upgrade.xml]
2023-10-23 13:48:54 [version: 3.3.0.15]
2023-10-23 13:48:54 [code: Installer Installer::checkPhpVersion]
2023-10-23 13:48:54 [data: dbscripts/xml/upgrade/3.1.0_preupdate_review_assignments.xml]
2023-10-23 13:48:54 [data: dbscripts/xml/upgrade/3.1.0_preupdate_notes.xml (skipped)]
2023-10-23 13:48:54 [data: dbscripts/xml/upgrade/3.1.0_preupdate_payments.xml]
2023-10-23 13:48:54 [data: dbscripts/xml/upgrade/3.1.1_preupdate_citations.xml]
2023-10-23 13:48:54 [data: dbscripts/xml/upgrade/3.1.2_preupdate_user_author_names.xml]
2023-10-23 13:48:54 [data: dbscripts/xml/upgrade/3.2.0_preupdate_email_templates.xml]
2023-10-23 13:48:54 [data: dbscripts/xml/upgrade/3.2.0_preupdate_versioning_articleGalleySettings.xml (skipped)]
2023-10-23 13:48:54 [data: dbscripts/xml/upgrade/3.2.0_preupdate_versioning.xml]
2023-10-23 13:48:55 [data: dbscripts/xml/upgrade/3.2.0_preupdate_last_activity.xml]
2023-10-23 13:48:55 [schema: lib/pkp/xml/schema/common.xml]
2023-10-23 13:48:56 [schema: lib/pkp/xml/schema/log.xml]
2023-10-23 13:48:56 [schema: lib/pkp/xml/schema/announcements.xml]
2023-10-23 13:48:56 [schema: lib/pkp/xml/schema/scheduledTasks.xml]
2023-10-23 13:48:56 [schema: lib/pkp/xml/schema/temporaryFiles.xml]
2023-10-23 13:48:56 [schema: lib/pkp/xml/schema/metadata.xml]
2023-10-23 13:48:57 [schema: lib/pkp/xml/schema/reviews.xml]
2023-10-23 13:48:57 [schema: lib/pkp/xml/schema/reviewForms.xml]
2023-10-23 13:48:57 [schema: lib/pkp/xml/schema/controlledVocab.xml]
2023-10-23 13:48:57 [schema: lib/pkp/xml/schema/submissions.xml]
2023-10-23 13:48:58 [schema: lib/pkp/xml/schema/submissionFiles.xml]
2023-10-23 13:48:59 [schema: lib/pkp/xml/schema/categories.xml]
2023-10-23 13:48:59 [schema: lib/pkp/xml/schema/notes.xml]
2023-10-23 13:48:59 [schema: lib/pkp/xml/schema/genres.xml]
2023-10-23 13:48:59 [schema: lib/pkp/xml/schema/tombstone.xml]
2023-10-23 13:48:59 [schema: lib/pkp/xml/schema/rolesAndUserGroups.xml]
2023-10-23 13:48:59 [schema: lib/pkp/xml/schema/metrics.xml]
2023-10-23 13:49:01 [schema: lib/pkp/xml/schema/views.xml]
2023-10-23 13:49:01 [schema: lib/pkp/xml/schema/libraryFiles.xml]
2023-10-23 13:49:01 [schema: lib/pkp/xml/schema/navigationMenus.xml]
2023-10-23 13:49:01 [schema: dbscripts/xml/ojs_schema.xml]
2023-10-23 13:49:02 [code: Installer Installer::installDefaultNavigationMenus]
PHP Notice: unserialize(): Error at offset 225 of 1207 bytes in /var/www/html/lib/pkp/classes/db/DAO.inc.php on line 254
2023-10-23 13:49:02 [code: Installer Installer::migrateStaticPagesToNavigationMenuItems]
PHP Notice: unserialize(): Error at offset 225 of 1207 bytes in /var/www/html/lib/pkp/classes/db/DAO.inc.php on line 254
2023-10-23 13:49:02 [code: Installer Installer::migrateSRLocale]
2023-10-23 13:49:02 [code: Installer Installer::migrateUserAndAuthorNames]
PHP Notice: unserialize(): Error at offset 225 of 1207 bytes in /var/www/html/lib/pkp/classes/db/DAO.inc.php on line 254
2023-10-23 13:49:02 [code: Installer Installer::migrateSubmissionCoverImages]
2023-10-23 13:49:02 [code: Installer Installer::installEmailTemplate]
2023-10-23 13:49:02 [data: dbscripts/xml/upgrade/3.1.0_update_a.xml]
2023-10-23 13:49:02 [code: Installer Installer::fixGenreIdInFileNames]
PHP Notice: unserialize(): Error at offset 225 of 1207 bytes in /var/www/html/lib/pkp/classes/db/DAO.inc.php on line 254
**PHP Fatal error: Uncaught Exception: A file assigned to the file stage 8 could not be migrated. in /var/www/html/classes/install/Upgrade.inc.php:1209**
Stack trace:
#0 /var/www/html/classes/install/Upgrade.inc.php(657): Upgrade->_fileStageToPath()
#1 /var/www/html/lib/pkp/classes/install/Installer.inc.php(445): Upgrade->fixGenreIdInFileNames()
#2 /var/www/html/lib/pkp/classes/install/Installer.inc.php(252): Installer->executeAction()
#3 /var/www/html/lib/pkp/classes/install/Installer.inc.php(175): Installer->executeInstaller()
#4 /var/www/html/lib/pkp/classes/cliTool/UpgradeTool.inc.php(89): Installer->execute()
#5 /var/www/html/lib/pkp/classes/cliTool/UpgradeTool.inc.php(65): UpgradeTool->upgrade()
#6 /var/www/html/tools/upgrade.php(22): UpgradeTool->execute()
#7 {main}
thrown in /var/www/html/classes/install/Upgrade.inc.php on line 1209

**Comment by asmecher** [comment]
@tiagosiqueira1, could you start with our support forum (https://forum.pkp.sfu.ca) rather than here?
