### ISSUE TITLE
OJS - HTTP error 500 from the link in the Review Request Email

### ISSUE THREAD

**Issue by plothost** [pkp/pkp-lib#9508]
**Describe the bug**
The accept or decline link {$reviewAssignmentUrl} in the "Review Request" email is giving 500 HTTP error if the user is not already logged in. If the user is already logged in, everything is fine.

**To Reproduce**
Click on the accept or decline link in the "Review Request" email

**What application are you using?**
OJS 3.4.0.3 / PHP 8.0.30

**Additional information**
[Mon Nov 13 15:41:39.923754 2023] [proxy_fcgi:error] [pid 28666:tid 139962671789824] [remote x.x.x.x:59842] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getAuthorizedContextObject() on null in /home/user/domains/domain.com/public_html/lib/pkp/classes/handler/PKPHandler.php:190\nStack trace:\n#0 /home/user/domains/domain.com/public_html/pages/reviewer/ReviewerHandler.php(108): PKP\\handler\\PKPHandler->getAuthorizedContextObject()\n#1 /home/user/domains/domain.com/public_html/pages/reviewer/ReviewerHandler.php(67): APP\\pages\\reviewer\\ReviewerHandler->_validateAccessKey()\n#2 /home/user/domains/domain.com/public_html/lib/pkp/classes/core/PKPRouter.php(324): APP\\pages\\reviewer\\ReviewerHandler->authorize()\n#3 /home/user/domains/domain.com/public_html/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest()\n#4 /home/user/domains/domain.com/public_html/lib/pkp/classes/core/Dispatcher.php(165): PKP\\core\\PKPPageRouter->route()\n#5 /home/user/domains/domain.com/public_html/lib/pkp/classes/core/PKPApplication.php(...'

**Comment by plothost** [comment]
I found that this was fixed in https://github.com/pkp/ojs/commit/537d5d86fda2783ec03d6e6e6ff6c7dd69d15af6
Hopefully, we'll see it in 3.4.0.4
