### ISSUE TITLE
Missing Review Assignment Repo in OPS

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#9521]
**Describe the bug**
Fatal error during testing:
```
Error: Call to undefined method APP\facades\Repo::reviewAssignment() in /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/classes/submission/maps/Schema.php:223
Stack trace:
#0 /Users/vitalii/Documents/development/ops-main/ops/classes/submission/maps/Schema.php(26): PKP\submission\maps\Schema->mapByProperties(Array, Object(APP\submission\Submission))
#1 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/classes/submission/maps/Schema.php(98): APP\submission\maps\Schema->mapByProperties(Array, Object(APP\submission\Submission))
#2 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/api/v1/submissions/PKPSubmissionController.php(601): PKP\submission\maps\Schema->map(Object(APP\submission\Submission), Object(Illuminate\Support\LazyCollection), Array)
#3 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Routing/CallableDispatcher.php(40): PKP\API\v1\submissions\PKPSubmissionController->add(Object(Illuminate\Http\Request), 'publicknowledge', 'v1')
#4 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Routing/Route.php(237): Illuminate\Routing\CallableDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Closure))
#5 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Routing/Route.php(208): Illuminate\Routing\Route->runCallable()
#6 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\Routing\Route->run()
#7 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/classes/middleware/HasRoles.php(69): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): PKP\middleware\HasRoles->handle(Object(Illuminate\Http\Request), Object(Closure), Object(Illuminate\Support\Collection))
#10 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/classes/middleware/HasContext.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): PKP\middleware\HasContext->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/classes/middleware/HasUser.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): PKP\middleware\HasUser->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#17 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#18 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#19 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/classes/handler/APIHandler.php(64): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): PKP\handler\APIHandler->PKP\handler\{closure}(Object(Illuminate\Http\Request))
#21 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/classes/middleware/PolicyAuthorizer.php(71): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): PKP\middleware\PolicyAuthorizer->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/classes/middleware/ValidateCsrfToken.php(46): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): PKP\middleware\ValidateCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/classes/middleware/DecodeApiTokenWithValidation.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): PKP\middleware\DecodeApiTokenWithValidation->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/classes/middleware/SetupContextBasedOnRequestUrl.php(65): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): PKP\middleware\SetupContextBasedOnRequestUrl->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/classes/middleware/AllowCrossOrigin.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): PKP\middleware\AllowCrossOrigin->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/classes/handler/APIHandler.php(63): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#41 /Users/vitalii/Documents/development/ops-main/ops/api/v1/submissions/index.php(27): PKP\handler\APIHandler->__construct(Object(APP\API\v1\submissions\SubmissionController))
#42 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/classes/core/APIRouter.php(103): require('/Users/vitalii/...')
#43 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/classes/core/Dispatcher.php(167): PKP\core\APIRouter->route(Object(APP\core\Request))
#44 /Users/vitalii/Documents/development/ops-main/ops/lib/pkp/classes/core/PKPApplication.php(378): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#45 /Users/vitalii/Documents/development/ops-main/ops/index.php(21): PKP\core\PKPApplication->execute()
#46 {main}
```

**What application are you using?**
OPS main branch

**Comment by Vitaliy-1** [comment]
PR OPS: https://github.com/pkp/ops/pull/595
