### ISSUE TITLE
Fatal error after upgrade because of missing highlights table

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#9534]
**Describe the bug**
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ojs-themes.highlights' doesn't exist in /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:416
Stack trace:
#0 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): PDO->prepare('select `h`.* fr...')
#1 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(809): Illuminate\Database\Connection->Illuminate\Database\{closure}('select `h`.* fr...', Array)
#2 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(776): Illuminate\Database\Connection->runQueryCallback('select `h`.* fr...', Array, Object(Closure))
#3 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(407): Illuminate\Database\Connection->run('select `h`.* fr...', Array, Object(Closure))
#4 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2751): Illuminate\Database\Connection->select('select `h`.* fr...', Array, true)
#5 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2740): Illuminate\Database\Query\Builder->runSelect()
#6 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3294): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2739): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#8 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/highlight/DAO.php(98): Illuminate\Database\Query\Builder->get()
#9 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/highlight/Collector.php(66): PKP\highlight\DAO->getMany(Object(PKP\highlight\Collector))
#10 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/pages/index/PKPIndexHandler.php(75): PKP\highlight\Collector->getMany()
#11 /Users/vitalii/Documents/development/ojs-main/ojs/pages/index/IndexHandler.php(64): PKP\pages\index\PKPIndexHandler->getHighlights(Object(APP\journal\Journal))
#12 [internal function]: APP\pages\index\IndexHandler->index(Array, Object(APP\core\Request))
#13 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPRouter.php(338): call_user_func(Array, Array, Object(APP\core\Request))
#14 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPPageRouter.php(279): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#15 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/Dispatcher.php(167): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#16 /Users/vitalii/Documents/development/ojs-main/ojs/lib/pkp/classes/core/PKPApplication.php(378): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#17 /Users/vitalii/Documents/development/ojs-main/ojs/index.php(21): PKP\core\PKPApplication->execute()
#18 {main}
```

**To Reproduce**
1. Upgrade from a command line from 3.3.0 to the current main
2. Go to the homepage after upgrade
3. See error

**What application are you using?**
 OJS, OMP or OPS main branch

**Comment by Vitaliy-1** [comment]
@NateWr, it looks like related to https://github.com/pkp/pkp-lib/issues/9262

**Comment by Vitaliy-1** [comment]
Migration and table description is missing for highlights, shouldn't it be under a feature flag and turned off if not ready or is there a missing commit?

**Comment by Vitaliy-1** [comment]
It seems to be resolved
