### ISSUE TITLE
Fatal error when adding reviewer

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9541]
**Describe the bug**
When trying to create a reviewer out of an existing user, the fatal error below will be shown if the user already has the reviewer role.

The main problem lies on the search, OJS 3.3 doesn't display users which are already reviewers, but OJS 3.4 has a regression.
But code that inserts unique data into the database should be more defensive, so there are two places to be fixed.
 
```php
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '186-1082' for key 'user_user_groups.user_user_groups_unique' in /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:545
Stack trace:
    #0 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(545): PDOStatement->execute()
#1 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('insert into `us...', Array)
#2 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#3 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(546): Illuminate\\Database\\Connection->run('insert into `us...', Array, Object(Closure))
#4 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(498): Illuminate\\Database\\Connection->statement('insert into `us...', Array)
#5 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3274): Illuminate\\Database\\Connection->insert('insert into `us...', Array)
#6 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1869): Illuminate\\Database\\Query\\Builder->insert(Array)
#7 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1306): Illuminate\\Database\\Eloquent\\Builder->__call('insert', Array)
#8 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1138): Illuminate\\Database\\Eloquent\\Model->performInsert(Object(Illuminate\\Database\\Eloquent\\Builder))
#9 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(986): Illuminate\\Database\\Eloquent\\Model->save()
#10 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/helpers.php(306): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}(Object(PKP\\userGroup\\relationships\\UserUserGroup))
#11 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(987): tap(Object(PKP\\userGroup\\relationships\\UserUserGroup), Object(Closure))
#12 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->create(Array)
#13 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2330): Illuminate\\Database\\Eloquent\\Model->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'create', Array)
#14 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2342): Illuminate\\Database\\Eloquent\\Model->__call('create', Array)
#15 /var/www/html/lib/pkp/classes/userGroup/Repository.php(263): Illuminate\\Database\\Eloquent\\Model::__callStatic('create', Array)
#16 /var/www/html/lib/pkp/controllers/grid/users/reviewer/form/EnrollExistingReviewerForm.php(84): PKP\\userGroup\\Repository->assignUserToGroup(1082, 186)
#17 /var/www/html/lib/pkp/classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.php(414): PKP\\controllers\\grid\\users\\reviewer\\form\\EnrollExistingReviewerForm->execute()
#18 /var/www/html/lib/pkp/classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.php(394): PKP\\controllers\\grid\\users\\reviewer\\PKPReviewerGridHandler->updateReviewer(Array, Object(APP\\core\\Request))
#19 [internal function]: PKP\\controllers\\grid\\users\\reviewer\\PKPReviewerGridHandler->enrollReviewer(Array, Object(APP\\core\\Request))
#20 /var/www/html/lib/pkp/classes/core/PKPRouter.php(334): call_user_func(Array, Array, Object(APP\\core\\Request))
#21 /var/www/html/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\\core\\Request), Array)
#22 /var/www/html/lib/pkp/classes/core/Dispatcher.php(165): PKP\\core\\PKPComponentRouter->route(Object(APP\\core\\Request))
#23 /var/www/html/lib/pkp/classes/core/PKPApplication.php(387): PKP\\core\\Dispatcher->dispatch(Object(APP\\core\\Request))
#24 /var/www/html/index.php(21): PKP\\core\\PKPApplication->execute()
#25 {main}
```

**To Reproduce**
1. Setup a submission to reach the review round
2. Click on the `Add Reviewer`
3. Click on `Enroll Existing User`
4. Search for a user which already has the reviewer role

**What application are you using?**
OJS 3.4

**Comment by Vitaliy-1** [comment]
PRs main
pkp-lib: https://github.com/pkp/pkp-lib/pull/9641
tests: https://github.com/pkp/ojs/pull/4153

(WIP, still requires fixing the search)

**Comment by Vitaliy-1** [comment]
@bozana, can you review the PR? The fix for the user group filter is tricky, because I didn't find a simpler way to aggregate data about user roles. 

The problem for excluding roles can be described in the following way - when joining 3 tables: `users`,` user_groups` and `user_user_groups`, the data is structured as:

| user_id | role_id |
|--------|--------|
| 7            | 4096   |
| 7            | 4097   |         

user with ID 7 has a reviewer role but is not being excluded with the current query `WHERE u.user_id IN (4096)`. 
What I did is aggregated a new column with information about whether the user has roles specified in the excluded roles filter. 

| user_id | role_id | roles_count|
|--------|--------|--------|
| 7            | 4096   | 1 |
| 7            | 4097   | 1  | 

Moreover, we need to extract that information depending on other user group filters, like role start and end date. That's why I've cloned the query with applied filters into the subquery with the aggregate function.

**Comment by Vitaliy-1** [comment]
Unfortunately, stable 3.4.0 depends on Laravel 9, in which `whereExists()` doesn't support Query Builder as an argument. Rewriting query for porting.
