### ISSUE TITLE
HttpClient missing when invoking PayPal

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9565]
**Describe the bug**
Invoking a PayPal interaction causes a fatal error due to a missing PHP dependency. From https://forum.pkp.sfu.ca/t/uncaught-error-interface-http-client-httpclient-not-found-when-clicking-on-apc-payment-link/83858:

```
[07-Dec-2023 17:36:49 America/New_York] PHP Fatal error:  Uncaught Error: Interface "Http\Client\HttpClient" not found in /home/jbaiiykr/public_html/plugins/paymethod/paypal/vendor/php-http/guzzle7-adapter/src/Client.php:22
Stack trace:
#0 /home/jbaiiykr/public_html/lib/pkp/lib/vendor/composer/ClassLoader.php(571): include()
#1 /home/jbaiiykr/public_html/lib/pkp/lib/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /home/jbaiiykr/public_html/plugins/paymethod/paypal/vendor/php-http/discovery/src/ClassDiscovery.php(247): class_exists()
#4 /home/jbaiiykr/public_html/plugins/paymethod/paypal/vendor/php-http/discovery/src/ClassDiscovery.php(184): Http\Discovery\ClassDiscovery::safeClassExists()
#5 /home/jbaiiykr/public_html/plugins/paymethod/paypal/vendor/php-http/discovery/src/ClassDiscovery.php(71): Http\Discovery\ClassDiscovery::evaluateCondition()
#6 /home/jbaiiykr/public_html/plugins/paymethod/paypal/vendor/php-http/discovery/src/HttpClientDiscovery.php(25): Http\Discovery\ClassDiscovery::findOneByType()
#7 /home/jbaiiykr/public_html/plugins/paymethod/paypal/vendor/omnipay/common/src/Common/Http/Client.php(34): Http\Discovery\HttpClientDiscovery::find()
#8 /home/jbaiiykr/public_html/plugins/paymethod/paypal/vendor/omnipay/common/src/Common/AbstractGateway.php(332): Omnipay\Common\Http\Client->__construct()
#9 /home/jbaiiykr/public_html/plugins/paymethod/paypal/vendor/omnipay/common/src/Common/AbstractGateway.php(69): Omnipay\Common\AbstractGateway->getDefaultHttpClient()
#10 /home/jbaiiykr/public_html/plugins/paymethod/paypal/vendor/omnipay/common/src/Common/GatewayFactory.php(88): Omnipay\Common\AbstractGateway->__construct()
#11 [internal function]: Omnipay\Common\GatewayFactory->create()
#12 /home/jbaiiykr/public_html/plugins/paymethod/paypal/vendor/omnipay/common/src/Omnipay.php(116): call_user_func_array()
#13 /home/jbaiiykr/public_html/plugins/paymethod/paypal/PaypalPaymentForm.php(55): Omnipay\Omnipay::__callStatic()
#14 /home/jbaiiykr/public_html/pages/payment/PaymentHandler.php(77): APP\plugins\paymethod\paypal\PaypalPaymentForm->display()
#15 [internal function]: APP\pages\payment\PaymentHandler->pay()
#16 /home/jbaiiykr/public_html/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()
#17 /home/jbaiiykr/public_html/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#18 /home/jbaiiykr/public_html/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter->route()
#19 /home/jbaiiykr/public_html/lib/pkp/classes/core/PKPApplication.php(388): PKP\core\Dispatcher->dispatch()
#20 /home/jbaiiykr/public_html/index.php(21): PKP\core\PKPApplication->execute()
#21 {main}
  thrown in /home/jbaiiykr/public_html/plugins/paymethod/paypal/vendor/php-http/guzzle7-adapter/src/Client.php on line 22
```

**What application are you using?**
OJS 3.4.0-4

**Comment by asmecher** [comment]
Composer dependencies need updating. To fix:
1. Apply this commit to your OJS repo: [8f075de1b25b4e5ff6c1c647a4c4ad1d16310ed8](https://github.com/pkp/ojs/commit/8f075de1b25b4e5ff6c1c647a4c4ad1d16310ed8)
2. Update the Composer dependencies:
   ```
   composer -d plugins/paymethod/paypal install
   ```
