### ISSUE TITLE
[OMP] PHP8 Incompatibility when navigating through the sidebar categories

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#9586]
**Describe the bug**
When browsing and clicking on categories of a press running under OMP, it returns an error 500 (server can't handle the request).  It seems that a constant , `ORDERBY_DATE_PUBLISHED`, is missing in the code.

**To Reproduce**
1. Go to OMP home page 
2. Click on any category on the sidebar
3. If your server is running PHP8, it returns an error
4. If you are running PHP7, the log error file will show the error

**What application are you using?**
 OMP version 3.3.0-16 (PHP8)

**Additional information**

Error log response:
## PHP8
```
Fatal error: Uncaught Error: Undefined constant "ORDERBY_DATE_PUBLISHED" in /var/www/html/lib/pkp/pages/catalog/PKPCatalogHandler.inc.php:57 Stack trace: 
 #0 /var/www/html/lib/pkp/classes/core/PKPRouter.inc.php(397): PKPCatalogHandler->category(Array, Object(Request))
 #1 /var/www/html/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)
 #2 /var/www/html/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPPageRouter->route(Object(Request))
 #3 /var/www/html/lib/pkp/classes/core/PKPApplication.inc.php(360): Dispatcher->dispatch(Object(Request))
 #4 /var/www/html/index.php(64): PKPApplication->execute()
 #5 {main} thrown in /var/www/html/lib/pkp/pages/catalog/PKPCatalogHandler.inc.php on line 57
```

## PHP7.4
```
AH01071: Got error 'PHP message: PHP Warning:  Use of undefined constant :q - assumed 'ORDERBY_DATE_PUBLISHED' (this will throw an Error in a future version of PHP)
```

**Comment by jonasraoni** [comment]
@asmecher
