### ISSUE TITLE
OJS 3.4 - Removing journal is not updating the list automatically

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#9590]
**Describe the bug**
When a journal is removed from a multi-journal OJS installation, neither the modal closes nor the list is automatically updated. It seems that the request doesn't work at all.

**To Reproduce**
1. Go to 'Administration'
2. Click on the blue arrow beside any journal title 
3. Click on 'remove' 
4. Click on 'ok' in the modal
5. See the error

**What application are you using?**
 OJS 3.4

**Additional information**

https://github.com/pkp/pkp-lib/assets/4992902/53ecc54f-0ebb-4f50-ae11-35cb33cac04c

The journals were just created and don't have either authors or submissions.

It is related to this issue against OMP 3.3 which has been already fixed:
https://github.com/pkp/pkp-lib/issues/6577

This is the output from the log error file:

```
[php:error] [pid 252] [client 172.24.0.1:64332] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lamp.highlights' doesn't exist in /app/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:414\nStack trace:\n
#0 /app/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): PDO->prepare('select `h`.* fr...')\n
#1 /app/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select `h`.* fr...', Array)\n
#2 /app/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback('select `h`.* fr...', Array, Object(Closure))\n
#3 /app/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(422): Illuminate\\Database\\Connection->run('select `h`.* fr...', Array, Object(Closure))\n
#4 /app/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2706): Illuminate\\Database\\Connection->select('select `h`.* fr...', Array, true)\n
#5 /app/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2694): Illuminate\\Database\\Query\\Builder->runSelect()\n
#6 /app/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3230): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()\n
#7 /app/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2695): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))\n
#8 /app/www/lib/pkp/classes/highlight/DAO.php(98): Illuminate\\Database\\Query\\Builder->get()\n
#9 /app/www/lib/pkp/classes/highlight/Collector.php(64): PKP\\highlight\\DAO->getMany(Object(PKP\\highlight\\Collector))\n
#10 /app/www/lib/pkp/classes/highlight/Repository.php(215): PKP\\highlight\\Collector->getMany()\n
#11 /app/www/lib/pkp/classes/highlight/Collector.php(72): PKP\\highlight\\Repository->deleteMany(Object(PKP\\highlight\\Collector))\n
#12 /app/www/lib/pkp/classes/services/PKPContextService.php(615): PKP\\highlight\\Collector->deleteMany()\n
#13 /app/www/lib/pkp/controllers/grid/admin/context/ContextGridHandler.php(289): PKP\\services\\PKPContextService->delete(Object(APP\\journal\\Journal))\n
#14 [internal function]: PKP\\controllers\\grid\\admin\\context\\ContextGridHandler->deleteContext(Array, Object(APP\\core\\Request))\n
#15 /app/www/lib/pkp/classes/core/PKPRouter.php(334): call_user_func(Array, Array, Object(APP\\core\\Request))\n
#16 /app/www/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\\core\\Request), Array)\n
#17 /app/www/lib/pkp/classes/core/Dispatcher.php(165): PKP\\core\\PKPComponentRouter->route(Object(APP\\core\\Request))\n
#18 /app/www/lib/pkp/classes/core/PKPApplication.php(388): PKP\\core\\Dispatcher->dispatch(Object(APP\\core\\Request))\n
#19 /app/www/index.php(21): PKP\\core\\PKPApplication->execute()\n
#20 {main}\n\n

Next Illuminate\\Database\\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lamp.highlights' doesn't exist 
(SQL: select `h`.* from `highlights` as `h` where `h`.`context_id` in (3) order by `h`.`sequence` asc) in /app/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760\nStack trace:\n
#0 /app/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback('select `h`.* fr...', Array, Object(Closure))\n
#1 /app/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(422): Illuminate\\Database\\Connection->run('select `h`.* fr...', Array, Object(Closure))\n
#2 /app/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2706): Illuminate\\Database\\Connection->select('select `h`.* fr...', Array, true)\n
#3 /app/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2694): Illuminate\\Database\\Query\\Builder->runSelect()\n
#4 /app/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3230): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()\n
#5 /app/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2695): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))\n
#6 /app/www/lib/pkp/classes/highlight/DAO.php(98): Illuminate\\Database\\Query\\Builder->get()\n
#7 /app/www/lib/pkp/classes/highlight/Collector.php(64): PKP\\highlight\\DAO->getMany(Object(PKP\\highlight\\Collector))\n
#8 /app/www/lib/pkp/classes/highlight/Repository.php(215): PKP\\highlight\\Collector->getMany()\n
#9 /app/www/lib/pkp/classes/highlight/Collector.php(72): PKP\\highlight\\Repository->deleteMany(Object(PKP\\highlight\\Collector))\n
#10 /app/www/lib/pkp/classes/services/PKPContextService.php(615): PKP\\highlight\\Collector->deleteMany()\n
#11 /app/www/lib/pkp/controllers/grid/admin/context/ContextGridHandler.php(289): PKP\\services\\PKPContextService->delete(Object(APP\\journal\\Journal))\n
#12 [internal function]: PKP\\controllers\\grid\\admin\\context\\ContextGridHandler->deleteContext(Array, Object(APP\\core\\Request))\n
#13 /app/www/lib/pkp/classes/core/PKPRouter.php(334): call_user_func(Array, Array, Object(APP\\core\\Request))\n
#14 /app/www/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\\core\\Request), Array)\n
#15 /app/www/lib/pkp/classes/core/Dispatcher.php(165): PKP\\core\\PKPComponentRouter->route(Object(APP\\core\\Request))\n
#16 /app/www/lib/pkp/classes/core/PKPApplication.php(388): PKP\\core\\Dispatcher->dispatch(Object(APP\\core\\Request))\n
#17 /app/www/index.php(21): PKP\\core\\PKPApplication->execute()\n
#18 {main}\n  
thrown in /app/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 760, referer: https://localhost:57276/index.php/index/admin/contexts
```

**Comment by asmecher** [comment]
Should be resolved by https://github.com/pkp/pkp-lib/commit/724e137bb6d92f320b12ab2debe07488b932cf59, applied in `lib/pkp`.
