### ISSUE TITLE
Mailables editing is broken

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9718]
**Describe the bug**
Attempting to edit a mailable leads to a fatal error:
```
[08-Feb-2024 21:50:41 UTC] Symfony\Component\HttpKernel\Exception\NotFoundHttpException: The route publicknowledge/api/v1/mailables/DISCUSSION_NOTIFICATION_COPYEDITING could not be found. in /home/username/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php:44
Stack trace:
#0 /home/username/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php(162): Illuminate\Routing\AbstractRouteCollection->handleMatchedRoute()
#1 /home/username/git/ojs-main/lib/pkp/classes/core/PKPBaseController.php(107): Illuminate\Routing\RouteCollection->match()
#2 /home/username/git/ojs-main/lib/pkp/classes/core/PKPBaseController.php(115): PKP\core\PKPBaseController::getRequestedRoute()
#3 /home/username/git/ojs-main/lib/pkp/classes/middleware/PolicyAuthorizer.php(43): PKP\core\PKPBaseController::getRouteController()
#4 /home/username/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): PKP\middleware\PolicyAuthorizer->handle()
#5 /home/username/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#6 /home/username/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#7 /home/username/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#8 /home/username/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#9 /home/username/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#10 /home/username/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#11 /home/username/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#12 /home/username/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#13 /home/username/git/ojs-main/lib/pkp/classes/middleware/ValidateCsrfToken.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 /home/username/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): PKP\middleware\ValidateCsrfToken->handle()
#15 /home/username/git/ojs-main/lib/pkp/classes/middleware/DecodeApiTokenWithValidation.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /home/username/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): PKP\middleware\DecodeApiTokenWithValidation->handle()
#17 /home/username/git/ojs-main/lib/pkp/classes/middleware/SetupContextBasedOnRequestUrl.php(65): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 /home/username/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): PKP\middleware\SetupContextBasedOnRequestUrl->handle()
#19 /home/username/git/ojs-main/lib/pkp/classes/middleware/AllowCrossOrigin.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /home/username/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): PKP\middleware\AllowCrossOrigin->handle()
#21 /home/username/git/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /home/username/git/ojs-main/lib/pkp/classes/handler/APIHandler.php(63): Illuminate\Pipeline\Pipeline->then()
#23 /home/username/git/ojs-main/api/v1/mailables/index.php(18): PKP\handler\APIHandler->__construct()
#24 /home/username/git/ojs-main/lib/pkp/classes/core/APIRouter.php(103): require('...')
#25 /home/username/git/ojs-main/lib/pkp/classes/core/Dispatcher.php(167): PKP\core\APIRouter->route()
#26 /home/username/git/ojs-main/lib/pkp/classes/core/PKPApplication.php(378): PKP\core\Dispatcher->dispatch()
#27 /home/username/git/ojs-main/index.php(21): PKP\core\PKPApplication->execute()
#28 {main}
```

**To Reproduce**
1. Go to Settings > Workflow > Emails
2. Click on 'Add and edit templates'
3. Click 'Edit' beside any mailable
4. See PHP error log

**What application are you using?**
 OJS, OMP or OPS version pre-3.5.0

This is probably introduced with https://github.com/pkp/pkp-lib/issues/7698.

**PRs**
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9720
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4184 [TEST ONLY]

**Comment by touhidurabir** [comment]
@asmecher PRs to review at https://github.com/pkp/pkp-lib/issues/9718#issue-2126132003
