### ISSUE TITLE
OMP - Browsing Categories on Multilingual Press return an error 500

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#9723]
**Describe the bug**
When setting an multilingual Press, if the categories don't have a description for each language (leaving the field empty), the system will return an error 500 page when browsing categories from the sidebar.

**To Reproduce**
1. Set a Press with more than one language, e.g.: English and French
2. Go to 'Dasboard > Press > Categories'
3. Create some categories but leave the "Description" field empty.
4. Navigate to the frontend of the Press (click on the Press Name at upper right corner)
5. Click on any Category from the sidebar
6. See the error

**What application are you using?**
OMP  3.4.0-4

**Additional information**
```
Fatal error: Uncaught TypeError: PKP\category\Category::getLocalizedDescription(): 
Return value must be of type string, null returned in /var/www/html/lib/pkp/classes/category/Category.php:112 Stack trace: 
#0 /var/www/html/cache/t_compile/487b610351ebf9d7c64f1869ee8d77745c23a9cb^5d0ca16a7c78afd59d26eb1b852e00f92f50a8d9_0.app.frontendpagescatalogCategory.tpl.php(46): PKP\category\Category->getLocalizedDescription() 
#1 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_65c8205c15ac39_83606210(Object(Smarty_Internal_Template)) 
#2 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template)) 
#3 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template)) 
#4 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 1) 
#5 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, '487b610351ebf9d...', NULL, 1) 
#6 /var/www/html/lib/pkp/classes/template/PKPTemplateManager.php(1326): Smarty_Internal_TemplateBase->display('frontend/pages/...', NULL, '487b610351ebf9d...', NULL) 
#7 /var/www/html/lib/pkp/pages/catalog/PKPCatalogHandler.php(113): PKP\template\PKPTemplateManager->display('frontend/pages/...') 
#8 [internal function]: PKP\pages\catalog\PKPCatalogHandler->category(Array, Object(APP\core\Request)) 
#9 /var/www/html/lib/pkp/classes/core/PKPRouter.php(334): call_user_func(Array, Array, Object(APP\core\Request)) 
#10 /var/www/html/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false) 
#11 /var/www/html/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter->route(Object(APP\core\Request)) 
#12 /var/www/html/lib/pkp/classes/core/PKPApplication.php(388): PKP\core\Dispatcher->dispatch(Object(APP\core\Request)) #13 /var/www/html/index.php(21): PKP\core\PKPApplication->execute() 
#14 {main} thrown in /var/www/html/lib/pkp/classes/category/Category.php on line 112
```

**Comment by kaitlinnewson** [comment]
@israelcefrin Is this still an issue? I wasn't able to reproduce it in the latest 3.4 branch of OMP.

**Comment by jonasraoni** [comment]
This has been fixed 6 months ago, closing.
