### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class "Locale" not found 

### ISSUE THREAD

**Issue by loadbrain** [pkp/pkp-lib#9768]
**Trying to upate from OJS 3.4.0.4 to 3.4.0.5**
At first, update did not work with error:
`PHP Fatal error:  Uncaught Error: Class "Locale" not found in /var/www/xxx.xxx.xx/lib/pkp/classes/i18n/Locale.php:148
Stack trace:
#0 /var/www/xxx.xxx.xx/lib/pkp/classes/i18n/Locale.php(130): PKP\i18n\Locale->setLocale()
#1 /var/www/xxx.xxx.xx/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): PKP\i18n\Locale->getLocale()
#2 /var/www/xxx.xxx.xx/lib/pkp/classes/template/PKPTemplateManager.php(162): Illuminate\Support\Facades\Facade::__callStatic()
#3 /var/www/xxx.xxx.xx/classes/template/TemplateManager.php(40): PKP\template\PKPTemplateManager->initialize()
#4 /var/www/xxx.xxx.xx/lib/pkp/classes/template/PKPTemplateManager.php(1437): APP\template\TemplateManager->initialize()
#5 /var/www/xxx.xxx.xx/lib/pkp/classes/plugins/Plugin.php(403): PKP\template\PKPTemplateManager::getManager()
#6 /var/www/xxx.xxx.xx/lib/pkp/classes/plugins/Plugin.php(137): PKP\plugins\Plugin->_registerTemplateResource()
#7 /var/www/xxx.xxx.xx/lib/pkp/classes/plugins/LazyLoadPlugin.php(34): PKP\plugins\Plugin->register()
#8 /var/www/xxx.xxx.xx/plugins/generic/error404/Error404Plugin.php(26): PKP\plugins\LazyLoadPlugin->register()
#9 /var/www/xxx.xxx.xx/lib/pkp/classes/plugins/PluginRegistry.php(76): APP\plugins\generic\error404\Error404Plugin->register()
#10 /var/www/xxx.xxx.xx/lib/pkp/classes/plugins/PluginRegistry.php(121): PKP\plugins\PluginRegistry::register()
#11 [internal function]: PKP\plugins\PluginRegistry::PKP\plugins\{closure}()
#12 /var/www/xxx.xxx.xx/lib/pkp/classes/plugins/PluginRegistry.php(121): array_walk_recursive()
#13 /var/www/xxx.xxx.xx/lib/pkp/classes/cliTool/CommandLineTool.php(72): PKP\plugins\PluginRegistry::loadCategory()
#14 /var/www/xxx.xxx.xx/lib/pkp/classes/cliTool/UpgradeTool.php(39): PKP\cliTool\CommandLineTool->__construct()
#15 /var/www/xxx.xxx.xx/tools/upgrade.php(21): PKP\cliTool\UpgradeTool->__construct()
#16 {main}
  thrown in /var/www/xxx.xxx.xx/lib/pkp/classes/i18n/Locale.php on line 148`

so I installed php-intl.
Tried to update again, on console, successful.
But in Browser 500 Error:
Log file from Apache:
`[Thu Feb 29 15:13:45.900895 2024] [php:error] [pid 171787] [client 193.197.86.24:22115] 
PHP Fatal error:  Uncaught Error: Class "Locale" not found in /var/www/xxx.xxx.xx/lib/pkp/classes/i18n/Locale.php:148\n
Stack trace:\n#0 /var/www/xxx.xxx.xx/lib/pkp/classes/i18n/Locale.php(130): PKP\\i18n\\Locale->setLocale()\n
#1 /var/www/xxx.xxx.xx/lib/pkp/classes/i18n/Locale.php(419): PKP\\i18n\\Locale->getLocale()\n#2 /var/www/xxx.xxx.xx/lib/pkp/classes/i18n/Locale.php(105): PKP\\i18n\\Locale->translate()\n#3 /var/www/xxx.xxx.xx/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(938): PKP\\i18n\\Locale->get()\n#4 /var/www/xxx.xxx.xx/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(973): trans()\n#5 /var/www/xxx.xxx.xx/plugins/themes/default/DefaultThemePlugin.php(45): __()\n#6 /var/www/xxx.xxx.xx/lib/pkp/classes/plugins/ThemePlugin.php(130): APP\\plugins\\themes\\default\\DefaultThemePlugin->init()\n#7 [internal function]: PKP\\plugins\\ThemePlugin->themeRegistered()\n#8 /var/www/xxx.xxx.xx/lib/pkp/classes/plugins/Hook.php(139): call_user_func_array()\n#9 /var/www/xxx.xxx.xx/lib/pkp/classes/plugins/Hook.php(113): PKP\\plugins\\Hook::run()\n#10 /var/www/xxx.xxx.xx/lib/pkp/classes/plugins/PluginRegistry.php(128): PKP\\plugins\\Hook::call()\n#11 /var/www/xxx.xxx.xx/lib/pkp/classes/template/PKPTemplateManager.php(1435): PKP\\plugins\\PluginRegistry::loadCategory()\n#12 /var/www/xxx.xxx.xx/lib/pkp/classes/plugins/Plugin.php(403): PKP\\template\\PKPTemplateManager::getManager()\n#13 /var/www/xxx.xxx.xx/lib/pkp/classes/plugins/Plugin.php(137): PKP\\plugins\\Plugin->_registerTemplateResource()\n#14 /var/www/xxx.xxx.xx/lib/pkp/classes/plugins/LazyLoadPlugin.php(34): PKP\\plugins\\Plugin->register()\n#15 /var/www/xxx.xxx.xx/plugins/generic/datacite/DatacitePlugin.php(60): PKP\\plugins\\LazyLoadPlugin->register()\n#16 /var/www/xxx.xxx.xx/lib/pkp/classes/plugins/PluginRegistry.php(76): APP\\plugins\\generic\\datacite\\DatacitePlugin->register()\n#17 /var/www/xxx.xxx.xx/lib/pkp/classes/plugins/PluginRegistry.php(121): PKP\\plugins\\PluginRegistry::register()\n#18 [internal function]: PKP\\plugins\\PluginRegistry::PKP\\plugins\\{closure}()\n#19 /var/www/xxx.xxx.xx/lib/pkp/classes/plugins/PluginRegistry.php(121): array_walk_recursive()\n#20 /var/www/xxx.xxx.xx/lib/pkp/classes/core/Dispatcher.php(155): PKP\\plugins\\PluginRegistry::loadCategory()\n#21 /var/www/xxx.xxx.xx/lib/pkp/classes/core/PKPApplication.php(388): PKP\\core\\Dispatcher->dispatch()\n#22 /var/www/xxx.xxx.xx/index.php(21): PKP\\core\\PKPApplication->execute()\n#23 {main}\n  thrown in /var/www/xxx.xxx.xx/lib/pkp/classes/i18n/Locale.php on line 148, referer: https://ojsdev.nomos-journals.de/index.php/index/admin/index
`
When I uncomment the line 148 in /lib/pkp/classes/i18n/Locale.php
`#     \Locale::setDefault(\Locale::lookup(ResourceBundle::getLocales(''), $locale, true));`

everthing is working.

Any ideas???

**Comment by loadbrain** [comment]
Solved.
php-intl was installed but not active...
After restarting webserver, it works now...
