### ISSUE TITLE
PHP Fatal error when search indexing submission created with Quicksubmit in OJS 3.4

### ISSUE THREAD

**Issue by ronste** [pkp/pkp-lib#9821]
**Describe the bug**
The following error/notice messages appear in the PHP error log after creating a submission with Quicksubmit in OJS 3.4

```PHP
[Thu Mar 21 14:58:12.371965 2024] [php:error] [pid 13] [client 172.24.0.1:35934] PHP Fatal error:  Uncaught Exception: The following errors happened while indexing the submission ID 13:\nTypeError: pclose(): Argument #1 ($handle) must be of type resource, null given in /var/www/html/ojs/lib/pkp/classes/search/SearchHelperParser.php:47\nStack trace:\n#0 /var/www/html/ojs/lib/pkp/classes/search/SearchHelperParser.php(47): pclose()\n#1 /var/www/html/ojs/classes/search/ArticleSearchIndex.php(137): PKP\\search\\SearchHelperParser->close()\n#2 /var/www/html/ojs/classes/search/ArticleSearchIndex.php(196): APP\\search\\ArticleSearchIndex->submissionFileChanged()\n#3 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitForm.php(429): APP\\search\\ArticleSearchIndex->submissionFilesChanged()\n#4 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitPlugin.php(178): APP\\plugins\\importexport\\quickSubmit\\QuickSubmitForm->execute()\n#5 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitPlugin.php(67): APP\\plugins\\importexport\\quickSubmit\\QuickSubmitPlugin->_saveSubmit()\n#6 /var/www/html/ojs/lib/pkp/pages/management/PKPToolsHandler.php(104): APP\\plugins\\importexport\\quickSubmit\\QuickSubmitPlugin->display()\n#7 [internal function]: PKP\\pages\\management\\PKPToolsHandler->importexport()\n#8 /var/www/html/ojs/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()\n#9 /var/www/html/ojs/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest()\n#10 /var/www/html/ojs/lib/pkp/classes/core/Dispatcher.php(165): PKP\\core\\PKPPageRouter->route()\n#11 /var/www/html/ojs/lib/pkp/classes/core/PKPApplication.php(388): PKP\\core\\Dispatcher->dispatch()\n#12 /var/www/html/ojs/index.php(21): PKP\\core\\PKPApplication->execute()\n#13 {main}\n\nNext Exception: Indexation failed for the file: "journals/1/articles/13/65fc4afc48795.css" in /var/www/html/ojs/classes/search/ArticleSearchIndex.php:140\nStack trace:\n#0 /var/www/html/ojs/classes/search/ArticleSearchIndex.php(196): APP\\search\\ArticleSearchIndex->submissionFileChanged()\n#1 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitForm.php(429): APP\\search\\ArticleSearchIndex->submissionFilesChanged()\n#2 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitPlugin.php(178): APP\\plugins\\importexport\\quickSubmit\\QuickSubmitForm->execute()\n#3 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitPlugin.php(67): APP\\plugins\\importexport\\quickSubmit\\QuickSubmitPlugin->_saveSubmit()\n#4 /var/www/html/ojs/lib/pkp/pages/management/PKPToolsHandler.php(104): APP\\plugins\\importexport\\quickSubmit\\QuickSubmitPlugin->display()\n#5 [internal function]: PKP\\pages\\management\\PKPToolsHandler->importexport()\n#6 /var/www/html/ojs/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()\n#7 /var/www/html/ojs/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest()\n#8 /var/www/html/ojs/lib/pkp/classes/core/Dispatcher.php(165): PKP\\core\\PKPPageRouter->route()\n#9 /var/www/html/ojs/lib/pkp/classes/core/PKPApplication.php(388): PKP\\core\\Dispatcher->dispatch()\n#10 /var/www/html/ojs/index.php(21): PKP\\core\\PKPApplication->execute()\n#11 {main}\n\nTypeError: pclose(): Argument #1 ($handle) must be of type resource, null given in /var/www/html/ojs/lib/pkp/classes/search/SearchHelperParser.php:47\nStack trace:\n#0 /var/www/html/ojs/lib/pkp/classes/search/SearchHelperParser.php(47): pclose()\n#1 /var/www/html/ojs/classes/search/ArticleSearchIndex.php(137): PKP\\search\\SearchHelperParser->close()\n#2 /var/www/html/ojs/classes/search/ArticleSearchIndex.php(180): APP\\search\\ArticleSearchIndex->submissionFileChanged()\n#3 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitForm.php(429): APP\\search\\ArticleSearchIndex->submissionFilesChanged()\n#4 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitPlugin.php(178): APP\\plugins\\importexport\\quickSubmit\\QuickSubmitForm->execute()\n#5 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitPlugin.php(67): APP\\plugins\\importexport\\quickSubmit\\QuickSubmitPlugin->_saveSubmit()\n#6 /var/www/html/ojs/lib/pkp/pages/management/PKPToolsHandler.php(104): APP\\plugins\\importexport\\quickSubmit\\QuickSubmitPlugin->display()\n#7 [internal function]: PKP\\pages\\management\\PKPToolsHandler->importexport()\n#8 /var/www/html/ojs/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()\n#9 /var/www/html/ojs/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest()\n#10 /var/www/html/ojs/lib/pkp/classes/core/Dispatcher.php(165): PKP\\core\\PKPPageRouter->route()\n#11 /var/www/html/ojs/lib/pkp/classes/core/PKPApplication.php(388): PKP\\core\\Dispatcher->dispatch()\n#12 /var/www/html/ojs/index.php(21): PKP\\core\\PKPApplication->execute()\n#13 {main}\n\nNext Exception: Indexation failed for the file: "journals/1/articles/13/65fc4ae1cecfd.pdf" in /var/www/html/ojs/classes/search/ArticleSearchIndex.php:140\nStack trace:\n#0 /var/www/html/ojs/classes/search/ArticleSearchIndex.php(180): APP\\search\\ArticleSearchIndex->submissionFileChanged()\n#1 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitForm.php(429): APP\\search\\ArticleSearchIndex->submissionFilesChanged()\n#2 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitPlugin.php(178): APP\\plugins\\importexport\\quickSubmit\\QuickSubmitForm->execute()\n#3 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitPlugin.php(67): APP\\plugins\\importexport\\quickSubmit\\QuickSubmitPlugin->_saveSubmit()\n#4 /var/www/html/ojs/lib/pkp/pages/management/PKPToolsHandler.php(104): APP\\plugins\\importexport\\quickSubmit\\QuickSubmitPlugin->display()\n#5 [internal function]: PKP\\pages\\management\\PKPToolsHandler->importexport()\n#6 /var/www/html/ojs/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()\n#7 /var/www/html/ojs/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest()\n#8 /var/www/html/ojs/lib/pkp/classes/core/Dispatcher.php(165): PKP\\core\\PKPPageRouter->route()\n#9 /var/www/html/ojs/lib/pkp/classes/core/PKPApplication.php(388): PKP\\core\\Dispatcher->dispatch()\n#10 /var/www/html/ojs/index.php(21): PKP\\core\\PKPApplication->execute()\n#11 {main} in /var/www/html/ojs/classes/search/ArticleSearchIndex.php:204\nStack trace:\n#0 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitForm.php(429): APP\\search\\ArticleSearchIndex->submissionFilesChanged()\n#1 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitPlugin.php(178): APP\\plugins\\importexport\\quickSubmit\\QuickSubmitForm->execute()\n#2 /var/www/html/ojs/plugins/importexport/quickSubmit/QuickSubmitPlugin.php(67): APP\\plugins\\importexport\\quickSubmit\\QuickSubmitPlugin->_saveSubmit()\n#3 /var/www/html/ojs/lib/pkp/pages/management/PKPToolsHandler.php(104): APP\\plugins\\importexport\\quickSubmit\\QuickSubmitPlugin->display()\n#4 [internal function]: PKP\\pages\\management\\PKPToolsHandler->importexport()\n#5 /var/www/html/ojs/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()\n#6 /var/www/html/ojs/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest()\n#7 /var/www/html/ojs/lib/pkp/classes/core/Dispatcher.php(165): PKP\\core\\PKPPageRouter->route()\n#8 /var/www/html/ojs/lib/pkp/classes/core/PKPApplication.php(388): PKP\\core\\Dispatcher->dispatch()\n#9 /var/www/html/ojs/index.php(21): PKP\\core\\PKPApplication->execute()\n#10 {main}\n  thrown in /var/www/html/ojs/classes/search/ArticleSearchIndex.php on line 204, referer: http://localhost:50020/ojs/index.php/dja/management/importexport/plugin/QuickSubmitPlugin/saveSubmit
[Thu Mar 21 14:58:12.552826 2024] [php:notice] [pid 13] [client 172.24.0.1:35934] #0 /var/www/html/ojs/lib/pkp/jobs/metadata/MetadataChangedJob.php(58): APP\\search\\ArticleSearchIndex->submissionFilesChanged()\n#1 /var/www/html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): PKP\\jobs\\metadata\\MetadataChangedJob->handle()\n#2 /var/www/html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()\n#3 /var/www/html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()\n#4 /var/www/html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()\n#5 /var/www/html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()\n#6 /var/www/html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()\n#7 /var/www/html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()\n#8 /var/www/html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#9 /var/www/html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()\n#10 /var/www/html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Bus\\Dispatcher->dispatchNow()\n#11 /var/www/html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()\n#12 /var/www/html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#13 /var/www/html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()\n#14 /var/www/html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()\n#15 /var/www/html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()\n#16 /var/www/html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(425): Illuminate\\Queue\\Jobs\\Job->fire()\n#17 /var/www/html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\\Queue\\Worker->process()\n#18 /var/www/html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(326): Illuminate\\Queue\\Worker->runJob()\n#19 /var/www/html/ojs/lib/pkp/classes/core/PKPQueueProvider.php(101): Illuminate\\Queue\\Worker->runNextJob()\n#20 /var/www/html/ojs/lib/pkp/classes/queue/JobRunner.php(220): PKP\\core\\PKPQueueProvider->runJobInQueue()\n#21 /var/www/html/ojs/lib/pkp/classes/core/PKPQueueProvider.php(128): PKP\\queue\\JobRunner->processJobs()\n#22 [internal function]: PKP\\core\\PKPQueueProvider->PKP\\core\\{closure}()\n#23 {main}, referer: http://localhost:50020/ojs/index.php/dja/management/importexport/plugin/QuickSubmitPlugin/saveSubmit
```

**To Reproduce**
1. Create a submission with Quicksubmit
2. See PHP error log

**What application are you using?**
 OJS 3.4.0-4

**Comment by jonasraoni** [comment]
@ronste that's a very unexpected message, see that there's a check at the `$this->fp`  before calling the `pclose()`:
https://github.com/pkp/pkp-lib/blob/64c89c512a0eb2211aae09fdaae0eedfbe4b3bb0/classes/search/SearchHelperParser.php#L51-L53

Given this validation didn't exist before, please check if you have the same code on your installation, perhaps your `pkp-lib` is missing updates.

**Comment by jonasraoni** [comment]
If you replace the `return Repo::section()->exists($sectionId, $contextId);` by `return Repo::section()->exists((int) $sectionId, $contextId);` are you able to continue?

**Comment by ronste** [comment]
Hi @jonasraoni ,

I am not able to reproduce the error anymore. Seems to have been a one-time event. Maybe because I just rebuild the container and had a fresh installation with only the default article section (just speculating). It was the first submission within this fresh installation. Now, even when I create a new section, I don't get the error anymore.

**Comment by jonasraoni** [comment]
Thanks for the feedback, I'll add the type cast nevertheless.
