### ISSUE TITLE
Fatal error at site-wide announcements 

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9824]
**Describe the bug**
When trying to insert a site-wide announcement, it fails with the exception below:

```php
Slim Application Error:
Type: Illuminate\\Database\\QueryException
Code: 23000
Message: SQLSTATE[23000]: Integrity constraint violation: 1048 Column &#039;assoc_id&#039; cannot be null (SQL: insert into `announcements` (`assoc_id`, `assoc_type`, `date_expire`, `date_posted`) values (?, 256, ?, 2024-03-21 19:41:46))
File: /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php
Line: 760
Trace: #0 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback('insert into `an...', Array, Object(Closure))
#1 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(546): Illuminate\\Database\\Connection->run('insert into `an...', Array, Object(Closure))
#2 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(498): Illuminate\\Database\\Connection->statement('insert into `an...', Array)
#3 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3274): Illuminate\\Database\\Connection->insert('insert into `an...', Array)
#4 /var/www/html/lib/pkp/classes/core/EntityDAO.php(151): Illuminate\\Database\\Query\\Builder->insert(Array)
#5 /var/www/html/lib/pkp/classes/announcement/DAO.php(124): PKP\\core\\EntityDAO->_insert(Object(PKP\\announcement\\Announcement))
#6 /var/www/html/lib/pkp/classes/announcement/Repository.php(139): PKP\\announcement\\DAO->insert(Object(PKP\\announcement\\Announcement))
#7 /var/www/html/lib/pkp/api/v1/announcements/PKPAnnouncementHandler.php(225): PKP\\announcement\\Repository->add(Object(PKP\\announcement\\Announcement))
#8 [internal function]: PKP\\API\\v1\\announcements\\PKPAnnouncementHandler->add(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Array)
#9 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Array)
#10 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(281): Slim\\Handlers\\Strategies\\RequestResponse->__invoke(Array, Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Array)
#11 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\Route->__invoke(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse))
#12 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(268): Slim\\Route->callMiddlewareStack(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse))
#13 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/App.php(503): Slim\\Route->run(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse))
#14 /var/www/html/lib/pkp/classes/security/authorization/internal/ApiAuthorizationMiddleware.php(90): Slim\\App->__invoke(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse))
#15 [internal function]: PKP\\security\\authorization\\internal\\ApiAuthorizationMiddleware->__invoke(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Object(Slim\\App))
#16 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(PKP\\security\\authorization\\internal\\ApiAuthorizationMiddleware), Array)
#17 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Object(Slim\\App))
#18 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Object(Slim\\App))
#19 /var/www/html/lib/pkp/classes/security/authorization/internal/ApiCsrfMiddleware.php(56): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse))
#20 [internal function]: PKP\\security\\authorization\\internal\\ApiCsrfMiddleware->__invoke(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Object(Closure))
#21 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(PKP\\security\\authorization\\internal\\ApiCsrfMiddleware), Array)
#22 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Object(Closure))
#23 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Object(Closure))
#24 /var/www/html/lib/pkp/classes/security/authorization/internal/ApiTokenDecodingMiddleware.php(140): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse))
#25 [internal function]: PKP\\security\\authorization\\internal\\ApiTokenDecodingMiddleware->__invoke(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Object(Closure))
#26 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(PKP\\security\\authorization\\internal\\ApiTokenDecodingMiddleware), Array)
#27 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Object(Closure))
#28 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Object(Closure))
#29 /var/www/html/lib/pkp/classes/handler/APIHandler.php(83): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse))
#30 [internal function]: PKP\\handler\\APIHandler->PKP\\handler\\{closure}(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Object(Closure))
#31 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#32 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Object(Closure))
#33 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Object(Closure))
#34 /var/www/html/lib/pkp/classes/handler/APIHandler.php(100): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse))
#35 [internal function]: PKP\\handler\\APIHandler->PKP\\handler\\{closure}(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Object(Closure))
#36 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#37 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Object(Closure))
#38 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Object(Closure))
#39 /var/www/html/lib/pkp/classes/handler/APIHandler.php(105): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse))
#40 [internal function]: PKP\\handler\\APIHandler->PKP\\handler\\{closure}(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Object(Closure))
#41 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#42 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Object(Closure))
#43 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Object(Closure))
#44 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse))
#45 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\\App->callMiddlewareStack(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse))
```

**To Reproduce**
1. Enable site-wide announcements through the `config.inc.php` using [features].site_announcements = "On"`
2. Access Administration > Site Settings > Announcements
3. Attempt to insert an entry

**What application are you using?**
OJS 3.4

**Comment by jonasraoni** [comment]
The code is behind a `feature flag`, so the behavior is expected, the migrations here https://github.com/pkp/pkp-lib/tree/stable-3_4_0/classes/migration/upgrade/v3_5_0 should address the exception at the issue description.

Anyway, a fix is still needed for the users that enabled the site-wide announcements, to avoid an upgrade failure when migrating from 3.4 to 3.5.

**Comment by jonasraoni** [comment]
@bozana Please review the linked PRs, they are just addressing the [comment above](https://github.com/pkp/pkp-lib/issues/9824#issuecomment-2016414954).

**Comment by bozana** [comment]
Hi @jonasraoni, yes the PRs look good. Could you maybe only create submodule updates for OJS, OMP and OPS for stable-3_4_0 -- for the users that use that branch to have it correctly? Then it can be merged...
