### ISSUE TITLE
Fatal error at announcement feed plugin

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9828]
**Describe the bug**
The following exception happens when enabling the `announcementFeed` plugin:

```php
PHP Fatal error:  Uncaught Error: Call to a member function getDatetimePosted() on null in /var/www/html/plugins/generic/announcementFeed/AnnouncementFeedGatewayPlugin.php:148
Stack trace:
#0 /var/www/html/pages/gateway/GatewayHandler.php(215): APP\plugins\generic\announcementFeed\AnnouncementFeedGatewayPlugin->fetch(Array, Object(APP\core\Request))
#1 [internal function]: APP\pages\gateway\GatewayHandler->plugin(Array, Object(APP\core\Request))
#2 /var/www/html/lib/pkp/classes/core/PKPRouter.php(334): call_user_func(Array, Array, Object(APP\core\Request))
#3 /var/www/html/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#4 /var/www/html/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#5 /var/www/html/lib/pkp/classes/core/PKPApplication.php(388): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#6 /var/www/html/index.php(21): PKP\core\PKPApplication->execute()
#7 {main}
  thrown in /var/www/html/plugins/generic/announcementFeed/AnnouncementFeedGatewayPlugin.php on line 148
```

**To Reproduce**
1. Enable the Announcement Feed plugin
2. Visit the journal page
3. Get a link to the feed at the source code
4. See the error

**What application are you using?**
OJS 3.4

**Comment by jonasraoni** [comment]
Fixed by:
- https://github.com/pkp/ojs/commit/74af528370271265a06c8e9c1d49aeca76d6be7b
- https://github.com/pkp/ojs/commit/db10abf1f87d4a4e337cc9b4a023cd06a6b2c277
