### ISSUE TITLE
Crash on authorDashboard prevents loading some components

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#9924]
**Describe the bug**
When loading authorDashboard, it does not display for example Reviewer's Attachments and it generates error in the log.

**To Reproduce**
1. Login as author, with default dataset for example as lkumiega
2. Select submission thats in review stage and click on View to open author dashboard
3. Reviewer's Attachment grid is missing

**What application are you using?**
 OJS main

**Additional information**
```
[Wed May  1 15:27:34 2024] PHP Warning:  filemtime(): stat failed for /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/lib/weblateLanguages/languages.json in /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/i18n/Locale.php on line 572
[Wed May  1 15:27:34 2024] PHP Fatal error:  Uncaught TypeError: Cannot assign array to property PKP\submission\reviewAssignment\Collector::$reviewMethods of type ?int in /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/submission/reviewAssignment/Collector.php:149
Stack trace:
#0 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/controllers/tab/authorDashboard/AuthorDashboardReviewRoundTabHandler.php(107): PKP\submission\reviewAssignment\Collector->filterByReviewMethods(Array)
#1 [internal function]: PKP\controllers\tab\authorDashboard\AuthorDashboardReviewRoundTabHandler->fetchReviewRoundInfo(Array, Object(APP\core\Request))
#2 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/core/PKPRouter.php(346): call_user_func(Array, Array, Object(APP\core\Request))
#3 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/core/PKPComponentRouter.php(293): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#4 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/core/Dispatcher.php(171): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#5 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/core/PKPApplication.php(379): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#6 /Users/jarda/git/pkp/pkp-main/ojs-main/index.php(21): PKP\core\PKPApplication->execute()
#7 {main}
  thrown in /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/submission/reviewAssignment/Collector.php on line 149
[Wed May  1 15:27:34 2024] [::1]:60146 [500]: GET /index.php/publicknowledge/$$$call$$$/tab/author-dashboard/author-dashboard-review-round-tab/fetch-review-round-info?submissionId=13&stageId=3&reviewRoundId=10&_=1714570053509 - Uncaught TypeError: Cannot assign array to property PKP\submission\reviewAssignment\Collector::$reviewMethods of type ?int in /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/submission/reviewAssignment/Collector.php:149
Stack trace:
#0 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/controllers/tab/authorDashboard/AuthorDashboardReviewRoundTabHandler.php(107): PKP\submission\reviewAssignment\Collector->filterByReviewMethods(Array)
#1 [internal function]: PKP\controllers\tab\authorDashboard\AuthorDashboardReviewRoundTabHandler->fetchReviewRoundInfo(Array, Object(APP\core\Request))
#2 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/core/PKPRouter.php(346): call_user_func(Array, Array, Object(APP\core\Request))
#3 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/core/PKPComponentRouter.php(293): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#4 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/core/Dispatcher.php(171): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#5 /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/core/PKPApplication.php(379): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#6 /Users/jarda/git/pkp/pkp-main/ojs-main/index.php(21): PKP\core\PKPApplication->execute()
#7 {main}
  thrown in /Users/jarda/git/pkp/pkp-main/ojs-main/lib/pkp/classes/submission/reviewAssignment/Collector.php on line 149
```

**Comment by asmecher** [comment]
Fixed, thanks!
