### ISSUE TITLE
Unknown column 'et.alternate_to' in 'field list'

### ISSUE THREAD

**Issue by frafra** [pkp/pkp-lib#9990]
**Describe the bug**
Error when trying to reset password: `Unknown column 'et.alternate_to' in 'field list'`

**To Reproduce**
1. Go to reset password 

**What application are you using?**
 OJS version 3.4.0 on Docker.

**Additional information**

```
Fatal error:  Uncaught TypeError: PKP\user\Repository::getByEmail(): Argument #1 ($email) must be of type string, null given, called in /var/www/html/lib/pkp/pages/login/LoginHandler.php on line 227 and defined in /var/www/html/lib/pkp/classes/user/Repository.php:85
Stack trace:
#0 /var/www/html/lib/pkp/pages/login/LoginHandler.php(227): PKP\user\Repository-&gt;getByEmail()
#1 [internal function]: PKP\pages\login\LoginHandler-&gt;requestResetPassword()
#2 /var/www/html/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()
#3 /var/www/html/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\core\PKPRouter-&gt;_authorizeInitializeAndCallRequest()
#4 /var/www/html/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter-&gt;route()
#5 /var/www/html/lib/pkp/classes/core/PKPApplication.php(388): PKP\core\Dispatcher-&gt;dispatch()
#6 /var/www/html/index.php(21): PKP\core\PKPApplication-&gt;execute()
#7 {main}
  thrown in /var/www/html/lib/pkp/classes/user/Repository.php on line 85
```

**Comment by asmecher** [comment]
@frafra, does your `email_templates` table have an `alternate_to` column?

**Comment by frafra** [comment]
No, there is not. The whole setup seems messed up. I can't even login.

```
Warning:  Undefined array key "required" in /var/www/html/lib/pkp/classes/submission/GenreDAO.php on line 250

Fatal error:  Uncaught TypeError: PKP\submission\Genre::setRequired(): Argument #1 ($required) must be of type bool, null given, called in /var/www/html/lib/pkp/classes/submission/GenreDAO.php on line 250 and defined in /var/www/html/lib/pkp/classes/submission/Genre.php:213
Stack trace:
#0 /var/www/html/lib/pkp/classes/submission/GenreDAO.php(250): PKP\submission\Genre-&gt;setRequired()
#1 /var/www/html/lib/pkp/classes/db/DAOResultFactory.php(133): PKP\submission\GenreDAO-&gt;_fromRow()
#2 /var/www/html/lib/pkp/classes/db/DAOResultFactory.php(232): PKP\db\DAOResultFactory-&gt;next()
#3 /var/www/html/lib/pkp/pages/dashboard/DashboardHandler.php(118): PKP\db\DAOResultFactory-&gt;toArray()
#4 [internal function]: PKP\pages\dashboard\DashboardHandler-&gt;index()
#5 /var/www/html/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()
#6 /var/www/html/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\core\PKPRouter-&gt;_authorizeInitializeAndCallRequest()
#7 /var/www/html/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter-&gt;route()
#8 /var/www/html/lib/pkp/classes/core/PKPApplication.php(388): PKP\core\Dispatcher-&gt;dispatch()
#9 /var/www/html/index.php(21): PKP\core\PKPApplication-&gt;execute()
#10 {main}
  thrown in /var/www/html/lib/pkp/classes/submission/Genre.php on line 213
```

I just upgraded from `pkpofficial/ojs:3_3_0-11` to `pkpofficial/ojs:stable-3_4_0`  and added these lines to the configuration files to avoid errors:

```
; Mailer driver (needed from 3.4 onwards)
default = sendmail
sendmail_path = "/usr/sbin/sendmail -bs"
```

I wonder if there is a bug that leaves the migration halfway if there is a configuration error at startup. Furthermore, I also wonder where are the release notes for 3.4 that documents breaking changes and a proper update path, if they exist.

**Comment by frafra** [comment]
No, I did not, I was not aware of it. I assumed eventual upgrades would run when the container starts. Thank you.
